### ISSUE TITLE
❓ Is there a way to access actual bytes of a frame from js?

### ISSUE THREAD

**Issue by Overtorment** [cuvent/react-native-vision-camera#1013]
### Question

Say, I want to do some basic image recognition in pure js.

The only option Im seeing right now is doing `takePhoto` so it saves it to a file, and then using `react-native-fs` to access actual data from this file

### VisionCamera Version

2.13.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey!

I experimented with exposing actualy bytes to the JS Runtime, but it turned out to be really slow and JS simply isn't fast enough to process information quick enough.

Frame Processor Plugins are native and fast, while still being relatively simple.
