### ISSUE TITLE
Certain Google Pixel devices doesn't return physical devices (no multicam)

### ISSUE THREAD

**Issue by tcank** [cuvent/react-native-vision-camera#1022]
### Question

I'm not quite sure if this situation is directly related with vision camera or CameraX.

## Dependencies versions
```
    "react-native": "0.67.1",
    "react-native-vision-camera": "2.13.1",
    "vision-camera-code-scanner": "0.1.6",
```

## Description of our problem
We implement a QR Scanner using [vision-camera-code-scanner](https://github.com/rodgomesc/vision-camera-code-scanner) frame processor. When using a virtual camera device (isMultiCam = true), the initialization of the device / cameraview takes a quite long, so we decided to use only physical camera devices (isMultiCam = false).

The implementation worked great. We copied and modified the original `useCameraDevices` and created a `usePhysicalCameraDevices`:

```typescript
export const usePhysicalCameraDevices = (): CameraDevices => {
  const [cameraDevices, setCameraDevices] = useState<CameraDevices>(
    DEFAULT_CAMERA_DEVICES,
  );

  useEffect(() => {
    let isMounted = true;

    const loadDevice = async (): Promise<void> => {
      const devices = await Camera.getAvailableCameraDevices();
      if (!isMounted) return;

      const prioritizedDevices = devices.sort(sortDevices);
      const physicalDevices = prioritizedDevices.filter(d => !d.isMultiCam);

      setCameraDevices({
        back: physicalDevices.find(d => d.position === 'back'),
        external: physicalDevices.find(d => d.position === 'external'),
        front: physicalDevices.find(d => d.position === 'front'),
        unspecified: physicalDevices.find(d => d.position === 'unspecified'),
      });
    };
    loadDevice();

    return () => {
      isMounted = false;
    };
  }, []);

  return cameraDevices;
};
```

We started to receive comments from some users that they couldn't use the scanner and that the screen stays black (we have a View with black background as BlackOut). There was a common factor with all these users and was that they had a Google Pixel (4, 5 or 6), with Android 12.

We tested and debugged the app on a Google Pixel 6 and we detected that **no physical devices were returned**.

## Fix
Our workaround was to fallback to a virtual device if there is no physical device on the phone, and this fixed the problem. Also, in this case of Google Pixel phones, virtual camera devices aren't a big performance problem, so the solution is ok for us.

```typescript
      setCameraDevices({
        back:
          physicalDevices.find(d => d.position === 'back') ??
          prioritizedDevices.find(d => d.position === 'back'),
        external:
          physicalDevices.find(d => d.position === 'external') ??
          prioritizedDevices.find(d => d.position === 'external'),
        front:
          physicalDevices.find(d => d.position === 'front') ??
          prioritizedDevices.find(d => d.position === 'front'),
        unspecified:
          physicalDevices.find(d => d.position === 'unspecified') ??
          prioritizedDevices.find(d => d.position === 'unspecified'),
      });
```

## Question
Is this the expected behavior? Is it okay that we can't always access physical camera devices?

### VisionCamera Version

2.13.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.
