### ISSUE TITLE
🐛 takePhoto and takeSnapshot throws Not in application's main thread

### ISSUE THREAD

**Issue by bekatd** [cuvent/react-native-vision-camera#1030]
### What were you trying to do?

When using `takePhoto()` or `takeSnapshot()` it throws this error:

`[unknown/unknown: [unknown/unknown] Not in application's main thread]`

### Reproduceable Code

```tsx
const snapshot = await camera.current.takePhoto();

OR

const snapshot = await camera.current.takeSnapshot();
```

### What happened instead?

App throw Not in application's main thread error in the console

### Relevant log output

```shell
[unknown/unknown: [unknown/unknown] Not in application's main thread]
```

### Device

Xiaomi mi A2 lite (real device)

### VisionCamera Version

2.13.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by bekatd** [comment]
I tried to patch-package with PR #961 but got the same result

**Comment by bekatd** [comment]
Sorry false alarm, forgot to add patch-package in scripts, closing issue.

**Comment by MuhammadAbdullah54321** [comment]
I am still facing this issue 
I am using version `2.13.0` because upgrading to `2.13.3` gives this error ` Unresolved reference: resolveView` [https://github.com/mrousavy/react-native-vision-camera/issues/1012](url)
I am using react-native version 0.63.4

and I have to use `takeSnapshot` for android because `takePhoto` is very slow. I am testing on Redmi Note 9S

**Comment by bekatd** [comment]
Is it just slow or you are experiencing same error as was me?

**Comment by bekatd** [comment]
If it gives error, don't forget to patch this too, alongside with changes #961 

![image](https://user-images.githubusercontent.com/6948919/170661331-1635ce52-1b07-44ea-a34b-13009fb82d49.png)

**Comment by MuhammadAbdullah54321** [comment]
> Is it just slow or you are experiencing same error as was me?

I am experiencing the same error 
Being slow is just an extra thing I mentioned. when I click button to take picture on **android**, picture gets clicked but camera still stays open for like 1 sec and then I get the picture to display ....which actually cause a big delay on screen ...which is not user friendly

**Comment by MuhammadAbdullah54321** [comment]
> If it gives error, don't forget to patch this too, alongside with changes #961
> 
> ![image](https://user-images.githubusercontent.com/6948919/170661331-1635ce52-1b07-44ea-a34b-13009fb82d49.png)

This works like charm ... thanks
Please update the other issue(#547 ) with this addition patching thing

**Comment by mrousavy** [comment]
Does the library not build without this fix? If yes, please send me a PR so we can merge this change upstream

**Comment by MuhammadAbdullah54321** [comment]
> Does the library not build without this fix? If yes, please send me a PR so we can merge this change upstream

I think the latest version is being build with this patch but version 2.13.0 does not and I was facing this issue in 2.13.0

**Comment by bekatd** [comment]
It's not about build failure, but about ability to use `takePhoto()` or `takeSnapshot()` without patching this two modules for RNVC - v2.13.0
1. https://github.com/mrousavy/react-native-vision-camera/commit/3850491b9f443257880964a4b0c0c70f484ab4f3#diff-92d80895b33f39de63569aa40b0dca15e3a6d1472f2536587b983af76711909c
2. https://github.com/mrousavy/react-native-vision-camera/commit/fe0129522634441733bfab624cbac4ebace8c326#diff-deec7b07b02523dd2ce0f8bc7116284c469ed4ddf58dacbefa2e76476f11730f
