### ISSUE TITLE
❓ How can I take Snapshot on IOS?

### ISSUE THREAD

**Issue by RoysyLee** [cuvent/react-native-vision-camera#1034]
### Question

I want to take a snapshot only restricted showing camera view frame, not full-screen photo.
I use 'takeSnapshot' function on Android.
But on IOS, that function is not supported.
How can I take Snapshot on IOS?

### VisionCamera Version

2.13.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
You can't take a snapshot on iOS at the moment. It is documented as Android only. On iOS, you can just use `takePhoto`.
