### ISSUE TITLE
🐛 Pinch zoom and pan (slide) zoom are not in sync...

### ISSUE THREAD

**Issue by nica0012** [cuvent/react-native-vision-camera#1042]
### What were you trying to do?

Based on the example app, I am looking to allow my users to  be able to zoom in by pinching or sliding their finger up/down while recording.

While both work, they are not in sync with each other. 

### What happened instead?

For example, if I zoom in with the pinch, then start recording and zoom out with my finger, the video will glitch because the zoom is not in sync.

I have tried to use enableZoomGesture={true} but I am getting the same problem.

Has anyone experiencing this same issue, I'd love some guidance resolving this!

### Device

iPhone 13 Pro Max / iPhone XS

### VisionCamera Version

2.13.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Well this problem is not caused by VisionCamera. How should `enableZoomGesture` know the offset of your custom animation value for `zoom`? 

You need to create the pinch animation yourself and set `enableZoomGesture` to false. Then you can correctly calculate the offset (starting point) from the pan gesture and vice versa

**Comment by forward-S** [comment]
@mrousavy This pacakge looks very good.
I set up custom pinch gesture according to the example. But there is some delay betwen moving the fingers and zoom effect.
How can I synchronize smoothly pinch gesture with zoom effect ?
