### ISSUE TITLE
Unable to get the zoom value❓ 

### ISSUE THREAD

**Issue by KaushalLalani98** [cuvent/react-native-vision-camera#1046]
### Question

I am able to zoom the camera with the help of enableZoomGesture={true} but unable to get the zoom value?

### What I tried

I also tried the example i am able to get the zoom value in the example provided but unable to get it in my project the difference is the example is in typeScript and i am coding in javaScript.

### VisionCamera Version

2.13.1

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
`enableZoomGesture` handles the zoom value internally. To manage the zoom value you need to add a custom Gesture (Reanimated + RNGH) and pass that to `zoom` (if REA, via animatedProps)
