### ISSUE TITLE
Is startRecording / stopRecording synchronous using jsi❓ 

### ISSUE THREAD

**Issue by angelos3lex** [cuvent/react-native-vision-camera#1058]
### Question

On my use case i need to know the exact time the video stopped capturing and also the time that the recording has started. I do not see a callback for the start of capture (as there was on the react native camera repo), i assume this is because the call happens synchronously using jsi? Or is this happening using the bridge, thus there may be over 16 ms until this actually calls the native start recording function? 
Same question for the stop capturing, i.e, on below code, will the `x++` line log be called after the native `stopCapturing` is called or i should wrap it inside a `setImmediate` or something as its not calling the native function synchronously?

```
camera.stopCapturing();
x++;
```
Thank you in advance!!

### VisionCamera Version

2.13.3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey - no.
