### ISSUE TITLE
Can I use this Library with Banuba library?❓ 

### ISSUE THREAD

**Issue by CMLCNL** [cuvent/react-native-vision-camera#1070]
### Question

Banuba; An sdk that provides filters like snapchat. How can we use this library with react native vision camera.

 When you review this link, you will understand much better what I am talking about.
`https://github.com/Banuba/ve-sdk-ios-integration-sample`

### VisionCamera Version

2.13.3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey! I don't think that's possible as of today. Or you need to write a separate View Module to render the filter ontop of the camera. But VisionCamera does not have a way to "draw back to the camera surface" (yet).
