### ISSUE TITLE
❓ How Can I stream Camera feed in Apple device using Apple Air Play(Only camera feed not entire screen)

### ISSUE THREAD

**Issue by harmit001** [cuvent/react-native-vision-camera#1071]
### Question

How Can I stream Camera feed in Apple device using Apple Air Play(Only camera feed not entire screen)

### VisionCamera Version

2.13.3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hi! This is possible in a Frame Processor plugin. You need to write the streaming code in the Plugin, which is in Swift just like any other iOS app. I'm sure Stackoverflow has useful resources for "sending a CMSampleBuffer over AirPlay" (Maybe [this](https://stackoverflow.com/questions/59273300/how-can-i-live-stream-encoded-cmsamplebuffer-and-play-it-on-server-side)?)
