### ISSUE TITLE
Frame processor for legal id card❓ 

### ISSUE THREAD

**Issue by wilav-dev** [cuvent/react-native-vision-camera#1105]
### Question

Hello, is there any frame processor with a rectangle to autocapture a document?

### VisionCamera Version

2.13.5

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
None of which are public afaik - we created a few internally at [Margelo](https://margelo.io) for our clients :)
