### ISSUE TITLE
Convert frame to image

### ISSUE THREAD

**Issue by devtyty** [cuvent/react-native-vision-camera#1107]
### Question

 How to i can convert frame to image?

### VisionCamera Version

2.13.5

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by ghost** [comment]
I have the same question

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

**Comment by MaganAnkur** [comment]
Is there a way i can save a frame as image?

**Comment by silent-101** [comment]
whats the solution ?? can anyone plx help me am trying to process the frame so i can use in my custom ai model with TensorFlow (react native) and i am not able to convert the frame into tensor-frame it gives errors

**Comment by MaganAnkur** [comment]
I was able to do it by using https://www.npmjs.com/package/vision-camera-base64-v3
Though it does not have out of box solution for png or jpeg but I was able to change Native implementation and get jpeg
