### ISSUE TITLE
✨ Press once to record

### ISSUE THREAD

**Issue by bmikaili** [cuvent/react-native-vision-camera#1113]
### What feature or enhancement are you suggesting?

I think it would be great to be able to press once to record and then press again to stop, as some people would want hands-free recording.

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

Manually modifying the gesture handler.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
Hey! 

The example app is built similar to how Snapchat works. The Camera library itself obviously supports this as you just call `startRecording` and `stopRecording` whenever you want to, either with hands free or with holding.
