### ISSUE TITLE
🐛  react-native-reanimated build issue

### ISSUE THREAD

**Issue by mrozkosz** [cuvent/react-native-vision-camera#1120]
### What were you trying to do?

@mrousavy When I install react-native-vision-camera the application builds correctly. But after installing react-native-reanimated it crashes. 

### What happened instead?

BUILD FAILED in 28s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/Documents/app/node_modules/react-native-vision-camera/android/build.gradle' line: 231

* What went wrong:
A problem occurred evaluating project ':react-native-vision-camera'.
> Expected directory '/Users/Documents/app/node_modules/react-native/android' to contain exactly one file, however, it contains more than one file.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s

    at makeError (/Users/Documents/app/node_modules/execa/index.js:174:9)
    at /Users/Documents/app/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/Documents/app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/Documents/app/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@0.0.1 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@0.0.1 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/praca/.npm/_logs/2022-07-05T
![Zrzut ekranu 2022-07-5 o 17 19 31](https://user-images.githubusercontent.com/35972437/177362371-bf284b06-e15d-422d-bf3f-d6b8456bc584.png)
15_05_44_102Z-debug.log

### Device

Android

### VisionCamera Version

2.13.5

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mocanSergiu666** [comment]
"react": "18.0.0"
"react-native": "0.69.3"
"react-native-vision-camera": "^2.14.0"
"react-native-reanimated": "^2.9.1" <--------- After I install this package, the Android build fails with the next error:

* What went wrong:
A problem occurred evaluating project ':react-native-vision-camera'.
> Expected directory '.../node_modules/react-native/android' to contain exactly one file, however, it contains more than one file.

If I uninstall "react-native-reanimated", the build succeeds.

Could anybody take a look at this issue, please? Thanks in advance!

**Comment by spsaucier** [comment]
This PR might fix this issue: https://github.com/mrousavy/react-native-vision-camera/pull/1116

**Comment by crispyfisherman** [comment]
I have the same problem.
I already have react-native-vision-camera in the project. Whenever I install react-native-reanimated and rebuild the project again, it crashes.

It also shows a log with this:
```console
> Configure project :react-native-vision-camera
VisionCamera: node_modules/ found at: /Users/danhsucowboy/Documents/DanHsu/BoxInThePARK/CaptureToEarn/capture2earn-dapp-v0/node_modules
VisionCamera: Building with JSC...
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
VisionCamera: Frame Processors are enabled! Building C++ part...
WARNING:DSL element 'dexOptions' is obsolete and should be removed.
It will be removed in version 8.0 of the Android Gradle plugin.
Using it has no effect, and the AndroidGradle plugin optimizes dexing automatically.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
...
```

**Comment by Mr-Rith** [comment]
> with
i got the same issue

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!
