### ISSUE TITLE
❓No devices are returned on iOS but everything works fine on Android

### ISSUE THREAD

**Issue by lucipacurar** [cuvent/react-native-vision-camera#1129]
### Question

I'm trying to integrate react-native-vision-camera in our project but I can't get it to work on iOS. Although the setup seems fairly simple somehow iOS isn't working. I isolated the problem in this RN TS template generated by the CLI: https://github.com/lucipacurar/react-native-vision-camera-problems

In the Swift code the devices list also looks empty.

### What I tried

I'm using the latest stable MacOS, Xcode, RN 0.68.2.
Played around with permissions but still nothing. I didn't see any weird log output.

### VisionCamera Version

2.13.5

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [x] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by lucipacurar** [comment]
I just read that it actually doesn't work in the iOS Simulator, it only works on real devices. I didn't expect that :D

**Comment by mrousavy** [comment]
Yea, that's a limitation from the iOS Simulator.app, can't do anything about it 🤷  (except of course rendering custom virtual camera, but that's a shit ton of work)

**Comment by lucipacurar** [comment]
I'm a user of react-native-camera and never thought that the iOS Simulator functionality was a custom one :D
