### ISSUE TITLE
🐛 ** BUILD FAILED ** on ios after installing package

### ISSUE THREAD

**Issue by mustafamoe** [cuvent/react-native-vision-camera#1130]
### What were you trying to do?

I just wanted to run the app after installing VisionCamera.

### Reproduceable Code

```tsx
npm i react-native-vision-camera
cd ios && pod install
npm run ios or react-native run-ios
```

### What happened instead?

when the app was running I just got "'CameraView' was null!" and that was before I installed the package, then I shut down metro and ran npm run ios / react-native run-ios. It started saying this:
<img width="1579" alt="Screen Shot 2022-07-08 at 11 13 15 PM" src="https://user-images.githubusercontent.com/72463475/178056204-9c930f7c-ecdc-412f-b73a-3182f837c345.png">
I literally tried everything out there, reinstalled pods / node_modules, I changed IPHONEOS_DEPLOYMENT_TARGET=11.0 or higher it's 12.4 now, I have Xcode on version 13.4, this is my Podfile
<img width="1246" alt="Screen Shot 2022-07-08 at 11 18 21 PM" src="https://user-images.githubusercontent.com/72463475/178056801-bd094d92-baad-40ef-ad8d-2f4733a0b4b1.png">
on android, everything is working like a charm

### Device

iPhone 13 - iOS 15.5

### VisionCamera Version

^2.13.5

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mustafamoe** [comment]
My bad I didn't search enough it's fixed.

**Comment by qeorqer** [comment]
> My bad I didn't search enough it's fixed.

Hi,
Having exactly the same issue. Can you say how did you fix it?
