### ISSUE TITLE
❓ How to change Android path name 

### ISSUE THREAD

**Issue by somiasHtec** [cuvent/react-native-vision-camera#1132]
### Question

When I'm taking a photo and I want to save it, it has this path:

`/data/user/0/com.myapp/cache/mrousavy8999427678902473567.jpg`

Is there a way to set custom path ?
Instead of **mrousavy8999427678902473567.jpg** it should be for example: **somias123456.jpg**

P.S. I'm using react-native-cameraroll to save the picture

### VisionCamera Version

2.13.3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Ah whoops probably left that in there back when I was developing the lib - no there's currently no way to change my branding there it has to be edited in the code 🙈

**Comment by micm0** [comment]
Hello @mrousavy, do you plan to add a path property to TakePhotoOptions ?

**Comment by fudr** [comment]
> Ah whoops probably left that in there back when I was developing the lib - no there's currently no way to change my branding there it has to be edited in the code 🙈

Hi, how do I get the final path after CameraRoll.save ?

**Comment by mindrootstech** [comment]
Did you get the Image from path "/data/user/0/com.myapp/cache/mrousavy8999427678902473567.jpg"?
I got a warning in android, but it is working fine on iOS
Warning: Image source "file path" doesn't exist

any solution?
please suggest to me how I can get data from the cache path?

**Comment by mrousavy** [comment]
Try with `file://` prefix

**Comment by mindrootstech** [comment]
> Try with `file://` prefix

Thanks, working fine

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.
