### ISSUE TITLE
Simple example in JS that prove it works ❓ 

### ISSUE THREAD

**Issue by Productivix** [cuvent/react-native-vision-camera#1133]
### Question

Now that the compilation pass the build step in 0.69.1,
lets focus on documenting and demonstrating and have picture (simple example), but in JS (not TSX)
(actual doc is so high in level , that the basics are not fulfilled)

### What I tried

I make : 
yarn add react-native-vision-camera

and in App.js put : 
'''
import React, {useEffect, useState} from 'react';
import {
  Camera,
  CameraPermissionStatus,
  useCameraDevices,
} from 'react-native-vision-camera';

import {SafeAreaView, LoadingView} from 'react-native';

const App = () => {
  const devices = useCameraDevices();
  const device = devices.back;
  const [cameraPermission, setCameraPermission] = useState();
  const [microphonePermission, setMicrophonePermission] = useState();

  useEffect(() => {
    Camera.getCameraPermissionStatus().then(setCameraPermission(true));
    Camera.getMicrophonePermissionStatus().then(setMicrophonePermission(true));
  }, []);

  console.log(
    `Re-rendering Navigator. Camera: ${cameraPermission} | Microphone: ${microphonePermission}`,
  );

  if (cameraPermission == null || microphonePermission == null) {
    // still loading
    return null;
  }

  if (device == null) return <LoadingView />;
  return (
    <SafeAreaView>
      <Camera device={device} isActive={true} />
    </SafeAreaView>
  );
};

export default App;

'''
but does not work 
after yarn run android, I get a successful build but an erro in Metro : 
'''
LOG  Re-rendering Navigator. Camera: true | Microphone: true
 ERROR  Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at App.js:39.
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in test_rn_qrscan(RootComponent) (at renderApplication.js:60)
 ERROR  Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

'''
Do you have please a simple app.js to take a picture ? 

### VisionCamera Version

2.13.5

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by Productivix** [comment]
hi, 
I see in "additional information" the question "I am using Expo" : do that mean that this package is only for Expo ?
My first question seems to me simple to answer and would help many people here : can we have an answer please ?
thanks

**Comment by EKOzkan** [comment]
You can use this if you still need an example app.

```
import { StyleSheet, Text, PermissionsAndroid} from 'react-native';
import {useEffect} from 'react';
import { useCameraDevices, Camera} from 'react-native-vision-camera';

const requestCameraPermission = async () => {
    try {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.CAMERA,
        {
          title: "Sample Photo App Camera Permission",
          message:
          "Sample Photo App needs access to your camera " +
          "so you can take awesome pictures.",
          buttonNeutral: "Ask Me Later",
          buttonNegative: "Cancel",
          buttonPositive: "OK"
        }
      );
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log("You can use the camera");
      } else {
        console.log("Camera permission denied");
      }
    } catch (err) {
      console.warn(err);
    }
  };


export default function App() {
  
  console.log("App Started");

  useEffect(() => {
    requestCameraPermission();
  }, []);
  

  const devices = useCameraDevices()
  const device = devices.back

  if (device == null){ return <Text>Loading</Text>}
  else{
    return (
      <Camera
      style={StyleSheet.absoluteFill}
      device={device}
      isActive={true}>
      </Camera>

      
    )
  }

}
```

**Comment by mrousavy** [comment]
> do that mean that this package is only for Expo ?

No, you answered your own question because you can select "I am using Expo" or bare React Native in that menu.

As for the example code, @EKOzkan was so kind and shared some. :)

**Comment by Productivix** [comment]
hi, I just tested late :  thank you @EKOzkan , it works now !

**Comment by NLanese** [comment]
I am still getting the same error as I was before using that code snippet. Are the any obvious potential package conflicts?
