### ISSUE TITLE
🐛 Unable to build  in  react native 0.69.1 

### ISSUE THREAD

**Issue by rvuyyuru1** [cuvent/react-native-vision-camera#1134]
### What were you trying to do?

error Failed to install the app. Make sure you have the Android development environment set up: 

FAILURE: Build failed with an exception.

..\node_modules\react-native-vision-camera\android\build.gradle' line: 231A problem occurred evaluating project ':react-native-vision-camera'.

> Expected directory '..\node_modules/react-native/android' to contain exactly one file, however, it contains more than one file.

### What happened instead?

unable to build the app

### Device

android 

### VisionCamera Version

2.13.5

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by Manojkumar-Ainqa** [comment]
Hi @rvuyyuru1. Is the above issue solved for you?

**Comment by rvuyyuru1** [comment]
> Hi @rvuyyuru1. Is the above issue solved for you? No...  using react-native-camera

**Comment by rvuyyuru1** [comment]
#1116 check this

**Comment by Manojkumar-Ainqa** [comment]
okay @rvuyyuru1, I think the react-native-camera is not working for react native 0.69.1. We need to downgrade the react-native version to 68. Also, the above PR is not merged right.

**Comment by rvuyyuru1** [comment]
yep

**Comment by Manojkumar-Ainqa** [comment]
[#1118](https://github.com/mrousavy/react-native-vision-camera/issues/1118) This solution works for me.

**Comment by rvuyyuru1** [comment]
i will check with it and update back

**Comment by rvuyyuru1** [comment]
Task :react-native-vision-camera:configureCMakeDebug[arm64-v8a] FAILED for me
#1125

**Comment by Manojkumar-Ainqa** [comment]
You're using the react-native version 0.69.1 right?

**Comment by rvuyyuru1** [comment]
> You're using the react-native version 0.69.1 right?

yes

**Comment by Manojkumar-Ainqa** [comment]
Is the npx patch-package command running successfully?
Reference: [#1083](https://github.com/mrousavy/react-native-vision-camera/issues/1083)

**Comment by rvuyyuru1** [comment]
#908 this helped me

**Comment by nica0012** [comment]
I cannot build on this version with IOS. 

I am getting the following error in xCode:

`'react/bridging/CallbackWrapper.h' file not found
`

**Comment by Manojkumar-Ainqa** [comment]
Hi @nica0012 , Yes I'm also facing the same problem for iOS. But the patched package is working for Android alone. I'm also waiting for the iOS fix :)

**Comment by nica0012** [comment]
@Manojkumar-Ainqa Thank you, I have been keeping my eyes peeled for the next update. I think I'll wait this week otherwise I will downgrade to RN v68.

**Comment by rvuyyuru1** [comment]
@nica0012  Better for now switch back to 68

**Comment by aha85b** [comment]
> I cannot build on this version with IOS.
> 
> I am getting the following error in xCode:
> 
> `'react/bridging/CallbackWrapper.h' file not found

Same issue.

**Comment by hengkx** [comment]
0.69.2 Same issue.

**Comment by bglgwyng** [comment]
I found that `react-native-vision-camera` alone worked well, but after installing `react-native-reanimated`, it started to emit the error message reported here.

https://github.com/bglgwyng/visionCameraReport
It only contains scaffolded code from `react-native` cli and `react-native-vision-camera` and `react-native-reanmiated` added to package.json. Clone this repo and try `npm i && npm run android`, then it will fail with the same error. Then you can remove `react-native-reanimated` dependency, and it will work well.

 I guess the problem is with `react-native-reanimated`.

**Comment by danielMuffin** [comment]
rn 0.69.3 fix this

**Comment by tokkozhin** [comment]
RN 0.69.3 fix this

**Comment by BartoszDombrow** [comment]
> RN 0.69.3 fix this

Still same issue

**Comment by doublex** [comment]
0.69.3 works for me

**Comment by BartoszDombrow** [comment]
> 0.69.3 works for me

Did you disable frame processors or just upgrade RN to 0.69.3?

**Comment by doublex** [comment]
Fresh install (0.69.2 failed)

**Comment by alexco2** [comment]
I still have the same problem with version 0.69.3 with this error

```
Build file '.../node_modules/react-native-vision-camera/android/build.gradle' line: 231

A problem occurred evaluating project ':react-native-vision-camera'.
> Expected directory '.../node_modules/react-native/android' to contain exactly one file, however, it contains more than one file.
```

Which is this line

` def rnAAR = fileTree("${nodeModules}/react-native/android").matching({ it.include "**/**/*.aar" }).singleFile`

**Comment by alkunjo** [comment]
> @Manojkumar-Ainqa Thank you, I have been keeping my eyes peeled for the next update. I think I'll wait this week otherwise I will downgrade to RN v68.

Hi @nica0012 have you got it work using RN 68? I've tried on newly created RN 0.68.2 and got the same issue
I installed it with `react-native-reanimated`

**Comment by Zhi0105** [comment]
> Hi @nica0012 , Yes I'm also facing the same problem for iOS. But the patched package is working for Android alone. I'm also waiting for the iOS fix :)

same issue

**Comment by criss02-cs** [comment]
@alexco2 I have the same issue

**Comment by alexco2** [comment]
Fixed with newest release of vision-camera

**Comment by jason840917gmail** [comment]
Same issue with RN 0.71.1
```
"@react-navigation/drawer": "^6.5.7",
    "@react-navigation/native": "^6.1.2",
    "latest": "^0.2.0",
    "patch-package": "^6.5.1",
    "react": "18.2.0",
    "react-native": "0.71.1",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-reanimated": "^2.14.4",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.19.0",
    "react-native-vision-camera": "^2.15.2"
```
```
* Where:
Build file 'D:\Daniel\work\React\NativeStoresMobile\node_modules\react-native-vision-camera\android\build.gradle' line: 279

* What went wrong:
A problem occurred evaluating project ':react-native-vision-camera'.
> Expected directory 'D:\Daniel\work\React\NativeStoresMobile\node_modules\react-native/android' to contain exactly one file, however, it contains no files.
```
