### ISSUE TITLE
Camera devices in simulator❓ 

### ISSUE THREAD

**Issue by jkester1986** [cuvent/react-native-vision-camera#1136]
### Question

I'd like to test this against a simulator. However, I'm not getting any devices returned when I try this

### What I tried

```
  const getDevices = useCallback(async () => {
    try {
      const deviceList = await Camera.getAvailableCameraDevices();
      console.log({ deviceList });
      setDevices(deviceList);
    } catch (e) {
      console.error("trouble getting devices:", e);
    }
  }, []);

  useEffect(() => {
    getDevices();
  }, []);
  ```

deviceList just ends up being an empty array though

### VisionCamera Version

2.13.5

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by aha85b** [comment]
@jkester1986 Could you run the package with iOS?

**Comment by mrousavy** [comment]
Hey! The iOS simulator does not have any simulated camera devices. This is a limitation by the Simulator app.
