### ISSUE TITLE
Camera devices in simulator❓ 

### ISSUE THREAD

**Issue by jkester1986** [cuvent/react-native-vision-camera#1137]
### Question

I'd like to test this against a simulator. However, I'm not getting any devices returned when I try this

### What I tried

```
  const getDevices = useCallback(async () => {
    try {
      const deviceList = await Camera.getAvailableCameraDevices();
      console.log({ deviceList });
      setDevices(deviceList);
    } catch (e) {
      console.error("trouble getting devices:", e);
    }
  }, []);

  useEffect(() => {
    getDevices();
  }, []);
  ```

deviceList just ends up being an empty array though

Also tried this:
```
  const devices = useCameraDevices();
  const device = devices?.back;

  console.log({ devices, device });
```
devices object exists in this case, but all keys (front/back/external/unspecified) are undefined

### VisionCamera Version

2.13.5

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mikerodham** [comment]
This library does not work with simulators as stated in the documentation. 

> The provided library doesn't work on simulators. These steps allow you to mock the library and use it for developing or testing. Based on [Detox Mock Guide](https://github.com/wix/Detox/blob/master/docs/Guide.Mocking.md).

[https://mrousavy.com/react-native-vision-camera/docs/guides/mocking](https://mrousavy.com/react-native-vision-camera/docs/guides/mocking)

I would recommend attaching a device to your development machine or if you're iOS based and using their ARM64 based computers, you can build the app natively as an option within Xcode. 

<img width="281" alt="Screenshot 2022-07-12 at 15 10 26" src="https://user-images.githubusercontent.com/7014362/178510411-a89920c8-90a3-4922-b01c-9a44736b0403.png">

This allows you to leverage the camera (if present) without having to use a physical device.

**Comment by mrousavy** [comment]
Please do not spam issues. This is an almost identical duplicate of #1136, and I gave an answer there.

Also @mikerodham gave a pretty good answer, thanks Mike!

**Comment by jkester1986** [comment]
@mrousavy I'm sorry I was not trying to spam anything. I didn't realize they were a result of the same thing. I opened them at nearly the same time, but separately because I thought they were separate issues.

**Comment by mrousavy** [comment]
No worries :)
