### ISSUE TITLE
Get off beta package of react-native-reanimated

### ISSUE THREAD

**Issue by jpike88** [cuvent/react-native-vision-camera#1151]
### What were you trying to do?

On react-native 0.69.1, and getting weird behaviour with latest react-native-reanimated. Then I noticed that this lib uses a very old, beta branch version. It should get off it and be compatible with the latest version

### What happened instead?

na

### Device

na

### VisionCamera Version

na

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.
