### ISSUE TITLE
MACOS: Being able to choose different audio input

### ISSUE THREAD

**Issue by jpike88** [cuvent/react-native-vision-camera#1165]
### What feature or enhancement are you suggesting?

I've built and run the library perfectly for macOS, but problem is I have a webcam plugged into my MacBook which I use instead. There seems to be no way to be able to choose which microphone to use for recording video, as I use my MacBook in clamshell mode, it means that my videos are silent.

However, my webcam was picked up (probably because was the only available video device) which is nice. I assume for now that the video devices method would behave correctly if the laptop was open, giving me a choice of video input. Just need audio to be handled as well.

### What Platforms whould this feature/enhancement affect?

iOS

### Alternatives/Workarounds

none at this point, other than forking the library

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
Hey! Unfortunately not, at the moment the default audio source is used.
