### ISSUE TITLE
🐛 Can't capture photo on iOS if I set preset

### ISSUE THREAD

**Issue by somiasHtec** [cuvent/react-native-vision-camera#1167]
### What were you trying to do?

Working in a team developing tablet app. I noticed that on some iPads we can't use preset="hd-3840x2160" it's returning issue that camera is not initialized. 

Permission to use camera and conditional to hide camera if device is null or it doesn't have required permission shouldn't cause any problems because it's already implemented and working on another (iOS) device.

Could this preset cause me a problem because this specific iPad doesn't support **hd-3840x2160** resolution or .. ?

Also we're using this library (vision-camera) just to take pictures nothing else.

### Reproduceable Code

```tsx
const CaptureTestImage = () => {
  const devices = useCameraDevices('wide-angle-camera');
  const device = devices.back;
  const camera = useRef<Camera>(null);

  const [hasPermission, setHasPermission] = useState<boolean>(false);
  const [photoPath, setPhotoPath] = useState<string>('');

  useEffect(() => {
    (async () => {
      const status = await Camera.requestCameraPermission();
      setHasPermission(status === 'authorized');
    })();
  }, []);

  const handleCapture = async () => {
    try {
      const photo = await camera.current?.takePhoto();
      if (photo?.path) {
        setPhotoPath(photo.path);
      }
    } catch (err) {
      console.log('Error while taking photo: ', err);
    }
  };

  if (!hasPermission) {
    return null;
  }


  return (
    <View style={styles.container}>
      <View style={styles.imageOverlay}>
        <Chip />
      </View>
      <TwoMinuteTimer secondsLeft={secondsLeft} />
      <View style={styles.cameraWrapper}>
        {device != null && hasPermission && (
          <Camera
            style={styles.camera}
            preset="hd-3840x2160"
            ref={camera}
            device={device}
            isActive
            photo
          />
        )}

        <TouchableOpacity onPress={handleCapture} style={styles.captureButtonWrapper}>
          <View style={styles.captureButton} />
        </TouchableOpacity>
      </View>
    </View>
  );
};

export default CaptureTestImage;
```

### What happened instead?

The app throws error: 
**session/camera-not-ready: The Camera is not ready yet! Wait for the onInitialized() callback!**

### Device

iPad 9th generaition

### VisionCamera Version

2.13.3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.
