### ISSUE TITLE
Problem when I try call frameProcessor from useScanBarcodes 🐛 

### ISSUE THREAD

**Issue by huandrey** [cuvent/react-native-vision-camera#1170]
### What were you trying to do?

I`m working in a project that i need use the feature of the qrcode.
When I use the lib react-native-vision-camera in the version 2.13.0, own this problem:
"Frame processors are not enable"
<img width="849" alt="Captura de Tela 2022-07-28 às 15 47 14" src="https://user-images.githubusercontent.com/62030386/181614625-57e589a7-984e-41ad-bca7-e059e7fc5630.png">
So, when use the lib in the version 2.14.0, I own this problem:
<img width="540" alt="Captura de Tela 2022-07-28 às 15 48 18" src="https://user-images.githubusercontent.com/62030386/181614830-50733ea5-e8c4-461e-997f-e5bef57fe30c.png">
<img width="863" alt="Captura de Tela 2022-07-28 às 15 51 03" src="https://user-images.githubusercontent.com/62030386/181615279-5cefebea-8a3a-4fe8-b8a3-63ea43fe9761.png">
<img width="866" alt="Captura de Tela 2022-07-28 às 15 51 35" src="https://user-images.githubusercontent.com/62030386/181615373-e6a6d417-e2e7-4719-9e91-5757ac599b66.png">

I already view this issues and still the same problem
- https://github.com/mrousavy/react-native-vision-camera/issues/626
- https://github.com/mrousavy/react-native-vision-camera/issues/560
- https://github.com/mrousavy/react-native-vision-camera/issues/957
- https://github.com/mrousavy/react-native-vision-camera/issues/1012

### What happened instead?

"Frame processors are not enable"

### Device

POCO F3 XIAOMI

### VisionCamera Version

2.14.0 e 2.13.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Which REA and RN version?

**Comment by huandrey** [comment]
> Which REA and RN version?
@mrousavy 
<img width="239" alt="Captura de Tela 2022-07-29 às 11 40 36" src="https://user-images.githubusercontent.com/62030386/181784139-555a69b3-ee28-4401-a1d3-8754badb21b4.png">

**Comment by mrousavy** [comment]
Please share your Reanimated version.

**Comment by huandrey** [comment]
> Please share your Reanimated version.
@mrousavy 
<img width="298" alt="Captura de Tela 2022-07-29 às 12 12 59" src="https://user-images.githubusercontent.com/62030386/181790195-87f1d8ef-5430-44e0-8e68-6020d8931321.png">

**Comment by mrousavy** [comment]
Did you read the error?

"Frame Processors are disabled because REA v2 does not exist"
