### ISSUE TITLE
❓ Pass image processing results to different frame processors

### ISSUE THREAD

**Issue by xulihang** [cuvent/react-native-vision-camera#1182]
### Question

There may be some use cases that need the cooperation of different frame processors. I wonder if it is possible.

For example, I have to scan a document and then run OCR to extract information. In such a case, I have to pass the bitmap generated by the document scanning frame processor to the OCR frame processor.

### VisionCamera Version

2.14.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hi, yes, you can use multiple Frame Processor Plugins in one frame processor.
