### ISSUE TITLE
Android build failing due to connection timeout while building downloadboost🐛 

### ISSUE THREAD

**Issue by rahul2992** [cuvent/react-native-vision-camera#1200]
### What were you trying to do?

I am building the app by running

npx react-native run-android

I think the download is failing due to a timeout. I have checked I do not have any internet issues at my end.

I am using the expo bare flow for the app. 

### What happened instead?

Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':expo-modules-core:downloadBoost'.
> A failure occurred while executing de.undercouch.gradle.tasks.download.internal.DefaultWorkerExecutorHelper$DefaultWorkAction
   > de.undercouch.gradle.tasks.download.org.apache.hc.core5.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 130274594; received: 53710)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-vision-camera:downloadBoost'.
> A failure occurred while executing de.undercouch.gradle.tasks.download.internal.DefaultWorkerExecutorHelper$DefaultWorkAction
   > de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.ConnectTimeoutException: Connect to https://jfrog-prod-usw2-shared-oregon-main.s3.amazonaws.com:443 [jfrog-prod-usw2-shared-oregon-main.s3.amazonaws.com/52.92.144.89] failed: connect timed out

### Device

All android builds

### VisionCamera Version

2.14.1

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by chandrapal1992** [comment]
follow few steps
1. delete node-modules
2. delete package-lock.json
3. npm i
4. npm run android
