### ISSUE TITLE
Is it possible to do LIVE TEXT with react-native-vision-camera❓ 

### ISSUE THREAD

**Issue by iamabdulhaseeb** [cuvent/react-native-vision-camera#1215]
### Question

I would like to implement a functionality that the user can place a camera on an image and he can copy text from image at that point, I have researched a lot but could not find any resource to do like this,
Is it possible to do this with this package?

### VisionCamera Version

^2.14.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by justindavies** [comment]
I'm looking at this too - but it should be possible with a frame processor and the new Live Text things with IOS 16

**Comment by iamabdulhaseeb** [comment]
Hey justin
If you are free these days
Can we both look together on this thing because I have been stucked on this
thing for days now.
I am creating my own app in which I wanted to implement this

**Comment by marcelxsilva** [comment]
HI @iamabdulhaseeb,

I am using [`vision-camera-ocr`](https://github.com/aarongrider/vision-camera-ocr) to recognize text by camera, I don't understand how I can copy text but text can be shown in terminal easily

**Comment by iamabdulhaseeb** [comment]
Hi @marcelxsilva , thank you for recommending that package, I will try that very soon :)

**Comment by sampadanaik** [comment]
> HI @iamabdulhaseeb,
> 
> I am using [`vision-camera-ocr`](https://github.com/aarongrider/vision-camera-ocr) to recognize text by camera, I don't understand how I can copy text but text can be shown in terminal easily

can we use for ios?

**Comment by marcelxsilva** [comment]
> > HI @iamabdulhaseeb,
> > I am using [`vision-camera-ocr`](https://github.com/aarongrider/vision-camera-ocr) to recognize text by camera, I don't understand how I can copy text but text can be shown in terminal easily
> 
> can we use for ios?

My app is only to Android, I believe that can use in iOS, without problems!!

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.
