### ISSUE TITLE
Is this project deprecated❓ 

### ISSUE THREAD

**Issue by swnei1215** [cuvent/react-native-vision-camera#1216]
### Question

Is this project deprecated❓ 

### What I tried

I tried to post some questions, so far no updates yet.

### VisionCamera Version

^2.14.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by siroccomask** [comment]
No, the creator is still posting comments on PRs so it doesn't seem to be deprecated.

**Comment by mrousavy** [comment]
Lmao, nope.
