### ISSUE TITLE
🐛 Barcode is not recognized correctly

### ISSUE THREAD

**Issue by jacob-li-hj** [cuvent/react-native-vision-camera#1224]
### What were you trying to do?

The scanning speed of the camera is relatively fast, but there is a certain chance that the barcode will be recognized as wrong data. I tried to use the provided demo to test, but there is still such a problem.

### Reproduceable Code

```tsx
"react": "17.0.2",
"react-native": "0.66.3",
"react-native-reanimated": "2.4.1",
"react-native-screens": "3.5.0",
"react-native-vision-camera": "^2.9.4"

import * as React from 'react';

import { StyleSheet } from 'react-native';
import { useCameraDevices, useFrameProcessor } from 'react-native-vision-camera';
import { Camera } from 'react-native-vision-camera';
import { useScanBarcodes, BarcodeFormat, scanBarcodes } from 'vision-camera-code-scanner';

export default function App() {
  const [hasPermission, setHasPermission] = React.useState(false);
  const devices = useCameraDevices();
  const device = devices.back;


  const frameProcessor = useFrameProcessor(
    frame => {
      // eslint-disable-next-line
      'worklet'
      const barcodes = scanBarcodes(frame, [BarcodeFormat.ALL_FORMATS])
      if(barcodes[0]?.content?.data){
        console.log('111111111111', barcodes[0]?.content?.data)
      }
    },
    []
  )

  React.useEffect(() => {
    (async () => {
      const status = await Camera.requestCameraPermission();
      setHasPermission(status === 'authorized');
    })();
  }, []);

  return (
    device != null &&
    hasPermission && (
      <>
        <Camera
          style={StyleSheet.absoluteFill}
          device={device}
          isActive={true}
          frameProcessor={frameProcessor}
          frameProcessorFps={5}
        />
      </>
    )
  );
}
```

### What happened instead?

Barcodes tested:Code-39 type barcode data generated by https://barcode.tec-it.com/en/Code39FullASCII?data=32343242 website：
![image](https://user-images.githubusercontent.com/75781670/188127636-3c15395f-4c64-43e1-b0da-6b0d0743e479.png)
But there is a chance that it will be recognized as wrong data

![image](https://user-images.githubusercontent.com/75781670/188127810-c3ee1ff2-c943-4a67-880e-222f7ccf354b.png)

### Device

All devices have a chance to reproduce

### VisionCamera Version

2.9.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by xulihang** [comment]
Is your camera stable? The barcode image may be blurred which may cause misreading.

You can also turn to this plugin using Dynamsoft Barcode Reader: <https://github.com/tony-xlh/vision-camera-dynamsoft-barcode-reader>, which is more robust.

**Comment by jacob-li-hj** [comment]
> Is your camera stable? The barcode image may be blurred which may cause misreading.
> 
> You can also turn to this plugin using Dynamsoft Barcode Reader: https://github.com/tony-xlh/vision-camera-dynamsoft-barcode-reader, which is more robust.

https://github.com/tony-xlh/vision-camera-dynamsoft-barcode-reader I tested this, it's good. There is no case of scanning the code and showing wrong data now, but this SDK is too expensive. Do you have any other recommendations, thanks.

**Comment by Productivix** [comment]
hi , the problem comes from your barcode printed : I cannot  read the 39-barcode you give here with a professionnal barcode terminal : so work on the barcode print first (the web site you named provide codes in .gif without the quiet zone first) - but if use the 128 font instead of 39 is ok if you make a screen shot copy from their site.
this code attached works .
![Capture](https://user-images.githubusercontent.com/6737060/189586491-d7baa54d-2c6a-40f9-b16e-a9980a75c3f8.JPG)

**Comment by jacob-li-hj** [comment]
> hi , the problem comes from your barcode printed : I cannot read the 39-barcode you give here with a professionnal barcode terminal : so work on the barcode print first (the web site you named provide codes in .gif without the quiet zone first) - but if use the 128 font instead of 39 is ok if you make a screen shot copy from their site. this code attached works . ![Capture](https://user-images.githubusercontent.com/6737060/189586491-d7baa54d-2c6a-40f9-b16e-a9980a75c3f8.JPG)

I'm just giving an example, the barcodes that can have issue are not just code-39 type barcodes. But barcodes in real products also have this issue. According to what you said, we have tested the code-128 type barcode and did not find this issue for the time being, but there are not only code-128 type barcodes in the real situation.

**Comment by Productivix** [comment]
normal : I got some distortions with 39 also : there is no checksum in 39 font, there is on I25, 128 fonts. Do not use 39 in production.

**Comment by jacob-li-hj** [comment]
> normal : I got some distortions with 39 also : there is no checksum in 39 font, there is on I25, 128 fonts. Do not use 39 in production.

Thank you for your answer, but we need to support most types of barcode, if you have any solution please let me know, thank you very much.

**Comment by jacob-li-hj** [comment]
> normal : I got some distortions with 39 also : there is no checksum in 39 font, there is on I25, 128 fonts. Do not use 39 in production.

https://github.com/react-native-camera/react-native-camera/tree/master, I did not find this problem when using react-native-camera, but react-native-camera scan code is too slow. After encountering this problem, I have to continue to use react-native-camera. The difference between the two is that one uses Firebase/MLVision and the other uses GoogleMLKit/BarcodeScanning. I haven't studied it in detail yet, and I don't know why this problem occurs.

**Comment by Productivix** [comment]
I think it's better that you close that issue here and continue on https://github.com/rodgomesc/vision-camera-code-scanner/issues/95

**Comment by jacob-li-hj** [comment]
>

**Comment by jacob-li-hj** [comment]
> I think it's better that you close that issue here and continue on [rodgomesc/vision-camera-code-scanner#95](https://github.com/rodgomesc/vision-camera-code-scanner/issues/95)

I also don't think this is a react-native-vision-camera issue. this is a vision-camera-code-scanner issue. so, close this issue, continue the discussion in https://github.com/rodgomesc/vision-camera-code-scanner/issues/95
