### ISSUE TITLE
✨ Is migrating to camera 2 api possible ?

### ISSUE THREAD

**Issue by tarikko** [cuvent/react-native-vision-camera#1233]
### What feature or enhancement are you suggesting?

I think that migrating to camera 2 api would be a good idea because of the multi device support in android (like switching to an ultra wide camera or to a macro camera on a device that supports it) ...

### What Platforms whould this feature/enhancement affect?

Android

### Alternatives/Workarounds

The alternative is to wait until the team behind camera x library actually add support to multi cameras

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
Yes, in V3 I rewrote the entire thing to Camera2! 🥳
