### ISSUE TITLE
Why the example project provided doesn't work in the debugging mode❓ 

### ISSUE THREAD

**Issue by yogedave** [cuvent/react-native-vision-camera#1234]
### Question

Why the example project provided doesn't work in the debugging mode, give an error - cannot set value of undefined evaluating setAttribute , in one of the reanimated file

### What I tried

Working fine if debugging is off.

### VisionCamera Version

2.14.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.
