### ISSUE TITLE
V2.14.0 CameraView+TakePhoto.kt: (91, 13): Unresolved reference: save❓ 

### ISSUE THREAD

**Issue by Easy47** [cuvent/react-native-vision-camera#1236]
### Question

Hello, I've been stuck for a very long time. The application was working very well before I upgraded to version 2.14.  (I can't go back  to 2.13 since I need this version to be able to return frames in frame processors). Since using version 2.14 I get these errors:
![image](https://user-images.githubusercontent.com/47692583/189418672-b63c1592-2116-4b0b-9dce-ff79e080412e.png)
![image](https://user-images.githubusercontent.com/47692583/189418861-53842d29-0616-49ba-b221-7376e495ab4b.png)

![image](https://user-images.githubusercontent.com/47692583/189420000-bb654366-da0c-430e-b7ed-031e9ce4dc2c.png)

### What I tried

I tried to reinstall SDK, NDK, delete gradle caches, change gradle dist in .gradle/wrapper/dist and many other thing but i really have no more idea. If anyone has solved this problem or has an idea ? Thanks in advance

### VisionCamera Version

2.14.0

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.
