### ISSUE TITLE
detect shapes (circular, square)✨ 

### ISSUE THREAD

**Issue by Productivix** [cuvent/react-native-vision-camera#1241]
### What feature or enhancement are you suggesting?

I think that process can detect geometric shapes as disks, circles, squares ?
Would be useful to count rapidly materials as tubes , bars from a profile photo

### What Platforms whould this feature/enhancement affect?

Android

### Alternatives/Workarounds

not known apart from Google..

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

**Comment by Productivix** [comment]
??

**Comment by mrousavy** [comment]
❓❓
