### ISSUE TITLE
Why when switch isActive camera cause a black flare to refresh it?

### ISSUE THREAD

**Issue by franciscocavalli** [cuvent/react-native-vision-camera#1256]
### Question

Image to have a configuration like instagram home page, when you scroll left, the camera just blurred-out and then activate it, if I do the same thing with vision-camera, when the camera is activated a black flare occurs to refresh the camera and set isActive to true.
Is there a way to make this switching transition smoother?
Thank you

### VisionCamera Version

^2.14.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
This is default camera behaviour.
