### ISSUE TITLE
How to zoom in Android device's❓ 

### ISSUE THREAD

**Issue by AhmadAl-Ghalban** [cuvent/react-native-vision-camera#1271]
### Question

How to zoom in android onPress Screen move in or out zoom ? 

### VisionCamera Version

react-native-vision-camera": "2.13.0"

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Pass a different value to the `zoom` prop. Please read [the documentation](https://mrousavy.com/react-native-vision-camera/docs/guides/zooming).
