### ISSUE TITLE
🐛 I'll be getting crash issues when using video capture

### ISSUE THREAD

**Issue by bhavnaproses** [cuvent/react-native-vision-camera#1272]
### What were you trying to do?

 <Camera
                        onInitialized={() => {
                         setactive(true)
                        }}
                        onError={onError}
                        ref={camera}
                        style={styles.absoluteFill}
                        device={device}
                        isActive={isActive}
                        photo={true}
                        video={isVideo ? true : false}      
                      
                       audio={isVideo ? true : false}
                    />

### Reproduceable Code

```tsx
capture photo is working finally but video not working
```

### What happened instead?

app crashed

### Relevant log output

```shell
no any getting error
```

### Device

Vivi V23e 5g

### VisionCamera Version

2.14.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by deviykeweb** [comment]
I'm having the same issue in my project

**Comment by jaypateljetbro** [comment]
i'm facing same issue.

**Comment by yash-gupta-dev** [comment]
Same here. App crashes when i set video={true'}

**Comment by laurencetroyv** [comment]
facing the same problem with my Realme 8i

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
