### ISSUE TITLE
🐛 App crahsed when try to use frameProcessor for QR code scanning

### ISSUE THREAD

**Issue by ApexcupDeveloper** [cuvent/react-native-vision-camera#1279]
### What were you trying to do?

 "react": "18.1.0",
 "react-native": "0.70.0",
 "react-native-reanimated": "^2.10.0",
"react-native-vision-camera": "^2.14.1",
"vision-camera-code-scanner": "^0.2.0",

### What happened instead?

The app crashed without any error message.

### Device

iPhone 11 Pro, iPhone 8s

### VisionCamera Version

^2.14.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by CaioQuirinoMedeiros** [comment]
@ApexcupDeveloper I haven't tested it on iOS yet, but I'm having crash on Android, you too?
RN 0.69.6 here

**Comment by ApexcupDeveloper** [comment]
Yes.

**Comment by mrousavy** [comment]
No logs from Xcode attached. I cannot reproduce and there is no info here.

**Comment by ApexcupDeveloper** [comment]
App crashed without any information.

**Comment by mrousavy** [comment]
The information is in Xcode. Check your Xcode logs.

**Comment by mrousavy** [comment]
Hey!

JFYI; **VisionCamera V3 now includes a QR/Barcode Scanner!** 😍  Check out the [CodeScanner Documentation](https://www.react-native-vision-camera.com/docs/guides/code-scanning) 🚀 

Try upgrading to V3 if you can, it has a much more stable yet flexible foundation.

If you appreciate me dedicating my free time to improving VisionCamera and implementing features like the Code Scanner, please consider [**sponsoring me on GitHub** 💖](https://github.com/sponsors/mrousavy) to show your support.
