### ISSUE TITLE
✨ Export FrameProcessor type

### ISSUE THREAD

**Issue by obasille** [cuvent/react-native-vision-camera#1289]
### What feature or enhancement are you suggesting?

Export `FrameProcessor` type so it can be used externally (instead of `(frame: Frame) => void`).

It's the type of the object returned by `useFrameProcessor()`.

As a side note, the `frameProcessor` property of `CameraProps` is not using the `FrameProcessor` type:
`frameProcessor?: (frame: Frame) => void;`

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

Typing a frame process with `(frame: Frame) => void` works just fine of course, but it would be nice to be able to use the `FrameProcessor` type.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
