### ISSUE TITLE
Vision Camera:downloadBoost is very very slow on build time🐛 

### ISSUE THREAD

**Issue by hmirzaa** [cuvent/react-native-vision-camera#1290]
### What were you trying to do?

I have followed all the steps and for the first build Vision camera downloadBoost failed, Folly download failed on build time.

Then I started the build again, Configuration part was 100% but on Executing after 96% it started downlaod React-Native-Vision-Camera:DownloadBoost 124MB and its very slow. My internet is working perfectly but this download is like 350Kb in 10 minutes.

### Reproduceable Code

```tsx
Npm run android
```

### What happened instead?

Downloading was very slow. I stopped the build

### Device

OPPO Reno 4

### VisionCamera Version

2.14.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by hmirzaa** [comment]
Tried to clean everything and build again. Now "react native vision camera boost download failed" on build time

**Comment by icc-romeu** [comment]
Hi, did you solve this finally? I think it might be related to server issues but... I'm stuck there.

**Comment by Yunnathai** [comment]
same here

**Comment by allen-hsu** [comment]
hmmm, I got the same issue...

**Comment by EwaGuziejko** [comment]
Issue still exists :/

**Comment by punov** [comment]
Same, today it's incredibly slow again.

**Comment by Hemuxue** [comment]
same issue。

**Comment by EldhoseKuriakose** [comment]
Same issue

**Comment by farhan-spinny** [comment]
same issue

**Comment by Ivanindiani** [comment]
same issue

**Comment by fimak** [comment]
same issue

**Comment by sarthakpranesh** [comment]
same issue
