### ISSUE TITLE
Has anyone been able to get Ml Kit Frame Processors to work with react native 0.70 > ❓ 

### ISSUE THREAD

**Issue by bearsworth** [cuvent/react-native-vision-camera#1294]
### Question

I have been able to install frame processors without issue. Everything works even the frame processor, but once I try to use the the image labeler like the example in frame processors, the IOS app crashes instantly. I have tried all kinds of things to get this to work, changing versions of react reanimated, etc. But to no avail.

If someone does manage to get ML kit frame processors work, please share your React reanimated version and any other versioning you had to specify. It would greatly help. 

### What I tried

All kinds of stuff that I cannot fathom to write it. 

### VisionCamera Version

Multiple versions tried, nothing worked. 

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by viljark** [comment]
I can't get frame processors to run with React Native 0.69 on iOS either.
Android is working fine.

Fails with the generic `Frame Processors are not enabled`.

I've tried: 
Xcode 14 & 13 builds.
Cleared all caches.
babel.config.js is set up (Android works)
`import 'react-native-reanimated'` is specified in the file

My last hope is to disable `use_frameworks!` which is required by @react-native-firebase@15, I'll update my comment when I get to it.

Edit:
So apparently using use_frameworks causes the `Frame Processors are not enabled` runtime crash.
I removed it for now and frame processor is working fine.

**Comment by KonstantinZhukovskij** [comment]
Maybe someone has more working solutions than removing the framework?

**Comment by VladyslavMartynov** [comment]
Have the same error when was trying to use Frame Processors are not enabled in RN v 0.70.1. Any solutions?

**Comment by bearsworth** [comment]
> Have the same error when was trying to use Frame Processors are not enabled in RN v 0.70.1. Any solutions?

I eventually gave up and decided to use expo camera. It might work for some purposes but you are limited to only barcode scanning + face detection. Pretty much the two things I actually needed fortunately. But this is not a great solution if you plan to use ML kit for other stuff. 

I believe vision camera has issues and you may need to download react native camera and figure it out or downgrade your version (which is quite sad).

**Comment by adolfogc** [comment]
It works for me on Android for barcode scanning using RN 0.70.4; need to test it on iOS.

Note: I'm using react-reanimated 2.5.0

**Comment by astanb** [comment]
Yes, I have a fork of vision-camera-code-scanner (had to fork it due to an android mlkit dependency mismatch and it's not maintained) working and my own image labelling ml-kit frame processor for custom models working on iOS and 0.70.5. 

Reanimated 2.13.0
Vision camera 2.15.2

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
