### ISSUE TITLE
❓ Is it possible to render the camera partially

### ISSUE THREAD

**Issue by yittoo** [cuvent/react-native-vision-camera#1328]
### Question

We would like to render camera just partially inside view however camera is rendering 100% device width/height behind the scenes and is overlapping over the `Status Bar` as can be seen in screenshot. Is there a way to write in such a way that we only take the displayed segment into consideration only?

<img width="399" alt="image" src="https://user-images.githubusercontent.com/33281801/200564727-b26c8ea0-2dac-4f73-9b2f-a3cf7e7b105f.png">

### What I tried

We tried `style` and `format` props and changing these but could not quite get it to work.

Relevant Library Versions:
react-native - 0.70.3
react-native-vision-camera: 2.15.2
react - 18.1.0
react-native-reanimated - 2.12.0

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by DomGarza** [comment]
Why would you do such a thing 😮

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖

Preview now has a resizeMode btw
