### ISSUE TITLE
iPhone SE 2nd Generation in portrait mode unable to recognise text on image

### ISSUE THREAD

**Issue by jhonghena** [cuvent/react-native-vision-camera#1336]
### What were you trying to do?

I am using MLKitTextRecognition for recognising text on image. 
Added code below which I am trying for text recognition.
Only iPhone SE 2nd Generation in portrait mode unable to recognise text on image. 
Though on iPhone SE 2nd Generation in landscape mode text recognition works perfect and all other iOS devices working perfect.
I think there is an issue with frame passed in iPhone SE 2nd Generation in portrait mode, will you please help me?
Thanks in advance.

### Reproduceable Code

```tsx
import AVKit
import Vision
import MLKitVision
import MLKitTextRecognition 


@objc(ExamplePluginSwift)

public class ExamplePluginSwift: NSObject, FrameProcessorPluginBase {
    private static var textRecognizer = TextRecognizer.textRecognizer()

    @objc

    public static func callback(_ frame: Frame!, withArgs args: [Any]!) -> Any! {

        guard let imageBuffer = CMSampleBufferGetImageBuffer(frame.buffer) else {

            return nil

        }

        NSLog("ExamplePlugin: \(CVPixelBufferGetWidth(imageBuffer)) x \(CVPixelBufferGetHeight(imageBuffer)) Image. Logging \(args.count) parameters:")



        args.forEach { arg in

            var string = "\(arg)"

            if let array = arg as? NSArray {

                string = (array as Array).description

            } else if let map = arg as? NSDictionary {

                string = (map as Dictionary).description

            }

            NSLog("ExamplePlugin:   -> \(string) (\(type(of: arg)))")

        }

               let visionImage = VisionImage(buffer: frame.buffer)
               visionImage.orientation = .up
            
               textRecognizer.process(visionImage){result, error in
                   guard error == nil, let result = result else {
                    return
                  }

                  print(“# Result text = \(result.text)”
               }
    



        return [

            "example_str": "Test",

            "example_bool": true,

            "example_double": 5.3,

            "example_array": [

                "Hello",

                true,

                17.38,

            ],

        ]

    }

}
```

### What happened instead?

on iPhone SE 2nd Generation in landscape mode text recognition works perfect and all other iOS devices working perfect.

### Device

iPhone SE 2nd Generation (iOS 14.0.1)

### VisionCamera Version

2.14.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖

**Comment by mrousavy** [comment]
Hey - I'm tracking Orientation in this feature request/issue now: https://github.com/mrousavy/react-native-vision-camera/issues/1891 ✨ 

Make sure to upvote or sponsor to support this feature, and leave a comment if you have any additional thoughts/ideas.
