### ISSUE TITLE
When install react-native-vision-camera Build Error❓ 

### ISSUE THREAD

**Issue by mehmettalhairmak** [cuvent/react-native-vision-camera#1359]
### Question

Hello,

I trying build my project after installed react-native-vision-camera but returning some errors.
How can i solve this erros?

React Native version : 0.66.4
Gradle version : 4.2.2

build.gradle file ;

![image](https://user-images.githubusercontent.com/29006999/204131816-0a4f8bc4-86c6-4284-85b2-8299a36eec17.png)

errors ;

![image](https://user-images.githubusercontent.com/29006999/204131781-1c5a89da-33bb-4984-9e43-832a8af4dc54.png)

### VisionCamera Version

^2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by IAmCoder** [comment]
Try changing you `compileSdkVersion` from 30 to 31.

**Comment by mehmettalhairmak** [comment]
> Try changing you `compileSdkVersion` from 30 to 31.

Fixed. Thanks :)
