### ISSUE TITLE
iOS app with frameProcessor crashes after reload 🐛 

### ISSUE THREAD

**Issue by sommcz** [cuvent/react-native-vision-camera#1360]
### What were you trying to do?

When vision camera with any frameprocessor (eg. empty) is used in iOS app, it crashes after reload (both debug and release build). Reload can be triggered by pressing "r" in metro console or with react-native-restart Restart method in regular release (my case for production).

I tried different RN (hermes) versions and different reanimated versions, but behaviour is still the same.

### Reproduceable Code

I prepared simple app based on latest RN (0.70.6) template and tested same behaviour.
When I comment out frameProcessor prop, restart works as expected.

[https://github.com/sommcz/vision-camera-crash-test1](https://github.com/sommcz/vision-camera-crash-test1)

```tsx

  const frameProcessor = useFrameProcessor(frame => {
    'worklet';
    console.log('Hello from frame processor');
  }, []);

  return (
    <View style={{flex:1}}>
      {device ? (
        <Camera
          style={StyleSheet.absoluteFill}
          device={device}
          isActive={true}
          frameProcessor={frameProcessor}
          frameProcessorFps={1}
        />
      ) : (
        <Text>No device yet!</Text>
      )}
    </View>
  );

```

### What happened instead?

Exception happen in debug mode. For non-debug, app just stops (crash).

![obrazek](https://user-images.githubusercontent.com/20799785/204218143-1c5e025d-1acd-4890-950c-466ed3b7dbc9.png)

### Relevant log output

```shell
Exception: com.facebook.react.JavaScript (15): EXC_BAD_ACCESS
Line: HostFunctionHandler.h:11


Build with Xcode version 14
```

### Device

iPhone 12 mini

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by Yunnathai** [comment]
same here

**Comment by Noah-Lc** [comment]
Same here

**Comment by Noah-Lc** [comment]
By the way, it's working fine on Xcode 13, but not on Xcode 14. I was following this, but this push didn't solve the problem.
[🐛 Vision Camera crashes when built with Xcode 14](https://github.com/mrousavy/react-native-vision-camera/issues/1244)

**Comment by sommcz** [comment]
I have this problem in my older version built with Xcode 13 (RN 0.67 and some older version of vision-camera and reanimated). I can't test Xcode13 + latest libraries versions. Can anyone confirm that combinaton?

**Comment by Noah-Lc** [comment]
```
"react-native": "0.70.5",
"react-native-reanimated": "2.12.0",
"react-native-vision-camera": "^2.15.2",
"vision-camera-code-scanner": "^0.2.0"
```
works on Xcode 13, and crash on Xcode 14

**Comment by mrousavy** [comment]
Huh, that's interesting. Wonder what changed in Xcode 14...

I am working on VisionCamera V3, which will use a new Worklet Runtime to replace Reanimated's. This will fix this issue (and probably a ton of other issues related to FPs) and improve performance - but I need companies willing to help fund the development of this project - here's the full proposal for anyone interested: https://gist.github.com/mrousavy/1c8ac7559b88bf0712edd628b27dffea

DM me on Twitter / Email me if you're interested

**Comment by TacticCoder** [comment]
Can confirm that this problem is not Xcode version related, at least on my side.
Test with Xcode 13.4
Test with Xcode 14.1
The same result, after the bundle reloads on IOS I get a crash.

The crash has led me to the  FrameProcessorRuntimeManager.

**Comment by JYBESiU** [comment]
Same with Android

**Comment by abejfehr** [comment]
This bug makes the library unusable for the purposes of scanning a QR code containing the URL of a JS bundle to swap to

**Comment by rocket13011** [comment]
We have the same problem, we have to reload the app. Is it possible to stop the frameprocessor completely? 

Because if I restart my app without going to my page with the active camera + frameprocessor + qrcode I have absolutely no problem restarting.
But when I go on it and leave the stack and restart even 2 minutes after the app crashes.

**Comment by maharjanrajans** [comment]
+1

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by hungnd6282** [comment]
how to resolved?

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
