### ISSUE TITLE
❓ Delete cached images/snapshots from cache

### ISSUE THREAD

**Issue by EKOzkan** [cuvent/react-native-vision-camera#1366]
### Question

Is there any way to clear/delete cached images/snapshots from cache? I used rn-fetch-blob but I am curious if is there any other solutions?

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hi! No, using a library that can perform file IO to delete those files is recommended. Either way, VisionCamera writes to cache so the files should be deleted (maybe after a phone restart)
