### ISSUE TITLE
✨ light detection to activate torch on camera

### ISSUE THREAD

**Issue by Productivix** [cuvent/react-native-vision-camera#1371]
### What feature or enhancement are you suggesting?

I suggest to detect in the camera as the flash for the picture the light level, and place a light threshold under which  which the torch would be activated automatically when it is too dark

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

currently torch is activated manually by a switch

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
Hi! This would be an ideal Frame Processor Plugin - check out the documentation to find out how to build it. Then, in your Frame Processor, just call something like `detectFrameBrightness(frame)` and if it's below a certain threshold, you can set your torch/flash to enabled. :)
