### ISSUE TITLE
Advise on making it work with react-native-hole-view❓ 

### ISSUE THREAD

**Issue by wan54** [cuvent/react-native-vision-camera#1389]
### Question

Hi,

The main question is that is there a way in react-native-vision-camera to adjust the capturing frame size and position so that it's align with that of react-native-hole-view? Anything that is outside of the box won't be scanned.

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by andreiwow2** [comment]
I tried once to do something like this, I think the only way to achieve this would be with math to edit the image after it was taken.

I think you could make use of the frame processor to create your own algorithm.
https://mrousavy.com/react-native-vision-camera/docs/guides/frame-processors-plugins-overview

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖

**Comment by mrousavy** [comment]
And no, SurfaceView is not under normal view hierarchy so this will only work on iOS
