### ISSUE TITLE
🐛 sortDevices doesn't really sort by "best" device

### ISSUE THREAD

**Issue by jackstudd** [cuvent/react-native-vision-camera#1390]
### What were you trying to do?

On an iPhone 12 Pro Max which has 3 cameras, the `sortDevices` function doesn't exactly returns the best back camera : https://github.com/mrousavy/react-native-vision-camera/blob/ae2c28a2c27a2ef6afa276b1b2d2034d2651027c/src/utils/FormatFilter.ts#L18

The function's description says that "`wide-angle-camera`s are ranked higher than others", except it's not the case on my Iphone 12 Pro Max, the "best" back devices are ranked as follow (here is the sorted list of each back device devices) : 

```json
[
   ["ultra-wide-angle-camera", "wide-angle-camera"],
   ["wide-angle-camera"],
   ["ultra-wide-angle-camera","wide-angle-camera","telephoto-camera"],
   ["wide-angle-camera","telephoto-camera"],
   ["ultra-wide-angle-camera"],
   ["telephoto-camera"]
]
```

The best back camera would be the standard "wide-angle-camera" except that here, it's second place.

To fix this, I suggest to add this in the `sortDevices` function : 

```ts
const leftHasUltraWide = left.devices.includes('ultra-wide-angle-camera') && left.devices.length == 2;
const rightHasUltraWide = right.devices.includes('ultra-wide-angle-camera') && right.devices.length == 2;
if (leftHasUltraWide) {
  leftPoints -= 2;
}
if (rightHasUltraWide) {
  rightPoints -= 2;
}
```

Which would decrease the rank of `dual-wide-camera` and result in this : 

```json
[
   ["wide-angle-camera"],
   ["ultra-wide-angle-camera","wide-angle-camera","telephoto-camera"],
   ["ultra-wide-angle-camera","wide-angle-camera"],
   ["wide-angle-camera","telephoto-camera"],
   ["ultra-wide-angle-camera"],
   ["telephoto-camera"]
]
```

### What happened instead?

The cameras were not sorted in the correct order

### Device

iPhone 12 Pro Max

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by JackStudd** [comment]
Misunderstood that we only need to use the neutralZoom attribute

**Comment by jackstudd** [comment]
Misunderstood that we only need to use the neutralZoom attribute
