### ISSUE TITLE
❓ Stream video rather than record?

### ISSUE THREAD

**Issue by Sid-Turner-Ellis** [cuvent/react-native-vision-camera#1393]
### Question

Is there any way to get access to the video stream rather than the end recording? 

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by anderpaz** [comment]
I have the same problem, I need to record the video on the device and transmit the recording in real time.
Does anyone have any suggestions or could help out?

**Comment by Sid-Turner-Ellis** [comment]
Do you need audio? If not then you could look into frame processors

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by fukemy** [comment]
@Sid-Turner-Ellis Can u provide some way to do it? I saw Agora WebRTC can using it by this method:
```
Agora.pushWebRTCFrame(newFrame)
```

 But I dont know how it were decraled

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖

JFYI; You can implement this with a native FP plugin 👍
