### ISSUE TITLE
Application Crash When Face Recog then Code Scanner🐛 

### ISSUE THREAD

**Issue by shiroze** [cuvent/react-native-vision-camera#1404]
### What were you trying to do?

I implement application that do face detection using this package
https://github.com/rodgomesc/vision-camera-face-detector

Then I switch my screen with button to scan QR Code using this package
https://github.com/rodgomesc/vision-camera-code-scanner

The app works fine if the app open one Example:
1. You can Face detect but crash when Scan QR
2. You can Scan QR but crash when Face detect

### Reproduceable Code

```tsx
<View>
<Button>Face Recog</Button>
<Button>Scan QR</Button>
</View>
```

### What happened instead?

My App crashed with emulator force close

### Device

LDPlayer 9 (Android 9)

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey!

JFYI; **VisionCamera V3 now includes a QR/Barcode Scanner!** 😍  Check out the [CodeScanner Documentation](https://www.react-native-vision-camera.com/docs/guides/code-scanning) 🚀 

Try upgrading to V3 if you can, it has a much more stable yet flexible foundation.

If you appreciate me dedicating my free time to improving VisionCamera and implementing features like the Code Scanner, please consider [**sponsoring me on GitHub** 💖](https://github.com/sponsors/mrousavy) to show your support.
