### ISSUE TITLE
🐛[android] navigation problem

### ISSUE THREAD

**Issue by baesumin** [cuvent/react-native-vision-camera#1406]
### What were you trying to do?

I come back from another screen and try to use the camera again.

### What happened instead?

I see only a black screen. But the camera function works.
(If i take a picture on a black screen, the actual screen is taken.)

### Device

s21+ ultra

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by ramssutharr** [comment]
having same issue. are you able to resolved it ?

**Comment by MatBdry** [comment]
Hi !

I think the problem will be fix in V3 (https://github.com/mrousavy/react-native-vision-camera/issues/1251).

As far I'm concerned, I "fixed" the issue by adding a condition on isActive, depending on isFocused props on react-navigation. It forces the Camera to be reload. It's not ideal, but it's better than nothing until V3 is ready :-)

**Comment by baesumin** [comment]
> Hi !
> 
> I think the problem will be fix in V3 (#1251).
> 
> As far I'm concerned, I "fixed" the issue by adding a condition on isActive, depending on isFocused props on react-navigation. It forces the Camera to be reload. It's not ideal, but it's better than nothing until V3 is ready :-)

thanks! :)

**Comment by muzhaqi16** [comment]
I am still having this issue on Android with react-nativgation. I am using the isFocused hook but it still persists.

**Comment by baesumin** [comment]
> I am still having this issue on Android with react-nativgation. I am using the isFocused hook but it still persists.

i resolved it.

const isfocused = useIsFocused();
<Camera isActive={isfocused} .../>

**Comment by dunapanta** [comment]
ﬁFor me it works with @baesumin solution but also if I use useNavigation hook instead of navigation

`const {navigate} = useNavigation();`
```
onPress={() =>navigate('ScreenName', {
          prop
        })
}
```

**Comment by jasbirrajrana** [comment]
still having this issue  I am using the isFocused hook but it still persists.
