### ISSUE TITLE
How to use takeSnapshot in foreground service ❓ 

### ISSUE THREAD

**Issue by MfaXyz** [cuvent/react-native-vision-camera#1408]
### Question

I'm trying to take pictures in foreground. for example taking pictures when the user is in another app. when we are in the app everything is running fine, But when I close the app while the foreground service is active, the camera stops working and gives this error:
```
WARN  Possible Unhandled Promise Rejection (id: 3):
session/camera-not-ready: [session/camera-not-ready] The Camera is not ready yet! Wait for the onInitialized() callback!
```
I am using this for foreground service: https://notifee.app/react-native/docs/android/foreground-service and for camera: https://github.com/mrousavy/react-native-vision-camera

**Here is my code:**
```
const HelloWorldApp = () => {
  const isAppForeground = useIsForeground();
  console.log('In Foreground?: ', isAppForeground);

  const cameraRef = useRef(null);

  const [finalPath, setPhotoPath] = useState('');

  const devices = useCameraDevices();
  const device = devices.front;

  useEffect(() => {
    console.log('useEffect');
    notifee.registerForegroundService(() => {
      console.log('registerForegroundService');
      return new Promise(() => {
        setInterval(() => {
          console.log('setInterval');
          const snapShotTaker = async () => {
            const snapshot = await cameraRef.current.takeSnapshot({
              quality: 20,
              skipMetadata: true,
            });
            console.log(snapshot);
            setPhotoPath('file://' + snapshot.path);
            console.log(finalPath);
          };
          snapShotTaker();
        }, 2000);
      });
    });
  }, []);

  if (device == null) {
    return <ActivityIndicator style={styles.indicator} size="large" />;
  }

  async function onDisplayNotification() {
    // Request permissions (required for iOS)
    await notifee.requestPermission();

    // Create a channel (required for Android)
    const channelId = await notifee.createChannel({
      id: 'default',
      name: 'Default Channel',
    });

    // Display a notification
    await notifee.displayNotification({
      title: 'Foreground service',
      body: 'This notification will exist for the lifetime of the service runner',
      android: {
        channelId,
        asForegroundService: true,
        color: AndroidColor.RED,
        colorized: true,
      },
    });
  }
  const onInitialized = () => {
    console.log('onInitialized');
  };

  return (
    <View style={styles.container}>
      <Camera
        ref={cameraRef}
        style={styles.camera}
        device={device}
        isActive={true}
        onInitialized={onInitialized}
      />
      <Image
        source={{uri: finalPath + '?' + new Date()}}
        style={[styles.image]}
      />

      <TouchableOpacity style={styles.button} onPress={onDisplayNotification}>
        <Text>Start F Service</Text>
      </TouchableOpacity>
    </View>
  );
};
```

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖

**Comment by shaikhkhamroddin** [comment]
try reset and set the isActive prop of camera when switching to other app, by using isAppForeground flag with settimeout use.
