### ISSUE TITLE
🐛 No devices available for iPhone simulator iOS 16.0

### ISSUE THREAD

**Issue by jp-23** [cuvent/react-native-vision-camera#1410]
### What were you trying to do?

I tried to implement the basic setup from the guide.

### Reproduceable Code

```tsx
function App() {
  const devices = useCameraDevices()
  const device = devices.back

  if (device == null) return <LoadingView />
  return (
    <Camera
      style={StyleSheet.absoluteFill}
      device={device}
      isActive={true}
    />
  )
}
```

### What happened instead?

The `device` variable is always undefined and `devices` variable always looks like this:

{"back": undefined, "external": undefined, "front": undefined, "unspecified": undefined}

Neither ever get updated, and the `<Camera>` component never renders.

### Device

iPhone 14 Pro (iOS 16.0) - Simulator for Mac

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by yasintorun** [comment]
Hi, I tried yesterday too.
Result; iOS simulator does not support camera.

Same issue #1136
