### ISSUE TITLE
🐛 iOS 'react/bridging/CallbackWrapper.h' file not found

### ISSUE THREAD

**Issue by salihgun** [cuvent/react-native-vision-camera#1413]
### What were you trying to do?

I was trying to add the library but can not run it

### What happened instead?

![Screenshot 2023-01-09 at 16 26 30](https://user-images.githubusercontent.com/47421572/211318672-982ca399-23e9-469a-9b66-5e6dc3dc0874.png)

### Device

iPhone 14 (iOS 16.0)

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by luchozamora** [comment]
@salihgun make sure you are using `SWIFT_VERSION = 5.2` in your project.
From react-native-camera's [troubleshooting website](https://mrousavy.com/react-native-vision-camera/docs/guides/troubleshooting):
```
3. iii. If the SWIFT_VERSION value is set, make sure it is set to 5.2 or higher.
```

**Comment by senrymori** [comment]
> @salihgun make sure you are using `SWIFT_VERSION = 5.2` in your project. From react-native-camera's [troubleshooting website](https://mrousavy.com/react-native-vision-camera/docs/guides/troubleshooting):
> 
> ```
> 3. iii. If the SWIFT_VERSION value is set, make sure it is set to 5.2 or higher.
> ```

i raised the swift version to 5.2 but it doesn't work (xCode v14.2)

but this answer helped me: https://github.com/mrousavy/react-native-vision-camera/issues/1159#issuecomment-1192621018

when I raised the version to 5.2 and registered this in my Podfile, then the whole project was assembled

```ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
        config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Private/React-bridging/react/bridging" '
        config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_CONFIGURATION_BUILD_DIR)/React-bridging/react_bridging.framework/Headers" '    
       end
    end
  end
```

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by kesha-antonov** [comment]
Having this issue in RN 0.72.0

**Comment by kesha-antonov** [comment]
In RN 0.72 paths changed. Here's fix:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
      config.build_settings['HEADER_SEARCH_PATHS'] << '"${PODS_ROOT}/../../node_modules/react-native/ReactCommon" '
    end
  end
end
```

**Comment by RRaideRR** [comment]
Small reproducible example - don't know if it helps you @mrousavy 

https://github.com/RRaideRR/vision-camera-expo-sdk-49

I'm seeing this only when I enable "useFrameworks": "static"

**Comment by mrousavy** [comment]
Hey thanks!
I'm not sure if VisionCamera can build with static frameworks, let me investigate that in v3. Thanks for the repro!

**Comment by RRaideRR** [comment]
> Hey thanks! I'm not sure if VisionCamera can build with static frameworks, let me investigate that in v3. Thanks for the repro!

before react-native 0.72.0 it did :-)

**Comment by RRaideRR** [comment]
For anyone also using expo SDK 49 or react native 0.72.0 with expo - here is what you need to do to modify the podfile:

1. add a new file e.g. plugins/withPodfile.js
2. in your app.json, add your plugin to the plugins key. 
```
...
    "plugins": [
      [
        "./plugins/withPodfile"
      ],
...
```

This is how my podfile looks like - its my first config plugin, so not quite sure if this is well written but in my project it works :-)

```
const fs = require('fs');
const path = require('path');

const { withDangerousMod, withPlugins } = require('@expo/config-plugins');

async function readFile(path) {
  return fs.promises.readFile(path, 'utf8');
}

async function saveFile(path, content) {
  return fs.promises.writeFile(path, content, 'utf8');
}

module.exports = (config) =>
  withPlugins(config, [
    (config) => {
      return withDangerousMod(config, [
        'ios',
        async (config) => {
          const file = path.join(
            config.modRequest.platformProjectRoot,
            'Podfile',
          );
          const thingsToAdd =
            '  post_install do |installer|\n' +
            '  installer.pods_project.targets.each do |target|\n' +
            '    target.build_configurations.each do |config|\n' +
            "      config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '\n" +
            "      config.build_settings['HEADER_SEARCH_PATHS'] << '\"${PODS_ROOT}/../../node_modules/react-native/ReactCommon\" '\n" +
            '    end\n' +
            '  end\n';

          // replaces the line post_install do |installer| with the content of thingsToAdd
          const contents = (await readFile(file)).replace(
            'post_install do |installer|\n',
            thingsToAdd,
          );
          /*
           * Now re-adds the content
           */
          await saveFile(file, contents);
          return config;
        },
      ]);
    },
  ]);


```

**Comment by kbrandwijk** [comment]
Are there any plans to fix this in the current VisionCamera version?

**Comment by mrousavy** [comment]
Hey @kbrandwijk - unfortunately not, no. I just can't focus on everything - I'm trying to plan my time as effective as possible and in V3 I'll do this - hope you understand

**Comment by kbrandwijk** [comment]
A little note in the readme that RN 0.71 is the last supported version might help in that case...

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖

**Comment by jackylu0124** [comment]
> In RN 0.72 paths changed. Here's fix:
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
>       config.build_settings['HEADER_SEARCH_PATHS'] << '"${PODS_ROOT}/../../node_modules/react-native/ReactCommon" '
>     end
>   end
> end
> ```

@kesha-antonov I have a quick question: should I put the code you mentioned before or after the `react_native_post_install()` and `__apply_Xcode_12_5_M1_post_install_workaround()` calls?

In other words, in my `Podfile`, should I do
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
      config.build_settings['HEADER_SEARCH_PATHS'] << '"${PODS_ROOT}/../../node_modules/react-native/ReactCommon" '
    end
  end

  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false
  )
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end
```

or should I do

```
post_install do |installer|
  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false
  )
  __apply_Xcode_12_5_M1_post_install_workaround(installer)

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
      config.build_settings['HEADER_SEARCH_PATHS'] << '"${PODS_ROOT}/../../node_modules/react-native/ReactCommon" '
    end
  end
end
```

Thanks a lot in advance!
