### ISSUE TITLE
"Expected directory 'node_modules/react-native/android' to contain exactly one file, however, it contains no files"🐛 

### ISSUE THREAD

**Issue by jason840917gmail** [cuvent/react-native-vision-camera#1427]
### What were you trying to do?

Just started a new react native project and install all the necessaries dependencies  to access the camera. I had seen that this issue always comes back with every new  version of RN or React native vision camera.
Dependencies: 
```
"@react-navigation/drawer": "^6.5.7",
    "@react-navigation/native": "^6.1.2",
    "latest": "^0.2.0",
    "patch-package": "^6.5.1",
    "react": "18.2.0",
    "react-native": "^0.71.1",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-reanimated": "^2.14.4",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.19.0",
    "react-native-vision-camera": "^2.15.2"
```

### What happened instead?

![image](https://user-images.githubusercontent.com/53618460/214413844-c71f72f2-0e3d-40ea-ba93-e8c462db6dcc.png)

### Device

Android 12

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by jason840917gmail** [comment]
found this on the last release of react native:
Starting from React Native 0.71, we're not shipping the `/android` folder inside the React Native NPM package
anymore due to sizing constraints on NPM. The Android artifacts are distributed via Maven Central.
You can read more about it in this RFC:
https://github.com/react-native-community/discussions-and-proposals/pull/508

If you're a library author and you're manipulating the React Native .aar files, to extract headers,
extract `.so` files or do anything with it, you're probably doing something wrong. React Native
0.71 ships with all the necessary logic to let you consume it transparently by just using:

```
implementation("com.facebook.react:react-android")
// or to keep backward compatibility with older versions of React Native:
implementation("com.facebook.react:react-native:+")

**Comment by DanielGannage** [comment]
Can confirm, I get the same error with RN 0.71.1

Currently our project cannot barcode scan, which requires older and deprecated modules that are in need of patching. How long do you think it will take before these artifacts get put in the right spot (i.e. the module gets fixed)?

**Comment by markjsc** [comment]
Confirming that we're seeing the same thing with React Native 0.71.1.

Would definitely appreciate any updates or workarounds. We're going to stay on React Native 0.70.x until this is resolved.

Side note - Thanks for all the work on this project!!

**Comment by zzz08900** [comment]
Duplicate of https://github.com/mrousavy/react-native-vision-camera/issues/1418

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!
