### ISSUE TITLE
🐛 iOS EXIF - FocalLenIn35mmFilm incorrect

### ISSUE THREAD

**Issue by MichHighlander** [cuvent/react-native-vision-camera#1430]
### What were you trying to do?

Get the "FocalLenIn35mmFilm" from the EXIF data.

### What happened instead?

I Received a value of 64, i checked at an online EXIF extractor site and i received 28.

### Device

iPhone XR

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
