### ISSUE TITLE
How to run CoreML Model❓ 

### ISSUE THREAD

**Issue by davidarnaub7** [cuvent/react-native-vision-camera#1440]
### Question

I am a complete beginner in swift. I am trying to run a model in CoreML.

From the frame I would have to output a MultiArray(1 × 224 × 224 × 3) entry.

Could someone explain me in detail what I would have to do?

The main problem is that I don't know where and how to use the "object" of my model in the callback function of the frame_processor. As well as I don't know how to cast Frame to MLMultiArray.

I have searched thousands of documents on the internet but I can't find anything and I'm going quite blind.

Any help would be appreciated.

### VisionCamera Version

2.15.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by zzz08900** [comment]
From my understanding you'll need a custom frame processor plugin for that.

https://mrousavy.com/react-native-vision-camera/docs/guides/frame-processors-plugins-overview

Basically, your custom frame processor plugin take in the frame, then you do whatever you want to the frame with Swift in the frame processor plugin and then return whatever you want back to the JS world.
Sounds simple enough, right?

For regular operations related to CVPixelBuffer there are plenty of code snippets floating around like this one
https://stackoverflow.com/questions/34569750/get-pixel-value-from-cvpixelbufferref-in-swift

**Comment by zzz08900** [comment]
If you REALLY want to run AI in the JS world, I recall there's one frame processor plugin that turns frame into base64 string of its content  lying around somewhere.

Found it.
https://github.com/yasintorun/vision-camera-base64

**Comment by davidarnaub7** [comment]
@zzz08900 Sure! I have created the frame processor plugin. The problem I have now is to develop that plugin in Swift.

**Comment by zzz08900** [comment]
> @zzz08900 Sure! I have created the frame processor plugin. The problem I have now is to develop that plugin in Swift.

I never tried CoreML myself but with other AI models, what I usually do is take pixel values(RGB integers) from imput(in my case it's usually a jpg or png file, decoders are everywhere) and store them into an ndArray, then pass them to the AI model.

Also you probably don't want to pass back the output of your model back to JS.

And what do you mean by "object" of my model? I figure those models take in an ndArray and aldo produces a 1d or nd array, and you can derive the final result from the resulting array, isn't that true for your case?

**Comment by nathangabriel27** [comment]
I have the same problem. I need to implement a corelML model, I can create the plugin in swift, but I don't know how to run the frame in the AI ​​and return the coordinates.

**Comment by CodingWithNobody** [comment]
This might help Try this https://www.youtube.com/watch?v=ybiMSEjl5mA

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by myselfuser1** [comment]
try this https://www.youtube.com/watch?v=YR7oeWzIToM

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
