### ISSUE TITLE
🐛 Camera orientation problem

### ISSUE THREAD

**Issue by galkinsden** [cuvent/react-native-vision-camera#1445]
### What were you trying to do?

If all orientations are available for the device, the camera rotates with the device.

### Reproduceable Code

```tsx
import React, { memo, useEffect } from 'react';
import { StyleSheet } from 'react-native';
import Orientation from 'react-native-orientation-locker';
import { Camera as CameraVision, useCameraDevices } from 'react-native-vision-camera';

const Camera = () => {
  const devices = useCameraDevices();
  const device = devices?.back;

  useEffect(() => {
    Orientation.unlockAllOrientations();
    return () => {
      Orientation.lockToPortrait();
    };
  }, []);

  return <CameraVision style={StyleSheet.absoluteFill} device={device} isActive photo enableZoomGesture />;
};

export default memo(Camera);
```

### What happened instead?

If all orientations are available for the device, the camera rotates with the device. The problem is reproduced only on version >= 2.15.3 

https://user-images.githubusercontent.com/46136101/215867915-209860b5-a166-4d44-9ee4-635a5d43c464.MP4

### Device

iPhone SE2

### VisionCamera Version

2.15.3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by alexhernandez** [comment]
```javascript
<CameraVision 
  style={StyleSheet.absoluteFill} 
  device={device} 
  isActive photo 
  orientation="portrait" // <---- this fixed it for me
  enableZoomGesture />;
  ```

**Comment by hightechhorn** [comment]
I have the same issue and still could not fix it, even with the suggested solution above

**Comment by bqrichards** [comment]
Same issue.

**Comment by UmerWarraich95** [comment]
@galkinsden  I have the same issue for IOS when I change camera rotation. For Android, the rotation is working fine.
@mrousavy  can you look into this issue? I know you worked on this library in your free time.

**Comment by mrousavy** [comment]
> @mrousavy can you look into this issue? I know you worked on this library in your free time.

Sorry no I have other things to do right now. If you want this fixed, reach out to us for consulting services: hello@margelo.io

**Comment by zonist** [comment]
Same issue

**Comment by lucksp** [comment]
I am not sure I understand the `orientation` prop expected outcome.  If I read [the docs](https://www.react-native-vision-camera.com/docs/api/interfaces/CameraProps#orientation), it appears that it impacts the captured "output".  

By having the following snippet:
```
<Camera
  photo
  orientation={'portrait'}
  device={device}
  isActive={isActive}
  format={formats?.[0]}
 />
```

I understand the docs to say:  _"If I have my device in landscape, the result will be a landscape picture rotated 90 degrees so that it's visible in `portrait` orientation.  Therefore I don't have to turn my head or device to see the photo since I am holding the phone in portrait mode after the picture is taken"_

However, the result is not this: 
On the web previewing my image is not `portrait`
<img width="487" alt="image" src="https://user-images.githubusercontent.com/15162169/233695550-3a589798-2353-4743-ae0c-140702650380.png">

and neither is it on my app when previewing image:
![image](https://user-images.githubusercontent.com/15162169/233695898-8aca60b3-82fe-4d8d-afef-27e4bd5136f5.png)

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖

**Comment by mrousavy** [comment]
Hey - I'm tracking Orientation in this feature request/issue now: https://github.com/mrousavy/react-native-vision-camera/issues/1891 ✨ 

Make sure to upvote or sponsor to support this feature, and leave a comment if you have any additional thoughts/ideas.

**Comment by luisreiskeys** [comment]
I Just made a module to handle the device orientation
https://www.npmjs.com/package/rn-device-orientation
the usage is pretty simple, and this module get de device orientation, not the interface orientation, so even if the interface is locked on portrait, it will work


to solve on vision camera a jus use like this

![Screenshot 2024-05-31 at 12 15 46](https://github.com/mrousavy/react-native-vision-camera/assets/27819268/a2f41e86-0b89-4bcd-a110-c3813f8a0310)

**Comment by medsabbar** [comment]
this is the workaround that worked for me

```
import ImageResizer from "@bam.tech/react-native-image-resizer";
import Exif from "react-native-exif";

const getCorrectRotation = async (
  imagePath: string,
  orientation: Orientation,
  cameraPosition: CameraPosition,
) => {
  const exifData = await Exif.getExif(imagePath);
  console.log("exifData", exifData);
  const exifOrientation = exifData?.Orientation || 1;

  // Handle iOS front camera mirroring
  const isFrontCamera = cameraPosition === "front";
  const shouldMirror = isFrontCamera && Platform.OS === "ios";

  // Convert EXIF orientation to rotation degrees
  const rotationMap: { [key: number]: number } = {
    1: 0, // Normal
    2: 0, // Normal
    3: 180, // 180° rotated
    4: 180, // 180° rotated
    5: 90, // 90° rotated (right)
    6: 90, // 90° rotated (right)
    7: -90, // 270° rotated (left)
    8: -90, // 270° rotated (left)
  };

  return {
    rotation: rotationMap[exifOrientation] || 0,
    shouldMirror,
  };
};

const { rotation } = await getCorrectRotation(
          oldImage.path,
          oldImage.orientation,
          selectedCamera,
        );
const image = await ImageResizer.createResizedImage(
          oldImage.path,
          oldImage.width,
          oldImage.height,
          "JPEG",
          100,
          rotation,
        );
```

**Comment by vincentsquintero** [comment]
Interesting thread — issues like this really highlight how community support and active contributions shape framework maturity.
For developers working with React Native and looking at react native consulting companies for deeper architectural support, check this out:
https://mobisoftinfotech.com/services/react-native-development-consulting 
It explains how expert guidance helps teams navigate tricky integration challenges. Thanks for the detailed discussion!
