### ISSUE TITLE
✨ Support for 4k with Dolby Vision format matching the native iOS camera quality

### ISSUE THREAD

**Issue by venu-nuncsys** [cuvent/react-native-vision-camera#1446]
### What feature or enhancement are you suggesting?

This library has provided the option for 4k. By capturing the video with 4k option using vision camera, video quality is not matching with the native iOS camera. 
When we check for the captured video(using native iOS camera) info, dolby vision with HEVC decode properties are present but with vision camera we can see only HEVC decode property only. Can you please help us on this feature(dolby vision).

### What Platforms whould this feature/enhancement affect?

iOS

### Alternatives/Workarounds

There are no alternatives for this feature

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖

Do you have any links for the dolby format?
