### ISSUE TITLE
🐛 iOS build error: 'jsi/JSCRuntime.h' file not found

### ISSUE THREAD

**Issue by hoseinfo** [cuvent/react-native-vision-camera#1450]
### What were you trying to do?

Try to build iOS project with Xcode.

### What happened instead?

I faced this issue:

### Device

iPhone14(iOS 16.2)

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by hoseinfo** [comment]
"react-native": "0.71.1"

**Comment by FDiskas** [comment]
If you are not using hermes then it could help

```patch
diff --git a/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h b/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h
index a428c01..663ee4b 100644
--- a/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h	
+++ b/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h	
@@ -22,7 +22,7 @@
   #include <v8runtime/V8RuntimeFactory.h>
 #else
   // JSC
-  #include <jsi/JSCRuntime.h>
+  #include <React_jsc/JSCRuntime.h>
 #endif
 
 using namespace facebook;
```

**Comment by zzz08900** [comment]
I guess a proper title should be: Vision camera breaks on RN 0.71 with Hermes disabled.

(If you enabled Hermes the build script won't be making JSI runtime)

**Comment by mikebouwmans** [comment]
> 

Your solution would trigger `'React_jsc/JSCRuntime.h' file not found`. It should be `#include <React_jsc/JSCRuntime.h>`

**Comment by mikebouwmans** [comment]
> If you are not using hermes then it could help
> 
> ```diff
> diff --git a/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h b/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h
> index a428c01..663ee4b 100644
> --- a/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h	
> +++ b/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h	
> @@ -22,7 +22,7 @@
>    #include <v8runtime/V8RuntimeFactory.h>
>  #else
>    // JSC
> -  #include <jsi/JSCRuntime.h>
> +  #include <React_jsc/JSCRuntime.h>
>  #endif
>  
>  using namespace facebook;
> ```

This solution would trigger `React_jsc/JSCRuntime.h file not found`. It should be `React-jsc/JSCRuntime.h`

**Comment by mikebouwmans** [comment]
Submitted a PR (#1456) with a fix.

**Comment by AntonioLi1** [comment]
> If you are not using hermes then it could help
> 
> ```diff
> diff --git a/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h b/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h
> index a428c01..663ee4b 100644
> --- a/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h	
> +++ b/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h	
> @@ -22,7 +22,7 @@
>    #include <v8runtime/V8RuntimeFactory.h>
>  #else
>    // JSC
> -  #include <jsi/JSCRuntime.h>
> +  #include <React_jsc/JSCRuntime.h>
>  #endif
>  
>  using namespace facebook;
> ```

in which file are you adding this?

**Comment by FDiskas** [comment]
We are using https://www.npmjs.com/package/patch-package

**Comment by hzcfy** [comment]
> > If you are not using hermes then it could help
> > ```diff
> > diff --git a/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h b/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h
> > index a428c01..663ee4b 100644
> > --- a/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h	
> > +++ b/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h	
> > @@ -22,7 +22,7 @@
> >    #include <v8runtime/V8RuntimeFactory.h>
> >  #else
> >    // JSC
> > -  #include <jsi/JSCRuntime.h>
> > +  #include <React_jsc/JSCRuntime.h>
> >  #endif
> >  
> >  using namespace facebook;
> > ```
> 
> This solution would trigger `React_jsc/JSCRuntime.h file not found`. It should be `React-jsc/JSCRuntime.h`

thank you

**Comment by maskowe** [comment]
Is there a specific android file at react-native-node_modules/react-native-vision-camera/android that can be changed with patch-package for the same fix?   I'm using "react-native-vision-camera": "2.15.3" and "react-native": "0.71.3" and have hermes disabled.
Thanks for any suggestions.

**Comment by hzcfy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by maskowe** [comment]
好，谢谢

**Comment by maskowe** [comment]
Nevermind, found it at:
node_modules\react-native-vision-camera\android\src\main\cpp\MakeJSIRuntime.h

**Comment by guthriet1230** [comment]
any resolution here? running into this error on my side too :/ 

RN 0.71.6
react-native-vision-camera ^2.15.4

have to remove Hermes for other purposes

**Comment by Jackwew** [comment]
> "react-native": "0.71.1"



> > > If you are not using hermes then it could help
> > > ```diff
> > > diff --git a/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h b/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h
> > > index a428c01..663ee4b 100644
> > > --- a/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h	
> > > +++ b/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h	
> > > @@ -22,7 +22,7 @@
> > >    #include <v8runtime/V8RuntimeFactory.h>
> > >  #else
> > >    // JSC
> > > -  #include <jsi/JSCRuntime.h>
> > > +  #include <React_jsc/JSCRuntime.h>
> > >  #endif
> > >  
> > >  using namespace facebook;
> > > ```
> > 
> > 
> > This solution would trigger `React_jsc/JSCRuntime.h file not found`. It should be `React-jsc/JSCRuntime.h`
> 
> thank you

I did it like you did, but it didn't work

**Comment by hzcfy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by m1771vw** [comment]
I spent two days trying to figure out what was going on, didn't know it was a hermes thing! Thank you!

Changing this in `/node_modules/react-native-vision-camera/ios/React Utils/MakeJSIRuntime.h` worked
```
-  #include <jsi/JSCRuntime.h>
+  #include <React-jsc/JSCRuntime.h>
```

**Comment by josh-thompson13** [comment]
@m1771vw I got the exact same "file not found" error. Only thing that makes it work is removing the line completely.

**Comment by hzcfy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by SkioFox** [comment]
https://github.com/margelo/react-native-worklets-core/issues/150 @hzcfy could you help me any idea? above link has the detail info about the issue in similar

**Comment by hzcfy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zpinto123** [comment]
This issue is now present on version 4.0.0/4.0.1.

**Comment by hzcfy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
