### ISSUE TITLE
https://mrousavy.com cannot be reached 🐛 

### ISSUE THREAD

**Issue by nikitph** [cuvent/react-native-vision-camera#1464]
### What were you trying to do?

I am trying to read the docs on https://mrousavy.com/react-native-vision-camera/docs/guides/ but the site is down

### What happened instead?

![image](https://user-images.githubusercontent.com/5007879/217721748-eb99175d-e43a-4708-95a9-1c4711890e2a.png)

### Device

desktop browser

### VisionCamera Version

latest

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
It works for me, even after clearing cache

![Screenshot 2023-02-09 at 11 53 29](https://user-images.githubusercontent.com/15199031/217792834-b7cf6479-3cdd-4660-9b96-3ae35451776c.png)

**Comment by nikitph** [comment]
It works for me now with cloudflare warp. I m not sure of the root cause but m glad its not a widespread problem
