### ISSUE TITLE
The Mi 13 can't call the camera❓ 

### ISSUE THREAD

**Issue by OPEN-9** [cuvent/react-native-vision-camera#1480]
### Question

![image](https://user-images.githubusercontent.com/42791280/219538787-9d12a6ba-deac-4299-bd68-24ffa5b38efa.png)

### VisionCamera Version

"react-native-vision-camera": "2.13.0"

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by OPEN-9** [comment]
The Mi 11 And Mi 12， is callable

version：MIUI13

**Comment by OPEN-9** [comment]
xiaomi13 doesn't work

**Comment by zzz08900** [comment]
I bet MIUI 13 is the source of evil here. You should ask them to fix their custom system image.

Also the current version of react-native-vision-camera is 2.15.4 and 2.13.0 is like a whole year behind.

**Comment by mrousavy** [comment]
Sorry not enough details
