### ISSUE TITLE
Programmatically ScreenShot of Camera View After frame Processing❓ 

### ISSUE THREAD

**Issue by subhahu-reddy** [cuvent/react-native-vision-camera#1491]
### Question

I am using React native vision camera for pose detection and I want to take a screenshot programmatically after pose detection is done with the landmarks visible on the camera view 

Need to know How can I do that

### What I tried

I tried taking a screenshot in react native using [react-native-view-shot](https://github.com/gre/react-native-view-shot) but this gives me a black screen in the camera view

I took screenshots of just the camera view and the entire screen too 

![iZd9Vt1k3U0SZ3](https://user-images.githubusercontent.com/88659600/220898519-286bf4c7-6560-4263-9b99-6021e419fac4.png)
![textKVU16Q](https://user-images.githubusercontent.com/88659600/220898527-c02ef578-7ff4-4964-bf21-cd84b5893d04.png)

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
The Camera View is rendered on the GPU so it's not in the Android view hierarchy. You can use `takePhoto()` (with runOnJS) to take a photo or write a Frame Processor Plugin that converts a Frame to a file
