### ISSUE TITLE
How much potential do react-native-vision-camera has with front camera? 

### ISSUE THREAD

**Issue by xts-bit** [cuvent/react-native-vision-camera#1493]
### Question

How much potential does react-native-vision-camera has with the front camera? I mean how high-quality photos can I take using this package with the front camera of both iPhone and android? How can I get the best quality photos? 

### What I tried

After looking at the docs I used some props but how can I make it best? with front camera only 

```
const devices = useCameraDevices('wide-angle-camera');
 const cameraDevice = devices.front;

         <Camera
            ref={cameraRef}
            style={styles.camera}
            device={cameraDevice}
            isActive={true}
            photo={true}
            focusable={true}
            fps={60}
            frameProcessorFps={1}
            preset='hd-3840x2160'
            enableZoomGesture={true}
            hdr={true}
            AutoFocusSystem="phase-detection"
            qualityPrioritization="quality"
            fixOrientation={true}
            enableHighQualityPhotos={true}
            enablePortraitEffectsMatteDelivery={true}
          />
```

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
As good as your phone's camera can take pictures.
