### ISSUE TITLE
No member named 'ShareableValue' in namespace 'reanimated'🐛 

### ISSUE THREAD

**Issue by Romick2005** [cuvent/react-native-vision-camera#1503]
### What were you trying to do?

Build iOS project with react-native-reanimated v3.0.0 (pod 1.11.3).
![image](https://user-images.githubusercontent.com/17779660/222172470-fbc434cb-aa5c-4242-bf4e-128adf136684.png)

### Reproduceable Code

```tsx
npm i react-native-reanimated@latest && cd ios && pod install
```

### What happened instead?

Build failed.

### Relevant log output

```shell
/node_modules/react-native-vision-camera/ios/Frame Processor/FrameProcessorRuntimeManager.mm:146:32 No member named 'ShareableValue' in namespace 'reanimated'
```

### Device

iPhone XS

### VisionCamera Version

latest

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by idrissakhi** [comment]
Actually having the same thing. it's only related to reanimated 3, if you downgrade then it will work just fine

**Comment by st0ffern** [comment]
@idrissakhi thanks!
Downgrade `react-native-reanimated` to `2.14.4` and run `pod install`

**Comment by astanb** [comment]
v3 of this library removes the dependency on reanimated, so if you want to use reanimated v3 then you'll need that.

**Comment by idrissakhi** [comment]
@alexstanbury v3 is in release candidates, so for me, it's not ready yet for implementation

**Comment by astanb** [comment]
@idrissakhi I understand that, just advising the situation. 

Be aware that v2 of reanimated has a lot of memory related issues, so if your app needs to remain open for long periods of time like mine does then your users are going to feel the effects of the memory leaks.

**Comment by albindb92** [comment]
Hi, any fix available for react-native-reanimated v3 without downgrading?

**Comment by TomWq** [comment]
When can react-native-reanimated v3 be compatible

**Comment by deflexable** [comment]
has anyone been able to fix this without downgrading rn-reanimated?

**Comment by bastiaanv** [comment]
v3 doesn't need reanimated. So we need to wait for that I guess?

https://github.com/mrousavy/react-native-vision-camera/issues/1376

**Comment by miguel-martinez-6661** [comment]
I had to downgrade the version and do the following:

a)  add `2.14.4` in `package.json`
b) `rm -rf node-modules`
c) `rm yarn.lock` && `yarn install`
d) `npx pod-install`
e) run project 

I hope this help you.

**Comment by Ahmedhamed77** [comment]
I am facing the same problem with react-native 0.71.6 any solution without downgrading reanimated?

**Comment by bastiaanv** [comment]
We switched to [react-native-camera-kit](https://github.com/teslamotors/react-native-camera-kit). That one does not use reanimated

**Comment by kshanmugam73** [comment]
I encountered the same issue with version 0.71.4, but after updating to `"react-native-reanimated": "^2.3.0"` in my project, I received a positive response.

**Comment by Jad-Jbara** [comment]
As of `reanimated 3`, the reanimated 1 APIs are dropped. This library needs to be updated to support reanimated 3.
Also, one of the maintainers stated that `reanimated 3` isn't supported yet by `react-native-vision-camera`. Check this comment [here](https://github.com/software-mansion/react-native-reanimated/issues/3831#issuecomment-1359263674)

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by Romick2005** [comment]
> Actually having the same thing. it's only related to reanimated 3, if you downgrade then it will work just fine

And now [react-native-reanimated@2.17.0 is not supported by react-native@0.72.0](https://github.com/software-mansion/react-native-reanimated/issues/4522). 
So your downgrade is very bad idea. 

So [react-native-camera-kit](https://github.com/teslamotors/react-native-camera-kit) is probably better option to not have modules that that use internal code of other modules or suggest to add unpublished [react-native-worklets and @shopify/react-native-skia](https://github.com/mrousavy/react-native-vision-camera/pull/1466#issuecomment-1553381626) that you have to install separate as react-native-vision-camera does not have them as internal dependancy.

So +1 for react-native-camera-kit

**Comment by Romick2005** [comment]
If you do not need frame processor you can patch react-native-vision-camera in order to build on iOS with latest react-native-reanimated@3.3.0.
```
--- a/node_modules/react-native-vision-camera/ios/Frame Processor/FrameProcessorRuntimeManager.mm	
+++ b/node_modules/react-native-vision-camera/ios/Frame Processor/FrameProcessorRuntimeManager.mm	
@@ -143,7 +143,7 @@ - (void) installFrameProcessorBindings {
 
     auto viewTag = arguments[0].asNumber();
     NSLog(@"FrameProcessorBindings: Adapting Shareable value from function (conversion to worklet)...");
-    auto worklet = reanimated::ShareableValue::adapt(runtime, arguments[1], runtimeManager.get());
+    // auto worklet = reanimated::ShareableValue::adapt(runtime, arguments[1], runtimeManager.get());
     NSLog(@"FrameProcessorBindings: Successfully created worklet!");
 
     RCTExecuteOnMainQueue([=]() {
@@ -155,9 +155,9 @@ - (void) installFrameProcessorBindings {
         NSLog(@"FrameProcessorBindings: Converting worklet to Objective-C callback...");
 
         auto& rt = *runtimeManager->runtime;
-        auto function = worklet->getValue(rt).asObject(rt).asFunction(rt);
+        // auto function = worklet->getValue(rt).asObject(rt).asFunction(rt);
 
-        view.frameProcessorCallback = convertJSIFunctionToFrameProcessorCallback(rt, function);
+        // view.frameProcessorCallback = convertJSIFunctionToFrameProcessorCallback(rt, function);
         NSLog(@"FrameProcessorBindings: Frame processor set!");
       });
     });

```

**Comment by sravis02** [comment]
@Romick2005 Thank you a lot mate, this works for IOS! 
Do you also have a patch for Android ? :))

**Comment by Romick2005** [comment]
It works for Android as is, but not with the latest reanimation 3.4.0

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
