### ISSUE TITLE
❓

### ISSUE THREAD

**Issue by rajnish05** [cuvent/react-native-vision-camera#1526]
### How to switch camera lens 

I am using Redmi device for testing having 3 camera lens "UW", "WIDE" and "TELE". 
But using "react-native-vision-camera" library I'm unable to access these lens.

### VisionCamera Version

 "react-native-vision-camera": "2.14.1",

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by zzz08900** [comment]
Are you sure those are camera "lens", instead of different (physical) camera modules?
AFAIK UW = Ultra Wide Angle Camera, WIDE = Wide Angle Camera and TELE = Telephoto Camera and those are definitely different camera modules on smart phones.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i
