### ISSUE TITLE
❓ How to get fish eye camera view?

### ISSUE THREAD

**Issue by vvusts** [cuvent/react-native-vision-camera#1527]
### Question

When using phone native camera on the bottom there are option for 0.5x (I think this is fish eye) and 1x zoom.
I am trying to set RNVC view to 0.5x but failing to do so.
This is my code:
```
const [zoom, setZoom] = useState(1);
const [nZoom, setNZoom] = useState(1);

const devices = useCameraDevices();
const device = devices.back;
<Camera
            style={cameraStyles.absoluteFill}
            device={device}
            isActive={true}
            enableZoomGesture={true}
            zoom={zoom}
            neutralZoom={nZoom}
        >
...
</Camera>
```
In camera I have buttons that add/sub 0.5 from each zoom state.
But none value gives me that wide (fish eye) camera.
What value should be set to get it?

### What I tried

I have tried different values from state from 0 and up.
I read similar issues but I can't' understand  what values I need.

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by vvusts** [comment]
I am still trying to get the same result as native camera but no luck.
On native camera when I press .5 I get nice fish eye, but on library can't get same effect.
```
const devices = useCameraDevices("ultra-wide-angle-camera");
const device = devices.back;

const minZoomFactor = device?.minZoom ?? 1;
const neutralZoomFactor = device?.neutralZoom ?? 1;
const maxZoomFactor = device?.maxZoom ?? 1;
const maxZoomFactorClamped = Math.min(maxZoomFactor, 15);

const neutralZoomOut = (neutralZoomFactor - minZoomFactor) / (maxZoomFactor - minZoomFactor);
const neutralZoomIn = (neutralZoomOut / maxZoomFactorClamped) * maxZoomFactor;
const maxZoomOut = maxZoomFactorClamped / maxZoomFactor;

<Camera zoom={maxZoomOut} enableZoomGesture ...
```

This is my device data:
```
{
  "devices": [
    "ultra-wide-angle-camera",
    "wide-angle-camera"
  ],
  "hasFlash": true,
  "hasTorch": true,
  "id": "com.apple.avfoundation.avcapturedevice.built-in_video:6",
  "isMultiCam": true,
  "maxZoom": 123.75,
  "minZoom": 1,
  "name": "Back Dual Wide Camera",
  "neutralZoom": 2,
  "position": "back",
  "supportsDepthCapture": false,
  "supportsFocus": true,
  "supportsLowLightBoost": false,
  "supportsParallelVideoProcessing": true,
  "supportsRawCapture": false
}
```

**Comment by vvusts** [comment]
Is this part of code valid? 
`const devices = useCameraDevices("ultra-wide-angle-camera");`

**Comment by emreharman** [comment]
it's same issue with me. as i see from logs, all the camera's minZoom are 1. Can it cause the problem? I'm still trying to implement fish-eye but can't handle. Have you found any solution?

**Comment by emreharman** [comment]
Hi. I was working about this issuse about 2 days and I found something. In the documentation, they say that there is a neutralZoom for camera types. For example: when we use wide-angle-camera or ultra-wide-angle-camera they have neutralZoom and minZoom attributes. If we start with zoom={neutralZoom} and if neutralZoom: 2; we can zoom out to minZoom:1. Here what documantation says:
```
The Camera's zoom property expects values to be in the same "factor" scale as the minZoom, neutralZoom and maxZoom values - so if you pass zoom={device.minZoom} it is at the minimum available zoom, where as if you pass zoom={device.maxZoom} the maximum zoom value possible is zoomed in. It is recommended that you start at device.neutralZoom and let the user manually zoom out to the fish-eye camera on demand (if available).
```

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖

Check the docs on Camera DEvices for more info
