### ISSUE TITLE
How can i manipulate the image taken❓ 

### ISSUE THREAD

**Issue by RBnavaneeth** [cuvent/react-native-vision-camera#1529]
### Question

How can I crop the photo taken using react native vision camera ? I have a Frame within which the object for the picture taken has to be filled (like a text recognition or barcode) and I want only that portion to be send to backend .

### What I tried

I tried to crop the image buy manipulating image height and width which was failed miserably. 

### VisionCamera Version

2.15.3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Hey - use a separate image processing library post-processing!
