### ISSUE TITLE
❓ Why do I need to Mock?  

### ISSUE THREAD

**Issue by lucksp** [cuvent/react-native-vision-camera#1545]
### Question

I am going thru [the Mocking guide](https://www.react-native-vision-camera.com/docs/guides/mocking), but it doesn't seem to be working for me.  I don't see the `console` message in my terminal:

> [DETOX] Using mocked react-native-vision-camera

So what value does mocking provide?    

Does it also offer video mock support in the simulator?

I see this:
> These mocked modules allows us to get authorized camera permissions, get one back camera available and take a fake photo, while the component doesn't render when instantiated.

Does it generate the camera "view" in the Simulator?  I am not planning to write unit tests since it's a 3rd party library.

### What I tried

(Expo SDK 46)

I followed the instructions, adding 2 new vision camera `e2e` files.

// metro.config:

```
defaultConfig.resolver = {
  ...defaultConfig.resolver,
  assetExts: assetExts.filter(ext => ext !== 'svg'),
  sourceExts: [
    process.env.RN_SRC_EXT && process.env.RN_SRC_EXT.split(','),
    ...defaultConfig.resolver.sourceExts,
  ],
};
```

in package.json, i added the flag for metro with the `dev-client` from Expo:

```
    "eas:dev": "RN_SRC_EXT=e2e.js,e2e.js npx expo start --dev-client",
```

### VisionCamera Version

^2.15.4

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

Here's what I see in my simulator:
![image](https://user-images.githubusercontent.com/15162169/228273745-437b2305-5456-4234-8a26-85400793f291.png)

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
