### ISSUE TITLE
vision-camera torch bug: torch can't be turned off within session

### ISSUE THREAD

**Issue by garmoshka-mo** [cuvent/react-native-vision-camera#1552]
### What were you trying to do?

wanna turn off torch

### Reproduceable Code

```tsx
const [torch, setTorch] = useState('off')

      <TouchableOpacity
        onPress={_ => setTorch(torch == 'off' ? 'on' : 'off')}
      >
        Switch torch
      </TouchableOpacity>

torch={torch}
```

### What happened instead?

torch stays turned on

### Device

android Samsung s20

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by garmoshka-mo** [comment]
it was local issue

**Comment by Tuan1O2** [comment]
I have same issue, first time press change torch 'on' after few seconds it auto set 'off', pressing from the second time onwards is normal 🤳
