### ISSUE TITLE
🐛 "Camera View" is not Fabric compatible yet

### ISSUE THREAD

**Issue by gokul1099** [cuvent/react-native-vision-camera#1554]
### What were you trying to do?

I am using vision camera in rn 0.71.4. There I am, getting this error message. Is that possible to run the vision camera with fabric enabled? 

![Screenshot_1681098993](https://user-images.githubusercontent.com/42144106/230822734-5d35de6f-b80e-46bd-b9a4-764ee353a58e.png)

### Reproduceable Code

```tsx
I used the code from the demo application in this repo.
```

### What happened instead?

Camera not opening because of this.

### Device

Pixel 5(Android 11), Nokia 5.3(Android 12)

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by EazycTee** [comment]
same issue... need help

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by robvigilleadingedje** [comment]
Same

**Comment by robvigilleadingedje** [comment]
Anyone find a solution to this?  App requires new RN architecture..  Anyone know how to disable fabric but keep new architecture?

**Comment by luvnishCapgemini** [comment]
I am facing this same issue. Any workaround?

**Comment by ravindraguptacapgemini** [comment]
@mrousavy please help suggest if the camera feature is not available yet for android? Getting same error "**Camera View is not fabric compatible yet**". Also if there is any workaround we can try to still run camera with fabric on both android and iOS. Thanks

**Comment by ace0109** [comment]
![Screenshot_1688809785](https://github.com/mrousavy/react-native-vision-camera/assets/18433582/5b5e8320-d597-4e6d-86d5-f8d0f0521941)
The same problem in the IOS is no problem

**Comment by ace0109** [comment]
> ![Screenshot_1688809785](https://user-images.githubusercontent.com/18433582/251965747-5b5e8320-d597-4e6d-86d5-f8d0f0521941.png) The same problem in the IOS is no problem

newArchEnabled=false
I set this configuration to false first, because it is not compatible, when will it be compatible?

**Comment by mrousavy** [comment]
Just like all 5 of you discovered, VisionCamera is not yet fabric compatible. 

I didn't work on making it Fabric compatible yet. If you want me to make it run on Fabric, either wait until I have the free time to do so, or pay me to do it: [sponsor me on GitHub](https://github.com/sponsors/mrousavy) :)

**Comment by DominikHinc** [comment]
Hey,
I have prepared an initial support for fabric: https://github.com/mrousavy/react-native-vision-camera/pull/1684

**Comment by keremkurtulus** [comment]
I overcame the issue with the help of this discussion article. 
https://github.com/reactwg/react-native-new-architecture/discussions/135

It may not be an absolute fix but it doesn't hurt to try. This approach could work until this library supports for fabric.

I created `react-native.config.js` file and updated it like here; if you want to know why I use this config file find the discussion article above.
```
module.exports = {
  project: {
    android: {
      unstable_reactLegacyComponentNames: ['CameraView'],
    },
    ios: {
      unstable_reactLegacyComponentNames: ['CameraView'],
    },
  },
};

```

**Comment by ravindraguptacapgemini** [comment]
> module.exports = {
>   project: {
>     android: {
>       unstable_reactLegacyComponentNames: ['CameraView'],
>     },
>     ios: {
>       unstable_reactLegacyComponentNames: ['CameraView'],
>     },
>   },
> };

@mrousavy  Somehow I am able to build the library with this inter-op layer change with Fabric on React Native 0.72.6, but still I see few issues with Events, please check the screenshot 
![MicrosoftTeams-image](https://github.com/mrousavy/react-native-vision-camera/assets/97147467/4a1499ba-587b-43f4-93bd-0c05873f00f6)

**Comment by turkergercik** [comment]
> > module.exports = {
> > project: {
> > android: {
> > unstable_reactLegacyComponentNames: ['CameraView'],
> > },
> > ios: {
> > unstable_reactLegacyComponentNames: ['CameraView'],
> > },
> > },
> > };
> 
> @mrousavy Somehow I am able to build the library with this inter-op layer change with Fabric on React Native 0.72.6, but still I see few issues with Events, please check the screenshot ![MicrosoftTeams-image](https://private-user-images.githubusercontent.com/97147467/283543233-4a1499ba-587b-43f4-93bd-0c05873f00f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMjg5OTcsIm5iZiI6MTcwMjEyODY5NywicGF0aCI6Ii85NzE0NzQ2Ny8yODM1NDMyMzMtNGExNDk5YmEtNTg3Yi00M2Y0LTkzYmQtMGMwNTg3M2YwMGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDEzMzEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMzgwMzhlY2NmNDQ5ZmQ1ZjEyZWQyMjI1MmEzNTQ3YTE5Y2RmNjM2ZDA3NGUwNzZiZmNjMWRmYWEyODk3MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ossgkQz3DK8qPV5gb5lkBLUD2heVmREiltC1AKRfkOU)

same for me

**Comment by fahadhaque007** [comment]
Any one manage to fix this issue?

**Comment by BaseMax** [comment]
Same issue. Any updates?

![image](https://github.com/mrousavy/react-native-vision-camera/assets/2658040/33bbdc2a-8b52-4268-a4fb-97d58fb5cbfc)

**Comment by mrousavy** [comment]
https://github.com/mrousavy/react-native-vision-camera/issues/1554#issuecomment-1628498006

**Comment by nonam4** [comment]
I'm using vision camera `3.8.2` and still recieving this error message, isn't this new version supposed to have fabric support?

**Comment by luicfrr** [comment]
also waiting for a fix

**Comment by felansu** [comment]
+1

**Comment by farwayer** [comment]
@ravindraguptacapgemini @turkergercik
https://github.com/mrousavy/react-native-vision-camera/pull/2569

**Comment by XilinJia** [comment]
no solution for about a year?!

**Comment by CarterSnich** [comment]
What is Fabric? I'm getting this issue, but the camera worked before.
