### ISSUE TITLE
🐛 Orientation always shows as 6

### ISSUE THREAD

**Issue by lucksp** [cuvent/react-native-vision-camera#1572]
### What were you trying to do?

I am trying to determine orientation so that if a photo taken in landscape (horizontal device), it can be viewed as a horizontal photo while holding the device vertically in a portrait orientation.

Since the `orientation` prop is not functioning as expected (there are open bugs & PR #1544 ), i need to make a work around.

I am trying to read the EXIF to have logic around what to do to manipulate the image being saved.

As you can see, the console output shows BOTH images as Orientation of `6`

![IMG_7083 (2)](https://user-images.githubusercontent.com/15162169/234346407-132be61c-75e6-4e09-902e-48e82e5bc456.jpeg) ![IMG_7084 (2)](https://user-images.githubusercontent.com/15162169/234346412-7a3b226e-73ce-4bf5-9a91-799732cecec5.jpeg)

### Reproduceable Code

```tsx
const capturePhoto = async () => {
    if (cameraRef?.current && !snapping) {
      setSnapping(true);
      const photo = await cameraRef.current.takePhoto({
        flash: flashMode,
      });
      console.error('photo.metadata.Orientation: ', photo.metadata.Orientation); // outputs 6

      handleSaveAsset([photo]);
    }
  };

<PinchGestureHandler onGestureEvent={onPinchGesture} enabled={isActive}>
  <ReanimatedCamera
    // Do not add enableZoomGesture since using the Animated lib
    // enableZoomGesture
    ref={cameraRef}
    photo
    device={device}
    isActive={isActive}
    format={formats?.[0]}
    animatedProps={animatedProps}
    orientation={'portrait'} // this doesn't seem to impact output
/>
</PinchGestureHandler>
<TouchableOpacity onPress={capturePhoto} disabled={speedbump}>
  <CameraButtonIcon />
</TouchableOpacity>
```
```


### What happened instead?



I would have expected a different number than 6.

I cannot use the EXIF data to read the orientation of the image.

### Relevant log output

_No response_

### Device

iPhone 13 Pro

### VisionCamera Version

^2.15.4

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by jpike88** [comment]
@mrousavy below commit borked up my app, I had to revert to the older copy of the file.

https://github.com/mrousavy/react-native-vision-camera/commit/bf71901968fcdb7fbb5864c435ff239df23c81a5

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖

JFYI; Camera sensors always have a 90deg orientation

**Comment by mrousavy** [comment]
Hey - I'm tracking Orientation in this feature request/issue now: https://github.com/mrousavy/react-native-vision-camera/issues/1891 ✨ 

Make sure to upvote or sponsor to support this feature, and leave a comment if you have any additional thoughts/ideas.

**Comment by marouane-edghoughi** [comment]
Facing the same issue, orientation metadata always returnin' 6

**Comment by Adeel984** [comment]
I was having the same orientation issue on Samsung devices, here is the code that worked for me.

import ImageResizer from 'react-native-image-resizer'; // import library

// use this code in your function
let { uri} = await ImageResizer.createResizedImage(path, width, height, 'JPEG', 100, 0); // it fixes the orientation issue

**Comment by luis-diego-ruiz** [comment]
This is what is currently happening. 
You can see the image in portrait. However the EXIF Orientation value is wrong. When use this image as input to an image processor like a thumbnail generator, the result is a rotated image.  
![image](https://github.com/user-attachments/assets/8dd31271-f299-44e9-85f8-ce97fae53761)
