### ISSUE TITLE
Best way to draw that accounts for aspect ratio❓ 

### ISSUE THREAD

**Issue by eledahl** [cuvent/react-native-vision-camera#1574]
### Question

Hey hey,

I am trying to draw a pose with this repo. It works great for normal 16:9 iphones but when someone uses an phone pro max which is 19.5:9 then the pose doesn't grow with the screen. 

![IMG_0702](https://user-images.githubusercontent.com/47552416/234489237-9f1b4e63-b92e-45f7-9aea-aea6cd189e02.PNG)

**Comment by eledahl** [comment]
This _may_ actually be a bug. When I console log the frame height and width of the iphone pro max, the ratio is still 16:9. Looking through the formats, it doesn't appear there are any 19.5:9 options that even appear.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by Michal41** [comment]
Hi, i have similar problem, did you resolve it ?
