### ISSUE TITLE
Crash on iOS - Memory Exception🐛 

### ISSUE THREAD

**Issue by mafaqriaz-tr** [cuvent/react-native-vision-camera#1576]
### What were you trying to do?

I opens Camera Screen and Camera is initialized. There are a lot of apps open in background.

### What happened instead?

The app crashes with exception "EXC_BAD_ACCESS: XTUM >
KERN_INVALID_ADDRESS at 0x4650."

### Device

iPhone Xs, iPhone 11 and Other iOS Devices

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
