### ISSUE TITLE
A high MP sample image needed, using this lib❓ 

### ISSUE THREAD

**Issue by ontheway16** [cuvent/react-native-vision-camera#1590]
### Question

Hello,
Searched on web but could not find anything useful, other than some factory samples
Can someone share a link of camera image, taken by this library, "without" pixel binning? I am particularly looking for Xiaomi 10-13 range outputs, but others also work well. I am looking to evaluate detail loss. Therefore, any image format with minimal loss is good for me.

-I am specifically looking for high MegaPixel camera outputs,
-40MP or higher. The higher the better.
-Jpeg or HEIF (or any other that preserves details well, as far as I understand, there is no RAW suppport yet)
Thanks for any help !

### What I tried

n/a

### VisionCamera Version

n/a

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
