### ISSUE TITLE
🐛 Non-fatal Exception: io.invertase.firebase.crashlytics.d [unknown/unknown] androidx.camera.core.v: q.f: CAMERA_DISCONNECTED (2): validateConnectLocked:1084: No camera device with ID "0" currently available

### ISSUE THREAD

**Issue by quantiantechnologies** [cuvent/react-native-vision-camera#1594]
### What were you trying to do?

Some device not loading camera view.

### What happened instead?

User not able to take photo

### Device

Vivo 1814

### VisionCamera Version

latest

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
