### ISSUE TITLE
How to crop a photo at a specific point

### ISSUE THREAD

**Issue by mzeba** [cuvent/react-native-vision-camera#1597]
### Question

Hi there!

I work with react-native-vision-camera which I like for its simplicity and quality of rendering. I would like to make a frame appear on the screen and when capturing the picture, only consider the part that is in the frame. I thought about **frameProcessor** but I'm stuck on the approach. Could someone please guide me?

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by samartsevigor** [comment]
Same problem

**Comment by bglgwyng** [comment]
https://github.com/mrousavy/react-native-vision-camera/issues/1119#issuecomment-1173654329

I think you need to take a photo by `takePhoto` and manipulate the file created after then.
There's no way to crop a photo just when it's taken.

**Comment by mzeba** [comment]
Thank you for your different feedbacks. It's something like this that I wanted to do. 
 <img src="http://i.imgur.com/e8wLCpS.jpg" width="450">

**Comment by samartsevigor** [comment]
I noticed that if you take a photo, then its edges will be larger than what we see in the phone. This creates a large error

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by bryanltobing** [comment]
@parice02 do you able to resolve the issue?

**Comment by bryanprimus** [comment]
@parice02 did you able to resolve the issue?

**Comment by mzeba** [comment]
> @parice02 did you able to resolve the issue?

Oh no!

**Comment by bglgwyng** [comment]
https://github.com/bglgwyng/RNVC3Sandbox/blob/face-recognition-example/ios/FrameProcessors/FaceRecognizer/FaceRecognizerPlugin.swift#L17

Not sure if this code is helpful for you. It crops the faces by rectangles from the frame object.
If I understood it right and this is what you were looking for, I'll share the Android code also soon.

**Comment by mzeba** [comment]
Thanks for your reply. I'm thinking of writing some native code for that. I'm more interested in Android at the moment.

**Comment by bglgwyng** [comment]
@parice02, I came across a situation where it required some time to create an example using my project code. Therefore, here I have decided to share only the cropping logic with you. https://gist.github.com/bglgwyng/4173f6096cf553f98909b0b07fd2e701
I believe you will be able to easily incorporate this code into your own project. It seems to be more related to an Android API matter rather than a specific issue with RNVC3. I suggest exploring alternative avenues where you can receive more helpful responses.

**Comment by mzeba** [comment]
Thanks for the help. I will customize it and integrate it into my code.

**Comment by uzunhair** [comment]
> Я заметил, что если вы сделаете снимок, то его края будут больше, чем мы видим в телефоне. Это создает большую ошибку

Это из-за не правильных пропорций компонента камеры. Посмотрите какие фотографии у вас получаются после съемок, если к примеру их размер 1920 на 1080 (пропорции 1.77777) то на телефоне IphoneX с шириной 375 высота камеры должна быть (375*1.7777 ) ~666.6666. Если нарушена пропорция то по бокам или сверху будут появляться лишние элементы фото

**Comment by SlavaC7** [comment]
> > Я заметил, что если вы сделаете снимок, то его края будут больше, чем мы видим в телефоне. Это создает большую ошибку
> 
> Это из-за не правильных пропорций компонента камеры. Посмотрите какие фотографии у вас получаются после съемок, если к примеру их размер 1920 на 1080 (пропорции 1.77777) то на телефоне IphoneX с шириной 375 высота камеры должна быть (375*1.7777 ) ~666.6666. Если нарушена пропорция то по бокам или сверху будут появляться лишние элементы фото

и как определить настоящие размеры картинки на выходе?

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖

JFYI; this should be handled in post-processing
