### ISSUE TITLE
🐛 The documentation link doesn't load the css correctly

### ISSUE THREAD

**Issue by VitoMars** [cuvent/react-native-vision-camera#1598]
### What were you trying to do?

The documentation link doesn't load the css correctly, specifically I'm referring to the provided "Guides" and "API" links in npm: https://www.npmjs.com/package/react-native-vision-camera

Guides: https://mrousavy.github.io/react-native-vision-camera/docs/guides
API: https://mrousavy.github.io/react-native-vision-camera/docs/api

### What happened instead?

The site formatted with the css should appear

### Device

Web

### VisionCamera Version

It's not important

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
