### ISSUE TITLE
GrRecordingContext.h file not found🐛 

### ISSUE THREAD

**Issue by adityabishtedu** [cuvent/react-native-vision-camera#1602]
### What were you trying to do?

i was building my ios application with react 0.71.7 with skia version : 0.1.191 and getting this header not found error

### What happened instead?

i recieved an import error
<img width="969" alt="image" src="https://github.com/mrousavy/react-native-vision-camera/assets/80385830/833f9c84-a6d8-4f79-a33e-bbf450f9858b">

### Device

iPhone 14

### VisionCamera Version

3.0.0-rc-2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by AnomalousLLC** [comment]
Please reference the discussion thread: https://github.com/mrousavy/react-native-vision-camera/issues/1376

A patch was posted about a month ago.

**Comment by AnomalousLLC** [comment]
Please reference the discussion thread: https://github.com/mrousavy/react-native-vision-camera/issues/1376

A patch was posted, over a month ago, that resolves this issue.

**Comment by psyrenpark** [comment]
I am experiencing a build failure due to the mentioned reasons above. 
The current versions I am using are as follows:

```
"react-native": "0.72.0-rc.2",
"react": "18.2.0",
"react-native-reanimated": "^3.1.0",
"react-native-vision-camera": "^3.0.0-rc.2",
"@shopify/react-native-skia": "0.1.191",
"react-native-worklets": "https://github.com/chrfalch/react-native-worklets#d62d76c",
```

Please share your actual in-use package.json.
Thank you.

**Comment by bglgwyng** [comment]
Please ensure that you set the version of '@shopify/react-native-skia' to 0.1.175 by pinning it.
Another option is to apply the patch, which can be found at https://github.com/mrousavy/react-native-vision-camera/issues/1376#issuecomment-1525731923.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by tomgreco** [comment]
```
"@shopify/react-native-skia": "^0.1.175",
"react-native-worklets": "https://github.com/chrfalch/react-native-worklets#d62d76c",
"react-native-vision-camera": "^v3.0.0-rc.2",
"react-native": "0.70.10",
```

'include/gpu/GrRecordingContext.h' file not found

**Comment by fukemy** [comment]
thanks @bglgwyng , worked to me
@tomgreco  did u tried to re-install pod

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
