### ISSUE TITLE
Get device that would be used for specific view resolution BEFORE rendering

### ISSUE THREAD

**Issue by skizzo** [cuvent/react-native-vision-camera#1608]
### Question

Given the 3 numbers for

1. a view's width (in px), 
2. a view's height (in px), and
3. the device's pixel ratio,

is it possible to determine which device would be used **before** the camera view is actually added to the component tree?

I'm trying to get the `fieldOfView` value of the camera that *would* be used

### What I tried

I tried to use `Camera.getAvailableCameraDevices()` and filtered those out that don't have the `position` property set to `back`. For my test device (iPhone 7) I get 3 different values for all available `fieldOfView` properties, and I'm not sure which one to choose out of those.

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Hey - you are expected to choose your own CameraDevice, so just use the `Camera.getAvailableCameraDevices()` func in a `useEffect` and don't use the `useCameraDevice` func. Then find a device you want, and pass it to the `<Camera>`
