### ISSUE TITLE
🐛 latest version of gradle 1.6.20 is not supported

### ISSUE THREAD

**Issue by sabermed** [cuvent/react-native-vision-camera#1610]
### What were you trying to do?

i have installed a latest version of android studio and nodejs v18 and setup everything correctly then i created a simple app with react-native(not Expo) that only shows button on the center the app running ok but when i installed react-native-vision-camera to use it after that whenever i run npx react-native run-android i get an error of unsupported ktolin gradle extention

### What happened instead?

whenever i type npx react-native run-android i get this error:

The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':react-native-vision-camera' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.30

i think because of the react-native-vision-camera uses version 1.5.30 of kotlin but the version i have is 1.6.20

could you update the react-native-vision-camera to support the latest version of gradle?

### Relevant log output

```shell
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':react-native-vision-camera' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.30
```

### Device

Lenovo ideapad gaming 3 i5 RTX3050

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by Jackson3195** [comment]
Can confirm same issue upgrading to RN 0.71.8

I did get around this by temporarily adding the following to the `android/build.gradle` file

![Screenshot 2023-06-06 at 09 22 31](https://github.com/mrousavy/react-native-vision-camera/assets/11081409/66db523a-4b2b-4dee-9689-f683accb6271)

**Comment by YaoGuangyuan** [comment]
Also have this issue.

**Comment by a792883583** [comment]
> Can confirm same issue upgrading to RN 0.71.8
> 
> I did get around this by temporarily adding the following to the `android/build.gradle` file
> 
> ![Screenshot 2023-06-06 at 09 22 31](https://user-images.githubusercontent.com/11081409/243625665-66db523a-4b2b-4dee-9689-f683accb6271.png)

Hello, I can call normally according to your Settings, but I found a new problem, when I started the debug mode, I found that the app would exit abnormally, and the app would still exit abnormally when I re-opened the app. Have you ever encountered this problem? Now my react-native is the latest version 0.71.8, kotlinVersion = "1.7.0". Thank you

**Comment by eprice122** [comment]
I am seeing this issue as well

**Comment by tahir-jamil** [comment]
i am having the same issue

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by SCJMENGMENG** [comment]
> Can confirm same issue upgrading to RN 0.71.8
> 
> I did get around this by temporarily adding the following to the `android/build.gradle` file
> 
> ![Screenshot 2023-06-06 at 09 22 31](https://user-images.githubusercontent.com/11081409/243625665-66db523a-4b2b-4dee-9689-f683accb6271.png)

it`s useful for me

**Comment by vaecebyZ** [comment]
It is very unfortunate that I am also experiencing the same issue，but it`s save my code and my time XD.

> Can confirm same issue upgrading to RN 0.71.8
> 
> I did get around this by temporarily adding the following to the `android/build.gradle` file
> 
> ![Screenshot 2023-06-06 at 09 22 31](https://user-images.githubusercontent.com/11081409/243625665-66db523a-4b2b-4dee-9689-f683accb6271.png)

**Comment by sahilrathi01** [comment]
i am also having the same issue
![Screenshot 2023-07-12 at 8 56 43 PM](https://github.com/mrousavy/react-native-vision-camera/assets/124804452/493b6ce7-15b1-4311-ac5a-6650b5bf863e)

**Comment by alanwong0922** [comment]
I have the same problem, I set the kotlinVerion as the latest version : 1.8.0, it still not work 

buildscript{ 
ext { 
`kotlinVerion:` 1.8.0
...
}
}

**Comment by laurencetroyv** [comment]
Can confirm same issue on RN 0.72.3
![image](https://github.com/mrousavy/react-native-vision-camera/assets/12975712/e3c65c1a-1183-4be1-b69d-0a33a87ad9e6)

**Comment by Desintegrator** [comment]
> Can confirm same issue on RN 0.72.3 ![image](https://user-images.githubusercontent.com/12975712/255891881-e3c65c1a-1183-4be1-b69d-0a33a87ad9e6.png)

same

**Comment by Mynameisjohndev** [comment]
I'm having the same problem, I've tried several things and so far nothing

**Comment by marklanham** [comment]
> Can confirm same issue upgrading to RN 0.71.8
> 
> I did get around this by temporarily adding the following to the `android/build.gradle` file
> 
> ![Screenshot 2023-06-06 at 09 22 31](https://user-images.githubusercontent.com/11081409/243625665-66db523a-4b2b-4dee-9689-f683accb6271.png)

This done the trick for now, thank you! 🙏

**Comment by VitaminC1989** [comment]
> > Can confirm same issue upgrading to RN 0.71.8
> > I did get around this by temporarily adding the following to the `android/build.gradle` file
> > ![Screenshot 2023-06-06 at 09 22 31](https://user-images.githubusercontent.com/11081409/243625665-66db523a-4b2b-4dee-9689-f683accb6271.png)
> 
> Hello, I can call normally according to your Settings, but I found a new problem, when I started the debug mode, I found that the app would exit abnormally, and the app would still exit abnormally when I re-opened the app. Have you ever encountered this problem? Now my react-native is the latest version 0.71.8, kotlinVersion = "1.7.0". Thank you

I also encountered the same problem. I don't know how to solve it. I am currently using `reactotron-react-native` for development

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
