### ISSUE TITLE
🐛 Error: EPERM: operation not permitted, lstat '...\node_modules\react-native-vision-camera\android\build\intermediates\cxx\Debug\3j3y4s34\obj\arm64-v8a\libVisionCamera.so.tmpfc89ebc' 

### ISSUE THREAD

**Issue by valery-lavrik** [cuvent/react-native-vision-camera#1615]
### What were you trying to do?

installed packages according to `package.json`
started **npm start -- --reset-cache**
then **npm run android**
```
"dependencies": {
    "@dhairyasharma/react-native-encryption": "^1.0.0",
    "@react-native-community/datetimepicker": "^7.0.1",
    "@react-native-community/netinfo": "^9.3.9",
    "@react-native-community/progress-bar-android": "^1.0.5",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "axios": "^1.4.0",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-native": "0.71.7",
    "react-native-blob-util": "^0.17.3",
    "react-native-encrypted-storage": "^4.0.3",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-reanimated": "~2.14.4",
    "react-native-safe-area-context": "^4.5.2",
    "react-native-screens": "^3.20.0",
    "react-native-sqlite-storage": "^6.0.1",
    "react-native-video": "^6.0.0-alpha.6",
    "react-native-vision-camera": "^2.15.4",
    "react-native-webview": "~12.1.0",
    "vision-camera-code-scanner": "^0.2.0"
  },
```

### What happened instead?

After running the **npm run android** command, an error appears in the **metro** console:
```

node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: EPERM: operation not permitted, lstat 'D:\RN\tnt_toro\node_modules\react-native-vision-camera\android\.cxx\Debug\3j3y4s34\arm64-v8a\CMakeFiles\CMakeTmp\cmTC_548d5.tmpecf3f15'
Emitted 'error' event on NodeWatcher instance at:
    at D:\RN\tnt_toro\node_modules\metro-file-map\src\watchers\NodeWatcher.js:231:14 {
  errno: -4048,
  code: 'EPERM',
  syscall: 'lstat',
  path: 'D:\\RN\\tnt_toro\\node_modules\\react-native-vision-camera\\android\\.cxx\\Debug\\3j3y4s34\\arm64-v8a\\CMakeFiles\\CMakeTmp\\cmTC_548d5.tmpecf3f15'
}

```

I checked the folder, it's really empty. There is no file **cmTC_548d5.tmpecf3f15**.

![image](https://github.com/mrousavy/react-native-vision-camera/assets/8047999/c0405870-93ee-40be-9b6f-a167489c560f)

### Device

android studio virtual device

### VisionCamera Version

^2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by valery-lavrik** [comment]
this happened after I lowered react-native-reanimated from version ^3.1.0 to ~2.14.4

**npm start -- --reset-cache**  -   it doesn't help

**Comment by valery-lavrik** [comment]
I tried to downgrade the react-native-vision-camera version to 2.15.3 and got this

![image](https://github.com/mrousavy/react-native-vision-camera/assets/8047999/ca59aeea-21e7-468b-92d1-74a7ee310e47)

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by yousefelgoharyx** [comment]
Same problem here

**Comment by valery-lavrik** [comment]
@yousefelgoharyx 
I found that this is due to react-native-reanimated
I suggest rolling back to
**"react-native-reanimated": "^2.12.0",**

**Comment by Husan-Negmatullaev** [comment]
> @yousefelgoharyx I found that this is due to react-native-reanimated I suggest rolling back to **"react-native-reanimated": "^2.12.0",**

In my case it doesn't work

**Comment by SalehArif** [comment]
> @yousefelgoharyx I found that this is due to react-native-reanimated I suggest rolling back to **"react-native-reanimated": "^2.12.0",**

 it doesn't work for me. I am lost on what version of react-native-reanimated will this work with (v3 doesn't work bcz I'm using frame processors to scan faces)

**Comment by valery-lavrik** [comment]
It works for me like this:
```
    "react-native-reanimated": "^2.12.0",
    "react-native-vision-camera": "^2.15.2",
```

**Comment by SalehArif** [comment]
> It works for me like this:
> 
> ```
>     "react-native-reanimated": "^2.12.0",
>     "react-native-vision-camera": "^2.15.2",
> ```

Getting this error now. Which version of react-native are you using?

![image](https://github.com/mrousavy/react-native-vision-camera/assets/60255252/90d6c2bb-5093-4b30-9957-6db0294368e5)

**Comment by valery-lavrik** [comment]
@SalehArif   it looks like you have too high a version of react-native
try this:


```
"@react-navigation/drawer": "^6.5.0",
"@react-navigation/native": "^6.0.13",
"@react-navigation/native-stack": "^6.9.1",
"react": "18.1.0",
"react-native": "0.70.10",
"react-native-gesture-handler": "2.8.0",
"react-native-reanimated": "^2.12.0",
"react-native-safe-area-context": "^4.4.1",
"react-native-screens": "^3.18.2",
"react-native-vision-camera": "^2.15.2",
"vision-camera-code-scanner": "^0.2.0"
```

**Comment by SalehArif** [comment]
`A problem occurred evaluating project ':react-native-reanimated'.
> Cannot get property 'react' on extra properties extension as it does not exist`

Got this error after using RN v0.70.10 in the existing project. Should I make a new project with this specific version to make sure all dependencies are compatible?

Edit: Its working with a fresh project. Thanks a bunch for the help, I have been having trouble with this for a few days

**Comment by vikingprank** [comment]
I'm having the same issue. I usually simply restart metro and launch the app from my emulator. I still would like to have a real fix to this.
```json
"react-native-reanimated": "2.14.4",
"react-native": "0.71.2",
"react-native-vision-camera": "2.15.4",
```

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out. Can you try and test the PR #1674 for me to see if you can still reproduce this issue here?

Here's an instruction on how you can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

If the issue cannot be reproduced with that version/PR anymore, then hoorayy, I fixed it! 🎉 
Otherwise please let me know and I'll keep this issue open to keep track of it.

Thank you!

**Comment by rezadod** [comment]
downgrade
react-native-reanimated": "^2.12.0"
its work for me

**Comment by bravo-stack** [comment]
> > It works for me like this:
> > ```
> >     "react-native-reanimated": "^2.12.0",
> >     "react-native-vision-camera": "^2.15.2",
> > ```
> 
> Getting this error now. Which version of react-native are you using?
> 
> ![image](https://private-user-images.githubusercontent.com/60255252/248788453-90d6c2bb-5093-4b30-9957-6db0294368e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMTY4NzIsIm5iZiI6MTcwNjExNjU3MiwicGF0aCI6Ii82MDI1NTI1Mi8yNDg3ODg0NTMtOTBkNmMyYmItNTA5My00YjMwLTk5NTctNmRiMDI5NDM2OGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDE3MTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZjdmNWIxNWYxYWE5NzhjYzdmZTc2OGZmYWE4YjMwZjQzYjVmZDNlMDhlODc0MjczYzZkMTYwNTdiNjQwNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7i8tJWGD9QfYQ_5fPLr8of0gubNiRzNFKiOS1B7b-qg)

I'm getting similar error, how were you able to resolve yours?
