### ISSUE TITLE
Trying to get face detector to work but frame processing is unavailable and are not enabled

### ISSUE THREAD

**Issue by kevmai96** [cuvent/react-native-vision-camera#1617]
### What were you trying to do?

I want to get face detecting to work

### Reproduceable Code

```tsx
useEffect(() => {
    console.log(faces, Date.now());
  }, [faces]);

  const frameProcessor = useFrameProcessor((frame) => {
    'worklet';
    const scannedFaces = scanFaces(frame);
    runOnJS(setFaces)(scannedFaces);
  }, []);

  useEffect(() => {
    getPermission()
  }, [])

  return (
    <View style={styles.container}>
      {(device != null && permission == true) && (
        <Camera
          style={{ height: '100%', width: '100%' }}
          device={device}
          isActive={true}
          frameProcessor={frameProcessor}
          frameProcessorFps={5}
        />
      )}
    </View>
  );
```

### What happened instead?

🐛 frame-processor/unavailable: Frame Processors are not enabled. See https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting, js engine: hermes

But only crashed on iOS
Android works great

### Relevant log output

```shell
frame-processor/unavailable: Frame Processors are not enabled. See https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting, js engine: hermes
```

### Device

iPhone 11

### VisionCamera Version

^2.15.4

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by myselfuser1** [comment]
Try this https://www.youtube.com/playlist?list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
