### ISSUE TITLE
❓ Not sure a bug, but I can not get the updated frame after drawing

### ISSUE THREAD

**Issue by fukemy** [cuvent/react-native-vision-camera#1628]
### Description

I want to push frame from Vision Camera to WebRTC, before push frame, I did some draw on it

```

const paint = Skia.Paint()
paint.setColor(Skia.Color("red"))
const frameProcessor = useFrameProcessor((frame) => {
        'worklet';
    
        frame.drawRect({ x: 400, y: 400, width: 100, height: 100 }, paint)
        FrameProcessorPlugins.beautifulFace(frame)
    }, [paint])

```

Here is the captured video in my device:
![Screen Shot 2023-06-20 at 11 19 52](https://github.com/Shopify/react-native-skia/assets/8202437/e58bc84f-99a1-4905-a6b8-b12937341521)

But in implement of `beautifulFace`, I didnt see updated frame, here is the captured image:
<img width="548" alt="Screenshot 2023-06-20 at 11 21 08" src="https://github.com/Shopify/react-native-skia/assets/8202437/95365fef-4055-43dc-a66f-1c84b3096a40">

I am debug using XCode, the code to debug is:
```
@objc(VisionFrameProcessorPlugin) => this called right afterFrameProcessorPlugins.beautifulFace(frame)
public class VisionFrameProcessorPlugin: NSObject, FrameProcessorPluginBase {
  @objc public static func callback(_ frame: Frame!, withArgs _: [Any]!) -> Any! {
    guard let imageBuffer = CMSampleBufferGetImageBuffer(frame.buffer) else {
      return nil
    }
    WebRTC.sendBuffer(frame.buffer)
...
```

Can u give me some advice

### What I tried

1. draw on to frame
2. check frame again

### VisionCamera Version

3.0.0 rc2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey - yep this is how it currently is in V3 - the Frame is only used for Preview. In the future this will also be used for Recording and TakePhoto, but I haven't got to this yet.

**Comment by fukemy** [comment]
hell thanks you, I am trying to send rtc buffer to my rtcvideocapturerdelegate. Hope this feature avaiable soon 👍
