### ISSUE TITLE
❓ How to check if a frame processor plugin is available at runtime?

### ISSUE THREAD

**Issue by lakhannad-udaan** [cuvent/react-native-vision-camera#1629]
### Question

My frame processor plugin is working when running inside `useFrameProcessor` and inside that frame processor code I am getting the type as function for `typeof __pluginName` but when trying to check this outside using code mentioned below I am getting it as undefined. 
Can you please help in what is right way to do this?

### What I tried

import 'react-native-reanimated'

function checkPluginAvailable() {
   'worklet';
   return typeof __pluginName === 'function';
}

### VisionCamera Version

^2.14.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖

In V3 you can try checking for null at runtime 👍
