### ISSUE TITLE
❓ How can I allow only a specific aspect ratio?

### ISSUE THREAD

**Issue by bryanprimus** [cuvent/react-native-vision-camera#1632]
### Question

I'm building a camera that will always in potrait mode. and I want the result of aspect ratio, width, and height to be deterministic. 

### What I tried

What I have tried was to sort `device.formats` from `useCameraDevice()`
```ts
const format =  device.formats.sort(sortLogicToFilterWidthAndHeightThatHasDesiredAspectRatio)
```

I'm also able to render camera view based on aspect ratio I defined.

```tsx
// not sure why height need to come first so that the camera view rendered in potrait mode
<Camera style={{aspectRatio: format.photoHeight / format.photoWidth }}/>
```

but the problem is `cameraRef.current.takePhoto` result size is not consistent based on the format provided. `takeSnapshot` will result in the different picture size width, and height as well.  I'm not sure this is a bug or intended or we need to add more config to get deterministic result.

in `expo-camera` we have options to provide picture size https://docs.expo.dev/versions/latest/sdk/camera/#picturesize for what result `takePictureAsync` will return. do we have this in `vision camera`? it also has support for determined ratio https://docs.expo.dev/versions/latest/sdk/camera/#ratio

how can I do this correctly on `vision camera`?

### VisionCamera Version

latest version

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
VisionCamera allows you to specify the exact format to use - other libraries do not allow you to do that and do cropping internally (hence they are slower) - so you get the raw dimensions as a photo output, and if you want to crop you need to do this yourself.

**Comment by bryanprimus** [comment]
I ended up with this approach, which ensures that the aspect ratio is always set to `16:9`. I'm not entirely sure if it's the correct way, but at least it works now.

However, I'm not sure why there isn't any documentation available for this particular case, considering that I believe it is a common scenario and not easy to figure out.

```ts
const reduceRatio = (numerator: number, denominator: number): string => {
  let temp: number | undefined;
  let left: number;
  let right: number;

  const gcd = function (a: number, b: number): number {
    if (b === 0) {
      return a;
    }
    return gcd(b, a % b);
  };

  if (numerator === denominator) {
    return '1:1';
  }

  if (+numerator < +denominator) {
    temp = numerator;
    // eslint-disable-next-line no-param-reassign
    numerator = denominator;
    // eslint-disable-next-line no-param-reassign
    denominator = temp;
  }

  const divisor = gcd(+numerator, +denominator);

  if (typeof temp === 'undefined') {
    left = numerator / divisor;
    right = denominator / divisor;
  } else {
    left = denominator / divisor;
    right = numerator / divisor;
  }

  if (left === 8 && right === 5) {
    left = 16;
    right = 10;
  }

  return `${left}:${right}`;
};

const availableRatios = useMemo(
  () =>
    device?.formats.reduce<Record<string, CameraDeviceFormat[]>>((acc, format) => {
      const ratio = reduceRatio(format.photoWidth, format.photoHeight);

      return {
        ...acc,
        // use 'sortFormats' from 'react-native-vision-camera' to get the best resolutions first
        [ratio]: [...(acc[ratio] || []), format].sort(sortFormats),
      };
    }, {}),
  [device?.formats],
);
  
const format = useMemo(() => availableRatios?.['16:9']?.[0], [availableRatios]);
 
```

**Comment by mrousavy** [comment]
Maybe we can introduce some funcs like this to the JS codebase of VisionCamera.

**Comment by jonjamz** [comment]
Would using the "hd-1920x1080" preset accomplish this without the need to filter the formats? Assuming 1080p resolution is enough for the use case, and we are capturing in portrait.

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖

JFYI: Check out the Camera Formats docs. You can use aspect ratios there

**Comment by iway1** [comment]
@mrousavy there's no aspect ratio option in formats, or any mention of them in docs... I'm assuming that `imageWidth` and `imageHeight` should be used but it's not obvious how to use those to get a 16/9 ratio for example

**Comment by mrousavy** [comment]
@iway1 https://react-native-vision-camera.com/docs/guides/formats
```ts
const format = useCameraFormat(device, [
  { videoResolution: { width: 3048, height: 2160 } },
  { videoAspectRatio: 16 / 9 },
  { fps: 60 }
])
```

**Comment by mrousavy** [comment]
Also just updated the docs to be more explicit about the link between video and preview, and how aspect ratio is affected.

**Comment by JoaoPLF** [comment]
@mrousavy I'm having an issue with setting the `format` on Android.

I set my aspect ratio to 3:4:
```
const cameraFormat = getCameraFormat(this.device, [
        {
          photoAspectRatio: 3 / 4,
        },
      ]);
```

I did a `console.log` and the camera has a format for it:
```
{"autoFocusSystem": "contrast-detection", "fieldOfView": 86.30477861601217, "maxFps": 30, "maxISO": 3200, "maxZoom": 10, "minFps": 1, "minISO": 50, "photoHeight": 3000, "photoWidth": 4000, "pixelFormats": ["yuv", "native"], "supportsDepthCapture": false, "supportsPhotoHdr": true, "supportsVideoHdr": false, "videoHeight": 2160, "videoStabilizationModes": ["off", "off", "cinematic-extended"], "videoWidth": 3840}
```

And I set it in the `format={cameraFormat}`. As soon as I open the camera, the app crashes with the following error:
```
FATAL EXCEPTION: mrousavy/VisionCamera.main
Process: com.myapp, PID: 29363
com.facebook.react.bridge.UnexpectedNativeTypeException: Value for videoStabilizationModes cannot be cast from ReadableNativeMap to ReadableArray at com.facebook.react.bridge.ReadableNativeMap.checkInstance(ReadableNativeMap.java:143) at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:131)
                                                                                                    	at com.facebook.react.bridge.ReadableNativeMap.getArray(ReadableNativeMap.java:170)
                                                                                                    	at com.mrousavy.camera.types.CameraDeviceFormat$Companion.fromJSValue(CameraDeviceFormat.kt:32)
                                                                                                    	at com.mrousavy.camera.CameraView$update$1$1.invoke(CameraView.kt:192)
                                                                                                    	at com.mrousavy.camera.CameraView$update$1$1.invoke(CameraView.kt:138)
                                                                                                    	at com.mrousavy.camera.core.CameraSession.configure(CameraSession.kt:155)
                                                                                                    	at com.mrousavy.camera.CameraView$update$1.invokeSuspend(CameraView.kt:138)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1b4b4e6, mrousavy/VisionCamera.main]
```

Am I missing something? I tested this on both Pixel 7 emulator and a Samsung S22 Ultra phone
