### ISSUE TITLE
🐛 Android build failure on v3

### ISSUE THREAD

**Issue by Romick2005** [cuvent/react-native-vision-camera#1641]
### What were you trying to do?

![image](https://github.com/mrousavy/react-native-vision-camera/assets/17779660/0b48e625-ff80-477c-b31e-0f842337366a)

### Reproduceable Code

```tsx
Any
```

### What happened instead?

App does not build on Android device.

### Relevant log output

```shell
* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-vision-camera'.
   > Could not determine the dependencies of null.
      > Could not resolve all task dependencies for configuration ':react-native-vision-camera:classpath'.
         > Could not find com.android.tools.build:gradle:.
           Required by:
               project :react-native-vision-camera
```

### Device

iPhone XS

### VisionCamera Version

RC3 v3

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by fukemy** [comment]
android still working in progress for rc3

**Comment by mrousavy** [comment]
I said this three times already- android is still work in progress. The latest v3 is iOS only

**Comment by moloudayat** [comment]
I have the same problem with android. Is there any solution?
