### ISSUE TITLE
🐛 App does not build on iOS

### ISSUE THREAD

**Issue by Romick2005** [cuvent/react-native-vision-camera#1642]
### What were you trying to do?

![image](https://github.com/mrousavy/react-native-vision-camera/assets/17779660/ec54c449-e1ee-45b6-aafc-48737c0b0d7d)

### Reproduceable Code

```tsx
Any
```

### What happened instead?

App does not build on iOS

### Relevant log output

```shell
'TensorFlowLiteObjC/TFLTensorFlowLite.h' file not found
```

### Device

iPhone XS

### VisionCamera Version

RC3 v3

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by fukemy** [comment]
Try adding the following to your podfile with modular headers.
```
pod 'TensorFlowLiteObjC', :modular_headers => true
pod 'TensorFlowLiteObjC/Metal', :modular_headers => true
pod 'TensorFlowLiteObjC/CoreML', :modular_headers => true
```

**Comment by mrousavy** [comment]
You need to add the pods to the podfile, will be fixed in next rc

**Comment by Alexispap** [comment]
I added the pods, but the error remains.

**Comment by lizcodezpink** [comment]
I have the same issue.

**Comment by patras1** [comment]
I have the some issue, added the pods but still the some error

**Comment by fukemy** [comment]
instead of claim the error, post the image or some error log

**Comment by sudoMoshe** [comment]
to anyone who might be facing the same issue
I had the same problem with the m1 processor  expo SDK 49 RC3 v3
manually adding the TensorFlow lite framework to the project "Link Binary With Libraries" phase solved it 
<img width="732" alt="Screenshot 2023-07-31 at 11 10 14" src="https://github.com/mrousavy/react-native-vision-camera/assets/92578102/47831854-d1db-4e01-abef-dbe3b7221917">

**Comment by willburstein** [comment]
I'm experiencing the same issue, but only once I incorporated Firebase with Firestore and use_frameworks
