### ISSUE TITLE
🐛 : frame-processor/unavailable chrome debug.

### ISSUE THREAD

**Issue by bhola-t2b** [cuvent/react-native-vision-camera#1643]
### What were you trying to do?

- This code runs fine when Chrome debugging is **Not** enabled, but I'm encountering an error when attempting to Chrome debugging.

### Reproduceable Code

```tsx
"react-native-reanimated": "2.12.0",    
"react-native-vision-camera": "2.15.4",
 "vision-camera-code-scanner": "0.2.0", 

babel.config.js

module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'react-native-reanimated/plugin',
      {
        globals: ['__scanCodes'],
      },
    ],
  ],
}


index.js

import 'react-native-reanimated'


 const [hasPermission, setHasPermission] = useState(false)
  const devices = useCameraDevices()
  const device = devices.back

  const [frameProcessor, barcodes] = useScanBarcodes([BarcodeFormat.ALL_FORMATS], {
    checkInverted: true,
  })

  const requestPermissions = async () => {
    const status = await Camera.requestCameraPermission()
    setHasPermission(status === 'authorized')
  }

  useEffect(() => {
    if (checkCameraPermission) requestPermissions()
  }, [])
  
  

    {device != null && hasPermission && isFocused && (
          <Camera
            device={device}
            isActive={true}
            frameProcessor={frameProcessor}
            frameProcessorFps={5}
            style={[styles.visionCamera, cameraStyle]}
            torch={torch ? 'on' : 'off'}
            {...cameraProps}
          />
      )}
          
```

### What happened instead?

<img width="976" alt="Screenshot 2023-07-06 at 4 33 17 PM" src="https://github.com/mrousavy/react-native-vision-camera/assets/93245523/453ceea3-80d0-47c3-89d2-8c0388a49462">

### Device

Android/iOS

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
You checked the "I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)" box, but you did not read it.
![Screenshot 2023-07-07 at 11 47 02](https://github.com/mrousavy/react-native-vision-camera/assets/15199031/e795270a-2e89-4d18-b01b-ea09b92afec4)

come on man.
