### ISSUE TITLE
🐛 App does not build on iOS rc 3

### ISSUE THREAD

**Issue by nikitapilgrim** [cuvent/react-native-vision-camera#1648]
### What were you trying to do?

```
 ** ARCHIVE FAILED **
[RUN_FASTLANE] ▸ The following build commands failed:
[RUN_FASTLANE] ▸        CompileC /Users/1/Library/Developer/Xcode/DerivedData/bloggshouse-cmieuysyqglyaxazizdqisawmnsf/Build/Intermediates.noindex/ArchiveIntermediates/bloggshouse/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/VisionCamera.build/Objects-normal/arm64/TensorHelpers.o /var/folders/9h/k6llh0jd1_n75sqdsch6lzmr0000gn/T/eas-build-local-nodejs/f5288223-530e-4586-8518-9320ccb01ed3/build/frontend/apps/expo/node_modules/react-native-vision-camera/ios/Tensorflow\ Plugin/TensorHelpers.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'VisionCamera' from project 'Pods')
```

### What happened instead?

error build

### Device

m1

### VisionCamera Version

rc 2

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Thanks for reporting, will fix!
