### ISSUE TITLE
error: package com.mrousavy.camera.frameprocessor does not exist 🐛 

### ISSUE THREAD

**Issue by ranvirgorai** [cuvent/react-native-vision-camera#1658]
### What were you trying to do?

Error : error: package com.mrousavy.camera.frameprocessor does not exist
import com.mrousavy.camera.frameprocessor.FrameProcessorPlugin;

<img width="531" alt="Screenshot 2023-07-21 at 10 53 36 AM" src="https://github.com/mrousavy/react-native-vision-camera/assets/5949243/811673ce-c14f-4966-98b8-430325fd0638">

### What happened instead?

Failing it gradle sync

### Device

Android

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by erickcrus** [comment]
How do you solve this?

**Comment by carlgrob5171989** [comment]
I am also facing the issue.
