### ISSUE TITLE
🐛 error: package FrameProcessorRuntimeManager does not exist

### ISSUE THREAD

**Issue by mingkaili** [cuvent/react-native-vision-camera#1669]
### What were you trying to do?

I had the same error as: https://github.com/mrousavy/react-native-vision-camera/issues/1373 but it doesn't seem to have an answer, so just want to create another ticket to see if anyone has a solution for this.

While trying to build android app, had the following error

```
> Task :react-native-vision-camera:compileDebugJavaWithJavac FAILED
/Users/th/workplace/proko-park-mobile/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/frameprocessor/FrameProcessorPlugin.java:51: error: package FrameProcessorRuntimeManager does not exist
        FrameProcessorRuntimeManager.Companion.getPlugins().add(plugin);
                                    ^
1 error
```

### Reproduceable Code

```tsx
"react-native": "0.66.1",
"react-native-vision-camera": "^2.15.2",

Android:

buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30

        kotlinVersion = "1.6.0"
        supportLibVersion = "27.1.1"
        googlePlayServicesAuthVersion = "16.0.1" // <--- use this version or newer
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:7.0.2')

        classpath 'com.google.gms:google-services:4.1.0' // <--- use this version or newer
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

### What happened instead?

App fails to build.

### Device

Any Android Device

### VisionCamera Version

2.15.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey! Looks like you don't have Kotlin installed. Add kotlin to your build.gradle dependencies
