### ISSUE TITLE
Cannot find interface declaration for 'VISION_EXPORT_SWIFT_FRAME_PROCESSOR'🐛 

### ISSUE THREAD

**Issue by fukemy** [cuvent/react-native-vision-camera#1670]
### What were you trying to do?

I I want to create customframeprocessor from my newProject, but I got this error

<img width="1512" alt="Screenshot 2023-07-27 at 14 36 20" src="https://github.com/mrousavy/react-native-vision-camera/assets/8202437/e68c7fb7-c1d0-4530-b6b1-1626671cbe28">

### Reproduceable Code

```tsx
I am sure to create bridging-header file:
```

### What happened instead?

I really dont know the problem

### Device

can not build

### VisionCamera Version

3.0.0 rc3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by fukemy** [comment]
I use the rc2 then it's working, not sure why those method removed in rc3

**Comment by fukemy** [comment]
now then i got this error, can u help @mrousavy 
<img width="1512" alt="Screenshot 2023-07-28 at 10 20 42" src="https://github.com/mrousavy/react-native-vision-camera/assets/8202437/116bd770-7259-482a-9a74-b30003a5b41c">


```
yarn add react-native-vision-camera@3.0.0-rc.2
yarn add react-native-worklets@https://github.com/chrfalch/react-native-worklets#3ac2fbb
yarn add yarn add @shopify/react-native-skia@0.1.197


    "react": "18.2.0",
    "react-native": "0.72.3",
```

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖

**Comment by erickcrus** [comment]
any solution? i`m using VisionCamera V3 (3.4.1).
<img width="566" alt="Captura de Tela 2023-10-19 às 14 31 24" src="https://github.com/mrousavy/react-native-vision-camera/assets/35431617/217a5a20-ee2b-46de-8fed-2f68e2c82641">

**Comment by mrousavy** [comment]
You need to upgrade to 3.5.1

**Comment by MartinTorresCh** [comment]
any solution? i'm using vision camera v4

**Comment by camboYY** [comment]
no solution till now

**Comment by mrousavy** [comment]
> no solution till now

Upgrade to V5, in V5 there is no custom code for Frame Processors - everything is just a Nitro Module.
