### ISSUE TITLE
'RNReanimated/REAIOSErrorHandler.h' file not found🐛 

### ISSUE THREAD

**Issue by senolkeskin** [cuvent/react-native-vision-camera#1676]
### What were you trying to do?

"react-native-reanimated": "^3.4.0",
"react-native-vision-camera": "^2.15.5",

When I run it through xcode I get the '**RNReanimated/REAIOSErrorHandler.h' file not found** error.

### Reproduceable Code

```tsx
#ifndef VISION_CAMERA_DISABLE_FRAME_PROCESSORS
  #if __has_include(<RNReanimated/NativeReanimatedModule.h>)
    #if __has_include(<RNReanimated/RuntimeManager.h>)
      #import <RNReanimated/RuntimeManager.h>
      #import <RNReanimated/RuntimeDecorator.h>
      #import <RNReanimated/REAIOSErrorHandler.h>
      #import "VisionCameraScheduler.h"
      #define ENABLE_FRAME_PROCESSORS
    #else
      #warning Your react-native-reanimated version is not compatible with VisionCamera, Frame Processors are disabled. Make sure you're using reanimated 2.2.0 or above!
    #endif
  #else
    #warning The NativeReanimatedModule.h header could not be found, Frame Processors are disabled. If you want to use Frame Processors, make sure you install react-native-reanimated!
  #endif
#endif

#import "FrameProcessorUtils.h"
#import "FrameProcessorCallback.h"
#import "../React Utils/MakeJSIRuntime.h"
#import "../React Utils/JSIUtils.h"
```

### What happened instead?

When I run it through xcode I get the '**RNReanimated/REAIOSErrorHandler.h' file not found** error.

### Relevant log output

```shell
'**RNReanimated/REAIOSErrorHandler.h' file not found**
```

### Device

Iphone 14

### VisionCamera Version

2.15.5

### Additional information

- [ ] I am using Expo
- [x] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by Farzin-Firoozi** [comment]
Same problem here.

**Comment by Farzin-Firoozi** [comment]
I fixed the issue by downgrading the react-native version to `0.71.7`.

**Comment by toandn96** [comment]
Same problem here.

**Comment by toandn96** [comment]
I fixed the issue by downgrading the react-native-reanimated version to `3.3.0`.

**Comment by caixingyue** [comment]
I also encountered the same problem, but it works fine on my real device. This problem occurs when running to the emulator, I have all the latest versions.

react-native-vision-camera/ios/Frame Processor/FrameProcessorRuntimeManager.mm:27:15 'RNReanimated/REAIOSErrorHandler.h' file not found

**Comment by caixingyue** [comment]
> I also encountered the same problem, but it works fine on my real device. This problem occurs when running to the emulator, I have all the latest versions.
> 
> react-native-vision-camera/ios/Frame Processor/FrameProcessorRuntimeManager.mm:27:15 'RNReanimated/REAIOSErrorHandler.h' file not found

I delete node_modules, after re-installation. The whole exception is directly. I've tried installing a clean framework and still can't fix the issue. This seems to be related to the new version released a few days ago

**Comment by nn1900** [comment]
as stated in https://www.react-native-vision-camera.com/docs/guides/frame-processors#disabling-frame-processors, I add `VISION_CAMERA_DISABLE_FRAME_PROCESSORS=1` to preprocessor definitions, however, it seems does not work and the error still shows up while rebuilding.

**Comment by RaphBlanchet** [comment]
I seem to have worked my way around this issue by completely removing the code related to Frame Processors on iOS. Of course, in my case, I wasn't using them anyway, so removing the code temporarily is good enough for now.

As @nn1900 stated, disabling the frame processors with the config flag wasn't working either, the compiler seemed to ignore it and look for the file to import anyway.

To do this, add and configure [patch-packge](https://www.npmjs.com/package/patch-package) to your project and add [this patch](https://gist.github.com/RaphBlanchet/1e8ab14edb7ad49929487fec8360dd5f) in the `patches` folder at the root of your project. You will then have to re-run `yarn install && npx pod-install`

Hopefully we won't have to keep this workaround for long! 🤞🏼

**Comment by chetanbhadarka** [comment]
> I fixed the issue by downgrading the react-native-reanimated version to `3.3.0`.

not working with RNAnimated version '3.3.0'

@mrousavy Can you please look into it, ASAP.

**Comment by mrousavy** [comment]
Hi, this is a duplicate issue.

In the other issues I already mentioned that this will be fixed in V3. For now, I don't have the free time to fix that.

**Comment by TheChrisOneil** [comment]
I used the @RaphBlanchet patch solution and it worked!  (BTW I could not get Version 3.3.0 to solve the problem.)

[Ben Awad has an easy tutorial on how to use patches](https://www.google.com/search?q=npm+patch-package+example&oq=patch+npm&gs_lcrp=EgZjaHJvbWUqCAgFEAAYFhgeMgYIABBFGDkyCAgBEAAYFhgeMggIAhAAGBYYHjIICAMQABgWGB4yCAgEEAAYFhgeMggIBRAAGBYYHjIICAYQABgWGB4yBggHEEUYPNIBCTE1NTYzajBqOagCALACAA&sourceid=chrome&ie=UTF-8#fpstate=ive&vld=cid:6253f04c,vid:2AVs-Yh1bS8)

**Comment by Shivampurbia** [comment]
> I used the @RaphBlanchet patch solution and it worked! (BTW I could not get Version 3.3.0 to solve the problem.)
> 
> [Ben Awad has an easy tutorial on how to use patches](https://www.google.com/search?q=npm+patch-package+example&oq=patch+npm&gs_lcrp=EgZjaHJvbWUqCAgFEAAYFhgeMgYIABBFGDkyCAgBEAAYFhgeMggIAhAAGBYYHjIICAMQABgWGB4yCAgEEAAYFhgeMggIBRAAGBYYHjIICAYQABgWGB4yBggHEEUYPNIBCTE1NTYzajBqOagCALACAA&sourceid=chrome&ie=UTF-8#fpstate=ive&vld=cid:6253f04c,vid:2AVs-Yh1bS8)

which version of RNanimated you have?

**Comment by Shivampurbia** [comment]
> > I used the @RaphBlanchet patch solution and it worked! (BTW I could not get Version 3.3.0 to solve the problem.)
> > [Ben Awad has an easy tutorial on how to use patches](https://www.google.com/search?q=npm+patch-package+example&oq=patch+npm&gs_lcrp=EgZjaHJvbWUqCAgFEAAYFhgeMgYIABBFGDkyCAgBEAAYFhgeMggIAhAAGBYYHjIICAMQABgWGB4yCAgEEAAYFhgeMggIBRAAGBYYHjIICAYQABgWGB4yBggHEEUYPNIBCTE1NTYzajBqOagCALACAA&sourceid=chrome&ie=UTF-8#fpstate=ive&vld=cid:6253f04c,vid:2AVs-Yh1bS8)
> 
> which version of RNanimated you have?

Thanks a lot man, it worked but i also had to comment this line,
` #import "../React Utils/MakeJSIRuntime.h"
`
otherwise it was giving me this error in multiple files whose call was initiated in this file.
`no template named 'optional' in namespace 'std'; did you mean 'folly::Optional'? `
this might be related to xCode version or something but i just commented that import alongside the changes that was mentioned in the patch.

My lib version:
 "react-native-reanimated": "^3.4.2",
    "react-native-vision-camera": "^2.13.0",

**Comment by novamaster-git** [comment]
If you guys are planning to use react-native-vision-camera with frame processor [i.e. QR scanner ]
then please use this version of packages:
```
react-native-reanimated: "2.17.0",
react-native-vision-camera: "2.15.4"
```
and it is working fine. 
for your information i am using 
React-Native: 0.70.12
ios: 16.6

**Comment by khanakia** [comment]
Getting this error Unimplemented CameraView after i applied the patch https://gist.github.com/RaphBlanchet/1e8ab14edb7ad49929487fec8360dd5f

![Screenshot 2023-08-30 at 8 59 45 PM](https://github.com/mrousavy/react-native-vision-camera/assets/2174170/c00d79c9-7ac0-4e3c-acd4-8e5d31018706)

**Comment by RaphBlanchet** [comment]
> Getting this error Unimplemented CameraView after i applied the patch https://gist.github.com/RaphBlanchet/1e8ab14edb7ad49929487fec8360dd5f
> 
> ![Screenshot 2023-08-30 at 8 59 45 PM](https://user-images.githubusercontent.com/2174170/264394379-c00d79c9-7ac0-4e3c-acd4-8e5d31018706.png)

This is unrelated to the patch since it removes the code used by FrameProcessors, not CameraView. Make sure that you apply this patch to the correct version of react-native-vision-camera

**Comment by khanakia** [comment]
I figured this out it's because of New Arch when i use this command it fails `RCT_NEW_ARCH_ENABLED=1 npx pod-install ios`

So i had to run this command instead of above command `npx pod-install ios`

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
