### ISSUE TITLE
🐛 "ReferenceError: Property '__scanOCR' doesn't exist, js engine: hermes" when using expo dev build.

### ISSUE THREAD

**Issue by erikemg** [cuvent/react-native-vision-camera#1688]
### What were you trying to do?

I have been trying to create an OCR app using React Native and Expo. However, I have encountered an issue where I cannot use the OCR package when using the Expo development client. I am utilizing react-native-vision-camera along with vision-camera-ocr to detect text.

### Reproduceable Code

```tsx
import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, ActivityIndicator, SafeAreaView } from 'react-native';
import { useCameraDevices, useFrameProcessor, Camera } from 'react-native-vision-camera';
import 'react-native-reanimated';
import { scanOCR } from 'vision-camera-ocr';
import { runOnJS } from 'react-native-reanimated';

const TextScanner = () => {
  const [text, setText] = useState(null)
  const devices = useCameraDevices();
  const cameraDevice = devices.back;



  const frameProcessor = useFrameProcessor((frame) => {
    'worklet'
    const scannedOcr = scanOCR(frame);
    runOnJS(setText)(scannedOcr.result.text)
  }, []);

  if (cameraDevice == null) {
    return <ActivityIndicator size="large" color="green" />;
  } else {
    return (
      <View>
        <Camera
        style={styles.camera}
        device={cameraDevice}
        isActive={true}
        frameProcessor={frameProcessor}
      />
        <View styles={styles.textContainer}>
          <Text style={styles.text}>{text}</Text>
        </View>
      </View>
    );
  }
};

export default TextScanner;

const styles = StyleSheet.create({
  textContainer: {
    position: 'absolute',
    bottom: 100,
    height: 100,
    width: 400,
    backgroundColor: 'white',
    zIndex: 1
  },
  text: {
    fontSize: 50
  },
  camera: {
    height: '80%',
    width: '100%',
    zIndex: 0
  }
})
```

### What happened instead?

Everything works fine when I build a standalone APK using EAS, but I face an error when attempting to run the app using the development client. I suspect this issue is related to the configuration of babel.config.js. I researched the problem, and it seems that some people forgot to include the following configuration in their babel.config.js:

   module.exports = {
     plugins: [
        [
          'react-native-reanimated/plugin',
          {
            globals: ['scanOCR'],
          },
        ],
      ],
    };
However, I have already included this configuration correctly in my babel.config.js. My question is whether there is a solution to make __scanOCR work in the Expo development client. Alternatively, is there another OCR plugin available for React Native using Expo that doesn't require an internet connection? I'm aiming to implement a popup that displays the recognized text with specific functionality, and having the ability to update the code quickly without using EAS would be very beneficial. 

### Relevant log output

```shell
ReferenceError: Property '__scanOCR' doesn't exist, js engine: hermes
```

### Device

Poco X3 Pro

### VisionCamera Version

2.15.5

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
