### ISSUE TITLE
🐛 Unable to build v3 in iOS

### ISSUE THREAD

**Issue by DeveloperMCD** [cuvent/react-native-vision-camera#1696]
### What were you trying to do?

Trying to successfully build project with v3.0.0-rc4 on iOS platform.

### Reproduceable Code

```tsx
npx react-native run-ios
```

### What happened instead?

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/developer/Library/Developer/Xcode/DerivedData/stackbay-hkdvgolugzmnjnbykqfllfpapwnp/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/VisionCamera.build/Objects-normal/arm64/SkImageHelpers.o /Users/developer/Documents/ios/stackbayapp/node_modules/react-native-vision-camera/ios/Skia\ Render\ Layer/SkImageHelpers.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'VisionCamera' from project 'Pods')
(1 failure)

### Relevant log output

/Users/developer/Documents/ios/stackbayapp/node_modules/@shopify/react-native-skia/cpp/skia/include/gpu/ganesh/SkImageGanesh.h:196:12: warning: parameter 'GrDirectContext' not found in the function declaration [-Wdocumentation]
    @param GrDirectContext  the GrDirectContext in play, if it exists
           ^~~~~~~~~~~~~~~
/Users/developer/Documents/ios/stackbayapp/node_modules/@shopify/react-native-skia/cpp/skia/include/gpu/ganesh/SkImageGanesh.h:197:12: warning: parameter 'SkImage' not found in the function declaration [-Wdocumentation]
    @param SkImage          a non-null pointer to an SkImage.
           ^~~~~~~
/Users/developer/Documents/ios/stackbayapp/node_modules/@shopify/react-native-skia/cpp/skia/include/gpu/ganesh/SkImageGanesh.h:198:12: warning: parameter 'skgpu::Mipmapped' not found in the function declaration [-Wdocumentation]
    @param skgpu::Mipmapped Whether created SkImage texture must allocate mip map levels.
           ^~~~~~~~~~~~~~~~
/Users/developer/Documents/ios/stackbayapp/node_modules/@shopify/react-native-skia/cpp/skia/include/gpu/ganesh/SkImageGanesh.h:200:12: warning: parameter 'skgpu::Budgeted' not found in the function declaration [-Wdocumentation]
    @param skgpu::Budgeted  Whether to count a newly created texture for the returned image
           ^~~~~~~~~~~~~~~
/Users/developer/Documents/ios/stackbayapp/node_modules/react-native-vision-camera/ios/Skia Render Layer/SkImageHelpers.mm:83:20: error: variable has incomplete type 'GrBackendTexture'
  GrBackendTexture backendTexture((int)texture.width,
                   ^

### Device

iPhone 13

### VisionCamera Version

3.0.0-rc4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by DeveloperMCD** [comment]
Although I got 3.0.0-rc5 to successfully build on Android, when I try to build in iOS I get this:

[!] Unable to find a specification for `react-native-worklets` depended upon by `VisionCamera`

**Comment by DeveloperMCD** [comment]
Just got the latest version 3.0.0-rc5 and updated the pod file AND the library-specific package.json (owned by react-native-vision camera) to use "react-native-worklets-core" version 0.2.0

The errors are different now, but I'm still getting an error on build, and still under "skia" --

The following build commands failed:
	CompileC /Users/developer/Library/Developer/Xcode/DerivedData/stackbay-hkdvgolugzmnjnbykqfllfpapwnp/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/VisionCamera.build/Objects-normal/arm64/SkImageHelpers.o /Users/developer/Documents/ios/stackbayapp/node_modules/react-native-vision-camera/ios/Skia\ Render\ Layer/SkImageHelpers.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'VisionCamera' from project 'Pods')
(1 failure)

/Users/developer/Documents/ios/stackbayapp/node_modules/react-native-vision-camera/ios/Skia Render Layer/SkImageHelpers.mm:84:20: error: variable has incomplete type 'GrBackendTexture'
  GrBackendTexture backendTexture((int)texture.width,
                   ^
In file included from /Users/developer/Documents/ios/stackbayapp/node_modules/react-native-vision-camera/ios/Skia Render Layer/SkImageHelpers.mm:14:
/Users/developer/Documents/ios/stackbayapp/node_modules/@shopify/react-native-skia/cpp/skia/include/core/SkSurface.h:25:7: note: forward declaration of 'GrBackendTexture'
class GrBackendTexture;
      ^
52 warnings and 1 error generated.

**Comment by patras1** [comment]
Having a similar issue:
[!] Unable to find a specification for `react-native-worklets` depended upon by `VisionCamera`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

I did install the 'react-native-worklets-core' .
Removed the old `react-native-worklets` from package-lock.json
Update to the latest version 3.0.0-rc5.
Run pod install 

what am I missing?
Thanks

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
