### ISSUE TITLE
🐛 EPERM: operation not permitted, lstat - react-native-vision-camera:configureCMakeDebug[arm64-v8a]

### ISSUE THREAD

**Issue by design-and-deliver** [cuvent/react-native-vision-camera#1700]
### What were you trying to do?

I recently joined an organization which is using react-native-vision-camera ("react-native-vision-camera": "^2.15.4") as part of a RN app.  2 devs who have been working on the app for a while are able to run 'yarn start' at the app root dir in order to successfully build the app which includes the react-native-vision-camera dependency.  However, I'm encountering the following error when running 'yarn start' on the app:

> Task :react-native-vision-camera:configureCMakeDebug[arm64-v8a]
node:events:492
      throw er; // Unhandled 'error' event
      ^
Error: EPERM: operation not permitted, lstat 'c:\MYCO\CODE\sales-tool\node_modules\react-native-vision-camera\android\build\intermediates\cxx\Debug\596g5031\obj\arm64-v8a\libVisionCamera.so.tmpe2f8d43'

The error appears to indicate some type of permissions issue.  I even tried a test where I ran the command in a command window with admin rights but the issue still occurs.  Like I mentioned, another developer is successfully able to 'yarn start' but I encounter the error above.

Can you think of any additional setup steps that I might need to perform in order for this operation to complete successfully?  Any other ideas about possible root causes for this error?  Is there a newer version of this library which may avoid this particular issue?

### What happened instead?

An eperm lstat error is output by yarn.  This completes successfully for another developer on the team but not for me.  We're both doing a fresh git clone and following the same next steps.

### Device

React Native build on Windows 11 Pro Version 10.0.22621 Build 22621

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
