### ISSUE TITLE
Android module is not initialized properly with Expo

### ISSUE THREAD

**Issue by bglgwyng** [cuvent/react-native-vision-camera#1701]
### What were you trying to do?

I created a fresh Expo project structure and added RNVC V3 as a dependency.

### Reproduceable Code

https://github.com/bglgwyng/Expo49RNVC3Sandbox

### What happened instead?

Initially, the error message in the **Relevant log output** appeared. 
This issue was resolved by commenting out the line `packages.add(new CameraPackage())` within the `getPackages` function of the MainApplication file. 
However, I'm unsure about the validity of this solution, as it led to a new problem being raised, which is documented in issue #1693(the reporter of this issue didn't use Expo though).

### Relevant log output

```
Native module CameraView tried to override CameraViewModule. 
Check the getPacakges() method in MainApplication.java, it might be that module is being created twice.
If this was your intention set canOverrideExsitingModule=true.
This error may also be present if the package is present only once in getPackages() but is also automatically added later during build time by autolinking. 
Try removing the existing entry and rebuild.
```

### Device

Galaxy S10

### VisionCamera Version

3.0.0-rc.5

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by AlimovSV** [comment]
Any updates?

**Comment by bglgwyng** [comment]
@AlimovSV In my case, RNVC 3.0.0 just solved issue.
