### ISSUE TITLE
Encrypted capture❓ 

### ISSUE THREAD

**Issue by jonjamz** [cuvent/react-native-vision-camera#1705]
### Question

Hi,

First off, thank you for this amazing library! 

I'm wondering if there is a way to encrypt the capture before it's ever saved to disk as a temporary file, or possibly to access the data from memory directly without it ever touching the disk. I'm working on an app where encryption is a key feature.

Thank you,

Jon

### VisionCamera Version

^2.15.5

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey, thanks! Sorry no, you have to encrypt later. This is not part of a Camera library
