### ISSUE TITLE
Record a camera while also screen recording on android device, screen permission popup makes camera unmount permanently

### ISSUE THREAD

**Issue by Jdowsett21** [cuvent/react-native-vision-camera#1707]
### What were you trying to do?

I am trying to start a camera recording after a screen recording starts in an expo project.  It seems the popup asking permission to start the screen recordings puts the application in the background and unmounts the camera causing the camera source to be inactive if the camera recording is started afterwards.  

If I eject from expo and build the project on a local physical device and add a 1 second set timeout to delay the start of the camera recording , the set timeout prevents the error from occurring allowing the camera enough time to remount after being in the background from the screen recording permission popup. 

However no matter what I do, when i build the app on google play store I get this inactive source error. I have tried adding a  30 second timeout, adding multiple retries with set timeouts in between to start the camera recording again long after screen recording has started, conditionally starting the camera recording only if the app state is active and screen recording has started, only mounting the camera component until after the screen permission popup is done and the app has resumed, I always get the inactive-source error- 

Here is my package.json

{
	"name": "test",
	"version": "1.0.6",
	"scripts": {
		"start": "expo start --dev-client",
		"android": "expo run:android",
		"ios": "expo run:ios",
		"web": "expo start --web",
		"eject": "expo eject",
		"build:tailwind": "tailwindcss --input input.css --output tailwind.css --no-autoprefixer && tailwind-rn",
		"dev:tailwind": "concurrently \"tailwindcss --input input.css --output tailwind.css --no-autoprefixer --watch\" \"tailwind-rn --watch\"",
		"format": "prettier --write \"./**/*.{ts,tsx,js,json}\"",
		"prebuild": "expo prebuild && npm run format",
		"build:ios": "eas build -p ios",
		"build:android": "eas build -p android",
		"build:all": "eas build --platform all",
		"update": "eas update --auto",
		"publish:ios": "eas submit -p ios",
		"publish:android": "eas submit -p android",
		"publish:all": "eas submit --platform all",
		"reset-pods": "cd ios && rm -rf Pods && pod install && cd ..",
		"postinstall": "patch-package",
		"clean-gradle": "cd android && ./gradlew clean && cd .."
	},
	"dependencies": {
		"@expo/webpack-config": "^0.16.19",
		"@fortawesome/fontawesome-svg-core": "^6.1.1",
		"@fortawesome/free-solid-svg-icons": "^6.1.1",
		"@fortawesome/react-native-fontawesome": "^0.3.0",
		"@hookform/resolvers": "^2.9.1",
		"@react-native-async-storage/async-storage": "^1.17.6",
		"axios": "^1.4.0",
		"expo": "^45.0.5",
		"expo-keep-awake": "~10.1.1",
		"expo-splash-screen": "~0.15.1",
		"expo-status-bar": "^1.3.0",
		"expo-updates": "~0.13.4",
		"patch-package": "^8.0.0",
		"react": "17.0.2",
		"react-dom": "17.0.2",
		"react-hook-form": "^7.32.0",
		"react-native": "0.68.5",
		"react-native-blob-util": "^0.16.0",
		"react-native-camera": "^4.2.1",
		"react-native-pdf": "6.5.0",
		"react-native-pdf-thumbnail": "^1.2.0",
		"react-native-record-screen": "^0.5.1",
		"react-native-svg": "^12.3.0",
		"react-native-toast-notifications": "^3.2.3",
		"react-native-vision-camera": "^2.15.6",
		"react-native-web": "0.17.7",
		"socket.io-client": "^4.5.4",
		"svg-builder": "^2.0.0",
		"tailwind-rn": "^4.2.0",
		"webpack-dev-server": "^4.9.2",
		"yup": "^0.32.11"
	},
	"devDependencies": {
		"@babel/core": "^7.12.9",
		"@trivago/prettier-plugin-sort-imports": "^3.3.0",
		"@types/react": "~17.0.21",
		"@types/react-dom": "^18.0.5",
		"@types/react-native": "^0.67.8",
		"concurrently": "^7.2.0",
		"postcss": "^8.4.14",
		"prettier": "^2.6.2",
		"tailwindcss": "^3.0.24",
		"typescript": "~4.3.5"
	},
	"private": true
}

`
	
### Reproduceable Code

```tsx
`import {  useEffect,  useRef, useState } from 'react';
import {
	Linking,
} from 'react-native';
import { AppState } from 'react-native';
import RecordScreen from 'react-native-record-screen';
import { useToast } from 'react-native-toast-notifications';
import { Camera, useCameraDevices } from 'react-native-vision-camera';
import { activateKeepAwake, deactivateKeepAwake } from 'expo-keep-awake';
import { useIsForeground } from '../common/utils/useIsForeground';

export const ContentContainer = () => {
	const [appState, setAppState] = useState(AppState.currentState);

	const toast = useToast();
	const [preventCameraEntry, setPreventCameraEntry] = useState(false);
	const stopFlagRef = useRef(false);
	const [recordingHasStarted, setRecordingHasStarted] = useState(false);
	const [isRecording, setIsRecording] = useState(false);
	const [cameraStatus, setCameraStatus] = useState<string[] | null>(null);
	const camera = useRef<any>(null);

	const deviceRef = useRef<any>(null);
;

const endRecording = async () => {
	if (!camera.current || !isRecording || !recordingHasStarted) return;

	await camera.current.stopRecording();

	await RecordScreen.stopRecording()
		.then((res) => {
			console.log('~ res:', res);
			setIsRecording(false);
			setRecordingHasStarted(false);
		})
		.catch((error) => console.log(`STOP SCREEN ERR ${error}`));
};

	const requestPermission = async () => {
		const cameraPermission = await Camera.requestCameraPermission();
		const microphonePermission = await Camera.requestMicrophonePermission();
		setCameraStatus([cameraPermission, microphonePermission]);
		if (cameraPermission !== 'authorized' || microphonePermission !== 'authorized') {
			setPreventCameraEntry(true);
			await Linking.openSettings();
		} else setPreventCameraEntry(false);
	};

	const getPermission = async () => {
		const cameraPermission = await Camera.getCameraPermissionStatus();

		const microphonePermission = await Camera.getMicrophonePermissionStatus();

		setCameraStatus([cameraPermission, microphonePermission]);
	};

	const startScreenRecordingAndroid = async () => {
		try {
			setRecordingHasStarted(true);
			const res = await RecordScreen.startRecording({ mic: false });
			if (res === 'permission_error') {
				toast.show('You must allow recording permission for a recorded event');
				return false;
			}
			return true;
		} catch (error) {
			console.log(`screen error ${error}`);
		}
	};

	const startCameraRecordingAndroid = async () => {
		try {
			console.log('CAMERA ANDROID');
			setIsRecording(true);
			setTimeout(() => {
				camera.current.startRecording({
					flash: 'on',
					onRecordingFinished: (video) => {
					console.log('🚀 ~ file: ContentContainer.tsx:96 ~ setTimeout ~ video:', video)
					},
					onRecordingError: (error) => {
						console.log('error:', error);
						toast.show(`Previous recording did not save, please DO NOT leave the application`, {
							type: 'warning',
							duration: 10000,
						});
					},
				});
			}, 3000);
		} catch (error) {
			toast.show(`${JSON.stringify(error)}`);
		}
	};

	const handleRecordAndroid = async () => {
		try {
			const screenRecordingStarted = await startScreenRecordingAndroid();

			if (!screenRecordingStarted) {
				setRecordingHasStarted(false);
				return;
			}
			toast.show(`Recording has commenced,please DO NOT leave the app or your recording will end`, {
				type: 'warning',
				duration: 10000,
			});
		} catch (error) {
			console.log(`handle record error ${error}`);
		}
	};


	const devices = useCameraDevices();
	
	const isAppForeground = useIsForeground();
	useEffect(() => {
		if (devices) deviceRef.current = devices.front;
	}, [devices]);

	useEffect(() => {
		const handleAppStateChange = (nextAppState) => {
			if (appState.match(/inactive|background/) && nextAppState === 'active') {
				if (!isRecording && !recordingHasStarted) {
						startCameraRecordingAndroid();
					activateKeepAwake();
				} else if (deviceRef.current && recordingHasStarted &&  !isRecording) {
					startCameraRecordingAndroid();
				}
			} else if (
				appState === 'active' &&
				nextAppState.match(/inactive|background/) &&
				isRecording &&
				recordingHasStarted
			) {
				console.log('INCORRECT ENDING');
				endRecording();
				deactivateKeepAwake();
				stopFlagRef.current = true;
			}
			setAppState(nextAppState);
		};

		const appStateSubscription = AppState.addEventListener('change', handleAppStateChange);

		return () => {
			appStateSubscription.remove();
		};
	}, [appState, isRecording, recordingHasStarted, isAppForeground]);

	useEffect(() => {
		if (!isRecording && !stopFlagRef.current) {
				handleRecordAndroid();
			activateKeepAwake();
		} else if (isRecording && !stopFlagRef.current) {
			toast.show(`Recording has ended, please switch role back to witness to resume`, {
				type: 'warning',
				duration: 10000,
			});
			endRecording();
			console.log('NORMAL END');
			deactivateKeepAwake();
		}
		if (stopFlagRef.current) {
			stopFlagRef.current = false;
		}
	}, [isRecording]);

	// GETTING CAMERA PERMISSIONS

	useEffect(() => {
		if (!cameraStatus) getPermission();
		if (cameraStatus?.filter((i) => i === 'authorized').length !== 2 && !preventCameraEntry) {
			requestPermission();
		}
	}, [cameraStatus]);



	return (
		<>
			{deviceRef.current && recordingHasStarted && (
				<Camera
					ref={camera}
					device={deviceRef.current}
					isActive={isAppForeground}
					video={true}
					photo={true}
					audio={true}
					key={recordingHasStarted}
				/>
			)}
			
		</>
	);
};
```

### What happened instead?

The camera start recording always throws this error `[capture/inactive-source] The recording failed because the source becomes inactive and stops sending frames.
One case is that if camera is closed due to lifecycle stopped, the active recording will be finalized with this error, and the output will be generated, containing the frames produced before camera closing. Attempting to start a new recording will be finalized immediately if the source remains inactive and no output will be generated.", "stacktrace": "com.mrousavy.camera.InactiveSourceError: [capture/inactive-source] The recording failed because the source becomes inactive and stops sending frames.
One case is that if camera is closed due to lifecycle stopped, the active recording will be finalized with this error, and the output will be generated, containing the frames produced before camera closing. Attempting to start a new recording will be finalized immediately if the source remains inactive and no output will be generated.
	at com.mrousavy.camera.CameraView_RecordVideoKt$startRecording$1.accept(CameraView+RecordVideo.kt:64)
	at com.mrousavy.camera.CameraView_RecordVideoKt$startRecording$1.accept(CameraView+RecordVideo.kt:52)
	at androidx.camera.video.Recorder$RecordingRecord.lambda$updateVideoRecordEvent$6$Recorder$RecordingRecord(Recorder.java:2624)
	at androidx.camera.video.-$$Lambda$Recorder$RecordingRecord$Uo40MCKPuma4aZ5df1-_fzufzHg.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
"}, "code": "capture/inactive-source", "message": "[capture/inactive-source] The recording failed because the source becomes inactive and stops sending frames.
One case is that if camera is closed due to lifecycle stopped, the active recording will be finalized with this error, and the output will be generated, containing the frames produced before camera closing. Attempting to start a new recording will be finalized immediately if the source remains inactive and no output will be generated.", "userInfo": null}`

### Device

Samsung Galaxy s20 FE

### VisionCamera Version

2.15.6

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
