### ISSUE TITLE
🐛 SkSurfaceGanesh.h

### ISSUE THREAD

**Issue by nikitapilgrim** [cuvent/react-native-vision-camera#1719]
### What were you trying to do?

build

### What happened instead?

`[RUN_FASTLANE] 
❌  (node_modules/react-native-vision-camera/ios/Skia Render Layer/SkiaRenderer.mm:22:9)

  20 | #import <include/gpu/mtl/GrMtlTypes.h>
  21 | #import <include/gpu/GrBackendSurface.h>
> 22 | #import <include/gpu/ganesh/SkSurfaceGanesh.h>
     |         ^ 'include/gpu/ganesh/SkSurfaceGanesh.h' file not found
  23 | #import <include/gpu/ganesh/mtl/SkSurfaceMetal.h>
  24 | 
  25 | #import "SkImageHelpers.h"

`

### Device

iPhone 11

### VisionCamera Version

rc6

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by chezhe** [comment]
I got same error when using `rc.9`, do you have any clue for the solution? @nikitapilgrim
