### ISSUE TITLE
🐛 Tried to synchronously call function {nonPromiseMethodWrapper} from a different thread

### ISSUE THREAD

**Issue by Antsthebul** [cuvent/react-native-vision-camera#1722]
### What were you trying to do?

I was trying to follow https://www.react-native-vision-camera.com/docs/guides/frame-processors-plugins-overview#async-frame-processors-with-event-emitters and by placing an EventEmitter within useFrameProcessor raises the "tried to synchronously call function from another thread" I find this interesting because https://reactnative.dev/docs/native-modules-ios#export-a-native-method-to-javascript states that RCT_EXPORT_METHOD creates asynchronous functions, so Im not sure why Im having this error

### Reproduceable Code

```tsx
EventEmitter.h

#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>

@interface LabelEventEmitter : RCTEventEmitter <RCTBridgeModule>
@end
```
EventEmitter.m
```
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>

@implementation EventEmitter

RCT_EXPORT_MODULE(LabelEventEmitter);
RCT_EXPORT_METHOD(process:(NSString *)frame){
  NSLog(@"Hello from the otherside");
}
@end
```

ReactNative
```
import { NativeModules } from 'react-native'; 
import * as React from 'react';
import { NativeEventEmitter, StyleSheet, View } from "react-native";
import Reanimated, { runOnJS, runOnUI, useAnimatedStyle, useSharedValue } from 'react-native-reanimated';
import { Camera, Frame, useCameraDevices, useFrameProcessor} from "react-native-vision-camera";
import { useIsFocused } from '@react-navigation/native';

export default function CameraPage(){

    const devices = useCameraDevices()
    const focused = useIsFocused()

    const device = devices.back
const { eventEmitter } = NativeModules;

    const frameProcessor = useFrameProcessor((frame)=>{
        'worklet';
        eventEmitter.process(frame) // this fails
        
        
        //@ts-ignore
        console.log("Running on the UI thread") // this workds
     
     
    }, [])
       return(
            <>
                {typeof device !== 'undefined' &&
                <>
                <Camera 
                    style={StyleSheet.absoluteFill}
                    device={device}
                    isActive={focused}
                    frameProcessor={frameProcessor}
                    fps={5}
                    />

                <Reanimated.View style={boxOverlayStyle} />
        </>
        }
            </>
        )
}
```

### What happened instead?

The app crashes with [native] Tried to synchronously call function {nonPromiseMethodWrapper} from a different thread.

Possible solutions are:
a) If you want to synchronously execute this method, mark it as a Worklet
b) If you want to execute this method on the JS thread, wrap it using runOnJS
2023-08-25 10:13:13.375430-0400 kc_mobile[463:7630] [javascript] Running on the UI thread
2023-08-25 10:13:13.772573-0400 kc_mobile[463:7822] [native] Tried to synchronously call function {nonPromiseMethodWrapper} from a different thread.

EDIT: Added Additional library versions
    "@react-native-community/cli-platform-ios": "^11.3.7",
    "@react-navigation/native": "^6.1.7",
    "react": "18.2.0",
    "react-native": "^0.71.3",
    "react-native-reanimated": "^2.14.4",
    "react-native-vision-camera": "^2.15.4"

### Device

iPhone XR (iOS 16.6)

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
