### ISSUE TITLE
🐛 Crash on creating local expo build (ios)

### ISSUE THREAD

**Issue by sravis02** [cuvent/react-native-vision-camera#1724]
### What were you trying to do?

I wanted to create a local build with expo on my mac m1.

I am using XCode 14.3.1

EAS development builds work, thats strange :O

### Reproduceable Code

```tsx
npx expo run:ios
```

### What happened instead?

Build crashed

### Relevant log output

```shell
› Planning build
› Compiling expo Pods/Expo » Expo-dummy.m
› Compiling expo Pods/Expo » EXAppDefinesLoader.m
› Compiling expo-image-loader Pods/EXImageLoader » EXImageLoader-dummy.m
› Compiling expo-splash-screen Pods/EXSplashScreen » EXSplashScreen-dummy.m
› Compiling expo-font Pods/EXFont » EXFont-dummy.m
› Compiling expo-file-system Pods/EXFileSystem » EXFilePermissionModule.m
› Compiling expo-application Pods/EXApplication » EXProvisioningProfile.m

❌  (/Users/lucasorzan/Entwicklung/projekte/Flashes/app/node_modules/react-native-vision-camera/ios/Skia Render Layer/SkiaPreviewView.swift:13:25)

  11 | // MARK: - SkiaPreviewLayer
  12 | 
> 13 | class SkiaPreviewLayer: CAMetalLayer {
     |                         ^ 'CAMetalLayer' is only available in iOS 13.0 or newer
  14 |   private var pixelRatio: CGFloat {
  15 |     return UIScreen.main.scale
  16 |   }
```

### Device

Apple M1  - macOS Ventura 13.2

### VisionCamera Version

3.0.0-rc.6

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

If your issue has been fixed, consider [sponsoring me on GitHub](https://github.com/sponsors/mrousavy) to say thanks 💖
