### ISSUE TITLE
[v3] frame processors with ios 17❓ 

### ISSUE THREAD

**Issue by peterbsmyth** [cuvent/react-native-vision-camera#1733]
### Question

what is the current suggestion for publishing and developing plugins for v3 that are also ios only?

### What I tried

today i made [vision-camera-plugin-animal-pose](https://github.com/myth-software/vision-camera-plugin-animal-pose) public.  

highlights from putting it together:  
- overcame issues working at all with swift by rewriting to objective-c
- learned a lot specifically related to ios 17, which made for an arduous experience in xcode with beta versions of apple's tooling
- adopted skia for drawing with great success and joy, though could bare for better performance

---

at the end of the day, the core ml for the plugin is an apple plugin, which means android compatibility on a 1:1 basis is impossible. is it plausible to go forward as a full plugin while remaining ios only? is it best to make an, even if not identical implementation, android version?

### VisionCamera Version

3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey, this should work and is plausible to add, yes.
