### ISSUE TITLE
❓ FaceDetect frameProcessor with v3

### ISSUE THREAD

**Issue by vahidid** [cuvent/react-native-vision-camera#1751]
### Question

Hi, I'm waiting for version 3 for a long time and now I want to add a face detector frame processor but i'm not a good Java developer. Can any body write an example for android and iOS? Please!!!

### What I tried

I tried to use the old lib [vision-camera-face-detector](https://github.com/rodgomesc/vision-camera-face-detector) to migrate them to v3 but i failed.

### VisionCamera Version

3.0.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by manolo-battista** [comment]
on iOS I have this error when I try to build with `"react-native-vision-camera": "^3.0.0-rc.10" / "3.0.0", and "vision-camera-face-detector": "^0.1.8"

<img width="1251" alt="Screenshot 2023-09-04 alle 19 30 14" src="https://github.com/mrousavy/react-native-vision-camera/assets/81776297/226f6b76-91b6-4ce0-9fb1-8cc2e4033093">

**Comment by duyanhv** [comment]
i've found a solution base on this guide: https://github.com/mrousavy/react-native-vision-camera/blob/b300209e3618a0ae6e46db8e0e9290d2beb09baf/docs/docs/guides/FRAME_PROCESSOR_CREATE_PLUGIN_IOS.mdx
you will have to setup a plugin like in the guide, and paste all of the content from VisionCameraFaceDetector callback function and it will work again 👍

**Comment by manolo-battista** [comment]
@duyanhv I tried to follow the guide through the automatic and manual process, but I'm not so strong on XCode and I found some problems. I used the automatic process, I copied callback and relatives functions, all build correctly, but I received undefined from my `detectFaces` function. 

I have to do something on `AppDelegate.m`? Cause when I tried to add my function I have problems on build.

Can you share your solution?

**Comment by duyanhv** [comment]
> @duyanhv I tried to follow the guide through the automatic and manual process, but I'm not so strong on XCode and I found some problems. I used the automatic process, I copied callback and relatives functions, all build correctly, but I received undefined from my `detectFaces` function.
> 
> I have to do something on `AppDelegate.m`? Cause when I tried to add my function I have problems on build.
> 
> Can you share your solution?

that's exactly what i did.
after running `npx vision-camera-plugin-builder ios` i got 2 file: 
![Screenshot 2023-09-06 at 17 00 43](https://github.com/mrousavy/react-native-vision-camera/assets/20358572/753d3f1b-92a4-4b1f-a6a0-9018f16c81b9)

FaceDetectorFrameProcessorPlugin.m
![Screenshot 2023-09-06 at 17 01 28](https://github.com/mrousavy/react-native-vision-camera/assets/20358572/16c7fa5b-3dc8-45e7-83ea-05a053f2c84e)

FaceDetectorFrameProcessorPlugin.swift
![Screenshot 2023-09-06 at 17 02 04](https://github.com/mrousavy/react-native-vision-camera/assets/20358572/023312d8-471f-4aac-8ce2-91afdf48aae2)

You don't have to do anything else, VisionCameraProxy will automatically pickup the plugin. 
On the JS side, i have something like this (declared it outside the react component)
![Screenshot 2023-09-06 at 17 02 34](https://github.com/mrousavy/react-native-vision-camera/assets/20358572/93d62155-56c4-4c11-8c0d-04f71bd5583f)

And this is what i have in useFrameProcessor
![Screenshot 2023-09-06 at 17 04 54](https://github.com/mrousavy/react-native-vision-camera/assets/20358572/f7ed1725-6811-4da3-9acb-8b2a4116af05)

Hope this help.
