### ISSUE TITLE
Android on Init Error🐛 

### ISSUE THREAD

**Issue by hamdij0maa** [cuvent/react-native-vision-camera#1752]
### What's happening?

<img width="529" alt="image" src="https://github.com/mrousavy/react-native-vision-camera/assets/20734472/ca120a36-9a23-4b81-9fd6-8d34b10c37dc">

### Reproduceable Code

```tsx
<ReanimatedCamera
                  style={globalStyles.cameraStyle}
                  device={device}
                  lowLightBoost={
                    device.supportsLowLightBoost && enableNightMode
                  }
                  isActive={isActive && cameraEnabled}
                  onInitialized={onInitialized}
                  onError={onError}
                  enableZoomGesture={false}
                  animatedProps={cameraAnimatedProps}
                  orientation="portrait"
                  photo={true}
                  video={true}
                  audio={hasMicrophonePermission}
                  //@ts-ignore
                  ref={camera}
                />
```

### Relevant log output

```shell
<img width="529" alt="image" src="https://github.com/mrousavy/react-native-vision-camera/assets/20734472/ca120a36-9a23-4b81-9fd6-8d34b10c37dc">
```

### Camera Device

```shell
Android Simulator Pixel 5
```

### Device

Pixel 5

### VisionCamera Version

3.0.0

### Can you reproduce this issue in the VisionCamera Example app?

- [X] I can reproduce the issue in the VisionCamera Example app.

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
You can reproduce this in the example app? I can't. C++ part of VideoPipeline is being built properly...

**Comment by Yasha33** [comment]
I have the same error when pass `video={true}`

**Comment by hamdij0maa** [comment]
yes same problem
the error show when video={true} in android

**Comment by hamdij0maa** [comment]
Here is the error showing when start recording : 
<img width="487" alt="image" src="https://github.com/mrousavy/react-native-vision-camera/assets/20734472/e83d661c-cb6f-4445-94b6-45f7651736cd">

**Comment by mrousavy** [comment]
Sorry I have no idea what you guys are trying to do (no reproduction steps) and I don't have the full code. The example app works.

**Comment by kocaagasefa** [comment]
https://github.com/mrousavy/react-native-vision-camera/issues/1769#issuecomment-1708240712
