### ISSUE TITLE
How to access the base64 of the image through the frame that comes from useFrameProcessor❓

### ISSUE THREAD

**Issue by MateusHoffman** [cuvent/react-native-vision-camera#1763]
### Question

```javascript
  const frameProcessor = useFrameProcessor(async (frame: any) => {
    'worklet'
    
  }, []);
``` 
I have this code above, it has the frame in this format below:

```javascript
frame === {"bytesPerRow": 1280, "close": [Function hostFunction], "height": 720, "isValid": true, "planesCount": 3, "toString": [Function hostFunction], "width": 1280}
```

I need to get the base64 or blob of this frame, what can I do to achieve this?

```javascript
  "dependencies": {
    "expo": "~48.0.18",
    "react": "18.2.0",
    "react-native": "0.71.8",
    "react-native-reanimated": "~2.14.4",
    "react-native-vision-camera": "^2.15.4"
  },
  ```

### VisionCamera Version

"react-native-vision-camera": "^2.15.4"

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by vonovak** [comment]
hello; I don't think you want to do that. base64 is slooow. Please don't use it 🙂

**Comment by MateusHoffman** [comment]
@mrousavy Please do not set to complete. I know base64 is slow but I still need it, can you help me?

**Comment by mrousavy** [comment]
Didn't I reply two times already to your message? You also posted this question on other issues and tagged me.

Again; you can convert the raw GPU frame to a byte buffer using frame.toByteArray().
Do whatever you want with the bytes from there on

**Comment by LPitonakova** [comment]
I would also like to know this. I need to upload base64 data to my API. How do you proceed after `const file = await this._camera.takePhoto();` ?

**Comment by v1n33th** [comment]
Frame processor plugins such as [tony-xlh/vision-camera-cropper](https://github.com/tony-xlh/vision-camera-cropper) can also be used to get base64 from frame.

**Comment by SANDEEP1938** [comment]
> Didn't I reply two times already to your message? You also posted this question on other issues and tagged me.
> 
> Again; you can convert the raw GPU frame to a byte buffer using frame.toByteArray(). Do whatever you want with the bytes from there on

@mrousavy 
frame.toByteArray()  is throwing error: Property 'toByteArray' does not exist on type 'Frame'.

**Comment by mrousavy** [comment]
If you're not using TypeScript or aren't reading the docs that's on you. It's `frame.toArrayBuffer()`, not `.toByteArray()`, I remembered it wrong.

**Comment by kitolog** [comment]
You can do it this way:
`
import {
    Camera,
    useCameraDevice,
    useCameraFormat,
    useCameraPermission,
} from "react-native-vision-camera";
import * as FileSystem from 'expo-file-system';

....

const photo = await cameraRef.current?.takePhoto();

let base64Image = null;
try {
    base64Image = await FileSystem.readAsStringAsync(`file:/${photo.path}`, {encoding: 'base64'});
} catch (e: any) {
    console.log('e');
    console.log(e);
}

//do smth with the base64 image
...
`
