### ISSUE TITLE
🐛 App crash while using useFrameProcessor (V3:Android)  

### ISSUE THREAD

**Issue by akshay8033** [cuvent/react-native-vision-camera#1766]
### What's happening?

My app is crashing when I'm trying to enable FrameProcessor. The app works fine without FrameProcessor. 

### Reproduceable Code

```tsx
import * as React from 'react';
import { StyleSheet, View, Text, Button } from 'react-native';
import {
  Camera,
  useCameraDevices,
  useFrameProcessor,
} from 'react-native-vision-camera';

export default function App() {
  // Permissions
  React.useEffect(() => {
    async function getPermissions() {
      await Camera.requestCameraPermission();
    }
    getPermissions();
  }, []);

  // Device
  const devices = useCameraDevices('wide-angle-camera');
  const device = devices.back;

  // Frame processor
  const frameProcessor = useFrameProcessor((frame) => {
    'worklet';
    console.log('Captured frame');
  }, []);

  if (device == null) return <Text>Loading camera...</Text>;
  return (
    <>
      <View style={styles.container}>
        <Camera
          frameProcessor={frameProcessor}
          device={device}
          isActive={true}
          style={StyleSheet.absoluteFill}
        />
      </View>
      <View>
        <Button title="Capture" />
      </View>
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

### Relevant log output

```shell
There is no error logged.
```

### Device

Samsung Galaxy S10+ 

### Package Versions
"react": "18.2.0"
"react-native": "0.72.4"
"react-native-reanimated": "^3.4.2"
"react-native-vision-camera": "^3.0.0"
"react-native-worklets-core": "^0.2.0"

### Can you reproduce this issue in the VisionCamera Example app?

- [ ] I can reproduce the issue in the VisionCamera Example app.

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Ah just saw this.

You didn't put any logs in here. Put the logs in here, or I can't help you.

**Comment by akshay8033** [comment]
Downgraded the example app react-native to 0.72.3 and it worked @mrousavy

**Comment by mashad6** [comment]
the issue still exist !

**Comment by mashad6** [comment]
<img width="1315" alt="Screenshot 2024-02-17 at 10 41 17 PM" src="https://github.com/mrousavy/react-native-vision-camera/assets/55269021/1a932a33-6088-48d7-ae2b-4097ca7e5bbb">
<img width="1364" alt="Screenshot 2024-02-17 at 10 41 32 PM" src="https://github.com/mrousavy/react-native-vision-camera/assets/55269021/aa0ae05e-4b88-419e-ba76-28be50a19f2b">

**Comment by mashad6** [comment]
@mrousavy these were the logs when i use frameProcessor

**Comment by mashad6** [comment]
@akshay8033 were you able to find the solution?

**Comment by mrousavy** [comment]
This is a cache issue. `yarn start --reset-cache`
