### ISSUE TITLE
❓ Creating a frame processor plugin for iOS in Swift for v3

### ISSUE THREAD

**Issue by xulihang** [cuvent/react-native-vision-camera#1778]
### Question

Following this guide: <https://www.react-native-vision-camera.com/docs/guides/frame-processors-plugins-ios>. I am stuck with step 6.

It cannot find the plugin class I defined.

```
[FrameProcessorPluginRegistry addFrameProcessorPlugin:@"decode"
                                        withInitializer:^FrameProcessorPlugin*(NSDictionary* options) {
    return [[VisionCameraDBRPlugin alloc] initWithOptions:options];
  }];
```

### VisionCamera Version

3.0.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by ManosChatzidakis** [comment]
Can you check the name in your implementation swift file `@objc` attribute? The string you use inside `@objc` needs to be the same as `VisionCameraDBRPlugin`

**Comment by mrousavy** [comment]
Yea maybe @objc or use a Swift header? Import the <YOURPRODUCT>-Swift.h proj

**Comment by ManosChatzidakis** [comment]
By the way I have a peristent issue with `-Swift.h` missing, but this is an Xcode issue. Look out for that too

**Comment by xulihang** [comment]
I defined the plugin here: https://github.com/tony-xlh/vision-camera-dynamsoft-barcode-reader/blob/ef6763bbc69e8a09dcf7167cbaa86f2cf636c1c8/ios/VisionCameraDBRPlugin.swift#L12

And import the header in the example's AppDelegate.mm: https://github.com/tony-xlh/vision-camera-dynamsoft-barcode-reader/blob/022281a337131cd832dea399c00374df7cbe5624/example/ios/VisionCameraDynamsoftBarcodeReaderExample/AppDelegate.mm#L4

**Comment by xulihang** [comment]
There aren't many frame processor samples for v3. I only found this fork: https://github.com/rkmackinnon/vision-camera-code-scanner/

It registers the processor here: https://github.com/rkmackinnon/vision-camera-code-scanner/blob/react-native-vision-camera-v3/ios/VisionCameraCodeScanner.m

I think this is a better way as the users don't need to modify the project's `AppDelegate.mm`.

**Comment by mrousavy** [comment]
Okay yea we can update the docs!
