### ISSUE TITLE
camera not working on all devices🐛 

### ISSUE THREAD

**Issue by hirendudhat03** [cuvent/react-native-vision-camera#1788]
### What's happening?

I tested camera in samsung s22 and s23.
In s22 working fine but in s23 camera not working only show white blank screen

### Device

samsung s23

### VisionCamera Version

3.0.0

### Can you reproduce this issue in the VisionCamera Example app?

- [ ] I can reproduce the issue in the VisionCamera Example app.

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
No logs attached here, closing because not enough info.
