### ISSUE TITLE
🐛 V3 runAsync doesn't work

### ISSUE THREAD

**Issue by manolo-battista** [cuvent/react-native-vision-camera#1791]
### What's happening?

On docs is described:

<img width="897" alt="Screenshot 2023-09-11 alle 17 32 27" src="https://github.com/mrousavy/react-native-vision-camera/assets/81776297/3676bbd1-4964-410f-b111-cf0bd599f19d">

But I think it needs update, cause request `frame` as first parameter and `func (callback)` as second parameter.

<img width="708" alt="Screenshot 2023-09-11 alle 17 33 10" src="https://github.com/mrousavy/react-native-vision-camera/assets/81776297/462b8721-7a16-4084-9182-42fc0d09e05a">

The callback function is never called. I saw that code reach the func on `runOnAsyncContext` function, but I think enter always on `finally` cause I can't see my log `ok 2`.

<img width="797" alt="Screenshot 2023-09-11 alle 17 38 02" src="https://github.com/mrousavy/react-native-vision-camera/assets/81776297/ad4ba54b-1ad7-440a-a0d0-3d049e0f52b4">

### Device

iPhone 14 Pro

### VisionCamera Version

3.0.0

### Can you reproduce this issue in the VisionCamera Example app?

- [ ] I can reproduce the issue in the VisionCamera Example app.

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by abdelrahman-muntaser** [comment]
@manolo-battista did you find any solution for this ?

**Comment by manolo-battista** [comment]
> @manolo-battista did you find any solution for this ?

no, unfortunately I still didn't find any solution. For my projects at the moment I'm using `runAtTargetFps` to run lower FPS rate.
```
const frameProcessor = useFrameProcessor((frame) => {
  'worklet'
  console.log("I'm running synchronously at 60 FPS!")
  runAtTargetFps(2, () => {
    'worklet'
    console.log("I'm running synchronously at 2 FPS!")
  })
}, [])
```

**Comment by mrousavy** [comment]
Hi. Would've been great if you could've sent a PR for that to fix it in docs.

But in my tests, `runAsync` works - can you put a console.log in there to double check that it does not get called?

Can you reproduce it in the example app?

**Comment by rodgomesc** [comment]
hey @mrousavy  i think we should keep this issue open, i'm facing the same issue since this function was released, can you provide a minimal example that's working for you?

**Comment by rodgomesc** [comment]
some weirdness scope things happening

### UseCase1:
`logcat` throws `JSI rethrowing JS exception: Regular javascript function cannot be shared. Try decorating the function with the 'worklet' keyword to allow the javascript function to be used as a worklet.`"

```tsx

  const frameProcessor = useFrameProcessor(
    (frame) => {
      "worklet";
      runAsync(frame, () => {
        "worklet";
        console.log("my awesome log");
      });
    },
    []
  );
  
  ```
  
  
  
### UseCase2:

do not throws anything on`logcat` but frameContext is always `undefined`, the `callback is not being triggered for some reason`

```tsx
  const myFn = (frameContext) => {
    "worklet";
    console.log("Here", frameContext);
  };

  const frameProcessor = useFrameProcessor(
    (frame) => {
      "worklet";
      runAsync(frame, myFn);
    },
    [myFn]
  );
  
  ```

**Comment by mrousavy** [comment]
Oh! Hm that's weird, I remember this worked when I built it.

@chrfalch do you maybe have any insights?

**Comment by rodgomesc** [comment]
oh wait 

it seems that by design the frame it's not being passed to `myFn` as a callback prop, this forces us to uses arrow functions to hook the frame scope, also it seems that's  no guarantees that `internal.decrementRefCount()` is being called after my long running function finishes the execution?, which causes a `java.lang.IllegalStateException: Image is already closed,`

https://github.com/mrousavy/react-native-vision-camera/blob/764897dcf119e26668b9fb6c6eb78f0e2993ffd1/package/src/FrameProcessorPlugins.ts#L50-L55

**Comment by mrousavy** [comment]
Wait what? not sure if I follow -

> it seems that by design the frame it's not being passed to myFn as a callback prop

 no you're right, you can just use the Frame inside your lambda directly, the lambda has no parameters.

> there's no guarantees that internal.decrementRefCount() is being called after my long running function finishes the execution

Why not? It runs in `finally`, no?

**Comment by rodgomesc** [comment]
@mrousavy yep you are totally right, i was very drunk that day sorry

found a pattern that doesn't make sense for me, `example app works` my app `doesn't work`, tried different combination of libs and now i'm using same version that's on example but it always end up with 

![image](https://github.com/mrousavy/react-native-vision-camera/assets/4893591/a1d5b18e-f18a-459f-909d-89c3f9e5eeab)

**Comment by rodgomesc** [comment]
i have a serie of frame processors at this moment running in sequence


something like this



```ts
const frameProcessor = (frame) => {
    'worklet';

     // processors
     const faces = faceDetectorProcessor(frame)
     const luminanceResults = luminanceDetectionProcessor(frame, faces)
     const spoofResults = antiSpoofingProcessor(frame);


    // callbacks
    handleSpoofingDetection(spoofResults)
    handleLuminanceDetection(luminanceResults)

},[handleSpoofingDetection, handleLuminanceDetection])
```


the problem is that at this point the frame are being deallocated before i finish my operations,
so i'm thinking to implement something like this, to drop some frames while my processors still running

```ts
const frameProcessor = (frame) => {
    'worklet';

    // just drop the frame
    if(!jsiUtil.finishedOperations) return;  

    const frameCopy = jsiUtil.copyFrame(frame);

     // processors      
     const faces = faceDetectorProcessor(frameCopy)
     const luminanceResults = luminanceDetectionProcessor(frameCopy, faces)
     const spoofResults = antiSpoofingProcessor(frameCopy);

    // cleanup frame copy
    jsiUtil.ReleaseFrameCopy()    

    // callbacks
    handleSpoofingDetection(spoofResults)
    handleLuminanceDetection(luminanceResults)

},[handleSpoofingDetection, handleLuminanceDetection])
```

would be nice to hear your opinion on this temporary solution to make sure i'm not missing anything

some final notes:

i'm linking my lib with `visionCamera.so` and unwraping the frame, i've tried increment refcount before my operations and decrement on the last one, but it seems to be ignored need further investigation

**Comment by mrousavy** [comment]
Woah, that's a weird error. Can you add `console.log` statements to your code (begin and end of sync calls, and begin and end of async calls) and then also to the native Frame's release method? 

This is weird and you shouldn't need such workarounds - it should just work magically with ref counting.

**Comment by rodgomesc** [comment]
i still couldn't figure out what's happening, i'll try to upload something reproducible

**Comment by rodgomesc** [comment]
Haaa I found out, i have a monorepo with this structure

-- packages
  ---- playground
  ---- mylib
  
  if i have reanimated in my lib i face this issue, removed reanimated from mylib and now i'm using it only in the playground, working like a charm
  
  ***Edit1:***
  
  if i try a simple `console.log` after removing reanimated lib it works
 
  ```ts
  useFrameProcessor(frame => .....
  
   runAsync(frame, () => {
   'worklet'
      console.log('hello from runAsync')
    })
    
  },[])
   ```
   
   if  i try to use any function inside of it, it crashes exactly with same error as before
   
  ```ts
   const myFunc = () => {
      'worklet'
       console.log('hello from runAsync')
   }
   
 useFrameProcessor(frame => .....
  
   runAsync(frame, () => {
    'worklet'
      myFunc();
    })
    
  },[myFunc])
   
   
```

**Comment by rodgomesc** [comment]
@mrousavy fyi it's reproducible on example app now

**Comment by mrousavy** [comment]
Wait so Reanimated makes it break? Yea it's a bit weird that Worklets and reanimated do the same thing... Maybe we can fix this compatibility for now and think about a better solution in the future.

**Comment by rodgomesc** [comment]
> Wait so Reanimated makes it break?

that's what i thought because after removing reanimated i can do a `console.log` inside the `runAsync`,  however if i call any function inside it i got the same error

**Comment by gbark** [comment]
Similar issue here. Using `@ismaelmoreiraa/vision-camera-ocr`, any call to `scanOCR` using `runAsync` throws:

```
JSI rethrowing JS exception: Exception in HostFunction: java.lang.ClassNotFoundException: Didn't find class "com.facebook.jni.MapIteratorHelper" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/system/lib64, /system/system_ext/lib64, /system/lib64, /system/system_ext/lib64]]

Error: Exception in HostFunction: java.lang.ClassNotFoundException: Didn't find class "com.facebook.jni.MapIteratorHelper" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/system/lib64, /system/system_ext/lib64, /system/lib64, /system/system_ext/lib64]]
    at call (native)
    at scanOCR (/Users/username/dev/app/node_modules/@ismaelmoreiraa/vision-camera-ocr/src/index.tsx:8:21)
    at fn (native)
    at anonymous (/Users/username/dev/app/packages/app/src/features/foo.tsx:18:27)
    at fn (native)
    at anonymous (/Users/username/dev/app/node_modules/react-native-vision-camera/src/FrameProcessorPlugins.ts:6:9)
```

Running the same exact same code using `runAtTargetFps` works fine. 

I'm not using Reanimated in my project.

**Comment by mrousavy** [comment]
Btw.; here's an explanation and a fix: https://github.com/margelo/react-native-worklets-core/issues/136

**Comment by mrousavy** [comment]
This is not related to VisionCamera, but rather about Reanimated.

If you do not use Reanimated, `runAsync` works fine. If you do use Reanimated, you need to enable `processNestedWorklets` in the Reanimated's babel plugin. See https://github.com/software-mansion/react-native-reanimated/issues/5576 for more info

**Comment by Cosmorider** [comment]
Enabling `processNestedWorklets` solved the error for me, but now this error pops up: `Frame Processor Error: Value is undefined, expected an Object, js engine: VisionCamera`

This is my code (from react-native-fast-tflite), note that the model is printed out, but then it shows the error, I'm trying to make the model not interfere with how the camera output is displayed in my app (it interferes on Android but not iOS):
```
  const frameProcessor = useFrameProcessor((frame) => {
    'worklet'
  
    const data = resize(frame, {
      size: {
        // center-crop
        x: (frame.width / 2) - (320 / 2),
        y: (frame.height / 2) - (320 / 2),
        width: 320,
        height: 320,
      },
      pixelFormat: 'rgb',
      dataType: 'uint8'
    })

    runAsync(frame, () => {
      'worklet'
      console.log(model)

      const output = model.runSync([data])
    
      const numDetections = output[0]
    })
  }, [model])
```

If I pass the frame into runAsync, I get this error:  `ERROR  Frame Processor Error: Exception in HostFunction: no ArrayBuffer attached, js engine: VisionCamera`

Not sure if I'm misunderstanding some fundamentals here.
```
"react-native-vision-camera": "^3.8.2",
"react-native-worklets-core": "^0.2.4",
"react-native-reanimated": "^3.6.1",
```

**Comment by mrousavy** [comment]
ArrayBuffers can't be shared (right @chrfalch?), do the resize also in runAsynx.

**Comment by chrfalch** [comment]
Correct.

**Comment by Cosmorider** [comment]
Sorry, I meant that I passed the `resize` into `runAsync` and then I got this error, if that was what you were asking for: `ERROR  Frame Processor Error: Exception in HostFunction: no ArrayBuffer attached, js engine: VisionCamera`

**Comment by mrousavy** [comment]
Yeah - try to move the resize call also into runAsync.

**Comment by Cosmorider** [comment]
I did that, and I get this error:
` ERROR  Frame Processor Error: Exception in HostFunction: java.lang.ClassNotFoundException: Didn't find class "com.mrousavy.camera.frameprocessor.Frame" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/system/lib64, /system/product/lib64, /system/lib64, /system/product/lib64]], js engine: VisionCamera`

When I use this code:
```
  const frameProcessor = useFrameProcessor((frame) => {
    'worklet'

    runAsync(frame, () => {
      'worklet'

      const data = resize(frame, {
        size: {
          // center-crop
          x: (frame.width / 2) - (320 / 2),
          y: (frame.height / 2) - (320 / 2),
          width: 320,
          height: 320,
        },
        pixelFormat: 'rgb',
        dataType: 'uint8'
      })
    })
  }, [])
```

Edit: If I have both resize outside and inside runAsync, it just crashes with no symbolic stack trace:
```
const frameProcessor = useFrameProcessor((frame) => {
    'worklet'

    const data = resize(frame, {
      size: {
        // center-crop
        x: (frame.width / 2) - (320 / 2),
        y: (frame.height / 2) - (320 / 2),
        width: 320,
        height: 320,
      },
      pixelFormat: 'rgb',
      dataType: 'uint8'
    })

    runAsync(frame, () => {
      'worklet'

      const data = resize(frame, {
        size: {
          // center-crop
          x: (frame.width / 2) - (320 / 2),
          y: (frame.height / 2) - (320 / 2),
          width: 320,
          height: 320,
        },
        pixelFormat: 'rgb',
        dataType: 'uint8'
      })
    })
  }, [])
```

**Comment by rodgomesc** [comment]
> I did that, and I get this error: ` ERROR Frame Processor Error: Exception in HostFunction: java.lang.ClassNotFoundException: Didn't find class "com.mrousavy.camera.frameprocessor.Frame" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/system/lib64, /system/product/lib64, /system/lib64, /system/product/lib64]], js engine: VisionCamera`
> 

that so weird, same problem here

**Comment by mrousavy** [comment]
From reading the error message, it looks like the reason the JNI class cannot be found in `runAsync` is because there is no JNI Environment set up on that specific Thread - which is weird, because we set it up here: https://github.com/margelo/react-native-worklets-core/blob/d8dae58ffac6b7050bb0b410b69acc621dcf74d8/cpp/WKTJsiWorkletContext.cpp#L147-L149

Is that not called when invoking a worklet from JS, @chrfalch ?

**Comment by mrousavy** [comment]
Hey @rodgomesc and @Cosmorider - a discord user posted a SIGABRT stacktrace with symbols attached so I was able to figure out that this came from `JVisionCameraScheduler` - can you guys maybe try if this PR fixes the issue for you? https://github.com/mrousavy/react-native-vision-camera/pull/2457

**Comment by MSchmidt** [comment]
I'm not seeing the same error. I have this one when using runAsync:
```
Frame Processor Error: Exception in HostFunction: java.lang.ClassNotFoundException: Didn't find class "com.facebook.jni.MapIteratorHelper" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/system/lib64, /system_ext/lib64, /system/lib64, /system_ext/lib64]], js engine: VisionCamera
```

The new PR does not fix this particular one.

**Comment by mrousavy** [comment]
@MSchmidt can you try to add a

```cpp
facebook::jni::ThreadScope scope;
```

right **at the top** of this method: https://github.com/mrousavy/react-native-vision-camera/blob/02bc8a979c192707efc5d6e1f424812e36f6369f/package/android/src/main/cpp/frameprocessor/java-bindings/JFrameProcessor.cpp#L35-L45

? Let me know if that works for you

**Comment by mrousavy** [comment]
@MSchmidt in any way to find a fix myself I would need you to also get me a symbolicated stacktrace/crash log just like the one I have posted in PR #2457.

**Comment by mrousavy** [comment]
A second idea would be that I am using `JMap`'s iterator function here: https://github.com/mrousavy/react-native-vision-camera/blob/02bc8a979c192707efc5d6e1f424812e36f6369f/package/android/src/main/cpp/frameprocessor/JSIJNIConversion.cpp#L155-L166

..maybe you are using an older version of fbjni where the map iterator part doesn't exist yet, hence it cannot find `com.facebook.jni.MapIteratorHelper`?

**Comment by MSchmidt** [comment]
`facebook::jni::ThreadScope scope;` added to `package/android/src/main/cpp/frameprocessor/java-bindings/JFrameProcessor.cpp` is not working.

It's the same as this one: https://github.com/mrousavy/react-native-vision-camera/issues/1791#issuecomment-1843543328

It's somehow related to reanimated still. Their plugin does something different from vision camera's. It works when reanimated is thrown out of the project. Which isn't an option though.

**Comment by mrousavy** [comment]
> It's the same as this one: https://github.com/mrousavy/react-native-vision-camera/issues/1791#issuecomment-1843543328

Yea I still need a symbolicated stacktrace. The error linked above just tells me that something inside the Frame Processor crashed, but I need the native C++ stacktrace.

Also the guy (@gbark) said he is not using Reanimated in his project, which makes me doubt that this is something coming from reanimated.

**Comment by mrousavy** [comment]
Okay nevermind - I was able to reproduce this 💪 - this fixes the issue: https://github.com/margelo/react-native-worklets-core/pull/141 🎉

**Comment by mrousavy** [comment]
**Fixed in react-native-worklets-core 0.3.0** 🎉🥳

**Comment by namnotfake** [comment]
> This is not related to VisionCamera, but rather about Reanimated.
> 
> If you do not use Reanimated, `runAsync` works fine. If you do use Reanimated, you need to enable `processNestedWorklets` in the Reanimated's babel plugin. See [software-mansion/react-native-reanimated#5576](https://github.com/software-mansion/react-native-reanimated/issues/5576) for more info

![image](https://github.com/mrousavy/react-native-vision-camera/assets/147969833/9e087adc-7ab8-4432-adce-3886ef108fc8)
![image](https://github.com/mrousavy/react-native-vision-camera/assets/147969833/845f1f3f-d204-41a7-8444-c4f256a0bc28)

I tried to fix it but it didn't work

**Comment by pke** [comment]
@mrousavy do you think it would be a good idea to include the worklet config param `processNestedWorklets` into the docs?

**Comment by Misterr-H** [comment]
<img width="1440" alt="Screenshot 2024-11-10 at 5 48 55 PM" src="https://github.com/user-attachments/assets/5dfaf5b4-83b2-4136-a8d0-9e361e868501">
I'm unable ti resolve this error even after enabling processNestedWorklets in babel config

**Comment by zrina1314** [comment]
My problem is solved, the cache problem, delete the Android project directory in the.gradle folder, and run again

Also, I can't use runAsync to report the same error as you.
I just changed it to runAtTargetFps

 ```
  const frameProcessor = useFrameProcessor(frame => {
    'worklet';
    runAtTargetFps(2, () => {
      ('worklet');
      const results = zxing(frame, { multiple: true });
      convertAndSetResultsJS(results, frame.width, frame.height, frame.orientation);
    });

    // runAsync(frame, frameProcessorCall);
  }, []);
```

**Comment by masterapptech** [comment]
below code works for me.  

//Note: useFrameProcessor from react-native-vision-camera.

  const frameProcessor = useFrameProcessor(
    (frame) => {
      "worklet";
      const faces = detectFaces(frame);
      handleDetectedFaces(faces);
    },
    [handleDetectedFaces, lastBlinkTime, capturePhoto]
  );
