### ISSUE TITLE
🐛 If you use the frame processor, the app will automatically shut down

### ISSUE THREAD

**Issue by dongseobb** [cuvent/react-native-vision-camera#1794]
### What's happening?

I added frame processor to implement vision-camera-ocr.

However, when building, the app shuts down at the same time when you operate the camera even though you saw the phrase "frame processor" is available.

Exits without outputting any error logs.

And when you annotate frameProcessor={frameProcessor}, the function does not work, but the app itself works fine.

What should I do?

### Reproduceable Code

```tsx
const frameProcessor = useFrameProcessor((frame) => {
  'worklet'
  console.log("log test")
}, [])

...

return(
  ...
  <Camera
    ref={camera}
    style={{
      height: '100%',
      width: windowWidth,
    }}
    device={device}
    isActive={showCamera}
    photo={true}
    fps={240}
    frameProcessor={frameProcessor}
  />
  ...
)
```

### Device

IPhone XS (ios 16.6.1)

### VisionCamera Version

3.0.0

### Can you reproduce this issue in the VisionCamera Example app?

- [ ] I can reproduce the issue in the VisionCamera Example app.

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by fedu44** [comment]
![image](https://github.com/mrousavy/react-native-vision-camera/assets/37313502/3e81c36c-c370-481f-a02e-58e4ba187eac)

**Comment by mrousavy** [comment]
> Exits without outputting any error logs.

This is wrong. The issue template tells you how to read logs, read the issue template before opening an issue.

Open adb logcat logs and post them here, otherwise I can't help you.

**Comment by mrousavy** [comment]
Should be fixedi n latest v3
