### ISSUE TITLE
🐛 photoOutput orientation is something weird.

### ISSUE THREAD

**Issue by alsdbtjd0103** [cuvent/react-native-vision-camera#1795]
### What's happening?

I used takePhoto() for Camera. In the case of the back camera, when orientation='portrait' is set, it is taken and stored normally, but even if the portrait is set, the front camera is rotated 90 degrees to the left and stored. (anti-clockwise)

At visionCamera V2 -> It perfectly worked
After update to visionCamera V3 -> It became weird (front camera photo output rotate 90 to left)

I knew that I can use V2, but I want to use V3 because of reanimatedV3

### Reproduceable Code

```tsx
const photo = await cameraRef.current?.takePhoto({
      enableShutterSound: false,
    });

          <View className="w-screen h-[500px] rounded-lg overflow-hidden mb-10">
            <Camera
              ref={cameraRef}
              device={device}
              isActive={active}
              className=" w-full h-full"
              photo={true}
              style={{ flex: 1 }}
              orientation={'portrait'}
            />
          </View>
```

### Relevant log output

```shell
when I used Front: 
photo {"height": 2460, "isMirrored": true, "isRawPhoto": false, "orientation": "landscape-left", "path": "/data/user/0/com.sleepy.mollu/cache/mrousavy854540589847414516.jpg", "width": 3280}

when I used Back:
photo {"height": 3492, "isMirrored": false, "isRawPhoto": false, "orientation": "landscape-right", "path": "/data/user/0/com.sleepy.mollu/cache/mrousavy1616464148184895130.jpg", "width": 4656}
```

### Camera Device

```shell
"formats": [
    {
      "pixelFormats": [
        "rgb",
        "native",
        "yuv"
      ],
      "videoStabilizationModes": [
        "off",
        "standard",
        "off"
      ],
      "autoFocusSystem": "contrast-detection",
      "supportsPhotoHDR": false,
      "photoHeight": 2460,
      "supportsVideoHDR": false,
      "maxISO": 800,
      "minISO": 50,
      "minFps": 1,
      "videoWidth": 1920,
      "videoHeight": 1440,
      "photoWidth": 3280,
      "fieldOfView": 68.83830743678364,
      "maxFps": 30
    },
```

### Device

Android

### VisionCamera Version

3.0.0

### Can you reproduce this issue in the VisionCamera Example app?

- [ ] I can reproduce the issue in the VisionCamera Example app.

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by fedu44** [comment]
+1 using react-native-reanimated same issue

**Comment by fedu44** [comment]
With library react-native-reanimated and orientation="portrait" that stop happening

**Comment by alsdbtjd0103** [comment]
> With library react-native-reanimated and orientation="portrait" that stop happening

How did you fix it??

I currently used imageResizer to rotate image, but I can't assure that this situation always happen in all of devices.

**Comment by mrousavy** [comment]
Yea I think orientation is still a bit weird on some devices. Unfortunately there's no clear solution provided by the Android system so I have to do a bunch of workarounds. I just don't have the devices here to test it on

**Comment by Space6188** [comment]
> With library react-native-reanimated and orientation="portrait" that stop happening

It doesn't work for me

It work only for back type of camera, but not for front.

Can you share your version of reanimated? 

Thank you)

**Comment by mrousavy** [comment]
Hey - orientation is quite tricky to implement, if I get enough sponsors I can take a look at it but there's a ton of edge cases. JFYI; Camera sensors are always 90deg oriented.

**Comment by mrousavy** [comment]
Hey - I'm tracking Orientation in this feature request/issue now: https://github.com/mrousavy/react-native-vision-camera/issues/1891 ✨
