### ISSUE TITLE
🐛 Android frameprocessor Image is already closed

### ISSUE THREAD

**Issue by jess-hwang** [cuvent/react-native-vision-camera#1797]
### What's happening?

When turning on frameprocessor, the following error occurs.

### Reproduceable Code

```tsx
react-native 0.72.0
react-native-vision-camera 3.0.0
react-native-reanimated 3.4.2
react-native-worklets-core 0.2.0
```

### Relevant log output

```shell
Error: Exception in HostObject::get for prop 'width': java.lang.IllegalStateException: Image is already closed, js engine: hermes
Error: Exception in HostObject::get for prop 'width': java.lang.IllegalStateException: Image is already closed, js engine: hermes
Received unknown JNI type "class [F"! Cannot convert to jsi::Value.
```

### Camera Device

```
using format
{
  "autoFocusSystem": "contrast-detection",
  "fieldOfView": 104.12870642532393,
  "maxFps": 30,
  "maxISO": 3200,
  "minFps": 1,
  "minISO": 50,
  "photoHeight": 1816,
  "photoWidth": 4032,
  "pixelFormats": [
    "rgb",
    "native",
    "yuv"
  ],
  "supportsPhotoHDR": true,
  "supportsVideoHDR": false,
  "videoHeight": 2160,
  "videoStabilizationModes": [
    "off",
    "standard",
    "off"
  ],
  "videoWidth": 3840
}
```

### Device

Android  SM-G981N 

### VisionCamera Version

3.0.0

### Can you reproduce this issue in the VisionCamera Example app?

- [X] I can reproduce the issue in the VisionCamera Example app.

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by jess-hwang** [comment]
solved 

I wrote wrong return type of plugin.ts

**Comment by vishva-simform** [comment]
I am facing same issue. Can you share your solution in detail?

**Comment by jess-hwang** [comment]
@vishva-simform  

```
export function plugin(frame:Frame): Frame {
  'worklet'
...
}


fixed

export function plugin(fame: Frame): String[] {
  'worklet'
...
}
```

**Comment by vishva-simform** [comment]
@jess-hwang  
This is my code where I am facing the above error and the error goes infinite, Can you please help me with that?

Error: **Error: Exception in HostObject::get for prop 'width': java.lang.IllegalStateException: Image is already closed**

`import React, {useEffect, useRef} from 'react';`
`import {StyleSheet, Text} from 'react-native';`

`import {
 Camera,
  useCameraDevices,
  useFrameProcessor,
} from 'react-native-vision-camera';`

`const HomeScreen = () => {`
  `const [cameraAccess, setCameraAccess] = React.useState(false);`
  `const devices = useCameraDevices();`
  `const isBackCamera = devices.back;`
  `const frameProcessor = useFrameProcessor(frame => {
    'worklet';
    console.log(frame, 'frame');
  }, []);`
  `const camera = useRef();`

  `const askPermission = async () => {`
    `try {`
      `const getPermission = await Camera.getCameraPermissionStatus();`
     ` if (getPermission === 'denied') {`
        `const reqPrmission = await Camera.requestCameraPermission();`
        `if (reqPrmission === 'granted') {
          setCameraAccess(true);
          console.log('Access granted');
        }`
      }`
    } catch (e) {
      console.log(e);
    }
  };`

  `useEffect(() => {
    console.log('useEffect is called');
    askPermission();
  }, []);`

 ` if (isBackCamera == null && !cameraAccess) {
    console.log('camera not found');
    return <Text>Waiting</Text>;
  }`
  
  `return (`
    `<Camera
      ref={camera}
      style={StyleSheet.absoluteFill}
      device={isBackCamera}
      isActive={true}
      frameProcessor={frameProcessor}
    />`
  `);`
`};`

`export default HomeScreen;
`

**Comment by w4t3r-45** [comment]
i have the same issue , any solutions please ?

**Comment by bglgwyng** [comment]
In my case, it happens occasionally when I turn off the Android device.

**Comment by abdelrahman-muntaser** [comment]
@mrousavy  can you help with this

**Comment by 7emretelli** [comment]
> i have the same issue , any solutions please ?

For anyone who is still facing this issue, here is how I solved the problem:

1) Firstly keep if camera is active or not in a useState hook and use it in the Camera component:
```diff
      <Camera
        frameProcessor={frameProcessor}
        device={device}
+        isActive={isCameraActive}
       {...otherCameraProps}
      />
```

2) Whenever page change or camera is supposed to be closed, set isCameraActive to false.
3) In your frameProcessor function which uses "useFrameProcessor", open an array for dependencies and include "isCameraActive".
```diff
  const frameProcessor = useFrameProcessor(frame => {
    'worklet';
    // your code here

+  }, [isCameraActive]);
```

4) Inside your frameProcessor function, after 'worklet', use condition to check if camera is active. If camera is not active, return without continue processing next lines.
```diff
  const frameProcessor = useFrameProcessor(frame => {
    'worklet';
+    if (!isCameraActive) {
+     return;
+   }
   // your code here
  }, [isCameraActive]);
```

**Comment by jessiemblack** [comment]
Happening on iOS device too.

Error: Cannot get `width`, frame is already closed!

**Comment by 7emretelli** [comment]
@mrousavy issue still continues, thanks.

**Comment by vishaljak** [comment]
@mrousavy getting this issue on android, but the interesting part is that I am not using frame processors. I am just trying to capture an image. I am not sure what's wrong. This is the error exactly: `unknown/unknown: [unknown/unknown] Image is already closed`. I am trying to debug but no idea so far

Testing on Samsung Note 9

TIA

**Comment by FernandoAOborges** [comment]
"java.lang.IllegalStateException: Image is already closed
     FATAL EXCEPTION: mrousavy/VisionCamera.video"  

any news?
