### ISSUE TITLE
V3 installation auto rolls to 2.16.1 after it's release

### ISSUE THREAD

**Issue by hamdij0maa** [cuvent/react-native-vision-camera#1816]
### What's happening?

V3 installation auto rolls to 2.16.1 after it's release

### Reproduceable Code

```tsx
V3 installation auto rolls to 2.16.1 after it's release
```

### Relevant log output

```shell
V3 installation auto rolls to 2.16.1 after it's release
 "react-native-vision-camera": "^2.16.1",
package.json
```

### Camera Device

```json
V3 installation auto rolls to 2.16.1 after it's release
```

### Device

iPhone 14 simulator

### VisionCamera Version

2.16.1

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [X] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
This should be fixedn ow
