### ISSUE TITLE
❓ How to enhance camera stability

### ISSUE THREAD

**Issue by bobbyecho** [cuvent/react-native-vision-camera#1845]
### Question

Hi folks, i wondering how to make live camera preview not shaky, like when i tried to use CameraApp , they don't feel like shaky at all. should i use the frameProcessor to achieve it? some insight might help me so much! thank you!

### What I tried

i tried to set the videoStabilizationMode to device format, but i think this is not intend to do the camera preview stabilization

```
const format = useCameraFormat(device, {
    videoStabilizationMode: {
      target: 'standard',
      priority: 1,
    }
  });
  ```

### VisionCamera Version

3.0.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
This is intended for Camera Preview Stabilization!

I can make this a bit easier though lets see
