### ISSUE TITLE
🐛 No camera device found in IOS simulator 

### ISSUE THREAD

**Issue by hamdij0maa** [cuvent/react-native-vision-camera#1847]
### What's happening?

<img width="489" alt="image" src="https://github.com/mrousavy/react-native-vision-camera/assets/20734472/0c6dea54-58db-47f6-b050-bd3415b8fb53">

### Reproduceable Code

```tsx
const device = useCameraDevice(cameraPosition, {
    physicalDevices: [
      'ultra-wide-angle-camera',
      'wide-angle-camera',
      'telephoto-camera',
    ],
  });
// this hook should check if we are in the simulator it should return null or undefined, without throwing an error in case of a simulator.
```

### Relevant log output

```shell
No camera device could be found!
```

### Camera Device

```json
{

}
```

### Device

Simulator iPhone 15

### VisionCamera Version

3.1.0

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [X] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Whoops, sorry. Fix: #1848
