### ISSUE TITLE
❓ Why Camera preview is a black screen?

### ISSUE THREAD

**Issue by pepperav** [cuvent/react-native-vision-camera#1855]
### Question

Hi 👋,
first of all, I want to thank you @mrousavy  in advance for your incredible work! 👏

Now my question: why I'm getting a black screen when app starts?

**package.json**
```
{
  "name": "visioncamera",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@types/react": "~18.2.14",
    "expo": "~49.0.12",
    "expo-dev-client": "~2.4.11",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.5",
    "react-native-vision-camera": "^3.1.0",
    "react-native-worklets-core": "^0.2.0",
    "typescript": "^5.1.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
```

**App.tsx**
```
import { Camera, useCameraDevice, useFrameProcessor } from 'react-native-vision-camera';
import { useEffect } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';

export default function App() {
	const frameProcessor = useFrameProcessor((frame) => {
		'worklet'
		console.log(`Frame: ${frame.width}x${frame.height} (${frame.pixelFormat})`)
	}, []);

	const device = useCameraDevice('back');

	useEffect(() => {
		const cameraPermissions = async () => {
			const cameraPermission = await Camera.getCameraPermissionStatus();
			console.log("cameraPermission", cameraPermission);
			await Camera.requestCameraPermission();
		};

		cameraPermissions();
	}, []);

	if (device == null) return <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}><Text>Loading...</Text></View>

	return (
		<>
			<StatusBar style='light' />
			<Camera
				style={StyleSheet.absoluteFill}
				device={device}
				isActive={true}
				frameProcessor={frameProcessor}
			/>
		</>
	);
}
```

**Platform**
Android (_RedMi - MIUI Global 12.5.1_)

### What I tried

I tried to use `useCameraDevices()` and then find device with `position === 'back'` but I get always a black screen

### VisionCamera Version

3.1.0

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey, thanks man I appreciate it.

This is not a question though, please create a bug report and fill out the bug report template.
