### ISSUE TITLE
🐛 Incorrect zoom on Android < 11

### ISSUE THREAD

**Issue by touchmarine** [cuvent/react-native-vision-camera#1865]
### What's happening?

Camera by default shows a zoomed preview and setting a larger zoom results in less zoom. For example, `zoom={4}` is less zoomed in than `zoom={1}`.

The issue is fixed if I replace the `Rect.zoomed` with:

```kotlin
fun Rect.zoomed(zoomFactor: Float): Rect {
  val dx = (width() / zoomFactor / 2).toInt()
  val dy = (height() / zoomFactor / 2).toInt()
  val left = centerX() - dx
  val top = centerY() - dy
  val right = centerX() + dx
  val bottom = centerY() + dy
  return Rect(left, top, right, bottom)
}
```

### Reproduceable Code

```tsx
const devices = Camera.getAvailableCameraDevices()
const device = devices.find((d) => d.position === 'front')

<Camera
  isActive
  device={device}
  style={StyleSheet.absoluteFill}
/>
```

### Relevant log output

```shell
/
```

### Camera Device

```json
{
  "sensorOrientation": "landscape-left",
  "hardwareLevel": "limited",
  "maxZoom": 4,
  "minZoom": 1,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": false,
  "isMultiCam": false,
  "name": "FRONT (1)",
  "hasFlash": false,
  "hasTorch": false,
  "position": "front",
  "id": "1"
}
```

### Device

Samsung Galaxy S8+ (Android 9)

### VisionCamera Version

3.1.0

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [X] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey! Thanks, if this fixes the issue please submit a PR :)
