### ISSUE TITLE
Does the package support recording at higher FPS❓ 

### ISSUE THREAD

**Issue by ainnotate** [cuvent/react-native-vision-camera#1868]
### Question

Hi, Thanks for the awesome package. We are considering integrating react-native-vision-camera to our project. 

Question: Does this package allow recording video at any desired FPS (10, 15, 30, 60, 120)? I understand that higheer fps such as 60 and 120 is dependent on the resolution used and the actual hardware support.

I've gone through  [this](https://www.react-native-vision-camera.com/docs/api/interfaces/RecordVideoOptions) and [this](https://github.com/mrousavy/react-native-vision-camera/issues/770). However, would like get an official confirmation of recording at a desired fps is fully supported with the latest version.

Thank you.

### VisionCamera Version

3.1.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey, yes it does. It supports recording at whatever Frame Rate the native Camera APIs allow you to record. 

Some Samsung devices don't allow you to record in 60 FPS even though their stock camera app can do 60 FPS though, this is on Samsung though.
