### ISSUE TITLE
[!] Unable to find a specification for `React-callinvoker` depended upon by `VisionCamera`🐛 

### ISSUE THREAD

**Issue by jagdeepChicmic** [cuvent/react-native-vision-camera#1872]
### What's happening?

when we install the pod file its gave me error

[!] Unable to find a specification for `React-callinvoker` depended upon by `VisionCamera`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

### Reproduceable Code

```tsx
update react native version 0.69.12 to 0.72.0
```

### Relevant log output

```shell
After pod install --repo-update command its shows same error

[!] Unable to find a specification for `React-callinvoker` depended upon by `VisionCamera`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

### Camera Device

```json
install pod
```

### Device

IPhone 13 prp

### VisionCamera Version

3.1.0

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
this should be fixed with latest
