### ISSUE TITLE
❓ Does the video format affect taking a photo 

### ISSUE THREAD

**Issue by stevengoldberg** [cuvent/react-native-vision-camera#1885]
### Question

I recently updated to expo SDK49 and vision-camera v 3.1.0 from 2.15 and I'm confused by the behavior of the camera. I'm trying to take a 4:3 photo in maximum quality while also minimizing delay. I'm testing with an iPhone 14 Pro.

This is how I'm selecting a device:

```
 const physicalDevices =
        cameraPosition === 'back'
            ? [
                  'ultra-wide-angle-camera',
                  'wide-angle-camera',
                  'telephoto-camera',
              ]
            : ['wide-angle-camera']

    const device = useCameraDevice(cameraPosition, { physicalDevices })

    const format = useCameraFormat(device, [
        {
            photoAspectRatio: 4 / 3,
        },
        { photoResolution: 'max' },
        { videoAspectRatio: 4 / 3 },
        { videoResolution: 'max' },
    ])
```
And this is how I'm taking the photo:
```
camera.current
            .takePhoto({
                qualityPrioritization: 'quality',
                enableAutoStabilization: true,
            })
```
When I take a photo like this, there's a noticeable delay between pressing the button and the load of the resulting image, but the photo looks good. The image is very sharp, even if the camera is moving as I take it. The iOS photos app reports it as 12MP, 3024x4032, 4.2MB, taken with the Telephoto Camera.

Now, if I change the format filter to this:
```
    const format = useCameraFormat(device, [
        {
            photoAspectRatio: 4 / 3,
        },
        { photoResolution: 'max' },
        { videoAspectRatio: 4 / 3 },
        { videoResolution: { height: 1944, width: 2592 } },
    ])
```
Taking the photo results in a much smaller delay, but the image quality is worse — it's very blurry, like image stabilization is not being used. My phone says this photo is taken by the same camera, same resolution, but has a smaller filesize: 1.8 MB.

Also, if I don't specify anything about the video format, like this:

```
 const format = useCameraFormat(device, [
        {
            photoAspectRatio: 4 / 3,
        },
        { photoResolution: 'max' },
    ])
```
It autoselects the lowest-resolution video format, which is 192x144, and the result of `takePhoto` is still 3024x4032 but very blurry.

Is this intended behavior? I find it surprising that the video settings would affect taking a photo.

### VisionCamera Version

3.1.0, 3.20

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey!

No, photo resolution should not affect video resolution or vice versa.

What you're seeing is technically a bug, so it would've been great if you filled out the bug template as it asks you a few more relevant questions, but now I'm just gonna ask them myself:

1. Can you please share the formats that are being chosen (`console.log(JSON.stringify(format))`), so both the good one and the low quality one
2. Is that iOS or Android?

**Comment by stevengoldberg** [comment]
Sure — this is an iPhone 14 Pro running iOS 16.6.1.

Fast result / blurry photo:
```
const format = useCameraFormat(device, [
        {
            photoAspectRatio: 4 / 3,
        },
        { photoResolution: 'max' },
    ])

// {"minFps":60,"maxFps":60,"videoHeight":144,"supportsVideoHDR":false,"photoHeight":3024,"maxZoom":189,"pixelFormats":["yuv","yuv","rgb","yuv","unknown","yuv","unknown","rgb","unknown"],"videoStabilizationModes":["auto","off"],"supportsPhotoHDR":false,"autoFocusSystem":"phase-detection","photoWidth":4032,"minISO":57,"maxISO":5472,"supportsDepthCapture":false,"videoWidth":192,"fieldOfView":98.91507720947266}
```
Or:
```
 const format = useCameraFormat(device, [
        {
            photoAspectRatio: 4 / 3,
        },
        { photoResolution: 'max' },
        { videoAspectRatio: 4 / 3 },
        { videoResolution: { height: 1944, width: 2592 } },
    ])

// {"supportsVideoHDR":false,"photoHeight":3024,"videoHeight":1944,"fieldOfView":101.3733901977539,"supportsPhotoHDR":false,"autoFocusSystem":"phase-detection","minISO":57,"maxZoom":189,"pixelFormats":["yuv","yuv","rgb","yuv","unknown","yuv","unknown","rgb","unknown"],"videoStabilizationModes":["auto","off"],"videoWidth":2592,"minFps":30,"maxISO":5472,"supportsDepthCapture":false,"photoWidth":4032,"maxFps":30}
```

Slower result / sharp photo:
```
const format = useCameraFormat(device, [
        {
            photoAspectRatio: 4 / 3,
        },
        { photoResolution: 'max' },
        { videoAspectRatio: 4 / 3 },
        { videoResolution: 'max' },
    ])

// {"supportsDepthCapture":false,"maxISO":12768,"minFps":30,"fieldOfView":101.3733901977539,"maxFps":30,"maxZoom":189,"videoStabilizationModes":["auto","off"],"pixelFormats":["yuv","yuv","rgb","yuv","unknown","yuv","unknown","rgb","unknown"],"supportsPhotoHDR":false,"autoFocusSystem":"phase-detection","minISO":57,"videoHeight":3024,"supportsVideoHDR":false,"photoHeight":3024,"videoWidth":4032,"photoWidth":4032}
```
The rest of the code is the same in both instances —

```
 <Camera
    ref={cameraRef}
    device={device}
    enableHighQualityPhotos
    enableAutoStabilization
    isActive={isActive}
    photo
    hdr
    format={format}
    zoom={device.neutralZoom}
/>

// ...

camera.current.takePhoto({
    qualityPrioritization: 'quality',
    enableAutoStabilization: true,
})
```

It seems like the ISO is the difference. The blurry photo is reported as ISO 80 with 1/30 s speed, and the sharp photo is ISO 250 with 1/60 s speed.

**Comment by mrousavy** [comment]
Interesting!

1. Does the preview look like it has lower resolution in the first case?
2. Does the resulting photo actually have the dimensions that it claims in the format?
3. If ISO is the case, I need to investigate that more - I want to expose those props anyways.

**Comment by stevengoldberg** [comment]
Yes, the preview looks like it matches the video resolution in the format, so it’s very visibly pixelated in the first example above when video resolution isn’t explicitly chosen. But the camera starts up very quickly!

And yes, the resulting photo always has the chosen resolution. The only difference I can see in the EXIF data seems to be ISO and exposure time.

**Comment by mrousavy** [comment]
Awesome okay so looks like there's no issue with VisionCamera and everything works as expected!

I guess you want your video resolution to be somewhat close to the screen resolution at least.

As for ISO; I'll maybe do a PR in the coming days or weeks to implement explicit support for controlling that, but this is unrelated to your question as you could just filter for high ISO right?

Or actually now that I'm writing this I don't think that the filter supports ISO filtering so I'll just quickly add that to the useCameraFormat function and you should be good 👍

**Comment by nica0012** [comment]
I too am seeing a blurry camera preview, with a similar format.

Camera quality seems to be poor when I am using a different size camera view (square or 4:3).

**Comment by stevengoldberg** [comment]
Hey @mrousavy, thanks for all of your work on this library. You mentioned adding support for filtering by ISO to `useCameraFormat` is that still on the TODO list?

**Comment by mrousavy** [comment]
Yea, but it's way back on my TODO list since no one is sponsoring that. I'll focus on sponsored issues first :)

**Comment by stevengoldberg** [comment]
Gotcha, no worries since it’s pretty straightforward to do manually anyway.

**Comment by mrousavy** [comment]
@stevengoldberg see this for a WIP: https://github.com/mrousavy/react-native-vision-camera/pull/2234

**Comment by commbits** [comment]
videoResolution clearly affects photoResolution: In the implementation below, photos are taken at 1024X768, although photoResolution='max'.
If we only change videoResolution: 'max', then photo resolution is going up to max indeed.
 const format = getCameraFormat(device, [
        { videoStabilizationMode: 'auto' },
        { photoAspectRatio: 4 / 3 },
        { videoAspectRatio: 4 / 3 },
        { lowLightBoost: true },
        { photoResolution: 'max' },
        {
           videoResolution: { width: 1024, height: 768 },
        },
    ])

**Comment by stevengoldberg** [comment]
> videoResolution clearly affects photoResolution: In the implementation below, photos are taken at 1024X768, although photoResolution='max'. If we only change videoResolution: 'max', then photo resolution is going up to max indeed. const format = getCameraFormat(device, [ { videoStabilizationMode: 'auto' }, { photoAspectRatio: 4 / 3 }, { videoAspectRatio: 4 / 3 }, { lowLightBoost: true }, { photoResolution: 'max' }, { videoResolution: { width: 1024, height: 768 }, }, ])

I don't think video resolution affects photo resolution per se; it's more a side effect of how formats work. There is a finite number of formats with fixed options. `getCameraFormat` tries to select an appropriate format based on your criteria, but there may not be a format that matches all of the options. By changing the options object, you end up with a different format.

So the format on your device with a video resolution of 1024x768 doesn't have the highest photo resolution. When you choose the format with the max video resolution, it has a higher photo resolution as well. You can see this by logging all of the available device formats.

**Comment by commbits** [comment]
I see. Thank you very much explaining.

How can we log all available formats?

**Comment by stevengoldberg** [comment]
> I see. Thank you very much explaining. How can we log all available formats? 

See here: https://www.react-native-vision-camera.com/docs/guides/formats#choosing-custom-formats
https://www.react-native-vision-camera.com/docs/api/interfaces/CameraDevice#formats

**Comment by mrousavy** [comment]
Exactly @stevengoldberg 👍🙌
