### ISSUE TITLE
FAILURE: Build failed with an exception. minSdkVersion = 24 & 26 too. 

### ISSUE THREAD

**Issue by hamdij0maa** [cuvent/react-native-vision-camera#1915]
### How were you trying to build the app?

bun Android , yarn android
FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:react-native-vision-camera:cleanCmakeCache
\--- :react-native-vision-camera:cleanCmakeCache (*)

### Full build logs

```tsx
FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:react-native-vision-camera:cleanCmakeCache
\--- :react-native-vision-camera:cleanCmakeCache (*)
```

### Project dependencies

```json
react-native-vision-camera:3.3.0
```

### VisionCamera Version

3.3.0

### Target platforms

Android

### Operating system

MacOS

### Can you build the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by hamdij0maa** [comment]
./gradlew clean error

**Comment by idrissakhi** [comment]
having the same issue with same version

**Comment by NTKrieger** [comment]
I'm also having this issue, but only in my build pipeline.  I don't see this in debug builds locally for some reason, probably cache.  I'm looking into it and will post a PR if I come up with a fix.

**Comment by NTKrieger** [comment]
Not sure this is a permanent fix, but I think it's related to calling .dependsOn(cleanCmakeCache) twice in build.gradle.  I commented out lines 177-179 at the bottom of android/build.gradle and it built.

```
tasks.configureEach { task ->
  // C++ build
  if (task.name.contains("configureCMakeDebug")) {
    rootProject.getTasksByName("packageReactNdkDebugLibs", true).forEach {
      task.dependsOn(it)
    }
  }
  if (task.name.contains("configureCMakeRel")) {
    rootProject.getTasksByName("packageReactNdkReleaseLibs", true).forEach {
      task.dependsOn(it)
    }
  }
  // C++ clean
  // if (task.name.contains("clean")) {
  //   task.dependsOn(cleanCmakeCache)
  // }
}
```

**Comment by l7aromeo** [comment]
Same problem here

```
What went wrong:
Circular dependency between the following tasks:
:react-native-vision-camera:cleanCmakeCache
\--- :react-native-vision-camera:cleanCmakeCache (*)
...
```

Packages:
```
"react": "18.2.0",
"react-native": "^0.72.5",
"react-native-reanimated": "^3.5.4",
"react-native-vision-camera": "^3.3.0",
"react-native-worklets-core": "^0.2.1",
```


I tried the example which has packages:
```
"react": "^18.2.0",
"react-native": "^0.72.3",
"react-native-reanimated": "^3.4.2",
"react-native-worklets-core": "^0.2.0"
```
and it's working.

-------------


### Temporary Solutions:
Need to edit "/node-modules/react-native-vision-camera/android/build.gradle" line 177.
From:
```
if (task.name.contains("clean")) {
    task.dependsOn(cleanCmakeCache)
}
```
To:
```
if (task.name.contains("clean") && task.name != "cleanCmakeCache") {
    task.dependsOn(cleanCmakeCache)
}
```

It was looping here I think

**Comment by mrousavy** [comment]
Hey, good catch @L7ARomeo, I would appreciate a PR for this :)

EDIT: ok I just did it myself in #1924

**Comment by FreTimmerman** [comment]
3.3.1 indeed fixes this. thanks for the fast work! 👍

**Comment by mrousavy** [comment]
thanks!
