### ISSUE TITLE
❓ Can you please change published latest version to 3.3.0 instead of 2.16.2?

### ISSUE THREAD

**Issue by Romick2005** [cuvent/react-native-vision-camera#1926]
### Question

![image](https://github.com/mrousavy/react-native-vision-camera/assets/17779660/5bcba6e1-42a3-48de-8b06-5b4dc42f19db)

### What I tried

`npm i react-native-vision-camera@latest`

### VisionCamera Version

3.2.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
done
