### ISSUE TITLE
Does your camera actually use 'telephoto-camera' while zooming❓ 

### ISSUE THREAD

**Issue by sonnv174** [cuvent/react-native-vision-camera#1933]
### Question

I'm trying and running your [Vision Camera example code](https://github.com/mrousavy/react-native-vision-camera/tree/main/package/example) and found that app did not use 'telephoto-camera' when I zoom in until max zoom.

I just tested and compared it with the original Camera app of the iPhone 13 Pro that I'm using for development. I saw that the quality of images were not same.

Image from Vision Camera app
![IMG_4862](https://github.com/mrousavy/react-native-vision-camera/assets/25454863/d0b83de6-6e8d-4820-9730-af38bd0f4c7e)
Image from iPhone Camera app
![IMG_4863](https://github.com/mrousavy/react-native-vision-camera/assets/25454863/1dc0ea25-3a0b-4896-8f5a-a8cffcf783e3)

I also fixed the code to choose Back Triple Camera (Ultra-Wide + Wide + Telephoto).
<img width="685" alt="image" src="https://github.com/mrousavy/react-native-vision-camera/assets/25454863/af3bc6e5-ff41-4a23-aaeb-fca237979610">

Does your camera actually use 'telephoto-camera' while zooming❓ 
And  1 more question, how can I convert the current zoom level to 0.5x - 1x - 3x and until 10x that is like the original Camera app of the iPhone 13 Pro❓ I wanna show this info on the screen.

### VisionCamera Version

V3

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
> Does your camera actually use 'telephoto-camera' while zooming

No, I changed the example to only use the wide-angle camera as it was faster to start up and simpler for most cases. The docs explain very well how you can use the telephoto as well, this is entirely possible and easy to do with VisionCamera.

> I also fixed the code to choose Back Triple Camera

This was not a bug.

> And 1 more question, how can I convert the current zoom level to 0.5x - 1x - 3x and until 10x that is like the original Camera app of the iPhone 13 Pro❓ I wanna show this info on the screen.

The device exposes those props
