### ISSUE TITLE
is it not work IPhone 14 Pro && IOS 17.0.2, 17.0.3❓ 

### ISSUE THREAD

**Issue by LESANF** [cuvent/react-native-vision-camera#1940]
### Question

I am using version 2.15.4 and also using react-native 0.70.5 version

The camera components are brought in, but they don't seem to work when you take a picture.

It operates normally on other devices.

It also works on iPhone 12 and iOS17 However, it does not work with iPhone 14 Pro and IOS 17.0.2, 17.0.3.

Is there a solution? 

### What I tried

I want to test by uploading the version of the vision camera, but xcode 15 also does not allow the connection of the ios17 to the practical machine test. The photographing function is not activated in the emulator, so it cannot be tested.

### VisionCamera Version

2.15.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Not a question. Should've been a bug report. Not enough details.
