### ISSUE TITLE
🐛 External Camera not working

### ISSUE THREAD

**Issue by huzaifaazim0** [cuvent/react-native-vision-camera#1950]
### What's happening?

i want to capture picture and record video from an external camera connected through usb otg.
useCameraDevice('external') is returning undefined
useCameraDevices() is also not returning any external camera\

i created a new react native  app, installed the latest library and used this code 

**i need the help fast
i am open to pay 100$ to a person who will help me**

### Reproduceable Code

```tsx
import React, { useEffect } from 'react';
import type {PropsWithChildren} from 'react';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  useColorScheme,
  View,
} from 'react-native';

import {
  Colors,
  DebugInstructions,
  Header,
  LearnMoreLinks,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';

import { useCameraDevice, Camera, useCameraPermission, useCameraDevices} from 'react-native-vision-camera';

type SectionProps = PropsWithChildren<{
  title: string;
}>;


function App(): JSX.Element {
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  const { hasPermission, requestPermission } = useCameraPermission()
  
  const device = useCameraDevice('external')
  var devices = useCameraDevices()
  
  // listener.remove()
  useEffect(()=>{
    requestPermission()
  })

  useEffect(()=>{
    console.log(devices)
  },[devices])

  useEffect(()=>{
    console.log("\"=====================\"",device)
  },[device])


  

  
  if (device == null) return <><Text>No Camera Found</Text></>
  return (
    <Camera
      style={StyleSheet.absoluteFill}
      device={device}
      isActive={true}
    />
  )
}

const styles = StyleSheet.create({
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
  },
  highlight: {
    fontWeight: '700',
  },
});

export default App;
```

### Relevant log output

```shell
...
```

### Camera Device

```json
undefined
```

### Device

Samsung s22 ultra

### VisionCamera Version

^3.3.1

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey, read the [External Devices](https://react-native-vision-camera.com/docs/guides/devices#selecting-external-cameras) section in the docs.
The external Camera needs to support the UVC (USB Video Class) Specification. If it does not support that, there's no way to use it with Camera2, meaning it cannot be used with VisionCamera.

Those devices require a fully manual USB driver, and this is not something VisionCamera should support as this is not generic at all.
