### ISSUE TITLE
✨ Distributable Frame Processor Plugin Example for v3

### ISSUE THREAD

**Issue by xulihang** [cuvent/react-native-vision-camera#1952]
### What feature or enhancement are you suggesting?

In the docs, it says we can create a blank Native Module using [bob](https://github.com/callstack/react-native-builder-bob) or [create-react-native-module](https://github.com/brodybits/create-react-native-module) to distribute frame processor plugins. 

But I didn't manage to make it work using bob for v3. I wish there was a distributable frame processor plugin example using bob.

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

No workarounds.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by xulihang** [comment]
A migration guide from v2 to v3 would also be great to have. Like Capacitor's guide: https://capacitorjs.com/docs/updating/plugins/5-0

**Comment by mrousavy** [comment]
Yea would be amazing if we can bring this into bob, but the create frame processor CLI can do this

**Comment by xulihang** [comment]
There is now an example here: https://github.com/ismaelsousa/vision-camera-ocr/tree/v2
