### ISSUE TITLE
Send Realtime Frame to python project using Socket❓ 

### ISSUE THREAD

**Issue by hasnainali9** [cuvent/react-native-vision-camera#1956]
### Question

i have a react native app with frame processor enabled. I have a senerio where i want to send the frame image to a python app using socket. i have try to convert the frame to base64 image but could able to achieve it as the community library is not maintained which cause issue while building the app. I just want to know what is the best to achieve the senerio of sending the image to python app without dependent on any external library.

### VisionCamera Version

3.3.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey, you can easily create a simple native Frame Processor Plugin inside your app for this. This is just very few lines of native code that can efficiently convert the Frame and send them over the Web
