### ISSUE TITLE
🐛 ReanimatedError: Property '__scanFaces' doesn't exist, js engine: reanimated

### ISSUE THREAD

**Issue by michelorth** [cuvent/react-native-vision-camera#1959]
### What's happening?

When activating the camera using

frameProcessor={frameProcessor}

Gives the following error: ReanimatedError: Property '__scanFaces' doesn't exist, js engine: reanimated

if I remove the frameProcessor it works

My dependencies are:

"react-native-worklets-core": "^0.2.2",
"vision-camera-face-detector": "^0.1.8",
"react-native-vision-camera": "^2.16.2",
"react-native-reanimated": "^3.5.3",

My babel.config

module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    ['react-native-worklets-core/plugin'],
    [
      'react-native-reanimated/plugin',
      {
        globals: ['__scanFaces'],
      },
    ],
  ],
};

### Reproduceable Code

```tsx
const frameProcessor = useFrameProcessor((frame) => {
    'worklet';
    const scannedFaces = scanFaces(frame);
    runOnJS(setFaces)(scannedFaces);
  }, []);

<Camera
        ref={camera}
        style={StyleSheet.absoluteFill}
        onInitialized={onInitialized}
        frameProcessor={frameProcessor}
        frameProcessorFps={5}
        takePhoto={() => takePhoto(props.isConnectedInternet)}
        id="camera"
        preset="medium"
        device={device}
        isActive={isActive}
        enableZoomGesture={false}
        orientation="portrait"
        photo
        zoom={0}
      />
```

### Relevant log output

```shell
ReanimatedError: Property '__scanFaces' doesn't exist, js engine: reanimated
```

### Camera Device

```json
{
  "minZoom": 1,
  "isMultiCam": false,
  "supportsLowLightBoost": false,
  "supportsDepthCapture": false,
  "neutralZoom": 1,
  "supportsRawCapture": false,
  "supportsFocus": false,
  "position": "front",
  "devices": [
    "wide-angle-camera"
  ],
  "hasTorch": false,
  "supportsParallelVideoProcessing": true,
  "hasFlash": true,
  "name": "Front Camera",
  "id": "com.apple.avfoundation.avcapturedevice.built-in_video:1",
  "maxZoom": 189
}
```

### Device

Iphone 12 - 17.0.3

### VisionCamera Version

2.16.2

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by sacha-c** [comment]
I get a similar issue after updating to v2.16.2 when trying to use `vision-camera-code-scanner` for qr code scanning. The error I get is `__scancodes` does not exist. Only occurs on iOS

I've tried updating to v3 and using Frame Processors there, but looks like the minimum API version for android is 29 when using frame processors which unfortunately too much of a leap for my project

(regarding my particular issue; I know rn camera vision v3 now comes shipped with qr scanning, but there is [this android](https://github.com/mrousavy/react-native-vision-camera/issues/1921) lagging issue which is why I tried to continue using frame processors and ran into the above issue)

**Comment by ronix1020** [comment]
RN Face Detector also need a update, any alternative?

**Comment by nhatnguyen95** [comment]
I have same issues, It works on previous versions but not on "react-native-vision-camera": "2.16.2"

**Comment by Spikus** [comment]
It's looks' with updated `react-native-reanimated ` globals in plugin not works anymore. 
Same issue for `__scanOCR` https://github.com/aarongrider/vision-camera-ocr

Can't update to V3 because no working OCR plugin for v3

**Comment by CaioQuirinoMedeiros** [comment]
Same issue here, `ReanimatedError: Property '__scanCodes' doesn't exist, js engine: reanimated`, on iOS, after updating vision-camera to "2.16.2" and reanimated to "3.5.4".

It was working fine with vision-camera "2.15.4" and reanimated "2.14.4"... I had to upgrade because of the #1840

**Comment by suwu150** [comment]
> It's looks' with updated `react-native-reanimated ` globals in plugin not works anymore. Same issue for `__scanOCR` https://github.com/aarongrider/vision-camera-ocr
> 
> Can't update to V3 because no working OCR plugin for v3

https://github.com/mrousavy/react-native-vision-camera/issues/1987

When I introduced these plugins, I encountered an error when compiling the camera version 3.3.0

**Comment by Simoon-F** [comment]
same.

```sh
"react-native": "0.71.14",
 "react-native-reanimated": "^3.5.4",
 "react-native-vision-camera": "^2.16.2",
```

**Comment by sommcz** [comment]
To test dependency on Xcode15 I've downgraded my Xcode to 14.3.1 (latest 14) and check app with following versions:

This version has no issue:
 "react-native-reanimated": "3.5.4",
 "react-native-vision-camera": "2.16.1" and  "react-native-vision-camera": "2.16.0",

This version has issue using both Xcode14 and 15.
 "react-native-reanimated": "3.5.4",
 "react-native-vision-camera": "2.16.2"

**Comment by Simoon-F** [comment]
I plan to upgrade the package 'react-native-vision-camera' to '3.3.1 'and use the new version's built-in frame processor, which will reduce the time I have to deal with many problems.

In fact, I have already replaced it, and the effect is very good at present.

**Comment by mrousavy** [comment]
So this is happening because the face-detector hasn't upgraded to V3 yet. Wait for the plugin from Aaron to upgrade to V3, then try again - there is a PR with that.

Not a VisionCamera issue

**Comment by abdulRafay2003** [comment]
any solution for this?.This issue still exist
