### ISSUE TITLE
🐛 Adding border around Camera's direct parent causes offset preview

### ISSUE THREAD

**Issue by High5Apps** [cuvent/react-native-vision-camera#1964]
### What's happening?

Using `react-native-vision-camera@3.3.1` on an iPhone 13 Mini, adding a border to the direct parent of a `Camera` component causes the preview to be offset and slightly smaller than it should be, despite the `Camera` having a `style` of `StyleSheet.absolutefill` (see first screenshot). Setting `borderWidth: 0` prevents the issue (see second screenshot). I believe the offset size is related to the `borderWidth`, since doubling the `borderWith` seems to double the offset (see third screenshot). This only happens on my iPhone 13 Mini, not on my Android S10, leading me to believe that this is an iOS-only issue. I did not face this same issue when I was on `2.15.4`, but only started hitting it when I recently upgraded from `2.15.4` to `3.3.1`.

Here's a **workaround** for others hitting this issue (see fourth screenshot). Just add an additional `View` component without a border as the direct child of your bordered component, and as direct parent of the `Camera`. **Note: The workaround below works for v3. For v4, use [this workaround](https://github.com/mrousavy/react-native-vision-camera/issues/1964#issuecomment-2071870999) instead. For v4.6.4 and React Native 77 (New Architecture), use [this workaround](https://github.com/mrousavy/react-native-vision-camera/issues/1964#issuecomment-2719263463) instead.**
```javascript
<View style={{ borderWidth: 8, borderColor: 'red', ... }}>
  {/* Add the view below as a workaround */}
  <View style={StyleSheet.absoluteFill}>
    <Camera ... />
  </View>
</View>
```

With `borderWidth: 8`:
![with-border](https://github.com/mrousavy/react-native-vision-camera/assets/3528716/89fb665a-0465-4dc9-83e6-2adc43587925)

With `borderWidth: 0`:
![without-border](https://github.com/mrousavy/react-native-vision-camera/assets/3528716/767f1e2d-35a3-4d71-af03-57aa80261fda)

With `borderWidth: 16`:
![with-double-sized-border](https://github.com/mrousavy/react-native-vision-camera/assets/3528716/77ae7bc1-7c25-4c96-aee7-c04d2619b228)

With `borderWith: 8` and workaround:
![with-border-workaround](https://github.com/mrousavy/react-native-vision-camera/assets/3528716/47768ea7-f6bb-41c9-82e2-ff689afbe8eb)

### Reproduceable Code

```tsx
// Modifying the 3.3.1 example app CameraPage.ts line 172
// https://github.com/mrousavy/react-native-vision-camera/blob/a498144fd5786c6dba1d78730d362e0f675cbaf7/package/example/src/CameraPage.tsx#L172
// The 2 Views are added, the ReanimatedCamera is unchanged, aside from disabling the fpsGraph
// Note that in order to get the 3.3.1 example app to build, I needed to comment out the line 289 in CameraView+AVCaptureSession.swift
// https://github.com/mrousavy/react-native-vision-camera/blob/a498144fd5786c6dba1d78730d362e0f675cbaf7/package/ios/CameraView%2BAVCaptureSession.swift#L289

<View style={{ flex: 1, justifyContent: 'center' }}>
  <View style={{ alignSelf: 'center', borderWidth: 8, borderColor: 'red', height: 150, width: 150 }}>
    <ReanimatedCamera ... />
  </View>
</View>
```

### Relevant log output

```shell
No relevant log outputs or errors, just a style issue
```

### Camera Device

```json
{
  "maxZoom": 121.875,
  "minZoom": 1,
  "hasTorch": true,
  "isMultiCam": false,
  "hardwareLevel": "full",
  "position": "back",
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsRawCapture": false,
  "supportsFocus": true,
  "neutralZoom": 1,
  "name": "Back Camera",
  "hasFlash": true,
  "id": "com.apple.avfoundation.avcapturedevice.built-in_video:0",
  "supportsLowLightBoost": false,
  "sensorOrientation": "portrait",
  "formats": []
}
```

### Device

iPhone 13 Mini (iOS 16.6.1)

### VisionCamera Version

3.3.1

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by High5Apps** [comment]
Regarding the note below from my code in the Reproduceable Code section:
```
// Note that in order to get the 3.3.1 example app to build, I needed to comment out the line 289 in CameraView+AVCaptureSession.swift
// https://github.com/mrousavy/react-native-vision-camera/blob/a498144fd5786c6dba1d78730d362e0f675cbaf7/package/ios/CameraView%2BAVCaptureSession.swift#L289
```

I believe that this build failure is likely unrelated to this bug report, but for completeness, here's the error message:
```
 'NSInvalidArgumentException', reason: '*** -[AVCaptureFigVideoDevice setAutomaticallyEnablesLowLightBoostWhenAvailable:] Not supported - use -isLowLightBoostSupported'
```

**Comment by mrousavy** [comment]
Lol this is an interesting issue

**Comment by davidredshaw** [comment]
I have a similar issue with 3.6.4 on an iPhone XS Max

Page Structure:

It's a flexbox layout - the header and controls are 75 pixels high and the camera is 100% with flexShrink = 1, so I expect it to occupy the full space between the header above and controls below:

<img width="361" alt="image" src="https://github.com/mrousavy/react-native-vision-camera/assets/47686115/016cdafb-4070-4414-8baf-6e0d0f02db62">

Camera Function

<img width="626" alt="image" src="https://github.com/mrousavy/react-native-vision-camera/assets/47686115/7132c68d-8727-4e42-820b-81ae3cda108a">

Stylesheet

<img width="310" alt="image" src="https://github.com/mrousavy/react-native-vision-camera/assets/47686115/695c9f77-0b17-4de4-9f9e-14d99d28a35b">

Result: the magenta background is the camera background

<img width="420" src="https://github.com/mrousavy/react-native-vision-camera/assets/47686115/40af7715-ad55-4a18-9370-6d57c25e42fa">

If I change the Camera Function as follows, wrapping the camera in two containers (AbsoluteFill is needed on the camera and the immediate parent):

<img width="920" alt="image" src="https://github.com/mrousavy/react-native-vision-camera/assets/47686115/0620c150-f590-447b-bf5c-dfc9d7a6cf74">

The display is as expected:

<img width="420" src="https://github.com/mrousavy/react-native-vision-camera/assets/47686115/2ec70fbf-d9e0-4816-abdf-23ee344b9f1f">

**Comment by ClaireLundy** [comment]
@davidredshaw I had the same issue and was able to fix it by wrapping the Camera component in a View with flex 1. Try changing it to
```
<View style={{flex: 1, backgroundColor: 'green`}}>
    <Camera style={{flex:1}} ... />
</View>
```

**Comment by mrousavy** [comment]
Hey - I think this issue has been fixed in [VisionCamera 4.0.0](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v4.0.0). 🥳 

Please try V4 and let me know if you still experience this issue;
- if not, please consider [💖 **sponsoring me on GitHub** 💖](https://github.com/sponsors/mrousavy/) to support the development of VisionCamera and thank me for my time spent on fixing bugs and building new features.
- if you still see this issue, please comment and we can re-open this. But please update your native logs with the native (Xcode/Android Studio) logs from running VisionCamera V4 so I can investigate this.

**Comment by High5Apps** [comment]
Hey Marc- congrats on the v4 release, and thanks for all of your great work on this library!

After upgrading my app from `react-native-vision-camera@3.9.2` to `react-native-vision-camera@4.0.1`, I can confirm that the general issue of borders causing an offset camera preview remains, although the details of the issue and workaround have changed.

**I would recommend reopening this issue.**

On iOS with `v4`, the extra-view workaround mentioned above still works fine. Without the workaround, the preview offset still occurs (see screenshot 1 below).

On Android with `v4`, I'm now seeing similar offset preview issues (see screenshot 2 below). Recall that in `v3` this seemed like an iOS-only issue. Interestingly, the offset on Android is in the opposite direction as on iOS. On iOS the camera preview is offset to the bottom right, but on Android it is offset to the top left (compare screenshots 1 and 2 below)

Furthermore, the extra-view workaround mentioned above wasn't sufficient on Android. Instead I now need to wait for the `Camera` to be `initialized` before setting the `absoluteFill` style.

I tried to see if the waiting-workaround would be enough to prevent the issue on iOS too, but it still needed the extra-view workaround. Fortunately, the new combined workaround seems to be working on both iOS and Android. I tested this on an iPhone 13 mini and a Samsung Galaxy S10.

## New workaround for v4

```jsx
function MyBorderedCamera() {
  const [cameraInitialized, setCameraInitialized] = useState(false);

  // ...

  return (
    <View style={{ borderWidth: 8, borderColor: 'purple', ... }}>
      {/* Add the View below as a workaround on iOS */}
      <View style={StyleSheet.absoluteFill}>
        <Camera
          // ...

          // Wait for the camera to be initialized as a workaround on Android
          onInitialized={() => setCameraInitialized(true)}
          style={cameraInitialized && StyleSheet.absoluteFill}
        />
      </View>
    </View>
  );
}
```

### Screenshot 1: On iPhone 13 Mini running v4 (without the workaround)
<img width="397" alt="i13m-rnvc-4 0 1-clip" src="https://github.com/mrousavy/react-native-vision-camera/assets/3528716/df5fa2ea-b182-4867-8ba4-234fee4a34ac">

### Screenshot 2: On Samsung Galaxy S10 running v4 (without the workaround)
<img width="410" alt="s10-rnvc-4 0 1-clip" src="https://github.com/mrousavy/react-native-vision-camera/assets/3528716/eb878a9b-759b-4b35-a616-7acf0d868f86">

**Comment by High5Apps** [comment]
## New workaround for v4.6.4 and React Native 77 (New Architecture)

I recently updated to the versions mentioned above and started seeing an issue with the previous workaround where the iOS camera preview was blank and all white. However even with the blank camera preview, the actual scanning was still working.

It seems that the previous Android `cameraInitialized` workaround in `style` was causing the new issue on iOS. I tried to completely remove the `cameraInitialized` workaround, but then the original offset border issue reappeared 1 out of 3 times or so on Android, so it couldn't be removed completely. So the new workaround adds the `Platform.OS` check to keep things working on both platforms.

Additionally, it seems that the iOS `View` workaround from above is no longer needed. Even without it, the offset border issue didn't happen across 20ish tries, so I removed it from the new workaround below.

```jsx
function MyBorderedCamera() {
  const [cameraInitialized, setCameraInitialized] = useState(false);

  // ...

  return (
    <View style={{ borderWidth: 8, borderColor: 'purple', ... }}>
      <Camera
        // ...

        // Wait for the camera to be initialized as a workaround on Android
        onInitialized={() => setCameraInitialized(true)}
        style={(cameraInitialized || Platform.OS !== 'android') && StyleSheet.absoluteFill}
      />
    </View>
  );
}
```
