### ISSUE TITLE
❓ Autofocus v3 

### ISSUE THREAD

**Issue by ErrorPro** [cuvent/react-native-vision-camera#1967]
### Question

Since the upgrade from v2 to v3 camera view no longer auto-focuses. I've checked the doc and found a new method to focus on a specific point but in my case I can't use any point to pass it. Is there a way to have autofocus somehow? Thanks!
I am trying to scan a tiny QR code and the picture is quite blurry.

![Screenshot 2023-10-10 at 16 40 22](https://github.com/mrousavy/react-native-vision-camera/assets/6295152/e3637bbc-4b25-460d-8fb9-911f228eeb58)

### VisionCamera Version

3.3.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by iliapnmrv** [comment]
+1

**Comment by stevengoldberg** [comment]
It looks like this was addressed but hasn't made it into a release yet https://github.com/mrousavy/react-native-vision-camera/pull/1943

**Comment by ErrorPro** [comment]
Yeah but it still seems like you would have to call the function and it's a bit different from what is mentioned in the topic. It'd be nice to not call any function and have autofocus working. I've checked on Android and it works as expected.

**Comment by enthcoder** [comment]
Hi @ErrorPro 
I have encountered the same issue during Android development. 
Have you resolved this problem? 
Could you please inform me of the solution for this issue?

Thanks.

**Comment by mrousavy** [comment]
Hey!

First of all, as with pretty much every question here, this should've been a bug report. Stop skipping the bug report templates, I cannot help you if you intentionally leave out details such as logs, device or format. That's what the bug report template is for!

Anyways, here's a potential fix: https://github.com/mrousavy/react-native-vision-camera/pull/1999

**Comment by mrousavy** [comment]
Actually I don't know if this changes anything. I believe the default values are already continuously auto-focusing, I just ran the app on V3 (current main) and it properly auto-focuses all the time, no matter how close I move.

**Comment by mrousavy** [comment]
So in V3 it should still auto-focus as normally. Idk what's going on in your case, but please open an issue if this is not working for you so we can take a closer look at this.

For me, VisionCamera Example app auto-focuses perfectly fine on my iPhone 15 Pro.

**Comment by Binz1mp** [comment]
@ErrorPro, @enthcoder 
For me, it happened too testing with iPhone 7 (15.7.9) after I get `format` with nothing but `device`.
```js
const device = useCameraDevice(cameraPosition);
const format = useCameraFormat(device, []);
...
<Camera
  ref={cameraRef}
  device={device}
  style={{...StyleSheet.absoluteFillObject}}
  isActive={true}
  photo={true}
  orientation='portrait'
  resizeMode='cover'
  format={format}
/>
```
I solved the problem after having `fps: 60` option in `format`.
I don't know if it's your case since I can't find reproduce... but here's what I did:
```js
...
const format = useCameraFormat(device, [
  {fps: 60}
]);
...
```
I don't know why this worked. Anyway, that was my first-aid.
