### ISSUE TITLE
❓ How can I send live video stream to backend python script using webrtc 

### ISSUE THREAD

**Issue by osaidfaisal12** [cuvent/react-native-vision-camera#1989]
### Question

How can I send live video stream to backend python script using webRTC?

### What I tried

I want to video stream my data to my backend on which I have a python script which detects body and return the video stream in response.  

  const takePhoto = async () => {
    if (camera != null ) {
      const photo = await camera.current.startRecording({
        onRecordingFinished: (video:any) => console.log(video),
        onRecordingError: (error:any) => console.error(error)
      })
      setIsCamera(true)
    }
  }

I am trying this, but I cannot figure out in which format the data is.  

### VisionCamera Version

3.3.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
See this: https://github.com/mrousavy/react-native-vision-camera/issues/1956
