### ISSUE TITLE
✨ Allow enabling flash before recording starts & Allow disabling flash during recording

### ISSUE THREAD

**Issue by yspreen** [cuvent/react-native-vision-camera#1991]
### What feature or enhancement are you suggesting?

Allow enabling flash before recording starts & Allow disabling flash during recording

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

–

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
Hey!

You can already do that, just pass `torch="on"` or `torch="off"` to the `<Camera>` :)
