### ISSUE TITLE
Null pointer exception when running app🐛 

### ISSUE THREAD

**Issue by nys99** [cuvent/react-native-vision-camera#1992]
### What's happening?

After the app is built and runs, I see the error:
<img width="696" alt="image" src="https://github.com/mrousavy/react-native-vision-camera/assets/35327995/55efcc58-8c64-4a2a-a4ea-d1c0762001b3">
<img width="698" alt="image" src="https://github.com/mrousavy/react-native-vision-camera/assets/35327995/5104dccb-0e4f-4a64-96bc-9fe79504e2bc">
<img width="698" alt="image" src="https://github.com/mrousavy/react-native-vision-camera/assets/35327995/404e72a5-32e2-4170-ac35-b534a5678f2a">
<img width="698" alt="image" src="https://github.com/mrousavy/react-native-vision-camera/assets/35327995/00b41e15-aa03-4c2c-8192-dc83bba51eac">

Versions: 
Android 10 on an Elo Tablet
react-native-vision camera 3.3.1
React Native 0.72.5 and 0.71.13 
Expo 49.0.0 and 48.0.18

I tried upgrading to expo 49 and RN 72 and still had the same issue.

When I look into the node modules at the source code of `react-native-vision-camera` in the file `node_modules/react-native-vision-camera/src/CameraDevices.ts` I see this import `import { NativeModules, NativeEventEmitter } from 'react-native'` has the error that: `Module '"react-native"' has no exported member 'NativeModules'.ts`

This seems to be the root of the problem, but not sure why upgrading from v2 to v3 of `vision-camera` is causing this issue. It was not present in v2.

We tried upgrading to v3 because our external USB camera is not detected when running v2 of `vision-camera`

### Reproduceable Code

```tsx
// it seems the the import itself is having an issue
import * from 'react-native-vision-camera'
```

### Relevant log output

```shell
Android Bundling complete 9412ms
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
 ERROR  Error: Exception in HostObject::get for prop 'CameraDevices': java.lang.NullPointerException, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

### Camera Device

```json
unable to reach this part of the code
```

### Device

Elo 22inch I Series-4 (Android 10)

### VisionCamera Version

3.3.1

### Can you reproduce this issue in the VisionCamera Example app?

No, I cannot reproduce the issue in the Example app

### Additional information

- [X] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
This could be related to the latest RN version, there has been a fix regarding the "spread operator with NativeEventEmitter" in react-native 73.
