### ISSUE TITLE
🐛 Can't record at 60 FPS on a Google Pixel 6a

### ISSUE THREAD

**Issue by alejandroTecDam** [cuvent/react-native-vision-camera#2006]
### What's happening?

I want to record at 60 fps but the end result is at 30 fps.

### Reproduceable Code

```tsx
function App(): JSX.Element {
  const camera = useRef<Camera>(null);
  const device = useCameraDevice('back');
  const [recording, setRecording] = useState(false);

  const onPress = () => {
    if (!camera.current) return;
    if (recording) {
      camera.current.stopRecording();
    } else {
      camera.current.startRecording({
        onRecordingFinished: async video => {
          const path = video.path;
          await CameraRoll.save(`file://${path}`, {
            type: 'video',
          });
        },
        onRecordingError: error => console.error(error),
      });
    }
    setRecording(!recording);
  };

  if (device == null) {
    return (
      <View>
        <Text>No device</Text>
      </View>
    );
  } else {
    return (
      <View
        style={{
          flex: 1,
        }}>
        <Camera
          ref={camera}
          style={StyleSheet.absoluteFill}
          device={device}
          isActive={true}
          video={true}
          audio={true}
          fps={60}
        />
        <TouchableOpacity
          onPress={onPress}
          style={{
            position: 'absolute',
            bottom: 10,
            right: 10,
            padding: 20,
            backgroundColor: recording ? 'red' : 'green',
          }}>
          <Text>Start/Stop</Text>
        </TouchableOpacity>
      </View>
    );
  }
}
```

### Relevant log output

```shell
10-16 09:46:20.002   985 15579 I Lyric   : tuning_provider_base.cc:491: Requested tuning for: SENSOR19,FULL_16_9_2160P_60FPS,VIDEO_RECORDING_3P but matched with SENSOR19,FULL_16_9_2160P_60FPS,VIDEO_RECORDING instead.
10-16 09:44:30.003   985 15579 W Lyric   : whi_tuning_controller.cc:325: Cannot find tuning use case: sensor 19, FULL_16_9_2160P_60FPS, VIDEO_RECORDING_3P. Using default tuning for IsSubBlockEnabled()
```

### Camera Device

```json
{
  "sensorOrientation": "landscape-right",
  "hardwareLevel": "full",
  "maxZoom": 7,
  "minZoom": 0.6009132266044617,
  "supportsLowLightBoost": true,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": true,
  "isMultiCam": true,
  "name": "BACK (0)",
  "hasFlash": true,
  "hasTorch": true,
  "position": "back",
  "id": "0"
}
```

### Device

Google Pixel 6a

### VisionCamera Version

3.3.1

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
It doesn't look like you are using a `format`. See [Choosing a Camera Format](https://react-native-vision-camera.com/docs/guides/formats#choosing-custom-formats).

If your format can do 60 FPS, you can pass 60 FPS. Otherwise you can't. That's what it says in the docs, and that's also what it says in the `fps` prop's param-docs

**Comment by alejandroTecDam** [comment]
I've changed the code to add
```tsx
const format = useCameraFormat(device, [{fps: 60}]);
...
<Camera
          ref={camera}
          style={StyleSheet.absoluteFill}
          device={device}
          isActive={true}
          video={true}
          audio={true}
          format={format}
          fps={60}
        />
```

But the result video still with 30 fps.
This is the log for format:
`
{"autoFocusSystem": "contrast-detection", "fieldOfView": 65.59413150556766, "maxFps": 60, "maxISO": 7111, "minFps": 1, "minISO": 56, "photoHeight": 3024, "photoWidth": 4032, "pixelFormats": ["yuv", "native"], "supportsDepthCapture": false, "supportsPhotoHDR": false, "supportsVideoHDR": false, "videoHeight": 2160, "videoStabilizationModes": ["off", "standard", "cinematic", "off", "cinematic-extended"], "videoWidth": 3840}
`

**Comment by mrousavy** [comment]
That's weird.

The only explanation I have at this point is that either your phone does not allow other apps to use 60 FPS (only their stock app can do it, Samsung often does this for whatever reason), or that it has "auto-framerate":

![image](https://github.com/mrousavy/react-native-vision-camera/assets/15199031/6a9fa9d1-c8df-4df8-b230-e17de2d2e567)


VisionCamera has a solid devices API, so if something does not work here, it might not work in any third party apps at all.

To confirm this, download the official Google example for Camera apps; [camera-samples/Camera2Video](https://github.com/android/camera-samples/tree/main/Camera2Video) and run it on your phone. If you can't record in 60 FPS there either, there's nothing we can do. It's your phone's fault.


Please try the camera-samples app and let me know if you can record in 60 FPS there.

**Comment by mrousavy** [comment]
Does the preview look like it has 60 FPS?

**Comment by alejandroTecDam** [comment]
Just tested and works fine, it seems that the problem was that I had not added the camera format correctly.
Thanks!

**Comment by mrousavy** [comment]
🙃
