### ISSUE TITLE
❓What is the best way to determine frame boundaries in the `CodeScanner`?

### ISSUE THREAD

**Issue by spsaucier** [cuvent/react-native-vision-camera#2014]
### Question

Using the new `codeScanner`, each code's `frame` includes `height`, `width`, `x`, and `y`.

What is the best way to know/determine the frame boundaries, so that we can tell that, say, the `x` value is at 50% of the frame's width?

`resizeMode="contain"` also establishes that the frame boundaries may well not align with `Dimensions.get('screen').width` and `.height` at all. This reinforces the need for us to know the dimensions that `x` and `y` are referring to.

Context: I'm effectively trying to get `regionOfInterest` working on our side, since that doesn't seem to be working as intended in the package.

### What I tried

`Dimensions.get('screen').width`/`height` appears to work as expected on iOS (that is, it aligns with `x` and `y` exactly, but in my Android testing, the `x` or `y` values can exceed those.

This is from when the code was at the bottom-left of the view (per portrait mode) in Android:
```
  {
    "width": 137,
    "y": 561,
    "height": 148,
    "x": 1141,
    "DimensionsHeight": 984,
    "DimensionsWidth": 432
  }
```
Android is setting `device.sensorOrientation === "landscape-right"` (aside: this is inconsistent with iOS and isn't changed by setting `orientation="portrait"` on the Camera), so `x` should always be lower than `DimensionsHeight - width`, and `y` should always be lower than `DimensionsWidth - height` right? `x` and `y`'s values are too high for `Dimensions.get('window')`.

### VisionCamera Version

3.4.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
It's relative to the currently active Camera format. You need to select a format using `useCameraFormat`. I will document this more

**Comment by spsaucier** [comment]
Given your response, here is some code which converts the code's frame into constant-portrait coordinate values for its corner points:

```ts
const pxDiff = Math.max(PixelRatio.get() - 1, 1);

const portraitVideoHeight = Math.max(
  format.videoWidth,
  format.videoHeight
);
const portraitVideoWidth = Math.min(
  format.videoWidth,
  format.videoHeight
);

const getPortraitCornerPoints = (
  code: Code,
  device: CameraDevice | undefined,
  portraitVideoWidth: number
) => {
  if (!code.frame) return undefined;

  return {
    tl:
      device?.sensorOrientation === 'portrait'
        ? [code.frame.x * pxDiff, code.frame.y * pxDiff]
        : [
            portraitVideoWidth -
              (code.frame.y * pxDiff + code.frame.height * pxDiff),
            code.frame.x * pxDiff,
          ],
    tr:
      device?.sensorOrientation === 'portrait'
        ? [
            code.frame.x * pxDiff + code.frame.width * pxDiff,
            code.frame.y * pxDiff,
          ]
        : [portraitVideoWidth - code.frame.y * pxDiff, code.frame.x * pxDiff],
    br:
      device?.sensorOrientation === 'portrait'
        ? [
            code.frame.x * pxDiff + code.frame.width * pxDiff,
            code.frame.y * pxDiff + code.frame.height * pxDiff,
          ]
        : [
            portraitVideoWidth - code.frame.y * pxDiff,
            code.frame.x * pxDiff + code.frame.width * pxDiff,
          ],
    bl:
      device?.sensorOrientation === 'portrait'
        ? [
            code.frame.x * pxDiff,
            code.frame.y * pxDiff + code.frame.height * pxDiff,
          ]
        : [
            portraitVideoWidth -
              (code.frame.y * pxDiff + code.frame.height * pxDiff),
            code.frame.x * pxDiff + code.frame.width * pxDiff,
          ],
  };
};

...


  const device = useCameraDevice('back', {
    physicalDevices: ['wide-angle-camera'],
  });
  const isFocused = useIsFocused();
  const isActive = isFocused;
  const format = useCameraFormat(device, [
    { videoResolution: { width: 1920, height: 1080 } },
    { fps: 60 },
  ]);

...


          <Camera
            style={styles.preview}
            device={device}
            isActive={isActive}
            codeScanner={codeScanner}
            format={format}
            orientation="portrait"
            resizeMode="contain"
            enableZoomGesture
            enableHighQualityPhotos={false}
            torch={useTorch ? 'on' : 'off'}
          />
```

NOTE: `landscape-left` is currently handled as if it is `landscape-right`. Context:

In `3.4.1`, iOS codeScanner is:
* No longer in `sensorOrientation` `'portrait'` as it has been
* Reporting `device.sensorOrientation === 'landscape-left'`
* It is _actually_ in `'landscape-right'` orientation -- that is, `x === y === 0` is true when the code is in the top-righthand corner (when the home button is at the bottom [portrait orientation]).

**Comment by mrousavy** [comment]
Oh wow, that's a lot of code 😅 



> It is actually in 'landscape-right' orientation

Wait, you mean iPhone Cameras are actually landscape-right instead of landscape-left?

**Comment by spsaucier** [comment]
That's right - they are being shown as landscape-left but read the barcodes the same as Android's landscape-right.

**Comment by mrousavy** [comment]
Gotcha, I'll rename this then. thanks!

**Comment by mrousavy** [comment]
Related: https://github.com/mrousavy/react-native-vision-camera/issues/2046

**Comment by mrousavy** [comment]
This has been implemented a few weeks ago! :) https://react-native-vision-camera.com/docs/api/interfaces/CodeScannerFrame
