### ISSUE TITLE
🐛  [V3][iOS]Frame Processor threw an error: Failed to load Frame Processor Plugin "functionName"

### ISSUE THREAD

**Issue by ShchipskiiYura** [cuvent/react-native-vision-camera#2045]
### What's happening?

I create own custom Frame Processor plugin for convert frame to base64, and when I load camera, I catch error

```

  LOG  plugin undefined
  ERROR  Frame Processor threw an error: Failed to load Frame Processor Plugin "frameToBase64"!

```

### Reproduceable Code

```
import { frameToBase64 } from 'vision-camera-trustee-base64'
...

const frameProcessor = useFrameProcessor((frame) => {
  'worklet'
  const imageAsBase64 = frameToBase64(frame)
}, [])

```
```


### Relevant log output

```shell
LOG  plugin undefined
ERROR  Frame Processor threw an error: Failed to load Frame Processor Plugin "frameToBase64"!
```

### Camera Device

```json
camera
```

### Device

iPhone 11 Pro

### VisionCamera Version

3.5.0

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey! This might be due to the breaking change in 3.5.0, the function is now called `initFrameProcessorPlugin` instead of `getFrameProcessorPlugin`. But the old one should still work (it should just warn), so not sure where that error is coming from.


I googled vision-camera-trustee-base64 and I found this one: https://github.com/yasintorun/vision-camera-base64/blob/main/src/index.tsx - that's for VisionCamera V2, not for V3. That package needs to be updated so it works in V3

**Comment by ShchipskiiYura** [comment]
> Hey! This might be due to the breaking change in 3.5.0, the function is now called `initFrameProcessorPlugin` instead of `getFrameProcessorPlugin`. But the old one should still work (it should just warn), so not sure where that error is coming from.
> 
> I googled vision-camera-trustee-base64 and I found this one: https://github.com/yasintorun/vision-camera-base64/blob/main/src/index.tsx - that's for VisionCamera V2, not for V3. That package needs to be updated so it works in V3

I try update this package for my project

Okay, I try again with ```getFrameProcessorPlugin```

**Comment by mrousavy** [comment]
`initFrameProcessorPlugin` not `getFrameProcessorPlugin`

**Comment by mrousavy** [comment]
Check the docs

**Comment by ShchipskiiYura** [comment]
Also, I have error with android too, when build app

```
/Users/taki183/Desktop/work/trusteeNative/node_modules/vision-camera-trustee-base64/android/src/main/java/com/visioncamerabase64plugin/VisionCameraBase64Plugin.java:15: error: VisionCameraBase64Plugin is not abstract and does not override abstract method callback(Frame,Map<String,Object>) in FrameProcessorPlugin
public class VisionCameraBase64Plugin extends FrameProcessorPlugin {
       ^
/Users/taki183/Desktop/work/trusteeNative/node_modules/vision-camera-trustee-base64/android/src/main/java/com/visioncamerabase64plugin/VisionCameraBase64Plugin.java:17: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/taki183/Desktop/work/trusteeNative/node_modules/vision-camera-trustee-base64/android/src/main/java/com/visioncamerabase64plugin/VisionCameraBase64PluginPackage.java:21: error: constructor VisionCameraBase64Plugin in class VisionCameraBase64Plugin cannot be applied to given types;
            options -> new VisionCameraBase64Plugin(options)
                       ^
  required: no arguments
  found: Map<String,Object>
  reason: actual and formal argument lists differ in length
3 errors

FAILURE: Build failed with an exception.
```

**Comment by edritech93** [comment]
I have same issue,

index.tsx
```
const plugin = VisionCameraProxy.initFrameProcessorPlugin('scanFace');

export function scanFaces(frame: Frame): Face[] {
  'worklet';
  if (plugin == null) {
    throw new Error('Failed to load Frame Processor Plugin!');
  }
  return plugin.call(frame) as unknown as Face[];
}
```

VisionCameraFaceDetector.m
```
#import <VisionCamera/FrameProcessorPlugin.h>
#import <VisionCamera/FrameProcessorPluginRegistry.h>

#if __has_include("VisionCameraFaceDetector/VisionCameraFaceDetector-Swift.h")
#import "VisionCameraFaceDetector/VisionCameraFaceDetector-Swift.h"
#else
#import "VisionCameraFaceDetector-Swift.h"
#endif

VISION_EXPORT_SWIFT_FRAME_PROCESSOR(VisionCameraFaceDetectorPlugin, scanFace)
```

I use "react-native-vision-camera": "^3.6.4",
