### ISSUE TITLE
123

### ISSUE THREAD

**Issue by minhee0000** [cuvent/react-native-vision-camera#2061]

**Comment by zzz08900** [comment]
Hmm, what does your `device` look like?
And what's the phone model that those screenshot were taken?

**Comment by Kimdnel** [comment]
> Hmm, what does your `device` look like? And what's the phone model that those screenshot were taken?

/

It's iphone 13 pro max

**Comment by ldstein** [comment]
Have you tried making your camera view the exact same width and height of the default camera view?

**Comment by Kimdnel** [comment]
> Have you tried making your camera view the exact same width and height of the default camera view?

yes i did

**Comment by Kimdnel** [comment]
I solved this problem.

**Comment by mrousavy** [comment]
1. Check the format docs, there's multiple formats in a device. Select the one that you need.
2. If you "solved this problem", please post a solution for others and close the issue. No need to pollute the issues tab here

**Comment by un1234** [comment]
> I solved this problem.

Can you please tell me the solution?

**Comment by Kimdnel** [comment]
> > I solved this problem.
> 
> Can you please tell me the solution?

Use the "useCameraFormat" api
