### ISSUE TITLE
V3.6.0, Camera preview is black 🐛 

### ISSUE THREAD

**Issue by FouadMagdy01** [cuvent/react-native-vision-camera#2070]
### What's happening?

Camera preview in the last release is black, but taking photos is working normally, also the black preview go away when i refresh the Component from my code editor, 
This happen even the `format` property is provided or not

### Reproduceable Code

```tsx
const device = useCameraDevice('back')

  if (device == null) return <NoCameraDeviceError />
  return (
    <Camera
      style={StyleSheet.absoluteFill}
      device={device}
      isActive={true}
      style={{
      width,
      height 
      }}
    />
  )
```

### Relevant log output

```shell
.
```

### Camera Device

```json
{"autoFocusSystem": "contrast-detection", "fieldOfView": 68.38481019665146, "maxFps": 30, "maxISO": 3200, "maxZoom": 10, "minFps": 1, "minISO": 50, "photoHeight": 720, "photoWidth": 1280, "pixelFormats": ["yuv", "native"], "supportsDepthCapture": false, "supportsPhotoHDR": false, "supportsVideoHDR": false, "videoHeight": 1080, "videoStabilizationModes": ["off", "standard", "off"], "videoWidth": 1920}
```

### Device

Xiaomi Poco F3

### VisionCamera Version

3.6.0

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [X] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
log output explicitly ignored, closing.

**Comment by GaylordP** [comment]
I have exactly the same problem on Android (One Plus 6) (black preview, then after updating the code it works). :/

**Comment by FouadMagdy01** [comment]
> I have exactly the same problem (black preview, then after updating the code it works). :/

I rolled back to v3.5.1 and everything is working fine,

that's why i did not post the logs, i will re update the package and copy the logs, if you can do so, please add them so @mrousavy  can figure out the problem
