### ISSUE TITLE
Delay of codescanner ❓ 

### ISSUE THREAD

**Issue by Djhitman** [cuvent/react-native-vision-camera#2121]
### Question

I recently migrated to version 3 and how can I make the codescaner not as fast as it was on version 2 with the frameProcessorFps property

### What I tried

Tried to set fps property, it doesn't helped

### VisionCamera Version

3.6.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by sorinrinse** [comment]
You can import `runAtTargetFps` and use that with your function.

**Comment by Djhitman** [comment]
@sorinrinse thank you so much, that works!
