### ISSUE TITLE
🐛USB Camera producing undefined

### ISSUE THREAD

**Issue by OneLaddd** [cuvent/react-native-vision-camera#2131]
### What's happening?

I used 'USB Camera' app and another similar app to test out the capability of using UVC camera, and it did worked, however, when I tested this with Vision Camera, it just made an undefined and black screen response. I even cloned the repository to make sure it did work, I even changed the necessary permissions related to USB. Please help me, I really need this to succeed because I'm using this with my Practical Research subject and with the use of Arduino. I would appreciate a fast response because the deadline is near. If there is a way to have a get around this (e.g. somehow making 'front' as external) then I would like to know. Thank you!

### Reproduceable Code

```tsx
const devices = Camera.getAvailableCameraDevices();
const device = devices.find((d) => d.position === 'external');
console.log(device)
console.log(devices)


<View>
 <Camera
   frameProcessor={frameProcessor}
   device={device}
   ...
 />
</View>



----AndroidManifest.xml
    
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

    <uses-permission android:name="android.permission.CAMERA" />

    <uses-feature
        android:name="android.hardware.camera.any"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.camera"
        android:required="false" />
    
    <uses-feature android:name="android.hardware.usb.host" />
    <uses-permission android:name="android.permission.USB_PERMISSION" />
```

### Relevant log output

```shell
LOG  undefined
 LOG  [{"formats": [[Object], ...[Object]], "hardwareLevel": "full", "hasFlash": true, "hasTorch": true, "id": "0", "isMultiCam": false, "maxZoom": 4, "minZoom": 1, "name": "BACK (0)", "neutralZoom": 1, "physicalDevices": ["wide-angle-camera"], "position": "back", "sensorOrientation": "landscape-right", "supportsFocus": true, "supportsLowLightBoost": false, "supportsRawCapture": true}, {"formats": [[Object], [Object], ... [Object], [Object], [Object]], "hardwareLevel": "full", "hasFlash": false, "hasTorch": false, "id": "1", "isMultiCam": false, "maxZoom": 2, "minZoom": 1, "name": "FRONT (1)", "neutralZoom": 1, "physicalDevices": ["wide-angle-camera"], "position": "front", "sensorOrientation": "landscape-left", "supportsFocus": true, "supportsLowLightBoost": false, "supportsRawCapture": true}]
```

### Camera Device

```json
undefined
```

### Device

Vivo Y11 1906 (Android 11)

### VisionCamera Version

3.6.4

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by xulihang** [comment]
The USB Camera app is using this library: <https://github.com/saki4510t/UVCCamera>. There is a blog about it here: https://www.dynamsoft.com/codepool/usb-camera-android-barcode-scanner.html

Vision Camera uses Camera2. Not all devices support calling external devices via Camera2.

**Comment by OneLaddd** [comment]
Thanks for the reply, how will I use frameprocessor then? Those are really the key components of my project.

**Comment by mrousavy** [comment]
Yea exactly what @xulihang said - it only works if the UVC camera is supporting UVC through Camera2.

Frame Processor is a separate topic, read the docs on that
