### ISSUE TITLE
? emulator codeScanner not working 

### ISSUE THREAD

**Issue by Woobeen906** [cuvent/react-native-vision-camera#2155]
### Question

I would like to use codeScanner.
However, even if you show the barcode or QR in front of the camera, nothing happens.

### What I tried

```

 const [cameraPermission, setCameraPermission] = useState();
  const [microphonePermission, setMicrophonePermission] = useState();
  const camera = useRef(null);
  const devices = useCameraDevice();
  // const device = devices[0];

  const device = useCameraDevice("back");

  const codeScanner = useCodeScanner({
    codeTypes: ["qr", "ean-13", "code-128"],
    onCodeScanned: (codes) => {
      console.log(`Scanned ${codes} codes!`);
    },
  });

  const requestCameraPermission = async () => {
    try {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.CAMERA,
        {
          title: "Cool Photo App Camera Permission",
          message:
            "Cool Photo App needs access to your camera " +
            "so you can take awesome pictures.",
          buttonNeutral: "Ask Me Later",
          buttonNegative: "Cancel",
          buttonPositive: "OK",
        }
      );
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log("You can use the camera");
      } else {
        console.log("Camera permission denied");
      }
    } catch (err) {
      console.warn(err);
    }
  };

  

  useEffect(() => {
    requestCameraPermission();
  }, []);

  useEffect(() => {
    void Camera.getCameraPermissionStatus().then(setCameraPermission);
    void Camera.getCameraPermissionStatus().then(setCameraPermission);
  }, [cameraPermission, microphonePermission]);

return(
 <Camera
          style={StyleSheet.absoluteFillObject}
          device={device}
          isActive={true}
          codeScanner={codeScanner}
        />)
        
        
        
        
        
        
     "react": "18.2.0",
    "react-native": "0.72.6",
```

### VisionCamera Version

^3.6.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by scottko** [comment]
change implementation "com.google.android.gms:play-services-mlkit-barcode-scanning:18.3.0" 
to
implementation 'com.google.mlkit:barcode-scanning:17.2.0' in  ./node_modules/react-native-vision-camera/android/build.gradle

The reason it doesn't work on emulator might be the app is not in google store

But!!!
It scans too fast and causes crash.....
