### ISSUE TITLE
🔧 Crashed with SIGSEGV 

### ISSUE THREAD

**Issue by MajorTom007** [cuvent/react-native-vision-camera#2158]
the issue , v 3.6.4
Sometimes the application crashes with this issue. On average, there is one crash per five scans.

Crashed: Thread: SIGSEGV 0x0000007cc639d7e1

### Full build logs

```tsx
Crashed: Thread: SIGSEGV  0x0000007cc639d7e1
#00 pc 0x128bac libbarhopper_v3.so (BuildId: 73597d2de25bd3c29361db3c56dd9f18)
#01 pc 0x812f4 libbarhopper_v3.so (BuildId: 73597d2de25bd3c29361db3c56dd9f18)
#02 pc 0xa2600 libtflite_gmscore_jni.so (BuildId: abf371b4405232f9c7109f40a7426a23)
#03 pc 0xa17e4 libtflite_gmscore_jni.so (BuildId: abf371b4405232f9c7109f40a7426a23)
#04 pc 0x116474 libbarhopper_v3.so (BuildId: 73597d2de25bd3c29361db3c56dd9f18)
#05 pc 0x116484 libbarhopper_v3.so (BuildId: 73597d2de25bd3c29361db3c56dd9f18)
#06 pc 0x11601c libbarhopper_v3.so (BuildId: 73597d2de25bd3c29361db3c56dd9f18)
#07 pc 0x112160 libbarhopper_v3.so (BuildId: 73597d2de25bd3c29361db3c56dd9f18)
#08 pc 0x1124a0 libbarhopper_v3.so (BuildId: 73597d2de25bd3c29361db3c56dd9f18)
#09 pc 0x82b98 libbarhopper_v3.so (BuildId: 73597d2de25bd3c29361db3c56dd9f18)
#10 pc 0x7aee4 libbarhopper_v3.so (BuildId: 73597d2de25bd3c29361db3c56dd9f18)
#11 pc 0x83360 libbarhopper_v3.so (BuildId: 73597d2de25bd3c29361db3c56dd9f18)
#12 pc 0x213a5 libbarhopper_v3.so (BuildId: 73597d2de25bd3c29361db3c56dd9f18)
#13 pc 0x7ac2c libbarhopper_v3.so (BuildId: 73597d2de25bd3c29361db3c56dd9f18)
#14 pc 0x7ac38 libbarhopper_v3.so (BuildId: 73597d2de25bd3c29361db3c56dd9f18)
```

### Project dependencies

```json
"dependencies": {
    "react-native-vision-camera": "^3.6.4",
  },
```

### VisionCamera Version

3.6.4

### Target platforms

Android

### Operating system

Windows

### Can you build the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
This is not a build error. Wrong issue template. Also, if you receive native crashes in production I need **symbolicated** stack traces, aka the logs where there's filenames and line numbers. You can just run a tool against your build symbols to generate those symbolicated logs, Sentry has a guide for that.
