### ISSUE TITLE
🐛 photoCodec does not exist in TakePhotoOptions interface

### ISSUE THREAD

**Issue by nkulic** [cuvent/react-native-vision-camera#2159]
### What's happening?

'photoCodec' does not exist in type 'TakePhotoOptions':
- https://github.com/mrousavy/react-native-vision-camera/blob/main/package/src/PhotoFile.ts#L4
```ts
const takePhotoOptions: TakePhotoOptions = {
  photoCodec: 'jpeg', // Object literal may only specify known properties, and 'photoCodec' does not exist in type 'TakePhotoOptions'.ts(2322)
  qualityPrioritization: 'speed',
  flash: 'off',
  quality: 90,
  enableShutterSound: false,
};
```

### Reproduceable Code

```tsx
const takePhotoOptions: TakePhotoOptions = {
  photoCodec: 'jpeg',
  qualityPrioritization: 'speed',
  flash: 'off',
  quality: 90,
  enableShutterSound: false,
};
```

### Relevant log output

```shell
N/A
```

### Camera Device

```json
N/A
```

### Device

N/A

### VisionCamera Version

3.6.4

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Thanks, just removed `photoCodec` in https://github.com/mrousavy/react-native-vision-camera/commit/1055430cbb2952091565463ca9d697ba0c23bcf4.
