### ISSUE TITLE
❓ Simultaneously record video or take photos from both rear and front cameras

### ISSUE THREAD

**Issue by Skipperlla** [cuvent/react-native-vision-camera#2164]
### Question

My goal is to have both rear and ten cameras recording or taking photos at the same time, just like in the bereal app

### VisionCamera Version

3.6.6

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey - I'm not sure if this is currently possible, but you can try to just render two `<Camera>` Views and see what happens:

```tsx
<Camera device={backCamera} ... />
<Camera device={frontCamera} ... />
```

**Comment by Skipperlla** [comment]
> Hey - I'm not sure if this is currently possible, but you can try to just render two `<Camera>` Views and see what happens:
> 
> 
> 
> ```tsx
> 
> <Camera device={backCamera} ... />
> 
> <Camera device={frontCamera} ... />
> 
> ```

I tried this but one worked and the other didn't

**Comment by mrousavy** [comment]
Well then yea this does not currently work and is quite complex to implement. Did you test on both iOS and Android? I thought it would work

**Comment by Skipperlla** [comment]
> Well then yea this does not currently work and is quite complex to implement. Did you test on both iOS and Android? I thought it would work

Honestly, I didn't try the android part after I saw that it didn't work on the ios part because it was necessary for me on both sides.

**Comment by mrousavy** [comment]
Well yea, I think this is currently not possible. It would require quite a large refactor of the codebase as on iOS I would need to use a single AVCaptureSession and attach two input Cameras to that - quite a complex thing to do.

Might significantly change the API as well:

```tsx
const device = useCameraDevice('back')
const camera = useCamera(device)

return <Camera camera={camera} isActive={true} />
```

and for multi:

```tsx
const front = useCameraDevice('front')
const back = useCameraDevice('back')
const camera = useCamera([back, front])

return <Camera camera={camera} isActive={true} />
```

If you want this, consider contacting me thru my agency to figure out a way to collaborate on this.

**Comment by johhansantana** [comment]
in theory, could you use 2 libraries to record? For example, use this one for back camera and another one for front camera? Or do they basically use the same iOS API and would conflict with each other?

**Comment by mrousavy** [comment]
No it is the same iOS API.

**Comment by PaulGommard** [comment]
Did you find a solution ?
