### ISSUE TITLE
pod install is failing in fabric 🔧  

### ISSUE THREAD

**Issue by hamdij0maa** [cuvent/react-native-vision-camera#2165]
### How were you trying to build the app?

I fired this command : 
RCT_NEW_ARCH_ENABLED=1 bunx pod-install inside ios folder

### Full build logs

```tsx
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `VisionCamera` depends upon `react-native-worklets-core`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
Couldn't install Pods. Updating the Pods project and trying again...
Command `pod install` failed.
└─ Cause: The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `VisionCamera` depends upon `react-native-worklets-core`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

### Project dependencies

```json
"dependencies": {
    "react": "18.2.0",
    "react-native": "^0.72.7",
    "react-native-reanimated": "^3.5.4",
    "react-native-vision-camera": "^3.6.6",
    "react-native-worklets-core": "^0.2.4",
  }
```

### VisionCamera Version

3.6.6

### Target platforms

iOS

### Operating system

MacOS

### Can you build the VisionCamera Example app?

Yes, I can successfully build the Example app here

### Additional information

- [X] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by nivohayonDEV** [comment]
What solved this?
