### ISSUE TITLE
🐛 App crashed with SEGFAULT `std::__ndk1::__function::__func<T>::operator()`, occurs in the release build only(maybe)

### ISSUE THREAD

**Issue by bglgwyng** [cuvent/react-native-vision-camera#2178]
### What's happening?

When switching the app from the background to the foreground, it failed to reopen. I haven't encountered this error message with the debug builds.

### Reproduceable Code

```tsx
Not yet reproducible
```

### Relevant log output

```shell
OS Version: Android 13 (TP1A.220624.014.G981NKSU3IWH9)
Report Version: 104

Exception Type: Unknown (SIGSEGV)

Application Specific Information:
Segfault

Thread 0 Crashed:
0   split_config.arm64_v8a.apk      0x75461df2e4        std::__ndk1::__function::__func<T>::operator()
1   split_config.arm64_v8a.apk      0x73bdbeac1c        vision::JVisionCameraScheduler::trigger
2   split_config.arm64_v8a.apk      0x73bdbec448        facebook::jni::detail::MethodWrapper<T>::dispatch
3   split_config.arm64_v8a.apk      0x73bdbec3c0        facebook::jni::detail::FunctionWrapper<T>::call
4   split_config.arm64_v8a.apk      0x73bdbeb0e4        facebook::jni::detail::MethodWrapper<T>::call
5   base.odex                       0x7709a5c364        <unknown> + 511262966628
```

### Camera Device

```json
{"hardwareLevel": "full", "hasFlash": true, "hasTorch": true, "id": "0", "isMultiCam": false, "maxZoom": 8, "minZoom": 1, "name": "BACK (0)", "neutralZoom": 1, "physicalDevices": ["wide-angle-camera"], "position": "back", "sensorOrientation": "landscape-right", "supportsFocus": true, "supportsLowLightBoost": true, "supportsRawCapture": true}
```

### Device

Galaxy S21, Android 13

### VisionCamera Version

3.6.6

### Can you reproduce this issue in the VisionCamera Example app?

No, I cannot reproduce the issue in the Example app

### Additional information

- [X] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
I think this is the same as https://github.com/mrousavy/react-native-vision-camera/issues/2153
