### ISSUE TITLE
🐛 Image distorted when rotate the device

### ISSUE THREAD

**Issue by alejandroTecDam** [cuvent/react-native-vision-camera#2185]
### What's happening?

With the basic configuration, when the device is rotated, the image is distorted as shown in the video.

https://github.com/mrousavy/react-native-vision-camera/assets/86365078/f3daf9f5-1ec6-4317-9dd5-c6f7a35e8b29

### Reproduceable Code

```tsx
function App(): JSX.Element {
  const camera = useRef<Camera>(null);
  const device = useCameraDevice('back');
  const format = useCameraFormat(device, []);

  if (device == null) {
    return (
      <View>
        <Text>No device</Text>
      </View>
    );
  } else {
    return (
      <View style={StyleSheet.absoluteFill}>
        <Camera
          ref={camera}
          style={StyleSheet.absoluteFill}
          device={device}
          isActive={true}
          video={true}
          audio={true}
          format={format}
        />
      </View>
    );
  }
}
```

### Relevant log output

```shell
11-20 13:57:40.610  1668  3381 I WindowManager: finishDrawing of orientation change: Window{e16f7d7 u0 StatusBar} 69ms
```

### Camera Device

```json
{
  "sensorOrientation": "landscape-right",
  "hardwareLevel": "full",
  "maxZoom": 7,
  "minZoom": 0.6009132266044617,
  "supportsLowLightBoost": true,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera",
    "ultra-wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": true,
  "isMultiCam": true,
  "name": "BACK (0)",
  "hasFlash": true,
  "hasTorch": true,
  "position": "back",
  "id": "0"
}
```

### Device

Google Pixel 6a, Samsung S20 FE

### VisionCamera Version

3.6.8

### Can you reproduce this issue in the VisionCamera Example app?

No, I cannot reproduce the issue in the Example app

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by MrAccelerator** [comment]
I have the same problem, have you solved it?

**Comment by alejandroTecDam** [comment]
> I have the same problem, have you solved it?

No, sorry, I'm still with the issue

**Comment by Brianwebb22** [comment]
I am also seeing a similar issue where when rotated from portrait to landscape and back to portrait the image is distorted. I have `orientation: "portrait"` on the camera component.

**Comment by leobarcove** [comment]
Having same issue with VisionCamera Version 3.6.12

**Comment by juanctecdam** [comment]
Any update on this? We are also facing the same problem @mrousavy

**Comment by mrousavy** [comment]
Duplicate of a lot of issues. Orientation is not yet implemented in VisionCamera since that's quite a large effort.

I created a sponsor pool to start the efforts for this, if you want to see this happen consider supporting me here so I can implement Orientation: https://github.com/mrousavy/react-native-vision-camera/issues/1891
