### ISSUE TITLE
✨ Allow returning WritableNativeArray from frame processor in v3

### ISSUE THREAD

**Issue by xulihang** [cuvent/react-native-vision-camera#2190]
### What feature or enhancement are you suggesting?

In v2, I can return `WritableNativeArray` on Android from a frame processor like the following:

```java
WritableNativeArray array = new WritableNativeArray();
return array;
```

But this seems not possible and I have to use the following:

```java
List<Object> array = new ArrayList<>();
return array;
```

Since I also need to run a similar native module method , I need to use `WritableNativeArray`.

Allowing returning WritableNativeArray from frame processor in v3 would make the development easier.

### What Platforms whould this feature/enhancement affect?

Android

### Alternatives/Workarounds

I am currently returning WritableNativeArray for a native module method and an ArrayList for a frame processor.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by rodgomesc** [comment]
this is well documented on [the official documentation >> frame-processors-plugins >> overview >> types ](https://react-native-vision-camera.com/docs/guides/frame-processors-plugins-overview#types)

and also in the example app source code shows exactly how to hook up a object to javascript

https://github.com/mrousavy/react-native-vision-camera/blob/main/package/example/android/app/src/main/java/com/mrousavy/camera/example/ExampleFrameProcessorPlugin.java

`WritableNativeArray` uses react-native old architecture bridge using it is definitely not a good idea

**Comment by xulihang** [comment]
I think the supported types are lacking. `WritableNativeArray` is not supported.

**Comment by xulihang** [comment]
As I talked about in the original post, I need the frame processor and my native module method to return the same `WritableNativeArray`. This is possible in v2.

**Comment by rodgomesc** [comment]
i understand @xulihang  your request doesn't make sense for me, this was possible in v2 and in v3 we have a faster approach to hook up object to javascript, how this change will benefit hundreds of users that use that lib? i think you should change your approach to solve the problem, or could you provide a use case explaining why exactly `WritableNativeArray` solves your problem and `Map<String, Object>` don't?

**Comment by xulihang** [comment]
Allowing the react native bridge's types can make it easy to use previous work like the code here: https://github.com/tony-xlh/vision-camera-dynamsoft-barcode-reader/blob/main/android/src/main/java/com/visioncameradynamsoftbarcodereader/Utils.java#L34

I am just giving a tentative proposal which may benefit some users.

**Comment by rodgomesc** [comment]
i see, i'm really trying to help, but how your example can be benefit [over this](https://github.com/mrousavy/react-native-vision-camera/blob/deb3c41ee0a55e64cbb83ead912ccdd53d10988f/package/example/android/app/src/main/java/com/mrousavy/camera/example/ExampleFrameProcessorPlugin.java#L29C8-L40C20
)?, it's a easy change, i'm not seeing your point




the library maintainer needs to updates it to fit in the new requirements, not the opposite, i myself have one at [https://github.com/rodgomesc/vision-camera-face-detector](https://github.com/rodgomesc/vision-camera-face-detector ) and don't had the time to update it yet, what you are asking is same of asking facebook team to change react-native behavior to solve a 3rdparty library problem

**Comment by rodgomesc** [comment]
hey @xulihang apologizes for the confusion, i misread `WritableNativeArray` as `WritableNativeMap` since your first message, and you sent an example using `WritableNativeMap` also, why you didn't use `ArrayList<>` in the current v3?

**Comment by xulihang** [comment]
It turns out that the react native bridge's maps and arrays can be easily converted to the type v3 supports:

```java
map.toHashMap();
```

So there is no need to add this feature.
