### ISSUE TITLE
🐛 Camera not fully releasing on Android

### ISSUE THREAD

**Issue by MobileMon** [cuvent/react-native-vision-camera#2201]
### What's happening?

The camera is not fully releasing even after unmounting. 

I understand isActive is for pausing but when I unmount and the screen goes away, somewhere a camera reference is still held

I know this because im using a device with an integrated barcode scanner (keyence). When I open react native vision camera, it blocks the barcode scanner, but when i leave that screen, the barcode scanner is not reenabled. 

I dont have this problem with other camera apps on the device (google drive, camera, youtube, etc)

Which tells me react native vision camera is still holder a reference and not fully deallocating the camera like it should be

the problem is happening on android for sure, not sure about iOS

### Reproduceable Code

```tsx
n/a
```

### Relevant log output

```shell
n/a
```

### Camera Device

```json
n/a
```

### Device

Android

### VisionCamera Version

latest

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
![Screenshot 2023-11-22 at 18 00 49](https://github.com/mrousavy/react-native-vision-camera/assets/15199031/63645c01-9032-4a3f-b6cd-6133dee112ad)

I need the logs, without logs I will close the issue.

> "VisionCamera Version: latest"

That's also not a good idea. Which exact version are you using, I just released a new version 3 minutes ago, are you using that? Which is latest

**Comment by MobileMon** [comment]
furthermore when i execute this code to force open/close all camera references in native android (calling it from react native module), it fixes the problem, which proves to me the camera reference is still held


```
public void releaseAllCameraResources() {
        CameraManager cameraManager = (CameraManager) context.getSystemService(Context.CAMERA_SERVICE);
        try {
            for (String cameraId : cameraManager.getCameraIdList()) {
                try {
                    cameraManager.openCamera(cameraId, new StateCallback() {
                        @Override
                        public void onOpened(CameraDevice camera) {
                            camera.close();
                        }

                        @Override
                        public void onDisconnected(CameraDevice camera) {
                            camera.close();
                        }

                        @Override
                        public void onError(CameraDevice camera, int error) {
                            // Log or handle camera error
                        }
                    }, null);
                } catch (CameraAccessException e) {
                    // Handle exception if camera access fails
                }
            }
        } catch (CameraAccessException e) {
            // Handle exception if getting camera ID list fails
        }
    }
```

**Comment by MobileMon** [comment]
so i think we can conclude that when camera is unmounted in react native, its not calling .close() in android system

**Comment by mrousavy** [comment]
Hey! Thanks for reporting this issue.

I've been working the past days on making sure the Camera lifecycle is safely handled and released when needed to make sure this crash doesn't occur anymore.

I just created a PR for this - can you please this to see if that fixes the issue for you? https://github.com/mrousavy/react-native-vision-camera/pull/2339

If this fixes your issue, please consider [💖 **sponsoring me on GitHub** 💖](https://github.com/sponsors/mrousavy/) to support me / thank me for building VisionCamera and continuously improving it. 

If this does not fix your issue, please clone the repo, check out the branch `fix/blackscreen` (the PR above), run the Example app, reproduce your issue there and share the `adb logcat` logs with me (upload to pastebin or gist) so I can investigate this further.

Thank you! 🙏
