### ISSUE TITLE
🐛 MediaPage within the example app doesn't load on iOS

### ISSUE THREAD

**Issue by aharwood9** [cuvent/react-native-vision-camera#2205]
### What's happening?

Thanks for the great library 👏 I've been trying to build something similar to your MediaPage within the example app but found I can't get the video from the recording to load. I haven't gotten to the bottom of this yet... so I wanted to use your example App to see how you got your MediaPage to work. However, there seems to be a bug that the MediaPage doesn't load correctly after recording a video. 

Repo steps - 

- Boot on a real iOS device (in my case an iPhone 15).
- Record a video (any duration seems to be fine)
- See it gets stuck on the camera page
- See there is a console log for `Video loaded` from the MediaPage but still see the Camera page

- Photos on iOS and Android work great
- Video actually works on Android

Obviously, it is not a critical thing to the library but I was hoping it would help me figure out why I can't load a file:/// in either Expo AV or react native video. 

### Reproduceable Code

```tsx
Just using the example App with no code changes
```

### Relevant log output

```shell
LOG  calling startRecording()...
 LOG  called startRecording()!
 DEBUG  state: ACTIVE
 DEBUG  state: END
 LOG  calling stopRecording()...
 LOG  called stopRecording()!
 LOG  Recording successfully finished! file:///private/var/mobile/Containers/Data/Application/413550AA-0793-42F4-A3A2-A432A22212AF/tmp/ReactNative/CCAB62AE-6CE6-4358-A925-8448CCB8E161.mov
 LOG  Media captured! {"path":"file:///private/var/mobile/Containers/Data/Application/413550AA-0793-42F4-A3A2-A432A22212AF/tmp/ReactNative/CCAB62AE-6CE6-4358-A925-8448CCB8E161.mov","duration":1.016757584}
```

### Camera Device

```json
{
  "hardwareLevel": "full",
  "isMultiCam": false,
  "hasTorch": true,
  "sensorOrientation": "landscape-right",
  "supportsLowLightBoost": false,
  "hasFlash": true,
  "name": "Back Camera",
  "minZoom": 1,
  "id": "com.apple.avfoundation.avcapturedevice.built-in_video:0",
  "maxZoom": 129.125,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "neutralZoom": 1,
  "supportsFocus": true,
  "supportsRawCapture": false,
  "position": "back"
}
```

### Device

iPhone 15 (iOS 17.0.2)

### VisionCamera Version

3.6.9

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey! I think this has already been fixed. If not, feel free to re-open :)
