### ISSUE TITLE
Vibration not working while camera is active❓ 

### ISSUE THREAD

**Issue by DennisOstertag** [cuvent/react-native-vision-camera#2222]
### Question

Hello there,

first of all i am using version 2.15.0, due to related libraries and the version of react native being used.
At the moment upgrading is not possible, but will be considered later on in the future.

I am using this camera with a frame processor plugin to scan barcodes and qr-codes.
What i am trying to do is to add a vibration, when a code is scanned or entered.
But as long as the camera is active, vibration does not work. It does as soon as i disable the camera.

I found this issue from the previous lib
https://github.com/react-native-camera/react-native-camera/issues/1434
and tried to do what is suggested there, but that does not work here:

Here is my camera setup:
```
            <Camera
                photo={false}
                style={styles.absoluteFill}
                frameProcessor={frameProcessor}
                audio={false}
                video={false}
                frameProcessorFps={5}
                device={device}
                isActive={true}
                torch={isTorchOn ? "on" : "off"}
            />
```
any ideas on what i can do ? 

### VisionCamera Version

 2.15.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
1. You created a question instead of a bug report.
2. You did not tell me which device, or even platform (android or iOS) you are using.
3. You are not using V3 - I know you said you can't update right now, but I'm not providing such bug-hunting support for old versions of VisionCamera anymore. I just double-checked in my app, and Vibrations work in V3
