### ISSUE TITLE
(iOS) Camera Won't Open  (VisionCamera.EnumParserError error 0.)🐛 

### ISSUE THREAD

**Issue by Afhoward** [cuvent/react-native-vision-camera#2232]
### What's happening?

(iOS) In my app, I'm using the barcode scanner function, but whenever I go to open the camera, I receive this error. The program was working a week before but randomly started encountering this error this week. Since experiencing the error, I have updated to the most recent version of react-vision-camera as well as iOS.  ERROR  Camera.onError(unknown/unknown): The operation couldn’t be completed. (VisionCamera.EnumParserError error 0.) [unknown/unknown: The operation couldn’t be completed. (VisionCamera.EnumParserError error 0.)]

### Reproduceable Code

```tsx
const devices = Camera.getAvailableCameraDevices();
const device = getCameraDevice(devices, 'back', {
    physicalDevices: [
    'ultra-wide-angle-camera', 
    'wide-angle-camera', 
    'telephoto-camera'],
  });

<Camera
        style={StyleSheet.absoluteFill}
        device={device}
        isActive={true}
        codeScanner={codeScanner}/>
```

### Relevant log output

```shell
Camera.onError(unknown/unknown): The operation couldn’t be completed. (VisionCamera.EnumParserError error 0.) [unknown/unknown: The operation couldn’t be completed. (VisionCamera.EnumParserError error 0.)]

```
![IMG_0662](https://github.com/mrousavy/react-native-vision-camera/assets/118769029/d2aad1d7-11ae-485a-974f-f9e7f529d66f)

### Camera Device

```json
Cannot obtain logs 

```

### Device

iPhone 14 iOS 17.1.1

### VisionCamera Version

3.6.12

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the issue in the Example app

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Closing because I don't have any logs - but I think this is fixed
