### ISSUE TITLE
const device = devices.back; returning undefined🐛 

### ISSUE THREAD

**Issue by jahanzaibm29** [cuvent/react-native-vision-camera#2238]
### What's happening?

I want to use camera but it is returning undefined and executing (device == null) condition

### Reproduceable Code

```tsx
import {View, Text, StyleSheet} from 'react-native';
import React from 'react';
import {
  Camera,
  useCameraPermission,
  useCameraDevice,
  useCodeScanner,
  useCameraDevices,
} from 'react-native-vision-camera';

const App = () => {
  const {hasPermission, requestPermission} = useCameraPermission();
  const devices = useCameraDevices();
  const device = devices.back;
  console.log(device);

  const codeScanner = useCodeScanner({
    codeTypes: ['qr', 'ean-13'],
    onCodeScanned: codes => {
      console.log(`Scanned ${codes.length} codes!`);
    },
  });
  React.useEffect(() => {
    requestPermission();
  }, []);

  if (device == null)
    return (
      <View>
        <Text>No Found</Text>
      </View>
    );

  return (
    <Camera style={StyleSheet.absoluteFill} device={device} isActive={true} />
  );
};

export default App;
```

### Relevant log output

```shell
LOG  Running "QRScanner" with {"rootTag":11}
 LOG  Loading react-native-worklets-core...
 LOG  Worklets loaded successfully
 LOG  undefined
 LOG  undefined
 LOG  undefined
 LOG  undefined
```

### Camera Device

```json
TypeError: Cannot set property 'formats' of undefined
```

### Device

realme c2

### VisionCamera Version

"react-native-vision-camera": "^3.6.12",

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by KingSharkG** [comment]
Latest version of Vision camera return the array of available cameras useCameraDevices.
If you wanna get the beck camera use filter: 
```
const devices = useCameraDevices();
 devices.filter(device => device.position === 'back') // return array of back cameras
```
Or use: 
`const device = useCameraDevice('back')` - it's return only back camera which better to use

**Comment by festuskerich** [comment]
This should work,
const devices = useCameraDevices();
const device = devices.filter((device) => device.position === 'back')[0];
