### ISSUE TITLE
Using worklets useSharedValue to update state variables within Frame Processors❓ 

### ISSUE THREAD

**Issue by pvedula7** [cuvent/react-native-vision-camera#2244]
### Question

My goal is to utilize useSharedValue to mimic the functionality of use/setState within Vision Camera v3 frame processors.

With reanimated/RNv2 I would have this code which uses runOnJS to set the state variable which causes my component to re-render on each Camera frame. 

```
const [poses, setPoses] = useState<SKRNMLKitVisionCameraPluginResultPoseItem[]>([]);
const setPosetoVar = async (framePose) => {
    setPoses(framePose);
  };

const frameProcessor = useFrameProcessor((frame) => {
  "worklet";
  const pose = scanSKRNMLKitPose(frame);
  runOnJS(setPosetoVar)(pose);
  
}, []);
```

I have tried using useSharedValue but it does trigger re-render of the component. Is there a way to use useSharedValue to mimic the functionality of useState/setState? I am drawing on the camera image and need it to re-render each frame. 

### What I tried

I have tried using shared values like this, but no re-rendering of component.
``` 
const poses = useSharedValue<SKRNMLKitVisionCameraPluginResultPoseItem[]>([]);
const frameProcessor = useFrameProcessor((frame) => {
  "worklet";
  const pose = scanSKRNMLKitPose(frame);
  poses.value = pose
}, []);
```

I have also tried the setState within the createRunInJSFn which causes the Camera to keep reinitializing over and over again. 

```
const poses = useState<SKRNMLKitVisionCameraPluginResultPoseItem[]>([]);
const setPosetoVar = async (framePose) => {
    setPoses(framePose);
  };
  const setJSPose = Worklets.createRunInJsFn(setPosetoVar)

const frameProcessor = useFrameProcessor((frame) => {
  "worklet";
  const pose = scanSKRNMLKitPose(frame);
  setJSPose(pose)
}, []);
```

### VisionCamera Version

3.6.11

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey - yea I'm working on that with @tomekzaw. We'll have better Reanimated/useSharedValue interop soon :)

For now, this does not work. In future versions it will as we might use a different core lib
