### ISSUE TITLE
❓ The screen size is different before and after shooting (Android)

### ISSUE THREAD

**Issue by PYSoYa** [cuvent/react-native-vision-camera#2247]
### Question

  const device = useCameraDevice('back', {
    physicalDevices: ['wide-angle-camera'],
  });

  const cameraRef = useRef(null);

  const format = useCameraFormat(device, [
    {
      photoAspectRatio: Platform.OS === 'android' ? 1 : undefined,
    },
    {
      photoResolution: {
        width: 1080,
        height: 1080,
      },
    },
  ]);

        <Camera
          device={device}
          ref={cameraRef}
          isActive={true}
          photo={true}
          video={false}
          format={format}
          style={{
            width: width,
            height: width,
          }}
        />
![before](https://github.com/mrousavy/react-native-vision-camera/assets/104081510/0a342a88-12cc-4d26-a9b9-2a6cdc28fd61)
![after](https://github.com/mrousavy/react-native-vision-camera/assets/104081510/ef967ba5-967e-4572-9ffb-87ac1eb7bbf1)

          

### VisionCamera Version

3.6.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by Felipe-OT** [comment]
im having the same problem :/

**Comment by PYSoYa** [comment]
@Felipe-OT 
Found it
After setting the videoAspectTatio, the preview size and the size of the captured photo matched

**Comment by Felipe-OT** [comment]
Worked. Thanks!
