### ISSUE TITLE
🐛  IOS: Camera: `device` is null! Select a valid Camera device

### ISSUE THREAD

**Issue by konchak007** [cuvent/react-native-vision-camera#2252]
### What's happening?

<img width="512" alt="Screenshot 2023-12-04 at 14 39 19" src="https://github.com/mrousavy/react-native-vision-camera/assets/47667683/a4a5a924-e552-46f1-b2d8-f254e1daaf53">

### Reproduceable Code

```tsx
const [showCamera, setShowCamera] = useState(true)
  
  const camera = useRef(null)
  const device = useCameraDevice('back')

  .....
  
  return <View style={styles.container}>
      {showCamera ? (
        <>
          <Camera
            ref={camera}
            style={StyleSheet.absoluteFill}
            device={device}
            isActive={showCamera}
            photo={true}
            enableZoomGesture={true}
          />: <Text>Camera not available</Text>}
```

### Relevant log output

```shell
Error: Camera: `device` is null! Select a valid Camera device. See: https://mrousavy.com/react-native-vision-camera/docs/guides/devices

This error is located at:
    in Camera (created by CameraScreen)
    in RCTView (created by View)
    in View (created by CameraScreen)
    in CameraScreen (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabView)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by Screen)
    in Screen (created by BottomTabView)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by BottomTabView)
```

### Camera Device

```json
TypeError: Cannot set property 'formats' of undefined
```

### Device

Iphone SE 16.4

### VisionCamera Version

3.6.8

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
`device` might be `null`. You need to check for that in your code.
