### ISSUE TITLE
Cannot build on IOS with worklets-core

### ISSUE THREAD

**Issue by chienduc91** [cuvent/react-native-vision-camera#2289]
### How were you trying to build the app?

Im trying to install the library, i think i follow all steps and all iOS troubleshooting section. But always have the same issue

<img width="388" alt="Screenshot 2023-12-14 at 3 02 08 PM" src="https://github.com/mrousavy/react-native-vision-camera/assets/22932288/d50e0e1b-9bca-4429-84eb-3470eee35de9">

### Full build logs

```tsx
'react/bridging/CallbackWrapper.h' file not found
```

### Project dependencies

```json
"dependencies": {
 "react-native": "0.72.7",
 "react-native-vision-camera": "^3.6.16",
 "react-native-worklets-core": "^0.2.4",
}
```

### VisionCamera Version

3.6.16

### Target platforms

iOS

### Operating system

MacOS

### Can you build the VisionCamera Example app?

No, I cannot build the Example app either

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by Amurmurmur** [comment]
and you probably have use_frameworks set to static
and using firebase?

**Comment by Amurmurmur** [comment]
solved here: https://github.com/mrousavy/react-native-vision-camera/issues/2255#issuecomment-1889014507

**Comment by mrousavy** [comment]
Hey - I think this is not related to VisionCamera.
