### ISSUE TITLE
🐛 Android permission status behavior differs from what’s described in the Imperative API docs

### ISSUE THREAD

**Issue by audionerd** [cuvent/react-native-vision-camera#2307]
### What's happening?

The docs for the Imperative API indicate that you would first call `Camera.getCameraPermissionStatus`, and if it returns `not-determined` you would call `Camera.requestCameraPermission`, but if it returns `denied` then you can't use `Camera.requestCameraPermission` at all.

But in practice, we’re seeing `Camera.getCameraPermissionStatus` always returns `denied` for a fresh install of our app. It never returns `not-determined`. However, even after returning `denied`, `Camera.requestCameraPermission` does work.

So we changed our code to skip the status check, and just request permission immediately.

Not sure if this behavior differs between Android versions or devices or user configurations, but it’s what we’re seeing in our testing currently.

### Reproduceable Code

```tsx
N/A
```

### Relevant log output

```shell
N/A
```

### Camera Device

```json
N/A
```

### Device

Pixel 7 Pro (Android 13), Pixel 6 Pro (Simulator, Android 13)

### VisionCamera Version

3.6.13

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey! This is a good point, Android permissions work differently than iOS permissions. I'll update the docs! Thanks

**Comment by EmanuilM** [comment]
@mrousavy Did you update the docs? I still get status denied on fresh installed app


Here's my code
```javascript
    const { hasPermission, requestPermission } = useCameraPermission();

    useEffect(() => {
        if (!hasPermission) {
            requestPermission();
        }
    }, [])
```
