### ISSUE TITLE
🔧 Build failed for android sdk 33 and RN 0.71.13

### ISSUE THREAD

**Issue by ducminhleeh** [cuvent/react-native-vision-camera#2312]
### How were you trying to build the app?

I tried to build on android with command: `react-native run-android`, but got error. I wonder does package require any 
specific package (e.g: [react-native-worklets-core](https://github.com/margelo/react-native-worklets-core)) or any specific version for `react-native-reanimated` ?
My config:

**android/build.gradle**
```
kotlinVersion = '1.8.10'
buildToolsVersion = "33.0.0"
minSdkVersion = 26
compileSdkVersion = 33
targetSdkVersion = 33
```

**android/app/build.gradle**
```
android {
    ndkVersion rootProject.ext.ndkVersion
    compileSdkVersion rootProject.ext.compileSdkVersion
    minSdkVersion rootProject.ext.minSdkVersion
    targetSdkVersion rootProject.ext.targetSdkVersion
}
```

**android/gradle.properties**
```
hermesEnabled=false
VisionCamera_disableFrameProcessors = true
```

### Full build logs

```tsx
> Task :react-native-vision-camera:configureCMakeDebug[armeabi-v7a] FAILED
C/C++: /Users/user/Documents/project/camera/node_modules/react-native-vision-camera/android/CMakeLists.txt debug|armeabi-v7a : com.google.prefab.api.NoMatchingLibraryException: No compatible library found for //ReactAndroid/fabricjni. Rejected the following libraries:

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
1130 actionable tasks: 1125 executed, 5 up-to-date
Error: The 'kotlin-android-extensions' Gradle plugin is no longer supported. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.


1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-vision-camera:configureCMakeDebug[armeabi-v7a]'.
> [CXX1214] /Users/user/Documents/project/camera/node_modules/react-native-vision-camera/android/CMakeLists.txt debug|armeabi-v7a : User has minSdkVersion 16 but library was built for 21 [//ReactAndroid/fabricjni]

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)
```

### Project dependencies

```json

"react-native": "0.71.13",
"react-native-reanimated": "2.17.0",
"react-native-vision-camera" "^3.6.17"

```

### VisionCamera Version

3.6.17

### Target platforms

Android

### Operating system

MacOS

### Can you build the VisionCamera Example app?

No, I cannot build the Example app either

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
I don't think this is related to VisionCamera. Especially since you also can't build the example app. I'm guessing your system doesn't have enough RAM allocated to Gradle to build those RN projects.
