### ISSUE TITLE
Is it possible to use React Native Vision Camera with ViroReact or react-native-ar-viewer❓ 

### ISSUE THREAD

**Issue by colaquecez** [cuvent/react-native-vision-camera#2317]
### Question

I'm attempting to use the Vision Camera alongside another AR library. I want to utilize the Vision Camera for object recognition and the AR Viewer library to display AR items in the same frame that the Vision Camera captures. However, I'm unsure of how to achieve this. When attempting to use two cameras simultaneously, it seems there is a race condition, and only one library will work. I tried having two components of the Vision Camera, but only one is functional, when I've tried to do the same in React Native Ar Viewer it shows the 2 components with the cameras, but it seems Vision camera can not use 2 camera components at same time, does anyone know how to bypass it?

### Using React Native Vision Camera + React native Ar Viewer
<img src="https://github.com/mrousavy/react-native-vision-camera/assets/38195454/8752137c-ecec-4fd0-8119-b67263d722e7" width="250px" />

### Using React Native Ar Viwer Twice

<img src="https://github.com/mrousavy/react-native-vision-camera/assets/38195454/931c6849-3f62-48a6-bc06-768fd240a0ac" width="250px" />

### Using React Native Vision Camera Twice
<img src="https://github.com/mrousavy/react-native-vision-camera/assets/38195454/21960b0e-47d0-4cab-8d91-d42d2d84fc5f" width="250px" />

### VisionCamera Version

3.6.17

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey!

You cannot use a single Camera Device twice, this is by design by Apple and other phone manufacturers. It's just not possible.

AR just shows two Previews, using a single Camera device though. One with an overlay, one without.

Would be cool to have some interop with the react-native-ar-viewer package tho! Maybe create a feature request in their repo
