### ISSUE TITLE
✨ New Renderer Interop Layer

### ISSUE THREAD

**Issue by nikitapilgrim** [cuvent/react-native-vision-camera#2320]
### What feature or enhancement are you suggesting?

https://github.com/reactwg/react-native-new-architecture/discussions/135

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

I get this error when trying to build with interop layer 
` The following build commands failed:
[RUN_FASTLANE]  CompileC /Users/np/Library/Developer/Xcode/DerivedData/bloggshouse-bpmylusodavizihifrfswczrktob/Build/Intermediates.noindex/ArchiveIntermediates/bloggshouse/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/VisionCamera.build/Objects-normal/arm64/JSINSObjectConversion.o /var/folders/bj/ky1b7xq12n971y0qf9jcjymr0000gn/T/eas-build-local-nodejs/96ab3613-133a-4506-abea-8c11b64a1ff9/build/frontend/apps/expo/node_modules/react-native-vision-camera/ios/Frame\ Processor/JSINSObjectConversion.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'VisionCamera' from project 'Pods')`

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
Hey - there is no real error logs. If the build fails, please create a build error.
