### ISSUE TITLE
❓ Is it possible to work with video for development (some kind of mocking)

### ISSUE THREAD

**Issue by sketch55** [cuvent/react-native-vision-camera#2334]
### Question

Is there a way to use already recorded video to write a frame processor plugin?

### What I tried

I found the following page in the documentation:
https://react-native-vision-camera.com/docs/guides/mocking

however it mocks only the take photo and at least what I tried I did not find a way to mock the video frames, so I can develop the frame processor plugin on mocked video.

### VisionCamera Version

all versions

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey!

At the moment this is not possible. But I've been thinking of something similar. Please create a feature request :)
