### ISSUE TITLE
How to record video from a front camera without a mirror❓ 

### ISSUE THREAD

**Issue by HorbachAndrii** [cuvent/react-native-vision-camera#2338]
### Question

I am analyzing recorded video and for me, it matters to record video without a mirror.

For IOS, I added some hack. I changed this `connection.isVideoMirrored = false` (from true to false) at `node_modules/react-native-vision-camera/ios/Extensions/AVCaptureOutput+mirror.swift`.
https://github.com/mrousavy/react-native-vision-camera/blob/ef4e9fabf9410dc5630dee8220f281089c941495/package/ios/Extensions/AVCaptureOutput%2Bmirror.swift#L19

But for Android, I don't know how to record video from a front camera without a mirror.

Maybe somebody knows how can I record video from a front camera without a mirror?

### What I tried

I changing the Matrix for transformMatrix in VideoPipeline.kt and other stuff, but nothing helped

### VisionCamera Version

3.6.16

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by HorbachAndrii** [comment]
So I added also some hack that works for android.


VideoPipeline.kt `node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/core/VideoPipeline.kt` 

- update this line https://github.com/mrousavy/react-native-vision-camera/blob/ef4e9fabf9410dc5630dee8220f281089c941495/package/android/src/main/java/com/mrousavy/camera/core/VideoPipeline.kt#L165
```kotlin
onFrame(transformMatrix)
```  
-> 
```kotlin
onFrame(transformMatrix, isMirrored)
``` 

- update this line https://github.com/mrousavy/react-native-vision-camera/blob/ef4e9fabf9410dc5630dee8220f281089c941495/package/android/src/main/java/com/mrousavy/camera/core/VideoPipeline.kt#L212
```kotlin
private external fun onFrame(transformMatrix: FloatArray)
```  
->
```kotlin
private external fun onFrame(transformMatrix: FloatArray, isMirrored: Boolean)
``` 


VideoPipeline.cpp `node_modules/react-native-vision-camera/android/src/main/cpp/VideoPipeline.cpp`

- update this line https://github.com/mrousavy/react-native-vision-camera/blob/ef4e9fabf9410dc5630dee8220f281089c941495/package/android/src/main/cpp/VideoPipeline.cpp#L73
```c++
void VideoPipeline::onFrame(jni::alias_ref<jni::JArrayFloat> transformMatrixParam) {
``` 
->
```c++
void VideoPipeline::onFrame(jni::alias_ref<jni::JArrayFloat> transformMatrixParam, bool isMirrored) {
``` 

 - update this line https://github.com/mrousavy/react-native-vision-camera/blob/ef4e9fabf9410dc5630dee8220f281089c941495/package/android/src/main/cpp/VideoPipeline.cpp#L82
```c++
_recordingSessionOutput->renderTextureToSurface(texture, transformMatrix);
``` 
 ->
```c++
_recordingSessionOutput->renderTextureToSurface(texture, transformMatrix, isMirrored);
```  


VideoPipeline.h `node_modules/react-native-vision-camera/android/src/main/cpp/VideoPipeline.h`

-  update this line https://github.com/mrousavy/react-native-vision-camera/blob/ef4e9fabf9410dc5630dee8220f281089c941495/package/android/src/main/cpp/VideoPipeline.h#L39
```c++
void onFrame(jni::alias_ref<jni::JArrayFloat> transformMatrix);
``` 
 ->
```c++
void onFrame(jni::alias_ref<jni::JArrayFloat> transformMatrix, bool isMirrored);
``` 


OpenGLRenderer.cpp `node_modules/react-native-vision-camera/android/src/main/cpp/OpenGLRenderer.cpp`

- update this line https://github.com/mrousavy/react-native-vision-camera/blob/ef4e9fabf9410dc5630dee8220f281089c941495/package/android/src/main/cpp/OpenGLRenderer.cpp#L46
```c++
void OpenGLRenderer::renderTextureToSurface(const OpenGLTexture& texture, float* transformMatrix) {
``` 
-> 
```c++
void OpenGLRenderer::renderTextureToSurface(const OpenGLTexture& texture, float* transformMatrix, bool isMirrored) {
``` 

- update this line https://github.com/mrousavy/react-native-vision-camera/blob/ef4e9fabf9410dc5630dee8220f281089c941495/package/android/src/main/cpp/OpenGLRenderer.cpp#L68
```c++
_passThroughShader.draw(texture, transformMatrix);
``` 
->
```c++
_passThroughShader.draw(texture, transformMatrix, isMirrored);
``` 


OpenGLRenderer.h `node_modules/react-native-vision-camera/android/src/main/cpp/OpenGLRenderer.h`

- update this line https://github.com/mrousavy/react-native-vision-camera/blob/ef4e9fabf9410dc5630dee8220f281089c941495/package/android/src/main/cpp/OpenGLRenderer.h#L36
 
```c++
void renderTextureToSurface(const OpenGLTexture& texture, float* transformMatrix);
``` 
 ->
 
```c++
void renderTextureToSurface(const OpenGLTexture& texture, float* transformMatrix, bool isMirrored);
``` 
 
 
 PassThroughShader.cpp `node_modules/react-native-vision-camera/android/src/main/cpp/PassThroughShader.cpp`
 
 - update this line https://github.com/mrousavy/react-native-vision-camera/blob/ef4e9fabf9410dc5630dee8220f281089c941495/package/android/src/main/cpp/PassThroughShader.cpp#L27
```c++
 void PassThroughShader::draw(const OpenGLTexture& texture, float* transformMatrix) {
```
 ->
```c++
void PassThroughShader::draw(const OpenGLTexture& texture, float* transformMatrix, bool isMirrored) {
```
 
 - update this line https://github.com/mrousavy/react-native-vision-camera/blob/ef4e9fabf9410dc5630dee8220f281089c941495/package/android/src/main/cpp/PassThroughShader.cpp#L30
```c++
_programId = createProgram();
```
 ->
```c++
_programId = createProgram(isMirrored);
```
 
 - update this line https://github.com/mrousavy/react-native-vision-camera/blob/ef4e9fabf9410dc5630dee8220f281089c941495/package/android/src/main/cpp/PassThroughShader.cpp#L87
```c++
GLuint PassThroughShader::createProgram() {
``` 
 ->
```c++
GLuint PassThroughShader::createProgram(bool isMirrored) {
``` 
 
 - update this line https://github.com/mrousavy/react-native-vision-camera/blob/ef4e9fabf9410dc5630dee8220f281089c941495/package/android/src/main/cpp/PassThroughShader.cpp#L89
 ```c++
  GLuint fragmentShader = loadShader(GL_FRAGMENT_SHADER, FRAGMENT_SHADER);
```
 ->
```c++
GLuint fragmentShader;
if (isMirrored) {
  fragmentShader = loadShader(GL_FRAGMENT_SHADER, FRAGMENT_SHADER_FLIPPED);
} else {
  fragmentShader = loadShader(GL_FRAGMENT_SHADER, FRAGMENT_SHADER);
}
``` 


PassThroughShader.h `node_modules/react-native-vision-camera/android/src/main/cpp/PassThroughShader.h`

- update this line after https://github.com/mrousavy/react-native-vision-camera/blob/ef4e9fabf9410dc5630dee8220f281089c941495/package/android/src/main/cpp/PassThroughShader.h#L32
```c++
void draw(const OpenGLTexture& texture, float* transformMatrix);
``` 
->
```c++
void draw(const OpenGLTexture& texture, float* transformMatrix, bool isisMirrored);
``` 

- update this line after https://github.com/mrousavy/react-native-vision-camera/blob/ef4e9fabf9410dc5630dee8220f281089c941495/package/android/src/main/cpp/PassThroughShader.h#L37
```c++
static GLuint createProgram();
``` 
->
```c++
static GLuint createProgram(bool isisMirrored);
``` 

- add code after this FRAGMENT_SHADER https://github.com/mrousavy/react-native-vision-camera/blob/ef4e9fabf9410dc5630dee8220f281089c941495/package/android/src/main/cpp/PassThroughShader.h#L72-L81
```c++
static constexpr char FRAGMENT_SHADER_FLIPPED[] = R"(
    #extension GL_OES_EGL_image_external : require
    precision mediump float;
    varying vec2 vTexCoord;
    uniform samplerExternalOES uTexture;

    void main() {
        gl_FragColor = texture2D(uTexture, vec2(vTexCoord.x, 1.0 - vTexCoord.y));
    }
  )";
```

**Comment by CyxouD** [comment]
It doesn't work in my case on iOS with the same react-native-vision-camera. Could you say what iOS device you use? Also, could you send your Camera component JSX (if something differs here)?

**Comment by HorbachAndrii** [comment]
> It doesn't work in my case on iOS with the same react-native-vision-camera. Could you say what iOS device you use? Also, could you send your Camera component JSX (if something differs here)?

What VisionCamera Version are you using? 


> Could you say what iOS device you use?

it works for all IOS devices

**Comment by CyxouD** [comment]
@HorbachAndrii thank you for your quick response! 
> What VisionCamera Version are you using?

I tried with 3.6.16 (as you mentioned) and 3.9.2. I tested with iPhone 11.

**Comment by HorbachAndrii** [comment]
here is my AVCaptureOutput+mirror.swift file

```
//
//  AVCaptureOutput+mirror.swift
//  mrousavy
//
//  Created by Marc Rousavy on 18.01.21.
//  Copyright © 2021 mrousavy. All rights reserved.
//

import AVFoundation

extension AVCaptureOutput {
  /**
   Mirrors the video output if possible.
   */
  func mirror() {
    connections.forEach { connection in
      if connection.isVideoMirroringSupported {
        connection.automaticallyAdjustsVideoMirroring = false
        connection.isVideoMirrored = false
      }
    }
  }

  /**
   Sets the target orientation of the video output.
   This does not always physically rotate image buffers.

   - For Preview, an orientation hint is used to rotate the layer/view itself.
   - For Photos, an EXIF tag is used.
   - For Videos, the buffers are physically rotated if available, since we use an AVCaptureVideoDataOutput instead of an AVCaptureMovieFileOutput.
   */
  func setOrientation(_ orientation: Orientation) {
    // Set orientation for each connection
    connections.forEach { connection in
      #if swift(>=5.9)
        if #available(iOS 17.0, *) {
          // Camera Sensors are always in landscape rotation (90deg).
          // We are setting the target rotation here, so we need to rotate by landscape once.
          let cameraOrientation = orientation.rotateBy(orientation: .landscapeLeft)
          let degrees = cameraOrientation.toDegrees()

          // TODO: Don't rotate the video output because it adds overhead. Instead just use EXIF flags for the .mp4 file if recording.
          //       Does that work when we flip the camera?
          if connection.isVideoRotationAngleSupported(degrees) {
            connection.videoRotationAngle = degrees
          }
        } else {
          if connection.isVideoOrientationSupported {
            connection.videoOrientation = orientation.toAVCaptureVideoOrientation()
          }
        }
      #else
        if connection.isVideoOrientationSupported {
          connection.videoOrientation = orientation.toAVCaptureVideoOrientation()
        }
      #endif
    }
  }
}

```

**Comment by HorbachAndrii** [comment]
> @HorbachAndrii thank you for your quick response!
> 
> > What VisionCamera Version are you using?
> 
> I tried with 3.6.16 (as you mentioned) and 3.9.2. I tested with iPhone 11.

Did you 'Clean Build Folder' before building the app?

**Comment by CyxouD** [comment]
> Did you 'Clean Build Folder' before building the app?
@HorbachAndrii Thank you! I tried it with 3.9.1 and 3.9.2, but unfortunately it didn't work. I didn't clean the build folder with 3.6.16 because it had another bugs, but I tested with logs that changes were reflected.
I will check if it works with other versions of iPhone (not 11)

**Comment by mrousavy** [comment]
Hey all! I just spent some time to build a new feature: I created a PR to add a `isMirrored` prop to Camera: https://github.com/mrousavy/react-native-vision-camera/pull/3036

With this prop you can enable or disable output mirroring 🎉🥳

If you appreciate my time and dedication towards building new features and constantly improving this library, please [**consider sponsoring me on GitHub**](https://github.com/sponsors/mrousavy/)  :)

**Comment by CyxouD** [comment]
@mrousavy thank you for introducing new features! However, in this issue, we needed Preview to be not mirrored in the front camera, but it isn't supported:

> To avoid dizzyness for users, the Preview will always be mirrored in the front Camera, but not in the back Camera. This is the same behaviour as in the native iOS Camera app.

**Comment by mrousavy** [comment]
This is intentional - if the preview was mirrored the app would be pretty unusable because every movement goes in the wrong direction. All camera apps mirror the front preview.

If you really really need the preview not mirrored for whatever reason, you can just apply a `scaleX: -1` transform to the `<Camera>` view style.
