### ISSUE TITLE
Live Filter Preview✨ 

### ISSUE THREAD

**Issue by hashhirr** [cuvent/react-native-vision-camera#2347]
### What feature or enhancement are you suggesting?

Do Anyone have any idea how can i apply live preview filters in react native vision camera i have implemented the camera and all the features but what i am missing is the instagram like filters. i tried different sdks like img.ly etc but i have no solution yet.

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

i tried few of the react native libraries and it didn't work i am open to even work in native modules if anyone have any solution

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
There are multiple discussions like this in this repo, and I answered in each of those.

![Screenshot 2024-01-05 at 15 36 48](https://github.com/mrousavy/react-native-vision-camera/assets/15199031/c02c3035-7a41-43a4-b96f-c452c85243b9)

**Comment by mrousavy** [comment]
See https://github.com/mrousavy/react-native-vision-camera/pull/2727 👀
