### ISSUE TITLE
❓ The accuracy and quality of scanning are at 70%, which is not satisfactory

### ISSUE THREAD

**Issue by 786Muhammadshams** [cuvent/react-native-vision-camera#2349]
### Question

I am facing an issue with scanning duplicate barcodes from a single source. I implemented a debounce mechanism for the most frequently scanned items within 0 to 500 milliseconds before sending them to the 'isValidEan' check function. There, I use an algorithm to check EAN-8 and EAN-13 barcodes. However, when I scanned 50 barcodes from real products, 10 barcodes could not be read. The accuracy and quality of scanning are at 70%, which is not satisfactory. Can someone suggest a solution to this problem?

### VisionCamera Version

latest

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
1. "latest" is not a valid VisionCamera version
2. The QR code scanner is using 1280x720 resolution. Are those codes small?
3. The QR code scanner built into VisionCamera is using MLKit Barcode Detection. If that isn't working for you, you can at any point use a Frame Processor plugin with a custom algorithm, that's the beauty of VisionCamera.
