### ISSUE TITLE
🔧 ystem/camera-module-not-found: Failed to initialize VisionCamera: The native Camera Module (NativeModules.CameraView) could not be found

### ISSUE THREAD

**Issue by deeps0903** [cuvent/react-native-vision-camera#2359]
### How were you trying to build the app?

For Android :-
1. ./gradlew clean
2. rm -rf android/.gradle android/.idea android/app/build android/build
3. rm -rf package-lock.json yarn.lock node_modules
4. yarn
5. create debug apk and try to run 

### Full build logs

```tsx
Error: Unable to resolve module react-native-vision-camera from /data/home/ubuntu/Desktop/dhpapp-285028-react-native/src/packages/blocks/BluetoothIntegration19/src/BluetoothIntegration19.tsx: react-native-vision-camera could not be found within the project or in these directories:
  packages/blocks/BluetoothIntegration19/node_modules
 
i also try these steps :

 1. Reset Metro's cache: yarn start --reset-cache
 2. Remove the cache: rm -rf /tmp/metro-*
```

### Project dependencies

```json
"react-native-reanimated": "1.13.1”,
"react-native": "0.64.4”,
 "react-native-vision-camera": "^3.6.17”,
"react-native-worklets-core": "^0.2.4”,
gradle:4.2.2
Node: v16.20.2
```

### VisionCamera Version

3.6.17

### Target platforms

Android

### Operating system

Linux

### Can you build the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Did you go through the troubleshooting guide? what does npx react-native info do
