### ISSUE TITLE
🐛 QR/Barcode Scanning frame very slow.

### ISSUE THREAD

**Issue by tytom2003** [cuvent/react-native-vision-camera#2375]
### What's happening?

i added codeScanner in camera. My program frame is very slow. 

### Reproduceable Code

```tsx
const codeScanner = useCodeScanner({
    codeTypes: ['qr', 'ean-13'],
    onCodeScanned: codes => {
      console.log(`Scanned ${codes.length} codes!`);
    },
  });

      <Camera
        style={StyleSheet.absoluteFill}
        ref={camera}
        device={device}
        isActive={isActive}
        codeScanner={codeScanner} //when i remove the codeScanner function, camera frame will go back normal.
      />
```

### Relevant log output

```shell
For Android 
ERROR  Camera.onError(session/camera-has-been-disconnected): [session/camera-has-been-disconnected] The given Camera device (id: 1) has been disconnected! Error: UNKNOWN_CAMERA_DEVICE_ERROR [session/camera-has-been-disconnected: [session/camera-has-been-disconnected] The given Camera device (id: 1) has been disconnected! Error: UNKNOWN_CAMERA_DEVICE_ERROR]
```

### Camera Device

```json
const device = useCameraDevice('back');
```

### Device

android emulator - google pixel 2XL

### VisionCamera Version

3.7.0

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
What does "My program frame is very slow" mean?

You posted an error (`UNKNOWN_CAMERA_DEVICE_ERROR`) - what is it now, a slow "program frame" or an error?
