### ISSUE TITLE
Frame Processor Error: Exception in HostFunction: no ArrayBuffer attached, js engine: VisionCamera

### ISSUE THREAD

**Issue by jslok** [cuvent/react-native-vision-camera#2409]
### What's happening?

Trying out the updated vision-camera-resize-plugin with react-native-fast-tflite and getting the following error:
`Frame Processor Error: Exception in HostFunction: no ArrayBuffer attached, js engine: VisionCamera`
If I `console.log(data)` I get `Frame Processor Error: Array buffers are not supported as shared values., js engine: VisionCamera`.

The following code does appear to work, but if I understand correctly, it removes the benefits of SharedArray since it creates a new array to send to tflite.
```
      const data = resize(frame, {
        size: {
          width: 192,
          height: 192,
        },
        pixelFormat: 'rgb-uint8',
      })
      const array = new Uint8Array(data)
      const output = model.runSync([array])
```

### Reproduceable Code

```tsx
const data = resize(frame, {
        size: {
          width: 192,
          height: 192,
        },
        pixelFormat: 'rgb-uint8',
      })
const output = model.runSync([data])
```

### Relevant log output

```shell
Frame Processor Error: Exception in HostFunction: no ArrayBuffer attached, js engine: VisionCamera
```

### Camera Device

```json
{"hardwareLevel": "full", "hasFlash": true, "hasTorch": true, "id": "0", "isMultiCam": true, "maxExposure": 24, "maxZoom": 8, "minExposure": -24, "minFocusDistance": 10.500000100135805, "minZoom": 0.6704425811767578, "name": "BACK (0)", "neutralZoom": 1, "physicalDevices": ["wide-angle-camera", "ultra-wide-angle-camera", "telephoto-camera"], "position": "back", "sensorOrientation": "landscape-right", "supportsFocus": true, "supportsLowLightBoost": true, "supportsRawCapture": true}
```

### Device

Pixel 7

### VisionCamera Version

3.8.1

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
1. The code you shared is actually the way to go. This does **not** create a copy, this simply wraps it in a typed array, which is what tflite expects.
2. If you are using typescript it would tell you that you need to pass a typed array, so agajn that's fine
3. ArrayBuffers are not supported as shared values, so you cannot pass them to the console log function (which runs on the JS Thread)
