### ISSUE TITLE
Problem understanding barcode frame component❓ 

### ISSUE THREAD

**Issue by rveltonCL** [cuvent/react-native-vision-camera#2424]
### Question

First of all, I am running my application in portrait mode. I am trying to detect a barcode on a certain part of the view. In the view itself, it will utilize the standard pixel sizes. So based off my view elements, I can calculate the pixel X,Y coordinate box I need the barcode to line up in.

However, when i am looking at the barcode from, the X coordinate is always bigger than the Y coordinate.  I have been trying to find the property to set to have the barcode frame to a portrait view, but I am not having luck with the documentation or previous questions.

Does anyone know how to translate the barcode from location value to the pixel value represented in the React Native view?

Thanks.

### VisionCamera Version

3.8.2

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Camera sensors are pretty much always in landscape orientation. For now, I think you can assume that the coordinates are simply flipped to convert them to view coordinates - in the future this will be implemented with https://github.com/mrousavy/react-native-vision-camera/issues/1891.
