### ISSUE TITLE
Can we detect blurry image while capturing images?

### ISSUE THREAD

**Issue by shivlisyn** [cuvent/react-native-vision-camera#2427]
### Question

Can we detect blurry images while capturing picturing ?

### VisionCamera Version

3.8.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
You can use a Frame Processor Plugin to do that. This requires custom magic though.

I don't have an event for exposing auto-focus state at the moment if that's what you're asking, no.
