### ISSUE TITLE
🐛 [v2] capture/no-valid-data thrown when calling stopRecording on some Android devices

### ISSUE THREAD

**Issue by jblarriviere** [cuvent/react-native-vision-camera#2428]
### What's happening?

Hello !

On some Android devices, while recording with the front camera, calling `stopRecording` will crash and throw an `capture/no-valid-data` error

This issue seems similar to the one reported [here](https://issuetracker.google.com/issues/270656244)
It's related to an issue with CameraX fixed [here](https://paleforce.net/?_=%2Fplatform%2Fframeworks%2Fsupport%2F%2B%2F3130e614ac6950af495c45fedd44a3ee042b8d01%23KJWqMdlUlBnqJekHXxTkyYz6d4ZsHkyuvvEzKymVYFo%3D) but that has not been backported to 1.1.X

I do not have any of the impacted devices with me so I've not been able to get a repro running, but my guess is example app on any of those devices would run into the issue.

A patch that worked for our users is to have `configureSession` setting surface provider before binding preview to lifecycle

### Reproduceable Code

```tsx
const devices = useCameraDevices();

<Camera
                isActive={isAppForeground && isScreenFocused}
                ref={camera}
                video
                audio
                device={devices.front}
                orientation="portrait"
                style={flexGrowOne}
                onLayout={onCameraLayout}
              />

camera.current?.startRecording({
                      fileType: 'mp4',
                      onRecordingFinished: (video) => {
                        //proceeding with video.path. In our case we never get there
                      },
                      onRecordingError: (error) => {
                      //error monitoring, this is where we got the capture/no-valid-data error thrown
                      },
                    });
                  } catch (error) {
                    //error monitoring, never had issues here
                  }
```

### Relevant log output

```shell
Can't provide as I do not have any of the impacted device with me. Will run on example app and provide logs if I can get my hands on one.
```

### Camera Device

```json
Can't provide as I do not have any of the impacted device with me. Will run on example app and provide logs if I can get my hands on one.
```

### Device

M2012K11G, SM-S911B, 2109119DG, SM-A047F, SM-F711B, RMO-NX1, KB2003, SM-G990B, 23076RN8DY, SM-A236B

### VisionCamera Version

2.16.7

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey - sorry I am not working on any fixes or improvements for V2 in my free time anymore. If you find a fix for this and submit a PR, that's great - I can merge it & release a fix.

Otherwise - this is probably fixed in V3 - try to upgrade sooner or later :)
