### ISSUE TITLE
Regarding use of Frame processor

### ISSUE THREAD

**Issue by Virajmakwana** [cuvent/react-native-vision-camera#2429]
### Question

**I want to use the below code to get the frames and then draw onto a Camera Frame and have it rendered into the resulting photo or video in Realtime using Skia in VisionCamera. but when i am trying to get the frames using frameprocessor I am getting the error that frameprocessors are not enabled.**

```
function App() {
  const frameProcessor = useFrameProcessor((frame) => {
    'worklet'
    console.log(`Frame: ${frame.width}x${frame.height} (${frame.pixelFormat})`)
  }, [])

  return (
    <Camera
      {...cameraProps}
      frameProcessor={frameProcessor}
    />
  )
}
```

**I installed the "react-native-worklets-core": "^0.2.4" this to use it during getting frames but after installing this package i am getting below build failed error** 

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\skia\node_modules\react-native-worklets-core\android\build.gradle' line: 38

* What went wrong:
A problem occurred evaluating project ':react-native-worklets-core'.
Could not get unknown property 'hermesEnabled' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.

### Versions for my android build
        buildToolsVersion = "31.0.0"
        minSdkVersion = 24
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlinVersion = "1.6.0"

### React-native Version
 0.68.2

### VisionCamera Version

2.16.5

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
You need to be on RN 0.71+, and VisionCamera V3+.

**Comment by sir-stevie** [comment]
> You need to be on RN 0.71+, and VisionCamera V3+.

Hi, I have a question regarding skia frame processors. How do I make vision camera detect skia if  it doesn't happen automatically. In my project, Vision Camera can detect react native worklets core but not skia so I end up only being able to use 'useFrameProcessor' hook for frame processing but my use case needs 'useSkiaFrameProcessor' hook. I hope this makes sense, am using RN 0.72.4, Vision Camera 4.0.3, RN worklet core 1.2.0, RN skia 1.2.3.

Thanks
