### ISSUE TITLE
💭 Mux collaboration

### ISSUE THREAD

**Issue by kosmokoks** [cuvent/react-native-vision-camera#2451]
### Question

Hello guys,

Has anyone tried to collaborate with MUX (a platform for making live broadcasts), I know that this library has access to frame processors and native code could be written there, but is it at all possible to send frames to the rtmps server that provides MUX? 

Thanks in advance

### VisionCamera Version

3.0.0-rc.9

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey - yes you can simply write [native Frame Processor Plugins](https://react-native-vision-camera.com/docs/guides/frame-processor-plugins) that use Mux's APIs to upload the Frame data directly, should be pretty straight forward.

I am not aware of any current community plugins for Mux specificly though, so if you build one please share so we can add it to the plugin list :)
