### ISSUE TITLE
🔧 Build Failed on Android when Adding react-native-worklets-core

### ISSUE THREAD

**Issue by deadbeefv** [cuvent/react-native-vision-camera#2489]
### How were you trying to build the app?

I tried building my app with yarn expo run:android. This works when I remove react-native-worklets-core and fails when I reinstall it with yarn.

### Full build logs

```tsx
> Configure project :react-native-vision-camera
[VisionCamera] react-native-worklets-core found, Frame Processors enabled!

> Task :react-native-worklets-core:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-worklets-core:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-worklets-core:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: C:\Users\info\AppData\Local\Android\Sdk\platforms\android-34\core-for-system-modules.jar.
         > Error while executing process C:\Program Files\Java\jdk-21\bin\jlink.exe with arguments {--module-path C:\Users\info\.gradle\caches\transforms-3\4b1308f73665eeac924c132c45e496df\transformed\output\temp\jmod --add-modules java.base --output C:\Users\info\.gradle\caches\transforms-3\4b1308f73665eeac924c132c45e496df\transformed\output\jdkImage --disable-plugin system-modules}

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 31s
123 actionable tasks: 25 executed, 85 from cache, 13 up-to-date
Error: C:\Users\info\Fingerspelling\android\gradlew.bat exited with non-zero code: 1
Error: C:\Users\info\Fingerspelling\android\gradlew.bat exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Users\info\Fingerspelling\node_modules\@expo\cli\node_modules\@expo\spawn-async\build\spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:634:26)
    at ChildProcess.emit (node:events:519:28)
    at cp.emit (C:\Users\info\Fingerspelling\node_modules\@expo\cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at Object.spawnAsync [as default] (C:\Users\info\Fingerspelling\node_modules\@expo\cli\node_modules\@expo\spawn-async\build\spawnAsync.js:17:21)
    at spawnGradleAsync (C:\Users\info\Fingerspelling\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:72:46)
    at Object.assembleAsync (C:\Users\info\Fingerspelling\node_modules\@expo\cli\build\src\start\platforms\android\gradle.js:52:18)
    at runAndroidAsync (C:\Users\info\Fingerspelling\node_modules\@expo\cli\build\src\run\android\runAndroidAsync.js:36:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Project dependencies

```json
"dependencies": {
    "@babel/preset-env": "7.1.6",
    "@react-native/babel-preset": "*",
    "expo": "~50.0.4",
    "expo-status-bar": "~1.11.1",
    "expo-system-ui": "^2.9.3",
    "react": "18.2.0",
    "react-native": "0.73.2",
    "react-native-vision-camera": "^3.8.2",
    "react-native-worklets-core": "^0.3.0"
  },
```

### VisionCamera Version

3.8.2

### Target platforms

Android

### Operating system

Windows

### Can you build the VisionCamera Example app?

Yes, I can successfully build the Example app here

### Additional information

- [X] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by therealpurplemana** [comment]
I am also seeing this same error.  Note that downgrading to 0.2.4 still works.

**Comment by deadbeefv** [comment]
Let me try it.

**Comment by deadbeefv** [comment]
The build still fails with the same error message. What do you think could be the root cause?

**Comment by therealpurplemana** [comment]
> The build still fails with the same error message. What do you think could be the root cause?

0.2.4 works.  Make sure you wipe your node_modules and rebuild pod install / gradlew clean

**Comment by deadbeefv** [comment]
Still no luck

**Comment by mrousavy** [comment]
This is a cache issue.

1. Make sure to commit & push everything to your git repo so you don't f*ck anything up
2. Delete `android/`, `node_modules/` and `ios/` folders
3. Run `yarn` (or `npm i`) again
4. Open the Android project and do a Gradle sync, then hit run to run the app (don't hit build or refresh or rebuild or anything)

**Comment by deadbeefv** [comment]
Thank you for the assistance. It finally works.

Question though: why the convoluted setup to get react-native-worklets-core to work? Why didn't it work as per the documentation and what can I do to help, even if its to improve the documentation?

**Comment by mrousavy** [comment]
If you create a new project and install react-native-worklets-core, it works perfectly.

The issue is because of your local cache, as that apparently does not rebuild when you modify the library. 

To fix this, we need a way to clean or invalidate that buildcache in react-native-worklet-core's `build.gradle`, but I haven't played around with this yet.

If you wanna give this a go, we'd really appreciate a PR @deadbeefv!
