### ISSUE TITLE
💭 Where exactly the flag for QR code scanning need to be set?

### ISSUE THREAD

**Issue by balazsgerlei** [cuvent/react-native-vision-camera#2500]
### Question

The [guide ](https://react-native-vision-camera.com/docs/guides/code-scanning) says now you need to set the flag `VisionCamera_enableCodeScanner=true` in `build.gradle` on Android, but which `build.gradle`? The _project root_ or inside the _app module_? Furthermore, where exactly this flag should be set inside the gradle script?

Is it inside this in the `build.gradle` in the root of the project e.g.:
```
buildscript {
    ext {
        VisionCamera_enableCodeScanner=true
        ...
    }
}
```

If yes, please add a clear example, like above.

While we are at it, is the previous method (before 3.7.0 - declaring a dependency in the Manifest) no longer needed? If it is needed still for older versions, could you state this in the docs (e.g. from 3.7.0 the new method with the flag, before the Manifest addition).

Also if you would consider updating the example app with how to do this, it would be awesome!

Thank you for your kind consideration!

### VisionCamera Version

3.8.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
> The [guide ](https://react-native-vision-camera.com/docs/guides/code-scanning)says now you need to set the flag VisionCamera_enableCodeScanner=true in build.gradle on Android, but which build.gradle?

The guide you linked says `gradle.properties` file. Not `build.gradle`.

![Screenshot 2024-02-02 at 10 43 48](https://github.com/mrousavy/react-native-vision-camera/assets/15199031/c188ab7e-9d9d-4791-a2a4-e9698723d3e0)

> Also if you would consider updating the example app with how to do this, it would be awesome!

It is already updated. Just take a look at the `example/` app here in this repo. https://github.com/mrousavy/react-native-vision-camera/blob/97168c647c4fc8cd48c9989e6d6ef70ac65d88b4/package/example/android/gradle.properties#L44-L45

**Comment by balazsgerlei** [comment]
Ah okay, I misread it somehow, thank you for your fast repsonse!

**Comment by balazsgerlei** [comment]
And the Manifest addition is no longer needed, right?

**Comment by mrousavy** [comment]
No, no longer needed.
