### ISSUE TITLE
🔧 Build Fail after adding frame processor 

### ISSUE THREAD

**Issue by shivlisyn** [cuvent/react-native-vision-camera#2508]
### How were you trying to build the app?

I am using react-native-vision-camera
after adding "react-native-worklets-core": "^0.3.0" build fails in android and ios both

### Full build logs

```tsx
Execution failed for task ':react-native-vision-camera:buildCMakeDebug[arm64-v8a]
```

### Project dependencies

```json
"dependencies": {
"react-native": "0.72.7",
"react-native-vision-camera": "3.8.2",
"react-native-worklets-core": "^0.3.0"
}
```

### VisionCamera Version

3.8.2

### Target platforms

Android

### Operating system

MacOS

### Can you build the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by Bashar-Alziq** [comment]
Set minSdkVersion to 26 or higher in /android/build.gradle

**Comment by mrousavy** [comment]
![Screenshot 2024-02-05 at 12 37 58](https://github.com/mrousavy/react-native-vision-camera/assets/15199031/f9f4912f-60cd-4dfc-89f7-d2fae3c1d4c3)

Those are not full build logs at all.

**Comment by Bashar-Alziq** [comment]
https://react-native-vision-camera.com/docs/guides/troubleshooting
