### ISSUE TITLE
🐛 useCameraFormat and native code disagree on maxFps

### ISSUE THREAD

**Issue by ukk000** [cuvent/react-native-vision-camera#2529]
### What's happening?

On an iPhone SE 2nd Gen, using the example app, vision camera seems to return a format with a maxFps of 60. However, the native code throws an error.

`format`, as selected by the example app:
` LOG  {
  "minFps": 3,
  "videoWidth": 3840,
  "minISO": 22,
  "photoHeight": 2160,
  "maxFps": 60,
  "fieldOfView": 65.70668029785156,
  "videoHeight": 2160,
  "autoFocusSystem": "phase-detection",
  "supportsVideoHdr": false,
  "supportsPhotoHdr": false,
  "photoWidth": 3840,
  "supportsDepthCapture": false,
  "maxISO": 880,
  "pixelFormats": [
    "yuv",
    "yuv",
    "rgb"
  ],
  "maxZoom": 129.125,
  "videoStabilizationModes": [
    "auto",
    "cinematic",
    "off",
    "standard"
  ]
}`

### Reproduceable Code

```tsx
Reproduceable with the example app.
```

### Relevant log output

```shell
VisionCamera.onError(_:): Invoking onError(): The given format cannot run at 60 FPS! Make sure your FPS is lower than `format.maxFps` but higher than `format.minFps`.
```

### Camera Device

```json
{
  "isMultiCam": false,
  "formats": [],
  "minZoom": 1,
  "maxZoom": 16,
  "id": "com.apple.avfoundation.avcapturedevice.built-in_video:0",
  "name": "Back Camera",
  "hasFlash": true,
  "minExposure": -8,
  "minFocusDistance": 10,
  "sensorOrientation": "landscape-right",
  "hardwareLevel": "full",
  "position": "back",
  "supportsFocus": true,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsRawCapture": false,
  "supportsLowLightBoost": false,
  "maxExposure": 8,
  "hasTorch": true
}
```

### Device

iPhone SE 2nd Gen (iOS 17.3)

### VisionCamera Version

3.8.2, 3.9.0-beta.3

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
I'm commenting this on pretty much every issue now: Why does everyone simply ignore the logs?

What you put there is not a log, it is an error. I need to see the logs to see what format got selected, if it got applied, etc.

If you choose to ignore giving me that information I cannot help you.
