### ISSUE TITLE
🐛  The camera preview continues to distort with version 3.9.0-beta.2

### ISSUE THREAD

**Issue by correafederico25** [cuvent/react-native-vision-camera#2530]
### What's happening?

I am using version **3.9.0-beta.2** in my project where the distortion issue of the camera preview on Android was fixed, but I am still experiencing this problem, only in a different way. Before, the camera would stretch vertically, now something similar happens but horizontally. I am using React native CLI

**Photo from my app using react native vision camera:**

![Screenshot_20240208-123014](https://github.com/mrousavy/react-native-vision-camera/assets/53522327/bc960449-d25b-46c7-a8d6-b45dd265d883)

**Photo in normal conditions**

![Screenshot_20240208-123024](https://github.com/mrousavy/react-native-vision-camera/assets/53522327/b949e9e0-efce-4d06-8e1e-b7fdcb59e124)

**If I add the property resizeMode="contain", this happens:**

![Screenshot_20240208-125627-519](https://github.com/mrousavy/react-native-vision-camera/assets/53522327/9a231008-ca07-4473-ba35-397cdadb9f67)

I also noticed that when I make a change in my code and my application refreshes due to the automatic hot reload, the camera preview fixes itself and seems to work fine. (This only happens if the hot reload is triggered by a change in the code.)

### Reproduceable Code

```tsx
import React, { useEffect, useRef } from 'react';
import { StyleSheet } from 'react-native';
import {
  Camera as CameraVision,
  useCameraDevice,
  useCameraPermission,
} from 'react-native-vision-camera';

type CameraProps = {
  isActive: boolean;
};

const Camera: React.FC<CameraProps> = ({ isActive }) => {
  const cameraRef = useRef<CameraVision>(null);
  const device = useCameraDevice('back');
  const { hasPermission, requestPermission } = useCameraPermission();

  useEffect(() => {
    (async () => {
      if (!hasPermission) {
        await requestPermission();
      }
    })();
  }, []);

  if (!device) {
    return null;
  }

  if (!isActive) {
    return null;
  }

  return (
    <CameraVision
      ref={cameraRef}
      style={StyleSheet.absoluteFill}
      device={device}
      isActive={isActive}
      photo={true}
    />
  );
};

export default Camera;
```

### Relevant log output

```shell
No
```

### Camera Device

```json
{
  "formats": [],
  "sensorOrientation": "landscape-right",
  "hardwareLevel": "full",
  "maxZoom": 8,
  "minZoom": 1,
  "maxExposure": 12,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": true,
  "isMultiCam": false,
  "minFocusDistance": 10,
  "minExposure": -12,
  "name": "BACK (0)",
  "hasFlash": true,
  "hasTorch": true,
  "position": "back",
  "id": "0"
}
```

### Device

Motorola One Fusion (Android 11)

### VisionCamera Version

3.9.0-beta.2

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by tomerh2001** [comment]
+1

**Comment by mrousavy** [comment]
![Screenshot 2024-02-08 at 18 51 18](https://github.com/mrousavy/react-native-vision-camera/assets/15199031/ea508e4d-113f-452f-8757-31856db9566c)

Can't help you without logs.

**Comment by aazcast** [comment]
If logs are necessary, you should ask for them instead of closing the issue. i am also having the issue. i will move to another lib.

**Comment by mrousavy** [comment]
> If logs are necessary, you should ask for them instead of closing the issue. 

This is what you see when you create the issue: 

![image](https://github.com/mrousavy/react-native-vision-camera/assets/15199031/263b7f7d-bfcc-4840-a6d9-a9218deb4012)

Here I am asking for logs, and even telling you how to obtain them. I even gave an example how those logs look like on Android.

**Comment by mrousavy** [comment]
@correafederico25 as a test, could you try reversing this division: https://github.com/mrousavy/react-native-vision-camera/blob/919e6c9fe833f7d581442c5b2cac59a4b2bd598b/package/android/src/main/java/com/mrousavy/camera/core/PreviewView.kt#L76

So just swap width and height, and see if that changes anything.

If that works, I know what the issue is and we can re-open. 

If that does not work, I need the logs as I just said, and we can re-open if you add logs.

**Comment by matoakley** [comment]
@mrousavy I have been experiencing this issue too. Thanks for the suggestion above. Just to confirm that reversing the division resolved the problem for me on Android.

Making the recommended change doesn't seem to break anything on iOS.

Thanks for all your hard work on this great library, it's really appreciated!

**Comment by mrousavy** [comment]
Hey! I just released a new V4 beta ([v4.0.0-beta.7](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v4.0.0-beta.7)) where I fixed a bunch of issues! 💪🚀 Can you test that and see if that fixes the issue for you? 😅 

```
yarn add react-native-vision-camera@beta
```

You might need to increase the `compileSdk` to the newest Android SDK (34) if you are behind.

**Comment by matoakley** [comment]
`beta` build works perfectly on both Android and iOS. Thanks!

**Comment by mrousavy** [comment]
Thanks, great to hear that V4 now works perfectly! If you appreciate my work, please consider [💖 sponsoring me on GitHub 💖](http://github.com/sponsors/mrousavy/) so I can keep maintaining this library, fixing bugs and building new features! :)
