### ISSUE TITLE
🐛 ANDROID: 3.9.0-beta.3 stop recording with flash -  app shutdown

### ISSUE THREAD

**Issue by MilanRadon** [cuvent/react-native-vision-camera#2533]
### What's happening?

![Screenshot_2024-02-09-14-42-36-592_com miui bugreport](https://github.com/mrousavy/react-native-vision-camera/assets/1999282/4fc7e368-f852-4012-a2a9-8c242cf60089)
![Screenshot_2024-02-09-14-57-03-481_com video camerasafezones app](https://github.com/mrousavy/react-native-vision-camera/assets/1999282/0d26875b-e78e-4d96-8a4e-be58a8d9c29e)

### Reproduceable Code

```tsx
demo app
```

### Relevant log output

```shell
nothing
```

### Camera Device

```json
nothing
```

### Device

android 13

### VisionCamera Version

3.9.0-beta.3 

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [X] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by MilanRadon** [comment]
maybe is problem on ios..but i dont know..

**Comment by mrousavy** [comment]
![Screenshot 2024-02-13 at 13 56 24](https://github.com/mrousavy/react-native-vision-camera/assets/15199031/e2fb52ab-1c89-4897-86f6-bdcc2f825904)

Author did not post required information, closing issue.

**Comment by mrousavy** [comment]
Created a PR for this anyways sicne I know how to fix it: https://github.com/mrousavy/react-native-vision-camera/pull/2548
