### ISSUE TITLE
💭 Correct way to chain frame processors?

### ISSUE THREAD

**Issue by jslok** [cuvent/react-native-vision-camera#2570]
### Question

I have the output from rn-fast-tflite. What is the correct way to send the data to the next (custom) frame processor? If I do the below, it causes a 4+ second delay even without any code in the filterDetections plugin. If I try to send 'output' from tflite directly I get an unsupported type error.

### What I tried

```
export function filterDetections(frame: Frame, data) {
  'worklet'
  if (plugin == null) {
    throw new Error('Failed to load Frame Processor Plugin!')
  }
  return plugin.call(frame, data)
}
```

```
  const frameProcessor = useFrameProcessor(
    (frame) => {
      'worklet'
      if (model.state !== 'loaded') {
        return
      }
        const resized = resize(frame, {
          scale: {
            width: inputSize,
            height: inputSize,
          },
          pixelFormat: 'rgb',
          dataType: dataType,
        })
        const output = model.model.runSync([resized])

        const filteredDetections = filterDetections(frame, { boxes: output[1], masks: output[2] })
    },
    [model]
  )
  ```

### VisionCamera Version

beta 6

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
You could parallelize it using [`runAsync`](https://react-native-vision-camera.com/docs/api/#runasync)
