### ISSUE TITLE
🐛 [VisionCamera] react-native-worklets-core not found, Frame Processors disabled!

### ISSUE THREAD

**Issue by ABogdanovas** [cuvent/react-native-vision-camera#2580]
### What's happening?

After running `pod install` Vision camera cannot find react-native-worklets-core. I had installed react-native-worklets-core@0.3.0 and added `['react-native-worklets-core/plugin'],` into babel.config.js 

### Reproduceable Code

```tsx
-
```

### Relevant log output

```shell
[VisionCamera] node modules found at /Users/aleksandrbogdanov/Desktop/git/alcs/4.Implementation/alcs/java/alcs-react/react-app/node_modules/.pnpm/react-native@0.73.4_@babel+core@7.23.9_@babel+preset-env@7.23.9_react@18.2.0/node_modules/react-native/..
[VisionCamera] react-native-worklets-core not found, Frame Processors disabled!
Auto-linking React Native modules for target `driverapp`: RNBootSplash, RNFileViewer, RNGestureHandler, RNPermissions, RNReanimated, RNSVG, RNScreens, ReactNativeAvoidSoftinput, VisionCamera, VisionCameraOcr, VisionCameraV3BarcodeScanner, react-native-blob-util, react-native-document-picker, react-native-encrypted-storage, react-native-flipper, react-native-geolocation, react-native-im
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
[Codegen] generating an empty RCTThirdPartyFabricComponentsProvider
Analyzing dependencies
[Codegen] Found FBReactNativeSpec
[Codegen] Found rncore
[VisionCamera] node modules found at /Users/aleksandrbogdanov/Desktop/git/alcs/4.Implementation/alcs/java/alcs-react/react-app/node_modules/.pnpm/react-native@0.73.4_@babel+core@7.23.9_@babel+preset-env@7.23.9_react@18.2.0/node_modules/react-native/..
[VisionCamera] react-native-worklets-core not found, Frame Processors disabled!
Downloading dependencies
Generating Pods project
Setting USE_HERMES build settings
Setting REACT_NATIVE build settings
Setting CLANG_CXX_LANGUAGE_STANDARD to c++20 on /Users/aleksandrbogdanov/Desktop/git/alcs/4.Implementation/alcs/java/alcs-react/react-app/apps/driver/ios/driverapp.xcodeproj
Pod install took 30 [s] to run
Integrating client project
Pod installation complete! There are 101 dependencies from the Podfile and 108 total pods installed.```


### Camera Device

```json
-
```

### Device

-

### VisionCamera Version

3.9.0

### Can you reproduce this issue in the VisionCamera Example app?

No, I cannot reproduce the issue in the Example app

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
1. You created a bug report, not a build error. This is the wrong template, I'm closing this issue - please create a new one with the correct template.
2. The first line in your logs is:
    ```
    [VisionCamera] node modules found at /Users/aleksandrbogdanov/Desktop/git/alcs/4.Implementation/alcs/java/alcs-react/react-app/node_modules/.pnpm/react-native@0.73.4_@babel+core@7.23.9_@babel+preset-env@7.23.9_react@18.2.0/node_modules/react-native/..
    ```
    apparently something went (terribly) wrong when trying to find your node_modules path, where is your project located?
