### ISSUE TITLE
🐛 Preview stretch in Android landscape mode,Incorrect orientation in IOS  landscape mode.

### ISSUE THREAD

**Issue by boiboif** [cuvent/react-native-vision-camera#2584]
### What's happening?

Preview stretch in Android landscape mode, Normal in portrait mode.
![image](https://github.com/mrousavy/react-native-vision-camera/assets/58927554/f9c2d65b-058a-402a-9462-ac0195dd8142)

Incorrect orientation in IOS  landscape mode. No stretching issues.
![image](https://github.com/mrousavy/react-native-vision-camera/assets/58927554/ac11cf45-76ce-4221-9437-e5d15e0ad256)

### Reproduceable Code

```tsx
in AndroidManifest.xml
android:screenOrientation="landscape"

in Info.plist
<key>UISupportedInterfaceOrientations</key>
<array>
<string>UIInterfaceOrientationLandscapeRight</string>
</array>


/****************/

const [hasPermission, setHasPermission] = React.useState(false);
const camera = React.useRef<Camera>(null);
const device = useCameraDevice('back');

 React.useEffect(() => {
    (async () => {
      const status = await Camera.requestCameraPermission();
      if (status === 'denied') {
        return navigation.goBack();
      }
      setHasPermission(status === 'granted');
    })();
  }, [navigation]);

return device != null && hasPermission ? 
 <Camera
    orientation="landscape-right"
    ref={camera}
    style={StyleSheet.absoluteFill}
    device={device}
    isActive={true}
    photo
/> : null
```

### Relevant log output

```shell
-
```

### Camera Device

```json
{
  "formats": [],
  "sensorOrientation": "landscape-left",
  "hardwareLevel": "full",
  "maxZoom": 10,
  "minZoom": 1,
  "maxExposure": 24,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": true,
  "isMultiCam": false,
  "minFocusDistance": 10,
  "minExposure": -24,
  "name": "BACK (0)",
  "hasFlash": true,
  "hasTorch": true,
  "position": "back",
  "id": "0"
}
```

### Device

Redmi k50

### VisionCamera Version

3.9.0

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
As mentioned in the first pinned issue, Orientation is not yet supported and work in progress. https://github.com/mrousavy/react-native-vision-camera/issues/1891
