### ISSUE TITLE
✨ Is it possible to display the front and back cameras at the same time

### ISSUE THREAD

**Issue by Dablu77** [cuvent/react-native-vision-camera#2598]
### What feature or enhancement are you suggesting?

Displaying both the front and back cameras simultaneously in a React Native application is technically feasible, but it's not straightforward using the react-native-camera library alone. The library is designed to handle a single camera instance at a time.

### What Platforms whould this feature/enhancement affect?

Android

### Alternatives/Workarounds

Is it possible to display the front and back cameras at the same time

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by bglgwyng** [comment]
I haven't tried it before, but could you try just rendering two `Camera` components at the same time?

**Comment by mrousavy** [comment]
_Might_ work on Android, will not work on iOS.
This would require a lot of effort, but we actually built something like this before at Margelo. The Capture Session is a multi-cam session then.

**Comment by baatten** [comment]
Can we record from both? I mean without displaying it?

**Comment by Schabaani** [comment]
> I haven't tried it before, but could you try just rendering two `Camera` components at the same time?

It didn't work. It only shows the last camera. Maybe because  the library is designed to handle a single camera instance at a time.

**Comment by mrousavy** [comment]
No, in V5 I specifically redesigned the whole architecture to also allow multi camera support.

To do this, you have to use the hooks or imperative API yourself and render two `<NativePreviewView />` yourself, each with separate preview outputs and separate photo/video/frame outputs per device.

See https://visioncamera.margelo.com/docs/multi-camera
