### ISSUE TITLE
💭  How can I access iOS TrueDepth Camera?

### ISSUE THREAD

**Issue by giannavia** [cuvent/react-native-vision-camera#2605]
### Question

I've got an iphone 14 and I trying to use TrueDepth Camera to check how an object is. 

Probably this is the wrong approach but this is what I did:

1. I called useCameraDevices() and got a list of devices.
2. Filtered out deviced which "isMultiCam" is false 
3. The list devices ends up with a single element
4. I picked a format which "supportsDepthCapture" is true

This is what my camera element looks like:

<Camera
        style={{ width: '100%', aspectRatio: 16 / 9 }}
        device={trueDepthCamera}
        format={trueDepthCameraFormat}
        isActive={isCameraActive && isFocused}
        enableDepthData={true}
        ref={camera}
/>

However, I can't find any depth data. I've added a Frame Processor Plugin as well and still couldn't see any depth data.

Can you guys help me here ?

### VisionCamera Version

"react-native-vision-camera": "^3.9.0",

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
See this feature request: https://github.com/mrousavy/react-native-vision-camera/issues/2628
