### ISSUE TITLE
Programmatically deactivate codeScanner🐛 

### ISSUE THREAD

**Issue by mzeba** [cuvent/react-native-vision-camera#2611]
### What's happening?

When I try to disable the bare code scanner (by assigning *undefined* to the *codeScanner* props, I get this error: `Error while updating property 'codeScannerOptions' of a view managed by: CameraView. ... Parameter specified as non null is null: method com.mrousavy.camera.CameraViewManager.setCodeScanner, parameter codeScannerOptions.`

### Reproduceable Code

```tsx
<Camera
              style={StyleSheet.absoluteFill}
              device={device}
              isActive={isFocused && appState === "active"}
              ref={camera}
              codeScanner={enableBarreCodeScanner ? codeScanner : undefined}
              enableZoomGesture={true}
              animatedProps={animatedProps}
              torch={enableFlash && supportsFlash ? "on" : "off"}
              focusable={device?.supportsFocus}
              fps={fps}
              format={format}
              lowLightBoost={device.supportsLowLightBoost && enableNightMode}
              exposure={0}
              enableFpsGraph={true}
              onStarted={() => "Camera started!"}
              onStopped={() => "Camera stopped!"}
              onInitialized={onInitialized}
              onError={onError}
              orientation="portrait"
              photoHdr={supportsHdr && enableHdr}
              photo={true}
              enableHighQualityPhotos={true}
            />
```

### Relevant log output

```shell
Error while updating property 'codeScannerOptions' of a view managed by: CameraView. ... Parameter specified as non null is null: method com.mrousavy.camera.CameraViewManager.setCodeScanner, parameter codeScannerOptions

No log in the terminal.
```

### Camera Device

```json
{
  "formats": [],
  "sensorOrientation": "landscape-right",
  "hardwareLevel": "limited",
  "maxZoom": 4,
  "minZoom": 1,
  "maxExposure": 20,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": false,
  "isMultiCam": false,
  "minFocusDistance": 5,
  "minExposure": -20,
  "name": "BACK (0)",
  "hasFlash": true,
  "hasTorch": true,
  "position": "back",
  "id": "0"
}
```

### Device

Samsung A32

### VisionCamera Version

3.8.2

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
This has been fixed in 3.9.0 via https://github.com/mrousavy/react-native-vision-camera/commit/bda43d39846f2a874233e8882f133c4be417ef36.
