### ISSUE TITLE
💭 Android: Avoiding crashes caused by reading codes after camera closed, or avoid repeating paused code reading requests

### ISSUE THREAD

**Issue by paulwellnerbou** [cuvent/react-native-vision-camera#2655]
### Question

When setting the camera inActive after reading a QR code, and activating it after that later (without any QR code visible), there seem to be events triggered, still from the last read QR code.

How can I avoid this?

### What I tried

We are trying to implement a simple QR code reader in our Android app:

* User taps on QR icon
* Camera opens fullscreen
* If a QR code is read, an overlay button will appear in the middle (the camera is still on and reading)

This did not work for us, as the app crashed constantly because of something trying to read images from the already closed camera.

So we implemented a next step:

* If a QR code is read, the overlay button appears, and the camera stops (isActive=false)
* the overlay can be closed by the user, which will cause the camera to activate again to read QR codes

No, we don't have any crashes any more. But there seem to be code reading requests in the "queue" (or where ever) that are replayed when re-enabling the camera.

Once the overlay is closed, it shows up again instantly, `codeScanner.onCodeScanned` is executed, even if there is no QR code visible.

In the logs I could see following lines, between our logs (and no QR code is visible):

```
ReactNativeJS                 D  closeOverlay
ReactNativeJS                 D  'codeScanningResult', null
CameraView                    I  Updating CameraSession...
CameraSession                 I  configure { ... }: Waiting for lock...
CameraSession                 I  configure { ... }: Updating CameraSession Configuration... Difference(deviceChanged=false, outputsChanged=false, sidePropsChanged=false, isActiveChanged=true)
PersistentCamerCaptureSession D  --> setIsActive(true)
PersistentCamerCaptureSession D  Configure() with isActive: true, ID: 0, device: android.hardware.camera2.impl.CameraDeviceImpl@6c2742c, session: android.hardware.camera2.impl.CameraCaptureSessionImpl@361405c
PersistentCamerCaptureSession D  Updating repeating request...
PersistentCamerCaptureSession D  Configure() done! isActive: true, ID: 0, device: android.hardware.camera2.impl.CameraDeviceImpl@6c2742c, session: android.hardware.camera2.impl.CameraCaptureSessionImpl@361405c
CameraSession                 I  configure { ... }: Completed CameraSession Configuration! (isActive: true, isRunning: true)
CameraView                    I  invokeOnStarted()
ReactNativeJS                 D  'onCodeScanned', [ { frame: { width: 221, y: 23, height: 212, x: 300 }, ...
```

What does `PersistentCamerCaptureSession D  Updating repeating request...` mean?

Can I somehow clean the "queue"?

Thanks!

### VisionCamera Version

3.9.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey - I think this issue has been fixed in [VisionCamera 4.0.0](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v4.0.0). 🥳 

Please try V4 and let me know if you still experience this issue;
- if not, please consider [💖 **sponsoring me on GitHub** 💖](https://github.com/sponsors/mrousavy/) to support the development of VisionCamera and thank me for my time spent on fixing bugs and building new features.
- if you still see this issue, please comment and we can re-open this. But please update your native logs with the native (Xcode/Android Studio) logs from running VisionCamera V4 so I can investigate this.
