### ISSUE TITLE
Blur a region of the camera💭 

### ISSUE THREAD

**Issue by mzeba** [cuvent/react-native-vision-camera#2662]
### Question

Any idea for blurring an area of the camera?. I'm working on an OCR and would like part of the camera not to be extractable.

### VisionCamera Version

3.9.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by xulihang** [comment]
I think you can write your own frame processor to crop the frame or use this plugin to crop the frame as base64: https://github.com/tony-xlh/vision-camera-cropper

**Comment by mzeba** [comment]
Thank you
