### ISSUE TITLE
💭Not supported in Expo Go!

### ISSUE THREAD

**Issue by fneufken** [cuvent/react-native-vision-camera#2670]
### Question

I want to use vision camera to capture frames and run inference on them using Tensorflow Movenet on an Android tablet. To do this, I am using Expo Go to get the application on the tablet. However when starting the application, I get the following error: 

 ERROR  system/camera-module-not-found: react-native-vision-camera is not supported in Expo Go! Use EAS/expo prebuild instead (`expo run:android`). For more info, see https://docs.expo.dev/workflow/prebuild/., js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

### What I tried

I followed all the steps in the "Getting started" guide. I am currently working with expo@50.0.13 and react native version 0.73.5. There is nothing to find online on how to fix this. Hopefully you can help me!

### VisionCamera Version

3.9.1

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by jkaufman** [comment]
I would not expect React Native Vision Camera to work in Expo Go as it depends on native code.

**Comment by jonjamz** [comment]
You need to use development builds instead of Expo Go.

https://docs.expo.dev/develop/development-builds/introduction/

**Comment by mrousavy** [comment]
Exactly what @jkaufman and @jonjamz said.

**Comment by ganeshmohane** [comment]
for detecting face, expo-face-detector i was using it but now it says it is depreacated and tellling to use react native vision camera but it is not supported in expo so i dont know what to do, is there other solution to detect face in expo app

**Comment by mrousavy** [comment]
@ganeshmohane please read the above comments before posting.

**Comment by dlogvin** [comment]
> @ganeshmohane please read the above comments before posting.

Hey! I basically am getting the same error message on a development build. 

It's very odd.

**Comment by flikQ** [comment]
Only 'solution' i've found so I can continue working with Expo Go/Dev without interruption is to add the following to your top file, usually App.xxx, to suppress the error, still annoyingly appears in debugger etc tho.

`LogBox.ignoreLogs(['react-native-vision-camera is not supported in Expo Go!']);`

**Comment by ganeshmohane** [comment]
> @ganeshmohane please read the above comments before posting.

yes

**Comment by ganeshmohane** [comment]
> Only 'solution' i've found so I can continue working with Expo Go/Dev without interruption is to add the following to your top file, usually App.xxx, to suppress the error, still annoyingly appears in debugger etc tho.
> 
> `LogBox.ignoreLogs(['react-native-vision-camera is not supported in Expo Go!']);`

is it working then?
are u able to use react native vision camera with expo?

**Comment by ganeshmohane** [comment]
for face detection i am sending image to server and using deepface detecting face, it is not that good but works perfectly!!
