### ISSUE TITLE
💭 UI on qrcode scanner

### ISSUE THREAD

**Issue by tanzeel152** [cuvent/react-native-vision-camera#2674]
### Question

is there any way to draw on UI on camera like box container for qrcode scanner 

### VisionCamera Version

"react-native-vision-camera": "^3.9.0"

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.
cannot see any ui on camera 

`<SafeAreaView style={[styles.container]}>
      <View style={styles.mainContainter}>
        <TouchableOpacity onPress={closeModalAndNavigateToContacts}>
          <Text>X</Text>
        </TouchableOpacity>
      </View>
      {/* {modalVisible1 && ( */}
      <Camera
        device={device}
        isActive={modalVisible1}
        // style={styles.camera}
        // format={format}
        codeScanner={codeScanner}
        // Add frameProcessor and other props as needed
        onInitialized={() => doHack(1)}
        style={[
          StyleSheet.absoluteFill,
          {width: Dimensions.get('screen').width + hack}
        ]}>
        <View style={styles.overlay}>
          <View style={{borderRadius: 10, backgroundColor: 'white'}}>
            <Text style={styles.instructionText}>
              Point at a paper card, then tap the button below
            </Text>
          </View>
          <View style={styles.cardOutline} />
          <View
            style={{
              justifyContent: 'space-between',
              width: '100%',
              flexDirection: 'row',
              paddingHorizontal: 20
            }}></View>
        </View>
      </Camera>
     </SafeAreaView>`

**Comment by mrousavy** [comment]
VisionCamera V4 now has Skia Frame Processors! :)
