### ISSUE TITLE
💭 Aspect Ratio not work as expected?

### ISSUE THREAD

**Issue by jasonvnit** [cuvent/react-native-vision-camera#2677]
### Question

How can i take photo or record video with square aspect ratio or specfic aspect ratio? I used photoAspectRatio, videoAspectRatio as 1 but not work. Thanks

### VisionCamera Version

react-native-vision-camera

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Read the Formats documentation.
