### ISSUE TITLE
Android Exposure 💭 

### ISSUE THREAD

**Issue by wuvinotre** [cuvent/react-native-vision-camera#2679]
### Question

I created a slider with dynamic values between -2 and 2 to see the best exposure values 
On iOS it worked well, but on android there was no difference.

Are there any android-specific settings for the values of the exposure?

### What I tried

this is my code

```
const [exposure, setExposure] = useState(0.1);

return (
   <View style={styles.containerCamera}>
        <Camera
          ref={camera}
          style={styles.camera}
          isActive={true}
          device={device}
          video={true}
          torch={"on"}
          format={format}
          exposure={exposure}
          zoom={zoom}
          focusable={true}
          photo={true}
          enableHighQualityPhotos={true}
          fps={30}
          pixelFormat="native"
        />
        <View style={styles.sliderContainer}>
          <Slider
            maximumValue={2}
            minimumValue={-2}
            value={exposure}
            onValueChange={setExposure}
            step={0.1}
          />
        </View>
   </View>
)
```

### VisionCamera Version

3.8.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by predofrazao** [comment]
Did you solve this? I'm having a similar problem only on Android devices...

**Comment by wuvinotre** [comment]
Aoba @predofrazao, sim..
Os exposures no android são diferentes e bem variantes já que o range depende da fabricante do modelo.

Você pode fazer:
```
const device = useCameraDevice("back");
const maxExposure = device?.maxExposure; 
const minExposure = device?.minExposure;
```
Com esses valores já é possível colocar minimumVallue/maximumValue no slider (ou em algum outro component).

**Comment by predofrazao** [comment]
Oopa! Hmm... o problema que estou tendo aqui é um pouco diferente, o exposure não aumenta, apenas diminui.

**Comment by wuvinotre** [comment]
Consegue me mandar um exemplo do teu código no discord? meu nick é _vuinishiusu
