### ISSUE TITLE
Hi Im using react-native:0.73.6 after capturing photo or video if I try to close the view I have: FATAL EXCEPTION: mrousavy/VisionCamera.main 💭 

### ISSUE THREAD

**Issue by Mohamed-Ziyad** [cuvent/react-native-vision-camera#2696]
### Question

this is the error thrown from android logcat
![Screenshot 1445-09-16 at 14 30 44](https://github.com/mrousavy/react-native-vision-camera/assets/48976332/7664c772-2cdc-493c-b428-96eb3c56b90e)

do you have a patch for this? 

### VisionCamera Version

3.9.1

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Enable `photo={true}`.

**Comment by mrousavy** [comment]
Or `video={true}`
