### ISSUE TITLE
🐛 Error on iOS device while running the react-native-vision-camera example

### ISSUE THREAD

**Issue by erssykes** [cuvent/react-native-vision-camera#2697]
### What's happening?

I'm trying to run the react-native-vision-camera stock [example](https://github.com/mrousavy/react-native-vision-camera/tree/main/package/example),  It compiles and when I launch the app (iOS) through Xcode, and connected device, I get 
''' 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCapturePhotoOutput capturePhotoWithSettings:delegate:] settings.photoQualityPrioritization must not be higher than self.maxPhotoQualityPrioritization'
*** First throw call stack:
(0x19160a678 0x18990bc80 0x1add7b598 0x100e19d6c 0x100e0b434 0x104530f50 0x104532b34 0x10453a98c 0x10453b728 0x1045485f8 0x104547c2c 0x1fb4a7964 0x1fb4a7a04)
libc++abi: terminating due to uncaught exception of type NSException
'''

It seems to be coming from: 

'''
func takePhoto(options: NSDictionary, promise: Promise),  in CameraSession+Photo.swift

line 49:  photoSettings.photoQualityPrioritization = .quality

### Reproduceable Code

```tsx
it is the [example](https://github.com/mrousavy/react-native-vision-camera/tree/main/package/example)
```

### Relevant log output

```shell
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCapturePhotoOutput capturePhotoWithSettings:delegate:] settings.photoQualityPrioritization must not be higher than self.maxPhotoQualityPrioritization'
*** First throw call stack:
(0x19160a678 0x18990bc80 0x1add7b598 0x100e19d6c 0x100e0b434 0x104530f50 0x104532b34 0x10453a98c 0x10453b728 0x1045485f8 0x104547c2c 0x1fb4a7964 0x1fb4a7a04)
libc++abi: terminating due to uncaught exception of type NSException
```

### Camera Device

```json
iPad; iPhone;  same error for all devices
```

### Device

iPad Pro (3rd generation)

### VisionCamera Version

3.9.1

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Can you try running the example on the `v4` branch?

**Comment by erssykes** [comment]
Thanks; that worked
