### ISSUE TITLE
`VisionCamera` does not specify a Swift version and none of the targets (`foobar`) integrating it have the `SWIFT_VERSION` attribute set

### ISSUE THREAD

**Issue by marceloch2** [cuvent/react-native-vision-camera#2700]
### How were you trying to build the app?

Trying to pod install

### Full build logs

```tsx
`VisionCamera` does not specify a Swift version and none of the targets (`foobar`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.🔧
```

### Project dependencies

```json
"react-native": "0.73.6"
"react-native-vision-camera": "3.9.2"
"pod version = 1.14.0"
"ruby 3.2.2"
"node 20.11.0"
```

### VisionCamera Version

3.9.2

### Target platforms

iOS

### Operating system

MacOS

### Can you build the VisionCamera Example app?

Manage to build it, after some tweaks.

### Additional information

- [ ] I am using Expo
- [X ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

I have tried several things, ENV['SWIFT_VERSION'] = '5.2' inside pod file, using version 5.0, passing as env var command line to pod install, etc, etc.

I have the Swift empty file created as well, many of the answers online tell me to create it but for me, the error persists.

**Comment by mrousavy** [comment]
1. Add `ENV['SWIFT_VERSION'] = '5.2'` to your Podfile.
2. Update Xcode and your macOS version
3. Reboot your PC
4. Clean cache
5. pod install & rebuild the app
