### ISSUE TITLE
🐛 photoResolution: 'max' not the same as native camera photo.  

### ISSUE THREAD

**Issue by erssykes** [cuvent/react-native-vision-camera#2706]
### What's happening?

I wanted to take a picture using react-native-vision-camera that has the same resolution as the native device's camera app.
Currently, I have been experimenting with photoResolution: 'max' and was expecting to see the same resolution as the native camera.  
Currently, the react-native-vision-camera produces photos:  12MP, 3024x4032, whereas the device camera takes photos at 24MP, 4284 x 5712 (both are using the 'main camera').  I had thought the photoResolution: 'max' would force it to use the same high resolution as the native device's camera.  
Device is:  iPhone 15 max

Any insight on how to force it to use the maximum resolution available?

Thank you so much,

### Reproduceable Code

```tsx
const device = useCameraDevice('back');
const format = useCameraFormat(device, [
    { photoResolution: 'max'},  // use max resolution possible.
    { photoHdr: true }  // High Dynamic Range
]);

<Camera
        ref={camera}
        style={StyleSheet.absoluteFill}
        device={device!}
        format={format}
        enableHighQualityPhotos={true}  
        isActive={isActive}
        onTouchStart={handleFocus}
        enableZoomGesture
        photo
      />

const takePhoto = useCallback(async () => {
    const photo = await camera.current?.takePhoto({
      qualityPrioritization: 'quality',  
      flash: 'auto',
      enableShutterSound: true
    });
```

### Relevant log output

```shell
N/A
```

### Camera Device

```json
"id": "com.apple.avfoundation.avcapturedevice.built-in_video:0",
  "position": "back",
  "hardwareLevel": "full",
  "minFocusDistance": 20,
  "hasTorch": true,
  "sensorOrientation": "landscape-right",
  "supportsLowLightBoost": false,
  "maxExposure": 8,
  "maxZoom": 123.75,
  "supportsRawCapture": false,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsFocus": true,
  "neutralZoom": 1,
  "minZoom": 1,
  "isMultiCam": false,
  "formats": [],
  "hasFlash": true,
  "name": "Back Camera",
  "minExposure": -8
}
```

### Device

iPhone 15 pro max

### VisionCamera Version

3.9.2 (v4)

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [X] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
> 3.9.2 (v4)

Well, what is it? I'm assuming V4 then?

---

So I just ran this on my iPhone 15 Pro:

```ts
const f = useCameraFormat(device, [{ photoResolution: 'max' }])
console.log(JSON.stringify(f))
```

And I get 

```json
{
  "minISO": 55,
  "photoHeight": 6048,
  "fieldOfView": 71.28567504882812,
  "videoHeight": 3024,
  "autoFocusSystem": "phase-detection",
  "supportsVideoHdr": false,
  "pixelFormats": [
    "yuv",
    "yuv",
    "rgb",
    "unknown",
    "yuv",
    "unknown",
    "yuv",
    "unknown",
    "rgb"
  ],
  "videoStabilizationModes": [
    "auto",
    "off"
  ],
  "videoWidth": 4032,
  "minFps": 1,
  "supportsPhotoHdr": false,
  "photoWidth": 8064,
  "supportsDepthCapture": false,
  "maxISO": 12320,
  "maxFps": 30
}
```

..which is 8064x6048, the maximum available photo resolution.

I think the problem you're seeing is because you are using the wrong `device`, not all devices have the same formats. See the ["Camera Devices"](https://react-native-vision-camera.com/docs/guides/devices) documentation for more information.

Maybe you need to select the triple camera:

```ts
const device = useCameraDevice('back', {
  physicalDevices: ['ultra-wide-angle-camera', 'wide-angle-camera', 'telephoto-camera']
})
```

..as those devices use multiple devices to deliver photos that are stitched together - hence the higher resolution.

**Comment by erssykes** [comment]
hi, 

Thank you for your help.  So, I've experimented with the different physical devices ('ultra-wide-angle-camera', 'wide-angle-camera', 'telephoto-camera' and various multi-cam configurations.  Still can't seem to capture pictures that are of the same high-resolution as a native device's camera.  Here's a brief breakdown:  

Using an iPhone 15 pro max, the example app in 'react-native-vision-camera iOS example', the result is:   8MP, 2160x3840 
Using an iPhone 15 pro max, my react-native-vision-camera app and 
 const device = useCameraDevice('back', {
    physicalDevices: ['wide-angle-camera']
  });
the result is: 12MP, 3024 x 4032

Using an iPhone 15 pro max, my react-native-vision-camera app and 
 const device = useCameraDevice('back', {
    physicalDevices: ['ultra-wide-angle-camera', 'telephoto-camera']
  });
the result is: 12MP, 3024 x 4032

Using an iPhone 15 pro max, my react-native-vision-camera app and 
 const device = useCameraDevice('back', {
    physicalDevices: ['ultra-wide-angle-camera', 'wide-angle-camera', 'telephoto-camera']
  });
the result is:  12MP, 3024x4032

Using an iPhone 15 pro max, my react-native-vision-camera app and 
 const device = useCameraDevice('back', {
     physicalDevices: ['ultra-wide-angle-camera', 'wide-angle-camera']
  });
the result is:  12MP, 3024x4032

Using the iPhone 15 pro max's camera:
the result is: 24MP, 5712 x 4284

[The scene was exactly the same for all of the above picture taking]

So, the question is, how can I configure react-native-vision-camera to use the same high-resolution as the default camera (i.e, 24MP, 5712 x 4284)?

Thank you so much for your help

kind regards

**Comment by mrousavy** [comment]
I think the default Camera shoots ProRAW or HEIF or something where it can do higher resolution. VisionCamera doesn't have support for that yet (see https://github.com/mrousavy/react-native-vision-camera/issues/1851)

**Comment by erssykes** [comment]
Would you happen to know when "react-native-vision-camera" will support [RAW and Apple ProRAW Formats](https://developer.apple.com/documentation/avfoundation/photo_capture/capturing_photos_in_raw_and_apple_proraw_formats)?

**Comment by mrousavy** [comment]
As mentioned in the issue I linked, it is currently a feature request I'm raising money for (to fund the development) - I don't plan on developing this for free in my free time

**Comment by erssykes** [comment]
Could you explain how the process works, please?

**Comment by mrousavy** [comment]
People donate some funds, and once the pool is full I will implement it.

**Comment by erssykes** [comment]
how long does it generally take for the funds to reach the appropriate level?  how long will it take to implement the feature?  what if more funds are needed (ie., it is more complex than originally assessed)?

**Comment by mrousavy** [comment]
I don't know, I don't have a lot of experience with that.
But generally people don't like paying money for open source, so it's hard to raise funds.

If it takes longer, no more money will be requested, that's my risk.
