### ISSUE TITLE
💭 Place text on a frame

### ISSUE THREAD

**Issue by ma10as** [cuvent/react-native-vision-camera#2708]
### Question

Is it possible to place multiple texts on a frame like the example without `Skia`?
If yes how?
I have not managed to find a solution.
![fe4kuuhsgdaxjzfdvogg](https://github.com/mrousavy/react-native-vision-camera/assets/5831793/4b3ba168-a35f-4405-bdfc-ad9348f3f837)

### VisionCamera Version

3.9.1

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
No, Camera buffers are not simple images so "placing text onto them" is absolutely not trivial.


If you just want to do this for an Image **after capturing it**, you can simply load it into an offscreen Skia context, place the text there, and then re-save to a file.

For Preview (realtime) and Video, this is not yet supported as it requires setting up custom GPU drawing contexts, and a bunch of other magic to work.

We developed such solutions for multiple clients before at [Margelo](https://margelo.io), so if you want this developed for you, contact us :)
