### ISSUE TITLE
🔧 undefined symbols for architecture x86_64:   "_OBJC_CLASS_$_RCTFPSGraph"

### ISSUE THREAD

**Issue by AliRezaBeigy** [cuvent/react-native-vision-camera#2717]
### How were you trying to build the app?

I tried to build my app with react-native-vision-camera using the `yarn run ios --terminal zsh` command, and it failed.

### Full build logs

```tsx
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTFPSGraph", referenced from:
       in CameraView.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

ProcessInfoPlistFile /Users/arb/Library/Developer/Xcode/DerivedData/Challenger-codplphghcpvzucrnzvysqiwlihf/Build/Products/Debug-iphonesimulator/VisionCamera/VisionCamera.framework/Info.plist /Users/arb/WebstormProjects/app/ios/Pods/Target\ Support\ Files/VisionCamera/VisionCamera-Info.plist (in target 'VisionCamera' from project 'Pods')
    cd /Users/arb/WebstormProjects/app/ios/Pods
    builtin-infoPlistUtility /Users/arb/WebstormProjects/app/ios/Pods/Target\ Support\ Files/VisionCamera/VisionCamera-Info.plist -producttype com.apple.product-type.framework -expandbuildsettings -format binary -platform iphonesimulator -o /Users/arb/Library/Developer/Xcode/DerivedData/Challenger-codplphghcpvzucrnzvysqiwlihf/Build/Products/Debug-iphonesimulator/VisionCamera/VisionCamera.framework/Info.plist

...
** BUILD FAILED **


The following build commands failed:
        Ld /Users/arb/Library/Developer/Xcode/DerivedData/Challenger-codplphghcpvzucrnzvysqiwlihf/Build/Products/Debug-iphonesimulator/VisionCamera/VisionCamera.framework/VisionCamera normal (in target 'VisionCamera' from project 'Pods')
(1 failure)
```

### Project dependencies

```json
"dependencies": {
    "@react-native-firebase/app": "^19.1.2",
    "@react-native-firebase/crashlytics": "^19.1.2",
    "@react-native-firebase/messaging": "^19.1.2",
    "@react-native-picker/picker": "^2.7.2",
    "react-native": "0.73.6",
    "react-native-fs": "^2.20.0",
    "react-native-image-picker": "^7.1.2",
    "react-native-vision-camera": "^3.9.2",
...
  },
```

### VisionCamera Version

3.9.2"

### Target platforms

iOS

### Operating system

MacOS

### Can you build the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [x] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey - I think this issue has been fixed in [VisionCamera 4.0.0](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v4.0.0). 🥳 

Please try V4 and let me know if you still experience this issue;
- if not, please consider [💖 **sponsoring me on GitHub** 💖](https://github.com/sponsors/mrousavy/) to support the development of VisionCamera and thank me for my time spent on fixing bugs and building new features.
- if you still see this issue, please comment and we can re-open this. But please update your native logs with the native (Xcode/Android Studio) logs from running VisionCamera V4 so I can investigate this.
