### ISSUE TITLE
Issue on CAT phones🐛 

### ISSUE THREAD

**Issue by adoniscoder** [cuvent/react-native-vision-camera#2718]
### What's happening?

We are using vision-camera to detect car's license plates but on CAT phones with android 10 the detection is not working and the image of the camera is deformed

### Reproduceable Code

```tsx
<Camera
	style={StyleSheet.absoluteFill}
	device={device}
	ref={camera}
	photo={true}
	video={true}
	format={format}
	isActive={isFocused}
/>
```

### Relevant log output

```shell
-
```

### Camera Device

```json
"device": {
      "name": "Cat S42",
      "family": "S42",
      "model": "S42",
      "model_id": "SP1A.210812.016",
      "battery_level": 74.0,
      "orientation": "portrait",
      "manufacturer": "Cat",
      "brand": "Cat",
      "screen_width_pixels": 720,
      "screen_height_pixels": 1356,
      "screen_density": 1.9125,
      "screen_dpi": 306,
      "online": true,
      "charging": false,
      "low_memory": false,
      "simulator": false,
      "memory_size": 2996031488,
      "free_memory": 687214592,
      "storage_size": 21809311744,
      "free_storage": 13274906624,
      "boot_time": "2024-04-04T03:26:45.275Z",
      "timezone": "Europe/Sofia",
      "locale": "bg_BG",
      "processor_count": 4,
      "processor_frequency": 1800,
      "archs": [
        "armeabi-v7a",
        "armeabi"
      ],
      "battery_temperature": 27.9,
      "connection_type": "cellular",
      "id": "3769ba74-3fc7-4156-ad1c-3c41eba7f1eb",
      "language": "bg",
      "type": "device"
    },
    "os": {
      "name": "Android",
      "version": "12",
      "build": "SP1A.210812.016 release-keys",
      "kernel_version": "4.19.191-gdcda0bc13ccf",
      "rooted": false,
      "type": "os"
    },
```

### Device

CAT

### VisionCamera Version

3.9.2

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
> the detection is not working and the image of the camera is deformed

Not enough details at all for me to even remotely suggest anything. Closing
