### ISSUE TITLE
Remove iOS automaticallyStopTimeoutSeconds delay💭 

### ISSUE THREAD

**Issue by Mikewa33** [cuvent/react-native-vision-camera#2722]
### Question

How can I remove the automaticallyStopTimeoutSeconds? I am not to worried if a few frames get cut off and the delay in the ability to run the stopRecording call back is a really bad user experience.

### What I tried

Read through the code looking for a prop to pass

### VisionCamera Version

3.7.1

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Let's continue this discussion over the margelo community discord.
