### ISSUE TITLE
💭 What is the best way to set a React state from a Frame processor?

### ISSUE THREAD

**Issue by frodriguez-hu** [cuvent/react-native-vision-camera#2731]
### Question

Hey! I am wondering what is the best way to do what I am asking on the title. Which is the right worklet function or hook I should use?

### What I tried

I am executing this on the frame processor:
```
Worklets.createRunInJsFn(
```
And inside that function I am using a `sharedValue` from the the worklet library. 

I mean, I have things like this around all the code:

```
if (!isInsideLogic.value) {
          eventRegister.value = 0;
          isInsideLogic.value = true;
          setIsInside(true);
        }
```

A logic value coming from the `useSharedValue` so I do not use the state value which will have a wrong value cause the frames are executing super fast compared to the React life cycle. 
By doing that, it is working but I am not sure if it is the best way.

### VisionCamera Version

3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
React state is much slower than shared values. Only need it if you don't expect it to change often, like `hasFacesInView` or something like that. That's fine. 

For some realtime stuff, use Skia or SharedValues instead.
