### ISSUE TITLE
Custom Color Filters and Controls like Exposure, Contrast etc. 💭 

### ISSUE THREAD

**Issue by geekabhinavp** [cuvent/react-native-vision-camera#2734]
### Question

How can I achieve a custom color filter on the live feed of camera maybe using the color matrix like we do in Skia?  Along with that have advanced controlling features like Exposure, Contrast, Shutter Speed? Will I have to make changes in native code along with using Frame Processor? 

### VisionCamera Version

3.9.2

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [x] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
see https://github.com/mrousavy/react-native-vision-camera/pull/2727
