### ISSUE TITLE
✨ Use torch with ReactMethod

### ISSUE THREAD

**Issue by eloisp** [cuvent/react-native-vision-camera#2737]
### What feature or enhancement are you suggesting?

Hi,

Is there an easy way to set the torch on and off using a react method (using a useRef) and not the props ?
The props trigger a render that I don't want. I want to play with the torch without any render.

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

Set the props is too slow

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
Hey - nope, it is a prop. You can use Reanimated SharedValues if you want to avoid triggering a re-render, although a re-render isn't as bad as it sounds (unless your component is not organized very well)
