### ISSUE TITLE
🐛 [4.0.0-beta.10] IllegalArgumentException   android.util.Range in <init>

### ISSUE THREAD

**Issue by mgcrea** [cuvent/react-native-vision-camera#2740]
### What's happening?

Started to see some unhandled exception popup on Sentry lately, looks like it mostly impact a small subset of devices:

- Lenovo A2010l36 (Android 5.1)
- LG-X220 (Android 5.1)

The exact error is `IllegalArgumentException lower must be less than or equal to upper` in `com.mrousavy.camera.core.CameraDeviceDetails in getFormats at line 125` so I guess it should be an easy fix as these device must output some kind of garbage I guess.

### Reproduceable Code

```tsx
const devices = useCameraDevices();
  const device = devices.find(({position}) => position === 'back');
  const format = useCameraFormat(device, Templates.FrameProcessingBarcodeXGA);

```

```
    readonly FrameProcessingBarcodeXGA: [{
        readonly videoResolution: {
            readonly width: 1024;
            readonly height: 768;
        };
    }, {
        readonly pixelFormat: "native" | "yuv";
    }];
```

### Relevant log output

```shell
IllegalArgumentException lower must be less than or equal to upper

android.util.Range in <init> at line 59
com.mrousavy.camera.core.CameraDeviceDetails in getFormats at line 125
com.mrousavy.camera.core.CameraDeviceDetails in toMap at line 79
com.mrousavy.camera.CameraDevicesManager in getDevicesJson at line 87
com.mrousavy.camera.CameraDevicesManager in sendAvailableDevicesChangedEvent at line 94
com.mrousavy.camera.CameraDevicesManager$initialize$1 in invokeSuspend at line 71
kotlin.coroutines.jvm.internal.BaseContinuationImpl in resumeWith at line 33
kotlinx.coroutines.DispatchedTask in run at line 108
java.util.concurrent.ThreadPoolExecutor in runWorker at line 1112
java.util.concurrent.ThreadPoolExecutor$Worker in run at line 587
java.lang.Thread in run at line 818
```

### Camera Device

```json
Happens on devices in the field on the production release so I don't have them on hand.
```

### Device

Lenovo A2010l36

### VisionCamera Version

4.0.0-beta.10

### Can you reproduce this issue in the VisionCamera Example app?

No, I cannot reproduce the issue in the Example app

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
thanks for the report, fixed here: https://github.com/mrousavy/react-native-vision-camera/pull/2755
