### ISSUE TITLE
✨ Complete example of C++ Frame Processor Plugin

### ISSUE THREAD

**Issue by Itsthatotherguy** [cuvent/react-native-vision-camera#2745]
### What feature or enhancement are you suggesting?

Hi there,

I noticed that while there are reference examples for iOS and Android in the documentation, examples for C++ are missing. The documentation highlights that a C++ plugin can be beneficial for specific OpenCV tasks, which is exactly what I aim to utilize. However, I find the documentation somewhat lacking in detailed guidance for creating such a plugin.

To attempt this, I've been analyzing the TFLite plugin and even tried to reverse engineer it. I've also referred to a [blog post](https://medium.com/@lukasz.kurant/creating-a-high-performance-react-native-vision-camera-c-frame-processor-using-jsi-b00fa8df3221) on creating high-performance React Native vision camera frame processors, but so far, I've not had much success.

Could we possibly enhance the documentation to include examples on creating a C++ plugin, along with some debugging tips? I believe this could greatly assist developers like myself who are trying to extend your project's capabilities.

Once I manage to develop a working prototype, I would be more than willing to contribute back by submitting a pull request.

Thank you for considering my request.

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

Currently I am using Android and iOS specific frame processors.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
Hey - C++ plugins require you to have base knowledge/previous experience with JSI.
If you do have that, then the documentation is more than enough as it is currently.
I want to avoid explaining how JSI works in VisionCamera documentation though, as that is not really related to VisionCamera.
