### ISSUE TITLE
🐛 Camera component returns permission denied on initial load (Android)

### ISSUE THREAD

**Issue by EmanuilM** [cuvent/react-native-vision-camera#2749]
### What's happening?

I installed a fresh version of my app, and upon the initial camera open, it returns a permission denied error. However, when I open the camera for the second time, it works fine.

I've tried requesting permissions using React Native's PermissionsAndroid, but it still returns the same error.
I was able to reproduce the bug without calling any request permission functions. When the <Camera/> component is invoked, it gives the error.

### Reproduceable Code

```tsx
const Camera = () => {
    const cameraRef = useRef<any>(null);
    const [cameraState, setCameraState] = useState<"back" | "front">("back");
    const device = useCameraDevice(cameraState);

    if (!device) {
        return (
            <View>
                <Text>No camera device</Text>
            </View>
        )
    }

    return (
        <SafeAreaView style={{ flex: 1 }}>
            <Camera
                ref={cameraRef}
                style={StyleSheet.absoluteFill}
                device={device}
                isActive={true}
                photo={true}
                video={true}
                audio={false}
            />
        </SafeAreaView>

    )
}

export default Camera;
```

### Relevant log output

```shell
Camera.onError(permission/camera-permission-denied): The Camera permission was denied! [permission/camera-permission-denied: The Camera permission was denied!]
```

### Camera Device

```json
{
  "formats": [],
  "sensorOrientation": "landscape-left",
  "hardwareLevel": "limited",
  "maxZoom": 1,
  "minZoom": 1,
  "maxExposure": 6,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "ultra-wide-angle-camera"
  ],
  "supportsFocus": false,
  "supportsRawCapture": false,
  "isMultiCam": false,
  "minFocusDistance": 0,
  "minExposure": -6,
  "name": "10 (BACK) androidx.camera.camera2",
  "hasFlash": false,
  "hasTorch": false,
  "position": "back",
  "id": "10"
}
```

### Device

Samsung A71 - Android 13, Android Emulator - Android 13,14

### VisionCamera Version

3.9.2 and 4.0.0-beta.14

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [X] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
In 3.9.2 as well??

Can you please put the full `adb logcat` logs here? I need to know what gets called before the error is thrown

**Comment by mrousavy** [comment]
Wait - you're not using `useCameraPermission()`? You need to do that. It's the first step in the docs.

**Comment by EmanuilM** [comment]
I've removed it for the purpose of the test, I thought the error was from useCameraPermission(), but after removing it, I still get it.


Here's my code with `useCameraPermission()`

```js
const Camera = () => {
    const { hasPermission, requestPermission } = useCameraPermission();
    const cameraRef = useRef<any>(null);
    const [cameraState, setCameraState] = useState<"back" | "front">("back");
    const device = useCameraDevice(cameraState);

    useEffect(() => {
        if(!hasPermission) { 
            requestPermission();
        }
    }, [])

    if (!device) {
        return (
            <View>
                <Text>No camera device</Text>
            </View>
        )
    }

    return (
        <SafeAreaView style={{ flex: 1 }}>
            <Camera
                ref={cameraRef}
                style={StyleSheet.absoluteFill}
                device={device}
                isActive={true}
                photo={true}
                video={true}
                audio={false}
            />
        </SafeAreaView>

    )
}

export default Camera;
```

**Comment by mrousavy** [comment]
you shouldn't mount the camera at all if you don't have permission.
maybe I should add this to the docs explicitly as well

**Comment by EmanuilM** [comment]
That make sense, it would be great if this is in docs
