### ISSUE TITLE
How to properly switch between two modes (taking photo and scan QR mode)💭 

### ISSUE THREAD

**Issue by Kavosh-m** [cuvent/react-native-vision-camera#2760]
### Question

What is the best practice for switch between photo and scan qr modes. Let's say we have two Camera components, one for taking photos and the other one for scanning a QR. how can I properly switch between them? (I simply used a react state boolean to switch between them, but sometimes the code scanner screen goes blank/black. )

### VisionCamera Version

3.9.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Why do you need two Cameras? Why not just one `<Camera>` with `photo` and `codeScanner`?
