### ISSUE TITLE
🔧  [^4.0.0-beta.18] react-native cli-config unable to detect CameraPackage.

### ISSUE THREAD

**Issue by iamfat** [cuvent/react-native-vision-camera#2772]
### How were you trying to build the app?

I failed to build the project with  `beta-18` module. And I found that's because react-native cli-config will detect `namespace=com.mrousavy.camer` and use it to generate `packageImportPath` (`import com.mrousavy.camera.CameraPackage;`)  by parsing android `build.gradle` file.  But the correct import path should be `import com.mrousavy.camera.react.CameraPackage;`

### Full build logs

```tsx
> Task :app:compileReleaseJavaWithJavac FAILED
/Volumes/Codes/js/uno-container/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:31: error: cannot find symbol
import com.mrousavy.camera.CameraPackage;
                          ^
  symbol:   class CameraPackage
  location: package com.mrousavy.camera
/Volumes/Codes/js/uno-container/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:91: error: cannot find symbol
      new CameraPackage(),
          ^
  symbol:   class CameraPackage
  location: class PackageList
2 errors

FAILURE: Build failed with an exception.
```

### Project dependencies

```json
"dependencies": {
  "react-native": "^0.73.0",
  "react-native-vision-camera": "4.0.0-beta.18"
}
```

### VisionCamera Version

4.0.0-beta.18

### Target platforms

Android

### Operating system

MacOS

### Can you build the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
fixed
