### ISSUE TITLE
💭 Get the size of the image/video

### ISSUE THREAD

**Issue by nitin-mbook** [cuvent/react-native-vision-camera#2774]
### Question

 hi , I wonder if it is possible to get the size of the captured video or image somehow ?

### What I tried

I tried recording video , and wanted to know the size of the video .

### VisionCamera Version

2.15.5

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Upgrade to V4. Size is always returned.
