### ISSUE TITLE
💭 [frameProcessor] How to call/pass setState as an argument in worklet

### ISSUE THREAD

**Issue by thongquach** [cuvent/react-native-vision-camera#2775]
### Question

I'm wondering how to call/pass setState as an argument in worklet. Or is there any better way to achieve this?
Since `scanContainerInfo` is very complex, I need to extract it as a separate utils in another file.

Thanks for any suggestion/support.

With the following code, the `scanContainerInfoJS` worklet runs correctly, but the setState `setContainerInfo` is not called, leading to the value not being updated.

``` typescript
const [containerInfo, setContainerInfo] = useState<ContainerInfo | null>(null)
const scanContainerInfoJS = Worklets.createRunInJsFn(scanContainerInfo)

const frameProcessor = useFrameProcessor(
  (frame) => {
    'worklet'

    runAtTargetFps(2, () => {
      'worklet'
      const ocrFrame = scanOCR(frame)
      scanContainerInfoJS({
        frame: { ...frame },
        ocrFrame: { ...ocrFrame },
        setContainerInfo: setContainerInfo,
      })
    })
  },
  [setContainerInfo]
)

<Camera
  device={device}
  style={{ width: deviceWidth, height: cameraHeight }}
  isActive={true}
  photo={true}
  frameProcessor={frameProcessor}
  format={format}
  orientation="portrait"
  pixelFormat="yuv"
  onError={captureException}
/>
```

### VisionCamera Version

3.6.15

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Try upgrading to V4.

Also try adding logs here, this should be called. Either way, it's a react-native-worklets issue, not VisionCamera
