### ISSUE TITLE
🐛 RNVC^4.0.1 + WorkletsCore^1.1.1 [ Error: Value is undefined, expected a String, js engine: hermes ]

### ISSUE THREAD

**Issue by ExoticCoder16** [cuvent/react-native-vision-camera#2780]
### What's happening?

First, Thanks for the update, the RNVC v.4 is now compatible with VC resize plugin,
however, I run into another Error ( given I can open camera, just the problem of frame processor, if I comment out frame processor, everything works fine ) :
Error: Value is undefined, expected a String, js engine: hermes
<img width="767" alt="Screenshot 2024-04-22 at 9 23 41 PM" src="https://github.com/mrousavy/react-native-vision-camera/assets/58113539/f0228534-3c4e-4e26-b050-09eaec754b68">
<img width="396" alt="Screenshot 2024-04-22 at 9 24 01 PM" src="https://github.com/mrousavy/react-native-vision-camera/assets/58113539/26dc5637-f95f-4d48-83af-340270e6d4ca">
<img width="519" alt="Screenshot 2024-04-22 at 8 57 39 PM" src="https://github.com/mrousavy/react-native-vision-camera/assets/58113539/f0098b59-919d-4125-bd86-2efcef9b0893">

and I have tried the package/example app, it works fine, scan QR code successfully...etc

and I have tried to downgrade my RNVC to 3.9.2 / 3.8.0 + Worklets Core to 0.5.0 / 0.2.4
I have tried multiple combinations,
but the Error falls back to :
Loading react-native-worklets-core...
 LOG  Worklets loaded successfully
 LOG  Open Camera button pressed
 ERROR  system/frame-processors-unavailable: Frame Processors are not available, react-native-worklets-core is not installed!, js engine: hermes
 
 I have also tried it on my iPhone 15 physical device ( iOS  17.4.1 ), same Error,
 camera is successfully open, just the frame processor problem :
<img width="758" alt="Screenshot 2024-04-22 at 10 24 22 PM" src="https://github.com/mrousavy/react-native-vision-camera/assets/58113539/719e06a9-eae5-49ec-bc93-1a510ca1a241">

I did add request permission in the original project but I am trying to make the Reproduceable Code as simple as possible below,
I also copied and pasted the related Android Studio Logcat logs below,
you can scroll down and you will see something like :
21:13:17.176  I  PreviewView Surface updated! Surface(name=null)/@0xf49a7da 1920 x 1080
21:13:17.180  E  Error: Value is undefined, expected a String, js engine: hermes
21:13:17.183  I  PreviewView is 1080x1934, rendering 1080x1920

### Reproduceable Code

```tsx
import React from 'react';
import {
    Camera,
    useCameraDevice,
    useFrameProcessor,
} from 'react-native-vision-camera';

export default function CameraScreen() {
  const device = useCameraDevice('back');
  const frameProcessor = useFrameProcessor((frame) => {
    'worklet'
    // console.log(`Frame: ${frame.width}x${frame.height} (${frame.pixelFormat})`)
    console.log("RNVC logged")
  }, [])
  
    return (
      <Camera
        device={device}
        style={{ flex: 1 }}
        isActive={true}
        frameProcessorFps={5}
        frameProcessor={frameProcessor}
      />
    )
  }
```

### Relevant log output

```shell
:13:17.098  I  Creating new device...
21:13:17.098  I  Camera #10: Opening...
21:13:17.106  I  Camera #10 is now unavailable.
21:13:17.118  I  Camera #10: Opened!
21:13:17.118  I  Creating new session...
21:13:17.119  I  Camera #10: Creating Capture Session #76... (Hardware Level: 0 | Outputs: [VIDEO (1280x960 in NATIVE)])
21:13:17.119  I  Using new API (>=28)
21:13:17.157  I  Camera #10: Successfully created CameraCaptureSession #76!
21:13:17.157  D  Stopping repeating request...
21:13:17.158  D  Configure() done! isActive: false, ID: 10, device: android.hardware.camera2.impl.CameraDeviceImpl@254eda3, session: android.hardware.camera2.impl.CameraCaptureSessionImpl@da308a0
21:13:17.158  I  configure { ... }: Completed CameraSession Configuration! (isActive: false, isRunning: false)
21:13:17.158  I  invokeOnInitialized()
21:13:17.158  I  Updating CameraSession...
21:13:17.160  I  configure { ... }: Waiting for lock...
21:13:17.160  I  configure { ... }: Updating CameraSession Configuration... Difference(deviceChanged=false, outputsChanged=false, sidePropsChanged=false, isActiveChanged=true)
21:13:17.160  D  --> setIsActive(false)
21:13:17.161  D  Configure() with isActive: false, ID: 10, device: android.hardware.camera2.impl.CameraDeviceImpl@254eda3, session: android.hardware.camera2.impl.CameraCaptureSessionImpl@da308a0
21:13:17.161  D  Stopping repeating request...
21:13:17.161  D  Configure() done! isActive: false, ID: 10, device: android.hardware.camera2.impl.CameraDeviceImpl@254eda3, session: android.hardware.camera2.impl.CameraCaptureSessionImpl@da308a0
21:13:17.161  I  configure { ... }: Completed CameraSession Configuration! (isActive: true, isRunning: false)
21:13:17.164  I  PreviewView is 1080x2154, rendering 1080x1920 content (LANDSCAPE_LEFT). Resizing to: 1212x2154 (COVER)
21:13:17.168  I  PreviewView Surface created! Surface(name=null)/@0xf49a7da
21:13:17.169  I  Setting Preview Output...
21:13:17.169  I  configure { ... }: Waiting for lock...
21:13:17.169  I  configure { ... }: Updating CameraSession Configuration... Difference(deviceChanged=false, outputsChanged=true, sidePropsChanged=true, isActiveChanged=true)
21:13:17.169  I  Destroying previous outputs...
21:13:17.172  I  Closing 1280x960 Video Pipeline..
21:13:17.172  I  Creating outputs for Camera #10...
21:13:17.173  I  Adding 1280x960 Video Output in PRIVATE...
21:13:17.173  I  Initializing 1280 x 960 Video Pipeline (format: NATIVE)
21:13:17.175  I  Using ImageReader round-trip (format: #34)
21:13:17.175  I  Creating ImageReader with default usage flags...
21:13:17.176  I  Creating ImageWriter with format #34...
21:13:17.176  I  Adding 1280x960 Preview Output...
21:13:17.176  I  PreviewView Surface updated! Surface(name=null)/@0xf49a7da 1920 x 1080
21:13:17.180  E  Error: Value is undefined, expected a String, js engine: hermes
21:13:17.183  I  PreviewView is 1080x1934, rendering 1080x1920 content (LANDSCAPE_LEFT). Resizing to: 1088x1934 (COVER)
21:13:17.190  I  Resizing SurfaceHolder to 1280 x 960...
21:13:17.192  I  Surface Size changed: 1920x1080 -> 1280x960
21:13:17.192  I  PreviewView Surface updated! Surface(name=null)/@0xf49a7da 1280 x 960
21:13:17.192  I  Resized SurfaceHolder to 1280 x 960!
21:13:17.195  I  PreviewView is 1088x1934, rendering 960x1280 content (LANDSCAPE_LEFT). Resizing to: 1451x1934 (COVER)
21:13:17.195  D  --> setOutputs([VIDEO (1280x960 in NATIVE), PREVIEW (1280 x 960)])
21:13:17.195  I  Successfully configured Session with 2 outputs for Camera #10!
21:13:17.196  I  Updating Video Outputs...
21:13:17.196  I  Removing RecordingSession Output...
21:13:17.196  D  --> setRepeatingRequest(...)
21:13:17.196  D  --> setIsActive(true)
21:13:17.196  D  Configure() with isActive: true, ID: 10, device: android.hardware.camera2.impl.CameraDeviceImpl@254eda3, session: null
21:13:17.197  I  Creating new session...
21:13:17.197  I  Camera #10: Creating Capture Session #77... (Hardware Level: 0 | Outputs: [VIDEO (1280x960 in NATIVE), PREVIEW (1280 x 960)])
21:13:17.198  I  Using new API (>=28)
21:13:17.212  I  onLastStrongRef automatically unlinking death recipients: 
21:13:17.212  I  Camera #10: CameraCaptureSession #76 has been closed.
21:13:17.212  I  Session android.hardware.camera2.impl.CameraCaptureSessionImpl@da308a0 closed!
21:13:17.213  I  Camera #10: Successfully created CameraCaptureSession #77!
21:13:17.213  D  Updating repeating request...
21:13:17.459  D  Configure() done! isActive: true, ID: 10, device: android.hardware.camera2.impl.CameraDeviceImpl@254eda3, session: android.hardware.camera2.impl.CameraCaptureSessionImpl@3fa3b39
21:13:17.459  I  configure { ... }: Completed CameraSession Configuration! (isActive: true, isRunning: true)
21:13:17.459  I  invokeOnStarted()
21:13:17.463  I  PreviewView is 1088x1934, rendering 960x1280 content (LANDSCAPE_LEFT). Resizing to: 1451x1934 (COVER)
21:13:17.466  I  ImageReader::onImageAvailable!
21:13:17.478  I  ImageReader::onImageAvailable!
```

### Camera Device

```json
{
  "formats": [],
  "sensorOrientation": "landscape-left",
  "hardwareLevel": "limited",
  "maxZoom": 1,
  "minZoom": 1,
  "maxExposure": 6,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "ultra-wide-angle-camera"
  ],
  "supportsFocus": false,
  "supportsRawCapture": false,
  "isMultiCam": false,
  "minFocusDistance": 999.999985098839,
  "minExposure": -6,
  "name": "BACK (10)",
  "hasFlash": false,
  "hasTorch": false,
  "position": "back",
  "id": "10"
}
```

### Device

iPhone 15 physical device ( iOS  17.4.1 ) + Pixel_3a Emulator ( Android 14 API 34 )

### VisionCamera Version

4.0.1

### Can you reproduce this issue in the VisionCamera Example app?

No, I cannot reproduce the issue in the Example app

### Additional information

- [X] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Are you passing something weird to `frameProcessor`?

There have been some changes with how the `frameProcessor` prop is handled natively.

**Comment by ExoticCoder16** [comment]
> Are you passing something weird to `frameProcessor`?
> 
> There have been some changes with how the `frameProcessor` prop is handled natively.

No, I am just using the simple Reproduceable Code above,

In my original code, I am planning to use Worklets.createRunOnJS to pass the frame to websocket, 
but all the errors I encountered are just using the simple Reproduceable Code above

For example, I'm planning to implement this use case in the documentation :

const onFaceDetected = Worklets.createRunOnJS((face: Face) => {
  navigation.push("FiltersPage", { face: face })
})

const frameProcessor = useFrameProcessor((frame) => {
  'worklet'
  const faces = scanFaces(frame)
  if (faces.length > 0) {
    onFaceDetected(faces[0])
  }
}, [onFaceDetected])

but again I first used the above simple Reproduceable Code template to test it first, and I encountered the above error, and I successfully logged the frames few days ago before the update

**Comment by mrousavy** [comment]
`frameProcessorFps` no longer exists. Are you sure you are on react-native-vision-camera 4.0.1?

**Comment by mrousavy** [comment]
I think this might be a caching issue, or your native libraries are not updated.

Do you maybe have a library that depends on an older version of react-native-vision-camera, and so 4.0.1 is not actually installed but it's something older like 3.x.x.?

Check the version of `VisionCamera` in `Podfile.lock`.

**Comment by ExoticCoder16** [comment]
> I think this might be a caching issue, or your native libraries are not updated.
> 
> Do you maybe have a library that depends on an older version of react-native-vision-camera, and so 4.0.1 is not actually installed but it's something older like 3.x.x.?
> 
> Check the version of `VisionCamera` in `Podfile.lock`.

I finally get it working on my iPhone by re-uploading to EAS platform, yes I am sure I am on 4.0.1 before, I used "npm list react-native-vision-camera" to check the version as stated in the picture above and podfile.lock is also correct as below 
<img width="536" alt="Screenshot 2024-04-23 at 12 44 12 AM" src="https://github.com/mrousavy/react-native-vision-camera/assets/58113539/4e6d37bf-9c73-48ac-bf6b-c98f01eb3566">
I thought the error type changed = they were in sync, lesson learnt,

and I followed the troubleshoot guide in the documentation to remove and re-installe all the cached files and folder as much as I can before the re-build, 
I removed the frame processor fps props,
Worklets.createRunOnJS is also working fine 👍 Thank you so much
<img width="761" alt="Screenshot 2024-04-23 at 4 59 25 AM" src="https://github.com/mrousavy/react-native-vision-camera/assets/58113539/b383065f-7d1a-4a41-b185-07dd46b527bf">

I would close this post as it is solved,

but before closing, since you are here, I also want to report something about another library ( react-native-fast-tflite ) which is also created by you, it is not a big deal, it won't affect the functionality but it keeps showing up during pod install :
"CLANG_CXX_LANGUAGE_STANDARD" => "c++17" is duplicated, maybe you can remove that in the next version, just letting you know it exists in case you missed it
![IMAGE 2024-04-23 06:16:53](https://github.com/mrousavy/react-native-vision-camera/assets/58113539/31823467-cd5f-433d-9d93-787c06fb687a)
<img width="999" alt="Screenshot 2024-04-23 at 12 40 02 AM" src="https://github.com/mrousavy/react-native-vision-camera/assets/58113539/15b402eb-8e86-4204-be2e-b90dfd5b7b03">
