### ISSUE TITLE
🔧 Vision camera not working in ios 

### ISSUE THREAD

**Issue by Urviil** [cuvent/react-native-vision-camera#2785]
### How were you trying to build the app?

I tried to build the react-native-vision-camera through 'yarn-ios' command
![Screenshot 2024-04-23 at 5 59 30 PM](https://github.com/mrousavy/react-native-vision-camera/assets/153886514/9f01cec1-70e8-4c63-817f-92d11f12043b)

### Full build logs

```tsx
yarn run v1.22.19
$ react-native run-ios
info A dev server is already running for this project on port 8081.
info Found Xcode workspace "prooftech.xcworkspace"
info Found booted iPhone 13 Pro Max
info Building (using "xcodebuild -workspace prooftech.xcworkspace -configuration Debug -scheme prooftech -destination id=08C74478-860D-4D26-BA65-2BCFDCB37798")
⠹ Building the app......
```

### Project dependencies

```json
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-native-camera-roll/camera-roll": "^7.5.2",
    "@react-native-community/datetimepicker": "^7.6.3",
    "@react-native-community/netinfo": "^11.3.1",
    "@react-native-community/slider": "^4.5.1",
    "@react-native-masked-view/masked-view": "^0.3.1",
    "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/native": "6.1.15",
    "@react-navigation/native-stack": "6.9.24",
    "fbjs": "^3.0.5",
    "moment": "^2.30.1",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-calendars": "^1.1304.1",
    "react-native-camera-kit": "^13.0.0",
    "react-native-device-info": "^10.13.2",
    "react-native-document-picker": "^9.1.1",
    "react-native-gesture-handler": "^2.15.0",
    "react-native-image-crop-picker": "^0.40.3",
    "react-native-image-picker": "^7.1.2",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-modal-datetime-picker": "^17.1.0",
    "react-native-mov-to-mp4": "^0.2.2",
    "react-native-permissions": "^4.1.5",
    "react-native-responsive-fontsize": "^0.5.1",
    "react-native-safe-area-context": "^4.9.0",
    "react-native-screens": "^3.30.1",
    "react-native-video": "^5.2.1",
    "react-native-vision-camera": "^4.0.1"
  },
```

### VisionCamera Version

4.0.1

### Target platforms

iOS

### Operating system

MacOS

### Can you build the VisionCamera Example app?

No, I cannot build the Example app either

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
If you cannot build the Example App either, then it must be an issue with your Xcode. I can build it, a lot of people in the community can build it, and the CI here can build it.

**Comment by nolife08021** [comment]
@Urviil  Hi,  whats your Xcode version? did you able to fix it?
