### ISSUE TITLE
💭 Exclude react-native-vision-camera during the development web build

### ISSUE THREAD

**Issue by lv-saikrishna** [cuvent/react-native-vision-camera#2789]
### Question

I have a react native project and I test the application using expo development web build using web browser and after I installed "react-native-vision-camera" in my application, I am getting the below error and application is not loading in browser, but when I build the app in expo it works fine. 

**Is there any way to exclude this package from development web build?**

"NativeCameraModule.ts:11 
 Uncaught system/camera-module-not-found: Failed to initialize VisionCamera: VisionCamera currently does not work on web."

### VisionCamera Version

4.0.1

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Well then you have to set up your babel / metro resolver to exclude VisionCamera when building for web.
