### ISSUE TITLE
✨ Greyscale, B&W and more filters

### ISSUE THREAD

**Issue by DEMONCELL1** [cuvent/react-native-vision-camera#2792]
### What feature or enhancement are you suggesting?

I think we can use the Filter property in the camera for getting videos with simple filters like Greyscale, B&W, polaroid etc.

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

I am currently trying to do this with the Skia but I am not able to achieve a certain result.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
You can add such filters by using Skia Frame Processors. Read the docs

**Comment by DEMONCELL1** [comment]
Can you help me with some examples if possible?

**Comment by RutvinBhanderi** [comment]
> You can add such filters by using Skia Frame Processors. Read the docs

But when we capture the photo then it is not taking that effect. Can you help me with that?

**Comment by mrousavy** [comment]
See this section in the Skia FP docs.

![Screenshot 2024-05-21 at 10 40 55](https://github.com/mrousavy/react-native-vision-camera/assets/15199031/ab0c2e15-fa06-420a-94ca-824a5a652870)
