### ISSUE TITLE
Incorrect Photo Orientation Value After Upgrading to Version 4.0.0 💭 

### ISSUE THREAD

**Issue by MariaFF** [cuvent/react-native-vision-camera#2796]
### Question

In the previous version (2.15.2), I was able to retrieve the correct orientation value using the property photo.metadata.Orientation, which is no longer available in version 4.0.0.I've changed it to photo.orientation but I only get the portrait value

### VisionCamera Version

4.0.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Orientation is not yet supported. See the first pinned issue in this repo if you want to support the development of this feature :)
