### ISSUE TITLE
This API is provided only for React Native frameworks and not intended for general users. This API can change between minor versions in alignment with React Native frameworks and won't be considered a breaking change🔧 

### ISSUE THREAD

**Issue by a289459798** [cuvent/react-native-vision-camera#2798]
### How were you trying to build the app?

android build

### Full build logs

```tsx
e: file:///Users/zhangzy/workspace/android/5ichong/ichong_buy_new/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/frameprocessors/VisionCameraProxy.kt:31:79 This API is provided only for React Native frameworks and not intended for general users. This API can change between minor versions in alignment with React Native frameworks and won't be considered a breaking change.
e: file:///Users/zhangzy/workspace/android/5ichong/ichong_buy_new/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/frameprocessors/VisionCameraProxy.kt:36:19 This API is provided only for React Native frameworks and not intended for general users. This API can change between minor versions in alignment with React Native frameworks and won't be considered a breaking change.
e: file:///Users/zhangzy/workspace/android/5ichong/ichong_buy_new/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/frameprocessors/VisionCameraProxy.kt:36:47 This API is provided only for React Native frameworks and not intended for general users. This API can change between minor versions in alignment with React Native frameworks and won't be considered a breaking change.
e: file:///Users/zhangzy/workspace/android/5ichong/ichong_buy_new/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/frameprocessors/VisionCameraProxy.kt:75:73 This API is provided only for React Native frameworks and not intended for general users. This API can change between minor versions in alignment with React Native frameworks and won't be considered a breaking change.
```

### Project dependencies

```json
"dependencies": {
    "react": "18.2.0",
    "react-native": "0.74.0",
    "react-native-vision-camera": "^4.0.1"
  }
```

### VisionCamera Version

4.0.1

### Target platforms

Android

### Operating system

MacOS

### Can you build the VisionCamera Example app?

No, I cannot build the Example app either

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
see #2614. RN 0.74 does not work yet I need to migrate to new arch. support the efforts by sponsoring me if you want.

**Comment by GeekyCoder25** [comment]
I'm also experiencing this error while trying to build the app both locally and on eas, I'm on react Native v0.74.1 and react-native-vision-camera v4.0.5
![Screenshot 2024-05-23 004856](https://github.com/mrousavy/react-native-vision-camera/assets/96173120/92858f5c-dd15-45a9-b3a1-8996bf605ced)
