### ISSUE TITLE
Does ShadowLens app already uses v4?💭 

### ISSUE THREAD

**Issue by CyxouD** [cuvent/react-native-vision-camera#2800]
### Question

Hi everyone. Does anyone know if ShadowLens app already uses react-native-vision-camera v4? 
I suppose yes, because it was updated in the same day as v4 release and I see CameraX ("androidx.camera.camera2") in the Settings, which is the same dependency found in the latest code.

I still have ["Camera stretched on Android" bug](https://github.com/mrousavy/react-native-vision-camera/issues/2142) in this app, so I wondered if it was fixed.
At the other device, I get crash after allowing all permissions (location in the end)

### What I tried

Install ShadowLens app.

### VisionCamera Version

This is exactly what I ask

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Yes ShadowLens uses V4.
If you experience preview stretching, you need to create a new bug report with a project that uses VisionCamera V4, and add **native logs**. (adb logcat).
And a screenshot.
