### ISSUE TITLE
💭 How to create boilerplate for frame processors?

### ISSUE THREAD

**Issue by zzz08900** [cuvent/react-native-vision-camera#2810]
### Question

How to generate a boilerplate similar to those frame processors already floating around? 
They all have an android folder, an ios folder and an example folder. The docs say we should run `npx vision-camera-plugin-builder@latest {platformName}` but then it asks for the location of Android Manifest and .xcodeproj file, which, to be honest I don't have any.

Are we supposed to create a Android project using Android Studio and an iOS project using XCode and then run `npx vision-camera-plugin-builder@latest {platformName}` ? If that's the case what preset should be chosen during set up process of the said projects?

### VisionCamera Version

2.16.7 with in-house patches, works like a charm

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by zzz08900** [comment]
I kind set through the whole V2 -> V3 transition and are now evaluating how hard it is to do a V2 -> V4 transition.
So if someone can point me to a boilerplate for frame processor V4 that would be great.

**Comment by xulihang** [comment]
I have a blog which may help: https://www.dynamsoft.com/codepool/react-native-vision-camera-cropper-plugin.html

**Comment by zzz08900** [comment]
So basically `npx create-react-native-library@latest` lays down the boilerplate for you. 

I just tried it, and it works wonders. 

Thanks man, that helped a lot.
