### ISSUE TITLE
🐛 Document typo(android frame processor plugin)

### ISSUE THREAD

**Issue by thatsongkim** [cuvent/react-native-vision-camera#2816]
### What's happening?

I followed [this](https://react-native-vision-camera.com/docs/guides/frame-processors-plugins-android) document after migrate 3.9.1 to 4.0.1. But build failed.

So I checked package name, there is no 'frameprocessor' but instead 'frameprocessors'.

### Reproduceable Code

```tsx
import com.mrousavy.camera.frameprocessor.Frame;
import com.mrousavy.camera.frameprocessor.FrameProcessorPlugin;
import com.mrousavy.camera.frameprocessor.VisionCameraProxy;
```

### Relevant log output

```shell
error: package com.mrousavy.camera.frameprocessor does not exist
import com.mrousavy.camera.frameprocessor.Frame;
...
```

### Camera Device

```json
{}
```

### Device

android devices

### VisionCamera Version

4.0.1

### Can you reproduce this issue in the VisionCamera Example app?

No, I cannot reproduce the issue in the Example app

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Can you create a PR to change that?
