### ISSUE TITLE
💭4.0.1 unable to run 

### ISSUE THREAD

**Issue by zhengjialu520** [cuvent/react-native-vision-camera#2817]
### Question

when i yarn add react-native-vision-camera and run it .but the following errors will occur:
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find androidx.camera:camera-core:1.4.0-alpha04.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/androidx/camera/camera-core/1.4.0-alpha04/camera-core-1.4.0-alpha04.pom
       - file:/Users/zhengjialu/.m2/repository/androidx/camera/camera-core/1.4.0-alpha04/camera-core-1.4.0-alpha04.pom
       - file:/Users/zhengjialu/Desktop/ryapp/ryapp/node_modules/react-native/android/androidx/camera/camera-core/1.4.0-alpha04/camera-core-1.4.0-alpha04.pom
       - https://maven.aliyun.com/repository/google/androidx/camera/camera-core/1.4.0-alpha04/camera-core-1.4.0-alpha04.pom
       - https://maven.aliyun.com/repository/jcenter/androidx/camera/camera-core/1.4.0-alpha04/camera-core-1.4.0-alpha04.pom
       - http://maven.aliyun.com/nexus/content/groups/public/androidx/camera/camera-core/1.4.0-alpha04/camera-core-1.4.0-alpha04.pom
       - http://developer.huawei.com/repo/androidx/camera/camera-core/1.4.0-alpha04/camera-core-1.4.0-alpha04.pom
       - https://jitpack.io/androidx/camera/camera-core/1.4.0-alpha04/camera-core-1.4.0-alpha04.pom
       - file:/Users/zhengjialu/Desktop/ryapp/ryapp/node_modules/jsc-android/dist/androidx/camera/camera-core/1.4.0-alpha04/camera-core-1.4.0-alpha04.pom
       - https://repo1.maven.org/maven2/androidx/camera/camera-core/1.4.0-alpha04/camera-core-1.4.0-alpha04.pom
       - https://www.jitpack.io/androidx/camera/camera-core/1.4.0-alpha04/camera-core-1.4.0-alpha04.pom
       - file:/Users/zhengjialu/Desktop/ryapp/ryapp/android/app/libs/camera-core-1.4.0-alpha04.jar
       - file:/Users/zhengjialu/Desktop/ryapp/ryapp/android/app/libs/camera-core.jar
     Required by:
         project :app > com.github.jenly1314:zxing-lite:2.1.1
   > Could not find androidx.camera:camera-camera2:1.4.0-alpha04.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/androidx/camera/camera-camera2/1.4.0-alpha04/camera-camera2-1.4.0-alpha04.pom
       - file:/Users/zhengjialu/.m2/repository/androidx/camera/camera-camera2/1.4.0-alpha04/camera-camera2-1.4.0-alpha04.pom
       - file:/Users/zhengjialu/Desktop/ryapp/ryapp/node_modules/react-native/android/androidx/camera/camera-camera2/1.4.0-alpha04/camera-camera2-1.4.0-alpha04.pom
       - https://maven.aliyun.com/repository/google/androidx/camera/camera-camera2/1.4.0-alpha04/camera-camera2-1.4.0-alpha04.pom
       - https://maven.aliyun.com/repository/jcenter/androidx/camera/camera-camera2/1.4.0-alpha04/camera-camera2-1.4.0-alpha04.pom
       - http://maven.aliyun.com/nexus/content/groups/public/androidx/camera/camera-camera2/1.4.0-alpha04/camera-camera2-1.4.0-alpha04.pom
       - http://developer.huawei.com/repo/androidx/camera/camera-camera2/1.4.0-alpha04/camera-camera2-1.4.0-alpha04.pom
       - https://jitpack.io/androidx/camera/camera-camera2/1.4.0-alpha04/camera-camera2-1.4.0-alpha04.pom
       - file:/Users/zhengjialu/Desktop/ryapp/ryapp/node_modules/jsc-android/dist/androidx/camera/camera-camera2/1.4.0-alpha04/camera-camera2-1.4.0-alpha04.pom
       - https://repo1.maven.org/maven2/androidx/camera/camera-camera2/1.4.0-alpha04/camera-camera2-1.4.0-alpha04.pom
       - https://www.jitpack.io/androidx/camera/camera-camera2/1.4.0-alpha04/camera-camera2-1.4.0-alpha04.pom
       - file:/Users/zhengjialu/Desktop/ryapp/ryapp/android/app/libs/camera-camera2-1.4.0-alpha04.jar
       - file:/Users/zhengjialu/Desktop/ryapp/ryapp/android/app/libs/camera-camera2.jar
     Required by:
         project :app > com.github.jenly1314:zxing-lite:2.1.1
----

My environment
react native 0.68
android/build.gradle
buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 24
        compileSdkVersion = 30
        targetSdkVersion = 30
        googlePlayServicesVersion = "11.0.4"
        isEnableGoogleFCM = false    
        versionCodeNum = 1048576
        versionCodeBaseNum = 151 
        versionCode = 20220101
        googlePlayServicesVersion = '16.+'
        kotlinVersion = '1.6.10'
    }
    repositories {
        //maven {url "https://maven.google.com"}
        //google()
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://maven.aliyun.com/nexus/content/groups/public/' }
        jcenter() { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://developer.huawei.com/repo/' }
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.1.0')
        classpath 'com.huawei.agconnect:agcp:1.4.1.300'
        classpath('com.google.gms:google-services:4.3.2')
        classpath('com.sensorsdata.analytics.android:android-gradle-plugin2:3.5.2')

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        exclusiveContent {
            // We get React Native's Android binaries exclusively through npm,
            // from a local Maven repo inside node_modules/react-native/.
            // (The use of exclusiveContent prevents looking elsewhere like Maven Central
            // and potentially getting a wrong version.)
            filter {
                includeGroup "com.facebook.react"
            }
            forRepository {
                maven {
                    url "$rootDir/../node_modules/react-native/android"
                }
            }
        }
//        mavenCentral {
//            content {
//                excludeGroup("com.facebook.react")
//            }
//        }
        mavenCentral()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        // mavenLocal()
        // maven {url "https://maven.google.com"}

        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }

        maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }
        maven() { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'http://developer.huawei.com/repo/' }
        maven { url "https://jitpack.io" }    // used for MPAndroidChart
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        maven { url 'https://repo1.maven.org/maven2' }
        maven { url 'https://www.jitpack.io' }
        //maven { url 'https://dl.bintray.com/umsdk/release' }  
    }
    subprojects {
        afterEvaluate {
            project ->
                if (project.hasProperty("android")) {
                    android {
                        compileSdkVersion = rootProject.ext.compileSdkVersion
                        buildToolsVersion = rootProject.ext.buildToolsVersion
                    }
                }
        }
    }
}

### VisionCamera Version

4.0.1

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
wrong issue template.
