### ISSUE TITLE
Which Slider Library are we using in ShadowLens app for Exposure? 💭 

### ISSUE THREAD

**Issue by geekabhinavp** [cuvent/react-native-vision-camera#2821]
### Question

Hi @mrousavy,
Might be a silly question but, can you please confirm which slider library we're utilizing in the ShadowLens app for exposure control?

### What I tried

Couldn't find any library which can do that yet.

### VisionCamera Version

4.0.1

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey!
I wrote this myself using Reanimated and Gesture Handler.

Might also be good to join the Discord to avoid posting such questions on GitHub / tagging me for such things.
