### ISSUE TITLE
🐛 Selfie camera recording on Android is inverted / upside down

### ISSUE THREAD

**Issue by likecarson** [cuvent/react-native-vision-camera#2828]
### What's happening?

Recording video using selfie mode on Android device is upside down / inverted. While recording the video is correct orientation but when playing back the recorded video it is inverted.

### Reproduceable Code

```tsx
 const onStartRecording = () => {
    setDescriptionIsOpen(false);
    setRecodingState('recording');
    onRecordingStarted();
    cameraRef.current?.startRecording({
      videoCodec: 'h265',
      onRecordingFinished: (video) => {
        stopCountdown();
        stopStopWatch();
        onRecordingFinished(video);
        setTimeout(() => {
          setCountdown(0);
          setRecodingState('idle');
          setIsFrontCamera(false);
        }, 150);
      },
      onRecordingError: (error) => {
        stopCountdown();
        stopStopWatch();
        onRecordingError?.(error);
      },
    });
    startCountdown();
    startStopWatch();
  };

        <VisionCamera
          ref={mergeRefs}
          audio
          enableZoomGesture
          focusable
          video
          device={device}
          format={bestVideoFormat}
          isActive={isAppForeground && isFocused}
          orientation="portrait"
          photo={false}
          pixelFormat="yuv"
          style={StyleSheet.absoluteFill}
          torch={device.hasTorch ? (torchEnabled ? 'on' : 'off') : 'off'}
          videoHdr={false}
          videoStabilizationMode="off"
          zoom={device.neutralZoom}
        />

<Camera
        ref={videoRecorder}
        enableZoomGesture
        video
        device={device}
        format={bestVideoFormat}
        isActive={isAppForeground && isFocused}
        style={STYLES.camera}
      />

```

### Relevant log output

```shell
No error logs for this, everything records fine it just show the recording as inverted.
```

### Camera Device

```json
no device info, but can reproduce on Android emulator, and production Pixel devices.
```

### Device

Pixel 5 (Android 14), Pixel 7 (Android 14)

### VisionCamera Version

4.0.1

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
> no device info, but can reproduce on Android emulator, and production Pixel devices.

Without the device info, I have no idea what your scenario or environment is like.

> No error logs for this, everything records fine it just show the recording as inverted.

Without error logs I don't know what is happening before recording and how the Camera sets up the Media Encoder.


Closing due to lack of information
