### ISSUE TITLE
🐛Build false

### ISSUE THREAD

**Issue by namnotfake** [cuvent/react-native-vision-camera#2833]
### What's happening?

When I install and then build the app, I get this error. Previously, the build did not have an error
![image](https://github.com/mrousavy/react-native-vision-camera/assets/147969833/18eb2a21-0e9e-4194-9dc3-a658d976fd74)

### Reproduceable Code

```tsx
I just installed the package
```

### Relevant log output

```shell
![image](https://github.com/mrousavy/react-native-vision-camera/assets/147969833/18eb2a21-0e9e-4194-9dc3-a658d976fd74)
```

### Camera Device

```json
Android build
```

### Device

Xiaomi redmi 9T

### VisionCamera Version

4.0.0 beta 11

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [X] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
No information.
