### ISSUE TITLE
💭 Overlay using SVG does not match the camera preview on Android

### ISSUE THREAD

**Issue by xulihang** [cuvent/react-native-vision-camera#2845]
### Question

Before vision camera v4, I can use react-native-svg to draw the overlays.

I set the `viewBox` to the size of the frame and set its `preserveAspectRatio` to `xMidYMid slice`

But using vision camera v4, the overlay cannot match the preview perfectly on Android.

![Screenshot_2024-05-06-10-46-01-20_21e8d11a9a1dc95c0558350b4af085c6](https://github.com/mrousavy/react-native-vision-camera/assets/5462205/c5259386-031e-4102-8fe2-05bab2302d69)

I know I can now use Skia to draw to the frames. But as my old examples are all using react-native-svg, I am still using it to draw the overlay. I would like to know how to match the two correctly.

### VisionCamera Version

4.0.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by rahuldasgupta** [comment]
Hi, are you able to generate builds with Expo? I'm using:
"expo": "~48.0.21",
"react-native-vision-camera": "^4.0.1"

but when I run `npx expo run:android`, it shows the error tagged below
![image](https://github.com/mrousavy/react-native-vision-camera/assets/66947252/18d5dda9-5e6e-4120-86c3-8f0b04af3942)

**Comment by xulihang** [comment]
> Hi, are you able to generate builds with Expo? I'm using: "expo": "~48.0.21", "react-native-vision-camera": "^4.0.1"
> 
> but when I run `npx expo run:android`, it shows the error tagged below ![image](https://private-user-images.githubusercontent.com/66947252/328081249-18d5dda9-5e6e-4120-86c3-8f0b04af3942.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NzM5MjAsIm5iZiI6MTcxNDk3MzYyMCwicGF0aCI6Ii82Njk0NzI1Mi8zMjgwODEyNDktMThkNWRkYTktNWU2ZS00MTIwLTg2YzMtOGYwYjA0YWYzOTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA1MzM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkODFjNzBjNDIwYWE2Y2NlNjk5OTgxZDRiODE3NjRlYTBlMTc5MjYwOWM2MjJmYjU4MGRhMzU1NzQ2YzM2NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JBBX5HopkaA0COv0Z4-Tv7TlalUQLinRaeZKiw1PO5M)

Check out this: https://github.com/expo/expo/issues/19534#issuecomment-1277597917

**Comment by mrousavy** [comment]
I'm sorry, I don't know - there's no code here or any reference coordinates - I did the same thing previously and for me it worked.

**Comment by xulihang** [comment]
I think there is some difference between v2-3 and v4 on how the camera preview is sized. I am just lazy since if you know then I don't have to figure this out myself.

**Comment by mrousavy** [comment]
Yea no I'd have to play around with this myself as well.

Skia Frame Processors use exactly the Frame as a coordinate system, but if you want to draw something onto the screen you need to calculate the coordinates manually - which can be a bit tricky.

_Maybe_ I can add a helper method for that, but I think that's going to be asynchronous because it has to be used from the UI Thread (not sure why those limitations exist on native).

Otherwise you can calculate it yourself by getting video width/height -> aspect ratio, getting view width/height -> aspect ratio, calculate center crop (either height or width overflow), then put it on screen.

**Comment by tony-xlh** [comment]
Having a method to draw the overlay would be very helpful.

**Comment by xulihang** [comment]
Setting the resizeMode to contain can make the SVG match with the camera preview in my case.
