### ISSUE TITLE
Open Flash light  by click on the Icon

### ISSUE THREAD

**Issue by zoobibackups** [cuvent/react-native-vision-camera#2846]
### Question

how I open flash light when I click on Icon

### VisionCamera Version

"react-native-vision-camera": "^4.0.1"

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by zoobibackups** [comment]
> ### Question
> how I open flash light when I click on Icon
> 
> ### What I tried
const toggleFlash =() => {
      cameraRef.current?.CameraDevice({
        hasTorch: 'on'
      })
    }
> 
> ### VisionCamera Version
> "react-native-vision-camera": "^4.0.1"
> 
> ### Additional information
> * [ ]  I am using Expo
> * [x]  I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
> * [x]  I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
> * [x]  I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22%F0%9F%92%AD+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by bruno-centanaro** [comment]
Why not have a state variable for the torch?

**Comment by zoobibackups** [comment]
const [torch,setTorch] = useState(false);
const toggleFlash =() => {
    cameraRef.current?.CameraDevice({
    hasTorch: 'on',
    })
    setTorch(!torch)
    }
 <Camera
              hasTorch={torch}
              ref={cameraRef}
              style={StyleSheet.absoluteFill}
              device={device}
              isActive={isActive}
            />

but error is that cameraRef.current.CameraDevice is not a function it is undefined

**Comment by bruno-centanaro** [comment]
but why is it not a prop of the camera component? With [this](https://react-native-vision-camera.com/docs/api/interfaces/CameraProps#torch)
So it should be something like `torch={torch ? 'on' : 'off'}`
