### ISSUE TITLE
💭 Compatible React Native Versions

### ISSUE THREAD

**Issue by xulihang** [cuvent/react-native-vision-camera#2865]
### Question

What React Native versions are Vision Camera compatible?

I know Vision Camera v2 works for versions 0.6x.

But I don't know if Vision Camera v4 also works for react native 0.6x.

### VisionCamera Version

4.0.3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
VisionCamera V4 requires 0.71+ I _think_. Not entirely sure if 0.70 works.
New arch will soon require 0.74

**Comment by csicky** [comment]
Look at these guys at reanimated how nice a table they made https://docs.swmansion.com/react-native-reanimated/docs/3.x/guides/compatibility/
It would be so useful if rnvc would have a similar table too.
@mrousavy will you add something like this when you have time pls?
