### ISSUE TITLE
💭 How can I get realtime frames in JS context

### ISSUE THREAD

**Issue by hjawwad** [cuvent/react-native-vision-camera#2872]
### Question

I want to get all realtime frames when camera is active. For now I'm getting first frame and camera gets stuck, not sending next frame. 

### What I tried

I tried multiple ways to process realtime frames. I tried out with shared values. 

- Using Shared Values 
           
            const sharedlatestFrame = useSharedValue(new Uint8Array(0));
            const frameProcessor = useFrameProcessor(
              frame => {
                'worklet';
                if (frame.pixelFormat === 'rgb') {
                  const buffer = frame.toArrayBuffer();
                  const data = new Uint8Array(buffer);
            
                  console.log(`Pixel at 0,0: RGB(${data[0]}, ${data[1]}, ${data[2]})`);
                  sharedlatestFrame.value = data;
                }
                return null;
              },
              [],
            );

          <View style={{flex: 1}}>
                <Camera
                  ref={camera}
                  frameProcessor={frameProcessor}
                  format={format}
                  style={styles.max}
                  pixelFormat="rgb"
                  device={device}
                  isActive={true}
                  video={true}
                  audio={true}
                />
              </View>
It's not setting the value of shared value and get's stuck after receiving first frame in frameProcessor

- Using createRunOnJS

            const [buffer, setBuffer] = useState<Uint8Array>();
            const pushVideoFrame = Worklets.createRunOnJS((frame: Uint8Array) => {
                console.log(`Pixel at 0,0: RGB(${frame[0]}, ${frame[1]}, ${frame[2]})`);
                setBuffer(frame);
                sharedlatestFrame.value = frame;
              });
            
              const frameProcessor = useFrameProcessor(frame => {
                'worklet';
                if (frame.pixelFormat === 'rgb') {
                  const buffer = frame.toArrayBuffer();
                  const data = new Uint8Array(buffer);
            
                  pushVideoFrame(data);
                }
              }, []);
Same here it's not setting the value of state and shared Value. Here I'm receiving frames but only one or two frames in a minute. I also tried with `runAsync` but not able to send frames outside this worklet context. 

Is there any way to send frames to the main js context. 

### VisionCamera Version

4.0.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Why are you trying to send the Frame to JS?

**Comment by hjawwad** [comment]
I've to pass these frames to agora webRTC for video chat.

**Comment by mrousavy** [comment]
Yea well 4k RGB Frames are 33MB, so at 60 FPS that's 2 GB per second.

If you use a lower resolution (e.g. 1280x720) that's 3.6MB per Frame, at 30 FPS that's 110 MB per second.

I think you'd need to encode or compress them before sending them over the network.

Either way, the problem here is that `ArrayBuffer`s cannot be shared between Worklet runtimes.

What you need to do is to send the Frame itself to JS first:

```ts
frame.incrementRefCount() // <-- otherwise Frame is deleted by the time `something` is called
runOnJS(something)(frame)
```

and then in `something` you do:

```ts
const array = frame.toArrayBuffer()
frame.decremetRefCount() // <-- otherwise camera stalls
```

**Comment by hjawwad** [comment]
I tried it out but it's producing the errors. 

      const receiveFrame = (frame: any) => {
          if (frame.pixelFormat === 'rgb') {
            const buffer = frame.toArrayBuffer();
            const data = new Uint8Array(buffer);
            frame.decremetRefCount();
            console.log(`Pixel at 0,0: RGB(${data[0]}, ${data[1]}, ${data[2]})`);
          }
        };
      
        const frameProcessor = useFrameProcessor((frame: any) => {
          'worklet';
          frame.incrementRefCount();
          runOnJS(receiveFrame)(frame);
        }, []);

I change `receiveFrame` as worklet but it dosn't work. 

<img width="316" alt="Screenshot 2024-05-14 at 7 10 57 PM" src="https://github.com/mrousavy/react-native-vision-camera/assets/61308073/761c42a8-7fdd-4ddc-9f00-109cfbc36121">

Here is the repo link to checkout complete code
https://github.com/hjawwad/VideoFrames/blob/master/App.tsx

**Comment by mrousavy** [comment]
`runOnJS` is from Reanimated. We are using react-native-worklets-core, so you need to do `Worklets.createRunOnJS`.

**Comment by shaheer741** [comment]
@hjawwad 
were you able to resolve your issue?

**Comment by hjawwad** [comment]
Yes, but it's only processing 5 or 7 frames per second. On average it's taking 200ms per frame. 
@mrousavy Is this expected behaviour or it's taking more time for me. 
  
    const pushVideoFrame = Worklets.createRunOnJS(
      async (resized: any, frame: FrameInternal) => {
        console.log(`Pixel in RGB ${resized[0]}, ${resized[1]}, ${resized[2]}`);
        frame.decrementRefCount();
      },
    );
  
    const frameProcessor = useFrameProcessor((frame: any) => {
      'worklet';
      runAtTargetFps(20, () => {
        'worklet';
        const start = performance.now();
        if (frame.pixelFormat === 'yuv') {
          const buffer = resize(frame, {
            scale: {
              width: 50,
              height: 100,
            },
            pixelFormat: 'rgba',
            dataType: 'uint8',
          });
  
          frame.incrementRefCount();
          pushVideoFrame(buffer!, frame);
          const end = performance.now();
  
          const diff = (end - start).toFixed(2);
          console.log(`Push Video Frames took ${diff}ms!`);
        }
      });
    }, []);
<img width="383" alt="Screenshot 2024-05-22 at 6 31 22 PM" src="https://github.com/mrousavy/react-native-vision-camera/assets/61308073/7242b64e-b8a4-47a2-991f-4b1512565d8e">

**Comment by ghost** [comment]
@hjawwad 

Did you solve it? I wonder how you did it.
