### ISSUE TITLE
💭 Android Camera view width/height and photo width/height not the same.

### ISSUE THREAD

**Issue by OlviXhaferaj** [cuvent/react-native-vision-camera#2875]
### Question

So I take the photo with camera.current.takePhoto function. The problem that I am facing, in android specifically, is that when I take a photo, if the camera view is set to, lets say, 370 width 700 height, the width of the photo is bigger or smaller than the view of the camera. For example if I resized the photo, it would be 400 width 700 height or something like that (this are just numbers to demonstrate). 

What I saw is that the photo width output is different if I play with the photoResolution. If i set it to max, the photo width is bigger than what the camera sees, while if I dont set the photoResolution, the camera defaults to the best next resolution i guess, and the width appears to be smaller than the width of the view of the camera. 

I want to take a photo and the output of it should be equal to the view that is presented to the user, not bigger or smaller than what the user sees.

Reason why this is a problem for me is because I want to make some automatic croping. The photo width/height ratio should be the same as the width/height ratio of the camera view.

If someone has some answer, would be appreciated!

### What I tried

What I tried to solve this is setting the resizeMode="contain", and tried to understand how setting the format would work and change things.

### VisionCamera Version

3.9.2

### Additional information

- [X] I am using Expo
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
This is not how cameras work. There are fixed formats for the Camera, and you need to find a format that most closely matches what you desire - then do some cropping afterwards to get exact permissions.
