### ISSUE TITLE
🐛 Android Back Camera Zoom Breaks in 4.0.4

### ISSUE THREAD

**Issue by elirichey** [cuvent/react-native-vision-camera#2884]
### What's happening?

If using the back camera, the video preview freezes. If recording, the frame freezes and recording stops.
Front camera works fine. 

### Reproduceable Code

```tsx
<Camera
            ref={cameraRef}
            style={cameraStyle}
            device={device}
            isActive={isFocused}
            onInitialized={onInitialized}
            onError={onError}
            enableZoomGesture={true}
            photo={config.photo}
            video={config.video}
            audio={config.video}
            enableLocation={locationPermission}
            videoStabilizationMode={videoStabilizationMode}
            format={format}
            orientation={'portrait'}
            frameProcessor={frameProcessor}
          />
```

### Relevant log output

```shell
[ERROR  ] chifeature2anchorsync.cpp:2536 UpdateSnapshotCropRegion() FRO-URO:796_MCXSuperFG:AnchorSync_0 Crop type RDI PSM crop (0 0 4080 3060) HAL Crop (0 0 4080 3060) Precrop (0 0 4080 3060) activeMask L 2 P 0 master 0
[ERROR  ] chifeature2anchorsync.cpp:2501 UpdateSnapshotCropRegion() Incorrect FD crop (0 0 640 480) Dim 640x480
[ERROR  ] chifeature2anchorsync.cpp:2536 UpdateSnapshotCropRegion() FRO-URO:796_MCXSuperFG:AnchorSync_0 Crop type FD PSM crop (0 0 640 480) HAL Crop (0 0 4080 3060) Precrop (0 0 4080 3060) activeMask L 2 P 0 mas[SS_ERR ]: [CHI         ]: chxextensionmodule.cpp: CheckGPSCoordinate: 24377: [EXIF_DBG] GetTag ANDROID_JPEG_GPS_COORDINATES Failed. frame(795)ter 0
MinkIPC_QRTR_Service: client with node 1 port 4ca6 went down
```

### Camera Device

```json
{
  "formats": [],
  "sensorOrientation": "landscape-left",
  "hardwareLevel": "full",
  "maxZoom": 10,
  "minZoom": 0.6000000238418579,
  "maxExposure": 20,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera",
    "ultra-wide-angle-camera",
    "wide-angle-camera",
    "telephoto-camera",
    "telephoto-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": false,
  "isMultiCam": true,
  "minFocusDistance": 0,
  "minExposure": -20,
  "name": "0 (BACK) androidx.camera.camera2",
  "hasFlash": true,
  "hasTorch": true,
  "position": "back",
  "id": "0"
}
```

### Device

Galaxy S23 Ultra

### VisionCamera Version

4.0.4

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
1. Not enough logs. I have no idea where you got those logs from, but they are not `adb logcat` logs, and also that's just 4 lines.
2. I don't really get what the problem is - what does "If using the back camera, the video preview freezes. If recording, the frame freezes and recording stops." mean?

**Comment by mrousavy** [comment]
Closing as there was no reply - we can reopen once you provide more details. 👍
