### ISSUE TITLE
✨ Contrast

### ISSUE THREAD

**Issue by RutvinBhanderi** [cuvent/react-native-vision-camera#2888]
### What feature or enhancement are you suggesting?

I think it would be great to have a contrast feature. 

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

I am trying to find a way to add contrast. need help to add this.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
There's no such thing as contrast in a Camera.
Contrast is a filter which you would do in post-processing.
