### ISSUE TITLE
💭 Why the Photo Result Does Not Come Out in the Specified Aspect Ratio

### ISSUE THREAD

**Issue by seereal-beomjin** [cuvent/react-native-vision-camera#2894]
### Question

When I set photoAspectRatio to 1/1 and photoResolution to 3048, which is a 1:1 ratio, and take a picture, the resulting width and height do not come out at 1:1.

I'm using samsung galaxy s10

### What I tried

```
const format = useCameraFormat(device, [
    {videoAspectRatio: ratio}, // 1:1
    {photoAspectRatio: ratio}, // 1:1 
    {photoResolution: {width: 3048, height: 3048}},
  ]);
```

the output is 

```
{"height": 288, "isMirrored": false, "isRawPhoto": false, "orientation": "landscape-left", "path": "/data/user/0/com.../cache/mrousavy2801553129656230601.jpg", "width": 352}
```

### VisionCamera Version

3.9.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
That's not how formats work. Please read the formats documentation. Formats is what your phone natively supports, 1:1 ratio is probably not natively supported as sensors are usually 4:3.

You need to crop the photo yourself after taking it.
