### ISSUE TITLE
💭 Focus not work

### ISSUE THREAD

**Issue by gh-pro** [cuvent/react-native-vision-camera#2906]
### Question

On a camera device mountain, not focus work on preview mode how to force focus in preview mode ?

### What I tried

i try to take a photo but focus not work and preview in blur

### VisionCamera Version

4..0.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
👍
