### ISSUE TITLE
💭 How does RNVC interact with OS camera settings?

### ISSUE THREAD

**Issue by titanium-cranium** [cuvent/react-native-vision-camera#2919]
### Question

I'm just wondering what happens when a user changes the OS settings for the camera and how that interacts (or does not) with RNVC.   Are there other OS settings that would influence RNVC?  Accessibility? 

e.g. iOS17 Camera settings. (just an example, I'm sure this applies to android as well)
![IMG_D1A2C17C3F8A-1](https://github.com/mrousavy/react-native-vision-camera/assets/15062524/74ed5a63-e8a0-4460-820e-3cb72cd3411a)

### What I tried

Not really necessary for this question.  

Note though, the "in the discussions page" link below is not functional and there is no "discussions" tab above. 

### VisionCamera Version

v4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
This doesn't change anything - those settings only exist for the stock Camera app.

You can build all those settings yourself in your VisionCamera app as well. Resolution, Frame Rate, Codec, etc
