### ISSUE TITLE
💭 Hello, Which version of react-native-vision-camera supports RN 0.67?

### ISSUE THREAD

**Issue by zhengjialu520** [cuvent/react-native-vision-camera#2924]
### Question

Hello team, my project's React Native version is 0.67, and it's quite challenging to upgrade to the latest version due to the project's size. Therefore, I'd like to ask which tag of react-native-vision-camera supports 0.67. I tried Tag 3.9.0, but it seems to require RN 0.70.

### What I tried

The error occurred at this step.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.facebook.react:react-android:+ as no versions of com.facebook.react:react-android are available.
     Searched in the following locations:
       - file:/Users/zhengjialu/Desktop/ryapp/ryapp/node_modules/react-native/android/com/facebook/react/react-android/maven-metadata.xml
     Required by:
         project :app > project :react-native-vision-camera
   > Could not find com.google.mlkit:barcode-scanning:17.2.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/google/mlkit/barcode-scanning/17.2.0/barcode-scanning-17.2.0.pom
       - file:/Users/zhengjialu/.m2/repository/com/google/mlkit/barcode-scanning/17.2.0/barcode-scanning-17.2.0.pom
       - file:/Users/zhengjialu/Desktop/ryapp/ryapp/node_modules/react-native/android/com/google/mlkit/barcode-scanning/17.2.0/barcode-scanning-17.2.0.pom
       - https://maven.aliyun.com/repository/google/com/google/mlkit/barcode-scanning/17.2.0/barcode-scanning-17.2.0.pom
       - https://maven.aliyun.com/repository/jcenter/com/google/mlkit/barcode-scanning/17.2.0/barcode-scanning-17.2.0.pom
       - https://maven.aliyun.com/nexus/content/groups/public/com/google/mlkit/barcode-scanning/17.2.0/barcode-scanning-17.2.0.pom
       - https://developer.huawei.com/repo/com/google/mlkit/barcode-scanning/17.2.0/barcode-scanning-17.2.0.pom
       - https://jitpack.io/com/google/mlkit/barcode-scanning/17.2.0/barcode-scanning-17.2.0.pom
       - file:/Users/zhengjialu/Desktop/ryapp/ryapp/node_modules/jsc-android/dist/com/google/mlkit/barcode-scanning/17.2.0/barcode-scanning-17.2.0.pom
       - https://repo1.maven.org/maven2/com/google/mlkit/barcode-scanning/17.2.0/barcode-scanning-17.2.0.pom
       - https://www.jitpack.io/com/google/mlkit/barcode-scanning/17.2.0/barcode-scanning-17.2.0.pom
       - https://nexus-online.speedtest.cn/repository/speedtest-release/com/google/mlkit/barcode-scanning/17.2.0/barcode-scanning-17.2.0.pom
       - file:/Users/zhengjialu/Desktop/ryapp/ryapp/android/app/libs/barcode-scanning-17.2.0.jar
       - file:/Users/zhengjialu/Desktop/ryapp/ryapp/android/app/libs/barcode-scanning.jar
     Required by:
         project :app > project :react-native-vision-camera

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

<img width="733" alt="image" src="https://github.com/mrousavy/react-native-vision-camera/assets/67678652/eb0e9354-f3b5-4706-afdc-9db8bc170af4">

### VisionCamera Version

3.9.0

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey - yea I honestly don't know. Maybe an old V2 version. Upgrading to RN 0.74 is really recommended, there's tons of improvements in the latest releases. We can help you migrate/upgrade your RN version as well.
