### ISSUE TITLE
✨ How can I save the video recording when the app state changes to "background" or "inactive". 

### ISSUE THREAD

**Issue by prasan2421** [cuvent/react-native-vision-camera#2938]
### What feature or enhancement are you suggesting?

On ios, while recording and you put the app on background and then reopen, the video cannot be saved anymore. I am using 'react-native-background-actions' to capture the video using 'onRecordingFinished' after calling stopRecording() but the error is still there. 

### What Platforms whould this feature/enhancement affect?

iOS

### Alternatives/Workarounds

No alternatives yet.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
> but the error is still there.

There's no error here in this issue.
