### ISSUE TITLE
Using react-native-vision-camera 4.0.5 there is increase of 3MB size in android bundle

### ISSUE THREAD

**Issue by shubhamdeol** [cuvent/react-native-vision-camera#2943]
### What's happening?

I have started using this library. I can notice there is size increase of 3MB. 
<img width="452" alt="Screenshot 2024-06-06 at 5 41 14 PM" src="https://github.com/mrousavy/react-native-vision-camera/assets/11364449/5f97a630-b168-4892-b4cd-a3b473b3dc70">

### Reproduceable Code

```tsx
NA
```

### Relevant log output

```shell
NA
```

### Camera Device

```json
NA
```

### Device

android

### VisionCamera Version

4.0.5

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [X] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by shubhamdeol** [comment]
Does META_DATA folder gets included in release build?
I am not sure if this is actually an issue

**Comment by mrousavy** [comment]
VisionCamera is quite a big library with C++ files and a dependency on the Barcode scanner. I think 3MB are not critical. 

What's the issue?

If there's anything in there that shouldn't be in there (like META_DATA) then please let me know.

**Comment by shubhamdeol** [comment]
I have done further analysis on app size using `bundletool`. It seems `META_DATA ` folder android studio app analyzer shows does not gets contribute to final app size. Library only takes 76.3 kb of native java classes on android. 
<img width="952" alt="Screenshot 2024-06-06 at 6 48 08 PM" src="https://github.com/mrousavy/react-native-vision-camera/assets/11364449/8288ceb1-b381-4665-813c-d75297cdcbc9">

So closing the issues. Thanks for quick revert.
