### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by chrispader** [cuvent/react-native-vision-camera#2966]
### What's happening?

aoishdawd

### Reproduceable Code

```tsx
htrthrhz45rzu54z45
htrthrhz45rzu54z45
htrthrhz45rzu54z45
htrthrhz45rzu54z45
htrthrhz45rzu54z45
```

### Relevant log output

```shell
.,>>../,.,.
htrthrhz45rzu54z45des
htrthrhz45rzu54z45
htrthrhz45rzu54z45
htrthrhz45rzu54z45
```

### Camera Device

```json
123456
htrthrhz45rzu54z45
htrthrhz45rzu54z45
htrthrhz45rzu54z45
htrthrhz45rzu54z45
```

### Device

macbook pro xs

### VisionCamera Version

-2.6°

### Can you reproduce this issue in the VisionCamera Example app?

No, I cannot reproduce the issue in the Example app

### Additional information

- [X] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Thank you Hans for your service

**Comment by chrispader** [comment]
Thank you Hans! You're such a valuable part of our community ❤️

**Comment by mrousavy** [comment]
Thank you @maintenance-hans

**Comment by mrousavy** [comment]
thank you hans 👍

**Comment by mrousavy** [comment]
danke hans
