### ISSUE TITLE
🐛 Hello, I have a question for you... we use your plugin, but we have a problem with the fact that the preview is smaller than the filmed or photographed area. how should we solve this?

### ISSUE THREAD

**Issue by MilanRadon** [cuvent/react-native-vision-camera#2975]
### What's happening?

Hello, I have a question for you... we use your plugin, but we have a problem with the fact that the preview is smaller than the filmed or photographed area. how should we solve this?

### Reproduceable Code

```tsx
example app
```

### Relevant log output

```shell
no
```

### Camera Device

```json
all
```

### Device

Iphone 15 pro

### VisionCamera Version

4.1

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [X] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
thank you hans 👍
