### ISSUE TITLE
💭 Diffrent area - video/photo

### ISSUE THREAD

**Issue by MilanRadon** [cuvent/react-native-vision-camera#2976]
### Question

Hello, I have a question for you... we use your plugin, but we have a problem with the fact that the preview is smaller than the filmed or photographed area. how should we solve this?

### VisionCamera Version

4.1

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey - Please read the [Formats](https://react-native-vision-camera.com/docs/guides/formats) documentation, or ask this on the community discord. Thanks
