### ISSUE TITLE
💭 How to get preview size (height and width) on resizeMode="contain"

### ISSUE THREAD

**Issue by MilanRadon** [cuvent/react-native-vision-camera#2981]
### Question

How to get preview size (height and width) on resizeMode="contain"?

### VisionCamera Version

"^3.9.2"

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Milan - please read the docs before posting issues here in the repo. This is the third issue you created within 3 hours that could've been answered immediately if you just read the docs.

**Comment by MilanRadon** [comment]
@mrousavy you don't write anywhere how to get the size of the preview... how to determine the size, yes...

**Comment by alex-alecu** [comment]
There is a workaround:

```js
const format = useCameraFormat(device, [{ videoResolution: 'max' }, { photoResolution: 'max' }]);
const windowWidth = Dimensions.get('window').width;
const previewHeight = format ? (format.photoWidth / format.photoHeight) * windowWidth : 0;
``` 

We know the photo resolution e.g. `photoHeight: 6048; photoWidth: 8064` and we know the width of our preview, so we can compute the height
