### ISSUE TITLE
💭 onIitialized only work when the isActive once.

### ISSUE THREAD

**Issue by minhkwan** [cuvent/react-native-vision-camera#2983]
### Question

Hello. I just update react-native-vision-camera from 3.9.2.
In 3.9.2 I used:
  const [isCameraInitialized, setIsCameraInitialized] = useState(
    // Platform.OS === 'android' ? true : 
    false,
  );

Camera:
isActive={isCameraInitialized && isActive} 
onInitialized={onInitialized}

  const onInitialized = useCallback(() => {
    setIsCameraInitialized(true);
  }, []);

In 4.2.1:
With the same code, the onInitialized seems never run. It will run as normal only when I set 
  const [isCameraInitialized, setIsCameraInitialized] = useState(
    Platform.OS === 'android' ? true : false,
  );
  
  I have to make it true once then the onInitialized on work after then. I make it true once, the camera open, then I change isCameraInitialized to false in my code. Even after that, the onInitialized still works fine. It seems like it has to be "true" at least once since I install the application
Is this normal?

### VisionCamera Version

4.2.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Check out the new documentation on [Lifecycle Events](https://react-native-vision-camera.com/docs/guides/lifecycle#events), `onInitialized` will always be called when outputs are there (preview, photo, video whatever) - and `onStarted` afterwards.
