### ISSUE TITLE
✨ Hello author, can you add a cropping function after taking the photo?

### ISSUE THREAD

**Issue by sanguineman91** [cuvent/react-native-vision-camera#2990]
### What feature or enhancement are you suggesting?

Hello author, can you add a cropping function after taking the photo? Thank you very much✨ [](url)

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

Hello author, can you add a cropping function after taking a photo? That is, after taking a photo, you can rotate, crop, enlarge it, etc. before sending or saving it.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by jthure** [comment]
There's a lightweight lib that does exactly that, [@react-native-community/image-editor
](https://github.com/callstack/react-native-image-editor). It's trivial to take output of the photo capture and crop/resize with that lib. Imo there's no need to have this in vision-camera

**Comment by mrousavy** [comment]
Hey - no, because this is related to image manipulation. If I add every feature that is related to media stuff, VisionCamera's codebase will get way too big.
