### ISSUE TITLE
🐛 system/camera-is-restricted Camera functionality is not available because it has been restricted by the operating system, possibly due to a device policy.

### ISSUE THREAD

**Issue by iliapnmrv** [cuvent/react-native-vision-camera#2991]
### What's happening?

Not sure if it is related to library but got an error in [Sentry](https://sentry.vibeapp.ru/share/issue/c277872cd5a940e4a2ddccacba42830b/)

> system/camera-is-restricted: Camera functionality is not available because it has been restricted by the operating system, possibly due to a device policy.

Any suggestions why can this happen?

### Reproduceable Code

```tsx
const device = useCameraDevice('back', {
    physicalDevices: [
      'ultra-wide-angle-camera',
      'telephoto-camera',
      'wide-angle-camera',
    ],
  });

<ReanimatedCamera
  format={format}
  zoom={device.neutralZoom}
  device={device}
  isActive={isCameraActive}
  onError={onError}
  codeScanner={codeScanner}
  animatedProps={cameraAnimatedProps}
  ref={cameraRef}
/>
```

### Relevant log output

```shell
09:03:47 I ReactNativeJS: Re-rendering App. Camera: undefined | Microphone: undefined
09:03:47 I VisionCamera: Installing JSI bindings...
```

### Camera Device

```json
{
"id": 0,
"devices": "wide-angle-camera",
"name": "0 (BACK) androidx.camera.camera2"
}
```

### Device

Samsung SM-G996B, Android 14

### VisionCamera Version

4.3.1

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by iliapnmrv** [comment]
could not add logs because its not a local bug

**Comment by jkaufman** [comment]
I’d expect this from either MDM or parental controls.

**Comment by mrousavy** [comment]
> I’d expect this from either MDM or parental controls.

Exactly. Nothing I can do.

**Comment by rohit-jindal018** [comment]
@mrousavy We are also facing the issue in Samsung devices and it gets corrected on killing the Application.

**Comment by iliapnmrv** [comment]
@rohit-jindal018 hey! did you manage to solve it? I use barcode scanner exactly from example app.

in sentry app just went from background state to foreground. In sentry its also mostly samsung devices

https://sentry.vibeapp.ru/share/issue/c277872cd5a940e4a2ddccacba42830b/

**Comment by ngocdevv** [comment]
I think this problem is due to AppState, you only need to handle it when the application is in active mode for the camera to be activated.

interface useAppStateCheckProps {
  setAppStateStatus: React.Dispatch<React.SetStateAction<AppStateStatus>>;
}
export default function useAppStateCheck(props: useAppStateCheckProps) {
  const { setAppStateStatus } = props;
  const handleAppStateChange = useCallback(async (nextAppState: AppStateStatus) => {
    setAppStateStatus(nextAppState);
  }, [setAppStateStatus]);
  useEffect(() => {
    let eventListener: NativeEventSubscription;
    eventListener = AppState.addEventListener('change', handleAppStateChange);
    return () => {
      eventListener && eventListener.remove();
    };
  }, [handleAppStateChange]);
}

(hasPermission && appStateStatus) && (
                <Camera
                  photo
                  ref={cameraRef}
                  device={devices}
                  outputOrientation={"device"}
                  preview
                  isActive
                  zoom={0}
                  style={StyleSheet.absoluteFillObject}
                />
              )

**Comment by rohit-jindal018** [comment]
> @rohit-jindal018 hey! did you manage to solve it? I use barcode scanner exactly from example app.
> 
> in sentry app just went from background state to foreground. In sentry its also mostly samsung devices
> 
> https://sentry.vibeapp.ru/share/issue/c277872cd5a940e4a2ddccacba42830b/

Hi, Yes we were able to fix it temporarily by unmounting the component whenever the app went into background. issue occured only when app went into background with scanner in opened state. So if user was on scanner page and he took the app into background, we unmounted the component and took him to the previous screen

**Comment by ngocdevv** [comment]
> > @rohit-jindal018Này! Bạn đã giải quyết được chưa? Tôi sử dụng máy quét mã vạch chính xác từ ứng dụng ví dụ.
> > trong ứng dụng Sentry chỉ chuyển từ trạng thái nền sang trạng thái nền trước. Trong Sentry, nó cũng chủ yếu là các thiết bị Samsung
> > https://sentry.vibeapp.ru/share/issue/c277872cd5a940e4a2ddccacba42830b/
> 
> Xin chào, Vâng, chúng tôi có thể sửa lỗi tạm thời bằng cách hủy gắn thành phần bất cứ khi nào ứng dụng chuyển sang chế độ nền. Sự cố chỉ xảy ra khi ứng dụng chuyển sang chế độ nền với máy quét ở trạng thái mở. Vì vậy, nếu người dùng đang ở trang máy quét và anh ta đưa ứng dụng vào chế độ nền, chúng tôi đã hủy gắn thành phần và đưa anh ta đến màn hình trước đó

After testing on Samsung and Xiaomi devices, I use the isActive field, to handle the above error, combined with AppState to capture the application state.
isActive={appStateStatus === "active"}

**Comment by iliapnmrv** [comment]
@rohit-jindal018 could you please also share your code?
@ngocleexuan I have the same logic, i copied it from this library. It fixed for me on almost all devices except some samsungs
https://github.com/mrousavy/react-native-vision-camera/blob/main/package/example/src/hooks/useIsForeground.ts

**Comment by jkaufman** [comment]
Sure enough, I'm hitting this, now, too. Thanks @ngocleexuan, @rohit-jindal018 for the tips. I think it's occurring in our app due to a misunderstanding of React Navigation `focus` state. We set `isActive` through the `useIsFocused` hook, but should rely on app state directly.

**Comment by jordanhippotec** [comment]
> > > @rohit-jindal018Này! Bạn đã giải quyết được chưa? Tôi sử dụng máy quét mã vạch chính xác từ ứng dụng ví dụ.
> > > trong ứng dụng Sentry chỉ chuyển từ trạng thái nền sang trạng thái nền trước. Trong Sentry, nó cũng chủ yếu là các thiết bị Samsung
> > > https://sentry.vibeapp.ru/share/issue/c277872cd5a940e4a2ddccacba42830b/
> > 
> > 
> > Xin chào, Vâng, chúng tôi có thể sửa lỗi tạm thời bằng cách hủy gắn thành phần bất cứ khi nào ứng dụng chuyển sang chế độ nền. Sự cố chỉ xảy ra khi ứng dụng chuyển sang chế độ nền với máy quét ở trạng thái mở. Vì vậy, nếu người dùng đang ở trang máy quét và anh ta đưa ứng dụng vào chế độ nền, chúng tôi đã hủy gắn thành phần và đưa anh ta đến màn hình trước đó
> 
> After testing on Samsung and Xiaomi devices, I use the isActive field, to handle the above error, combined with AppState to capture the application state. isActive={appStateStatus === "active"}

Work for me! thank you

**Comment by Tobbe** [comment]
This hook works great with the `isActive` prop on the `<Camera ... />` component

```tsx
import {useEffect, useState} from 'react'
import {AppState, AppStateStatus} from 'react-native'

export function useAppState() {
  const currentState = AppState.currentState
  const [appState, setAppState] = useState(currentState)

  useEffect(() => {
    function onChange(newState: AppStateStatus) {
      setAppState(newState)
    }

    const subscription = AppState.addEventListener('change', onChange)

    return () => {
      subscription.remove()
    }
  }, [])

  return appState
}
```
From https://github.com/react-native-community/hooks/blob/main/src/useAppState.ts

I use it like this
```tsx
<Camera
  style={StyleSheet.absoluteFill}
  device={device}
  isActive={appState === "active"}
  codeScanner={codeScanner}
/>
```

**Comment by iliapnmrv** [comment]
I have something like this
```js
const isFocused = useIsFocused();
const isForeground = useIsForeground();
const isActive = isFocused && isForeground;
```

and almost the same `Camera` component logic
```js
<Camera
  style={StyleSheet.absoluteFill}
  device={device}
  isActive={isActive}
  codeScanner={codeScanner}
/>
```

And also I've enabled the New Architecture and now I have around 3k events in Sentry in just 2 weeks

@Tobbe do you have the New Architecture enabled in your app?

**Comment by Tobbe** [comment]
No, I'm still on old arch. And I've only tested this with my own Pixel 8 Pro and Pixel 6A phones. Not any Samsung devices.

**Comment by iliapnmrv** [comment]
Somehow I also have errors in old arch but I've had the same logic for months 🤷‍♂️
But in logs I have firstly this:
08:33:32 
```js
{
  state: background
}
```
and then
08:33:32 
```
system/camera-is-restricted: Camera functionality is not available because it has been restricted by the operating system, possibly due to a device policy.
```

useIsForeground looks like [this](https://github.com/mrousavy/react-native-vision-camera/blob/main/example/src/hooks/useIsForeground.ts) 


Here are the logs from Sentry from New Architecture

| Timestamp                        | Level | Message                                                                                                           | Category     | Info                                             |
|----------------------------------|-------|-------------------------------------------------------------------------------------------------------------------|--------------|--------------------------------------------------|
| 2025-02-10T14:24:19.802000Z       | info  | Output orientation changed! PORTRAIT                                                                              | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:19.803000Z       | info  | invokeOnOutputOrientationChanged(PORTRAIT)                                                                        | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:19.862000Z       | info  | Output orientation changed! LANDSCAPE_LEFT                                                                        | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:19.863000Z       | info  | invokeOnOutputOrientationChanged(LANDSCAPE_LEFT)                                                                  | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:19.883000Z       | info  | Output orientation changed! PORTRAIT                                                                              | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:19.884000Z       | info  | invokeOnOutputOrientationChanged(PORTRAIT)                                                                        | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:19.944000Z       | info  | Output orientation changed! LANDSCAPE_RIGHT                                                                       | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:19.945000Z       | info  | invokeOnOutputOrientationChanged(LANDSCAPE_RIGHT)                                                                 | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:20.003000Z       | info  | Output orientation changed! PORTRAIT                                                                              | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:20.003000Z       | info  | invokeOnOutputOrientationChanged(PORTRAIT)                                                                        | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:20.083000Z       | info  | Output orientation changed! LANDSCAPE_LEFT                                                                        | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:20.084000Z       | info  | invokeOnOutputOrientationChanged(LANDSCAPE_LEFT)                                                                  | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:20.123000Z       | info  | Output orientation changed! PORTRAIT                                                                              | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:20.124000Z       | info  | invokeOnOutputOrientationChanged(PORTRAIT)                                                                        | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:20.145000Z       | info  | Output orientation changed! LANDSCAPE_LEFT                                                                        | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:20.146000Z       | info  | invokeOnOutputOrientationChanged(LANDSCAPE_LEFT)                                                                  | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:20.262000Z       | info  | Output orientation changed! PORTRAIT                                                                              | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:20.262000Z       | info  | invokeOnOutputOrientationChanged(PORTRAIT)                                                                        | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:20.502000Z       | info  | Output orientation changed! LANDSCAPE_LEFT                                                                        | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:20.503000Z       | info  | invokeOnOutputOrientationChanged(LANDSCAPE_LEFT)                                                                  | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:20.544000Z       | info  | Output orientation changed! PORTRAIT                                                                              | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:20.545000Z       | info  | invokeOnOutputOrientationChanged(PORTRAIT)                                                                        | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:20.645000Z       | info  | Output orientation changed! LANDSCAPE_LEFT                                                                        | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:20.646000Z       | info  | invokeOnOutputOrientationChanged(LANDSCAPE_LEFT)                                                                  | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:20.801000Z       | info  | invokeOnAverageFpsChanged(0.0)                                                                                      | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:21.461000Z       | info  | Output orientation changed! PORTRAIT                                                                              | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:21.461000Z       | info  | invokeOnOutputOrientationChanged(PORTRAIT)                                                                        | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:21.801000Z       | info  | invokeOnAverageFpsChanged(0.0)                                                                                      | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:21.921000Z       | info  | Output orientation changed! LANDSCAPE_LEFT                                                                        | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:21.922000Z       | info  | invokeOnOutputOrientationChanged(LANDSCAPE_LEFT)                                                                  | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:22.041000Z       | info  | Output orientation changed! PORTRAIT                                                                              | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:22.042000Z       | info  | invokeOnOutputOrientationChanged(PORTRAIT)                                                                        | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:22.401000Z       | info  | Output orientation changed! LANDSCAPE_LEFT                                                                        | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:22.402000Z       | info  | invokeOnOutputOrientationChanged(LANDSCAPE_LEFT)                                                                  | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:22.441000Z       | info  | Output orientation changed! PORTRAIT                                                                              | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:22.441000Z       | info  | invokeOnOutputOrientationChanged(PORTRAIT)                                                                        | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:22.461000Z       | info  | Output orientation changed! LANDSCAPE_LEFT                                                                        | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:22.461000Z       | info  | invokeOnOutputOrientationChanged(LANDSCAPE_LEFT)                                                                  | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:22.501000Z       | info  | Output orientation changed! PORTRAIT                                                                              | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:22.501000Z       | info  | invokeOnOutputOrientationChanged(PORTRAIT)                                                                        | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:22.541000Z       | info  | Output orientation changed! LANDSCAPE_LEFT                                                                        | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:22.541000Z       | info  | invokeOnOutputOrientationChanged(LANDSCAPE_LEFT)                                                                  | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:22.581000Z       | info  | Output orientation changed! PORTRAIT                                                                              | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:22.581000Z       | info  | invokeOnOutputOrientationChanged(PORTRAIT)                                                                        | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:22.801000Z       | info  | invokeOnAverageFpsChanged(0.0)                                                                                      | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:22.881000Z       | info  | Output orientation changed! LANDSCAPE_LEFT                                                                        | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:22.881000Z       | info  | invokeOnOutputOrientationChanged(LANDSCAPE_LEFT)                                                                  | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:22.942000Z       | info  | Output orientation changed! PORTRAIT                                                                              | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:22.943000Z       | info  | invokeOnOutputOrientationChanged(PORTRAIT)                                                                        | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:23.021000Z       | info  | Output orientation changed! LANDSCAPE_LEFT                                                                        | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:23.022000Z       | info  | invokeOnOutputOrientationChanged(LANDSCAPE_LEFT)                                                                  | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:23.163000Z       | info  | Output orientation changed! PORTRAIT                                                                              | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:23.163000Z       | info  | invokeOnOutputOrientationChanged(PORTRAIT)                                                                        | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:23.202000Z       | info  | Output orientation changed! LANDSCAPE_LEFT                                                                        | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:23.202000Z       | info  | invokeOnOutputOrientationChanged(LANDSCAPE_LEFT)                                                                  | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:23.443000Z       | info  | Output orientation changed! PORTRAIT                                                                              | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:23.443000Z       | info  | invokeOnOutputOrientationChanged(PORTRAIT)                                                                        | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:23.774000Z       | info  |                                                                                                                   | device.event | action: SCREEN_ON, extras: why=1                 |
| 2025-02-10T14:24:23.788000Z       | info  |                                                                                                                   | device.event | action: DREAMING_STOPPED                         |
| 2025-02-10T14:24:23.801000Z       | info  | invokeOnAverageFpsChanged(0.0)                                                                                      | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:24.802000Z       | info  | invokeOnAverageFpsChanged(0.0)                                                                                      | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:25.095000Z       | info  | PreviewView Stream State changed to IDLE                                                                          | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:25.095000Z       | info  | invokeOnPreviewStopped()                                                                                            | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:25.099000Z       | info  | Camera State: OPENING (has error: true)                                                                           | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:25.099000Z       | info  | invokeOnStopped()                                                                                                 | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:25.101000Z       | error | invokeOnError(...):                                                                                               | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:25.150000Z       | fatal | device/camera-already-in-use: The given Camera Device is already in use!                                            | sentry.event |                                                  |
| 2025-02-10T14:24:25.257000Z       | info  | Camera #0 is now available.                                                                                       | Logcat       | tag: CameraDevices                               |
| 2025-02-10T14:24:25.803000Z       | info  | invokeOnAverageFpsChanged(0.0)                                                                                      | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:26.266000Z       | info  | Camera State: OPENING (has error: false)                                                                          | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:26.277000Z       | info  | Camera State: OPENING (has error: true)                                                                           | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:26.277000Z       | error | invokeOnError(...):                                                                                               | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:26.324000Z       | fatal | system/max-cameras-in-use: The maximum amount of Cameras available for simultaneous use has been reached!          | sentry.event |                                                  |
| 2025-02-10T14:24:26.541000Z       | info  | Output orientation changed! LANDSCAPE_LEFT                                                                        | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:26.541000Z       | info  | invokeOnOutputOrientationChanged(LANDSCAPE_LEFT)                                                                  | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:26.581000Z       | info  | Output orientation changed! PORTRAIT                                                                              | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:26.581000Z       | info  | invokeOnOutputOrientationChanged(PORTRAIT)                                                                        | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:26.661000Z       | info  | Output orientation changed! LANDSCAPE_LEFT                                                                        | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:26.661000Z       | info  | invokeOnOutputOrientationChanged(LANDSCAPE_LEFT)                                                                  | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:26.701000Z       | info  | Output orientation changed! PORTRAIT                                                                              | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:26.701000Z       | info  | invokeOnOutputOrientationChanged(PORTRAIT)                                                                        | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:26.804000Z       | info  | invokeOnAverageFpsChanged(0.0)                                                                                      | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:27.047000Z       | info  | Output orientation changed! LANDSCAPE_LEFT                                                                        | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:27.047000Z       | info  | invokeOnOutputOrientationChanged(LANDSCAPE_LEFT)                                                                  | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:27.061000Z       | info  | Output orientation changed! PORTRAIT                                                                              | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:27.061000Z       | info  | invokeOnOutputOrientationChanged(PORTRAIT)                                                                        | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:27.243000Z       | info  | Output orientation changed! LANDSCAPE_LEFT                                                                        | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:27.244000Z       | info  | invokeOnOutputOrientationChanged(LANDSCAPE_LEFT)                                                                  | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:27.283000Z       | info  | Camera State: OPENING (has error: false)                                                                          | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:27.288000Z       | info  | Camera State: OPENING (has error: true)                                                                           | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:27.288000Z       | error | invokeOnError(...):                                                                                               | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:27.347000Z       | fatal | system/max-cameras-in-use: The maximum amount of Cameras available for simultaneous use has been reached!          | sentry.event |                                                  |
| 2025-02-10T14:24:27.803000Z       | info  | invokeOnAverageFpsChanged(0.0)                                                                                      | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:28.073000Z       | info  |                                                                                                                   | device.event | action: DREAMING_STARTED                         |
| 2025-02-10T14:24:28.210000Z       | info  |                                                                                                                   | device.event | action: SCREEN_OFF, extras: reason=4, why=2        |
| 2025-02-10T14:24:28.293000Z       | info  | Camera State: OPENING (has error: false)                                                                          | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:28.417000Z       | error | Error observed on open (or opening) camera device 0: ERROR_CAMERA_DISABLED closing camera.                        | Logcat       | tag: Camera2CameraImpl                           |
| 2025-02-10T14:24:28.418000Z       | info  | Camera State: CLOSING (has error: true)                                                                           | Logcat       | tag: CameraSession                               |
| 2025-02-10T14:24:28.418000Z       | error | invokeOnError(...):                                                                                               | Logcat       | tag: CameraView                                  |
| 2025-02-10T14:24:28.420000Z       | info  | Camera State: CLOSED (has error: false)                                                                           | Logcat       | tag: CameraSession                               |

Error goes here, right after last Logcat message:
system/camera-is-restricted: Camera functionality is not available because it has been restricted by the operating system, possibly due to a device policy

**Comment by Tobbe** [comment]
@iliapnmrv You're making me worried we'll start seeing the exact same problem once we get more users of our app 😬 
I think the only way you're going to get any help with this is to pay @mrousavy to help you.

**Comment by iliapnmrv** [comment]
Sure, our company tries to support Marc as much as possible. I've asked to help, for now we should just wait. This is strange that I'm the only one getting this error
Anyways this issue is not fatal, users only report that you need to reenter the camera screen. If camera is not a big part of your app, your users wouldn't even notice it

**Comment by mrousavy** [comment]
Hey @iliapnmrv thanks - what company do you work for?

**Comment by Tobbe** [comment]
> Sure, our company tries to support Marc as much as possible.

Thank you @iliapnmrv! You and you're company are doing us all a favor!

**Comment by iliapnmrv** [comment]
Hi! After an entire day of testing these are my results
- I can consistently get this warning on my `Samsung S9 (Android 10)`, even on basic example app
- Sentry has a bunch of different manufacturers but QA with Xiaomi phone was unable to reproduce the bug'

The steps are
1. Open camera, give all permissions
2. Send app to background
3. Use phone as normal (messengers, streaming platforms etc.) for around a minute
4. Go back to app, there you'll see the warning
5. But for some reason (not even related to library as I understand) in my production app I get black screen, while in example app, camera reloads and works just fine

For now I'm trying to figure out what module in my app causes this error

@Tobbe I don't think this issue is related to your app, so no worries 😊


UPD:
I could not figure out the module causing the bug, but perfect fix for me was just reloading camera component after this error. Got it from [here](https://stackoverflow.com/a/53837442/16786307)
```tsx
function MyComponent(){
  const [, forceUpdate] = useReducer(x => x + 1, 0);

  return (
    <div onClick={forceUpdate}>
      Click me to refresh
    </div>
  );
}
```

**Comment by sayan-avantai** [comment]
I am getting this error when I am trying to grant the two different permissions, one is camera(useCameraPermission ) and another is location (useLocationPermission) . then this error is coming. 
if i am asking for one permission like the camera, then using useEffect I can turn on the camera by passing to isActive. 
No issue for one permission.

**Comment by NikoFarrelly** [comment]
I know this issue is closed, but there isn't a clear resolution provided. I've just resolved it in my project which uses react-native 0.81.0.

Clarity on the issue:
Android devices throw an error when foregrounded (from being backgrounded). The Android system pre-emptively blocks camera preview usage because it doesn't believe there is an appropriate surface. 

The fix:
As mentioned above using the [`useAppState` hook](https://github.com/mrousavy/react-native-vision-camera/issues/2991#issuecomment-2648151557), specifically `appState === 'active'` wrapping the camera preview solves the issue. i.e
```
{appState === 'active' && <Camera ... />}
```

Note:
Providing the 'active' condition to the `isActive` prop doesn't resolve the problem. As the app reloads the camera preview quicker than the Android system can keep up. Resulting in the aforementioned error happening. Using the above condition provides enough of a delay to stop the error from being produced
