### ISSUE TITLE
💭 CodeScanner does not recognize Data Matrix code on a black background

### ISSUE THREAD

**Issue by vkoktashev** [cuvent/react-native-vision-camera#2993]
### Question

I have a Data Matrix with inverted colors - black background and white characters. CodeScanner cannot recognize this. However, if you invert the colors in the photo, everything works fine. Original photo:
<img width="197" alt="image" src="https://github.com/mrousavy/react-native-vision-camera/assets/24474150/2693910b-897e-4809-b342-07a2cb9931d5">
Inverted photo:
<img width="152" alt="image" src="https://github.com/mrousavy/react-native-vision-camera/assets/24474150/3dd584cf-765d-419a-b406-42e8e07795c4">

Can I use any FrameProccessor? And in this case, will CodeScanner work with an already processed image?
Or maybe there is a way to configure the recognition of codes of this type using the react-native-vision-camera configuration?

### VisionCamera Version

4.3.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey - the CodeScanner is just the system API for code scanning, it is very basic and lightweight.

If you need something more advanced, use a custom Frame Processor Plugin.

**Comment by KarimovAbdullo** [comment]
@mrousavy adnorid doesn't read these codes

react-native 0.71
react-native-vision-camera :3.6.4
