### ISSUE TITLE
💭 Add filter to photo when photo is taken

### ISSUE THREAD

**Issue by mcervantes3** [cuvent/react-native-vision-camera#2996]
### Question

How would I make it so that when I take a photo this Filter gets applied to it (the banner with the star in the middle)

![IMG_2812](https://github.com/mrousavy/react-native-vision-camera/assets/124613180/54deea4f-7565-4a1e-8ef6-5c71fbbdc270)

This filter does not need to detect the user's face. It just puts an image on top of the other. Thats it.

### VisionCamera Version

^4.1.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
You can do that in post processing using tools like react-native-skia. Create an offscreen context, load the captured image, draw the star banner, and save it again. This is not related to VisionCamera.
