### ISSUE TITLE
🔧 RCT_NEW_ARCH_ENABLED=1 failed pod install

### ISSUE THREAD

**Issue by wogno** [cuvent/react-native-vision-camera#3002]
### How were you trying to build the app?

I tried to enable new architecture but  pod install failed, my command **bundle install && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install**, when I disabled new architecture pod install work well, but video-camera required new architecture

### Full build logs

```tsx
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `VisionCamera` depends upon `react-native-worklets-core`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

### Project dependencies

```json
"dependencies": {
"@shopify/react-native-skia": "^1.3.6",
 "@wuba/react-native-echarts": "^1.3.1",
"react-native": "0.74.2",
"react-native-vision-camera": "^4.3.2",
    "react-native-worklets-core": "^1.3.3"
}
```

### VisionCamera Version

4.3.2

### Target platforms

iOS

### Operating system

MacOS

### Can you build the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Please create this issue in react-native-worklets-core - it's not a VisionCamera error. Also, maybe set `use_modular_headers!` in your Podfile
