### ISSUE TITLE
🐛 Cannot debug via Google Chrome if using Android Native method marked as synchronous

### ISSUE THREAD

**Issue by QuangBinhDinh** [cuvent/react-native-vision-camera#3003]
### What's happening?

I just recently install this library and I found a bug while debugging the app in Android devices via Google Chrome debugger:`Calling synchronous methods on native modules is not supported in Chrome`. When I dig deeper into the Android Native modules code, I found out some methods marked as synchronous.
![Untitled](https://github.com/mrousavy/react-native-vision-camera/assets/43164997/4459924c-7ac2-4748-af26-13f205b9c8d9)
According to RN docs (https://reactnative.dev/docs/native-modules-android), the app won't run if I use synchronous native methods. As a developer stick to Google Chrome debugger for long times, this is a bit annoying (I don't want to switch another debugger) and I want to fix them into async method. So I wanna ask if changing to asynchronous method can create an impact to this library functionality and performance ?

### Reproduceable Code

```tsx
useEffect(() => {
        const request = async () => {
            // because this method is marked as synchronous, app will crash if debugging via Chrome
            var result = await requestPermission();
            console.log('Permission granted: ', result);
        };
        request();
       
    }, []);
```

### Relevant log output

```shell
Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome
```

### Camera Device

```json
{
  "formats": [],
  "sensorOrientation": "landscape-left",
  "hardwareLevel": "full",
  "maxZoom": 10,
  "minZoom": 0.6000000238418579,
  "maxExposure": 20,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera",
    "ultra-wide-angle-camera",
    "wide-angle-camera",
    "telephoto-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": false,
  "isMultiCam": true,
  "minFocusDistance": 0,
  "minExposure": -20,
  "name": "0 (BACK) androidx.camera.camera2",
  "hasFlash": true,
  "hasTorch": true,
  "position": "back",
  "id": "0"
}
```

### Device

All Android devices

### VisionCamera Version

4.1.0

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
> So I wanna ask if changing to asynchronous method can create an impact to this library functionality and performance ?

Yes.

Non-native debuggers are not supported, because they cannot run synchronous methods.
