### ISSUE TITLE
💭 react-native-vision-camera:buildCMakeRelWithDebInfo[arm64-v8a] FAILED

### ISSUE THREAD

**Issue by FazilMuhammed** [cuvent/react-native-vision-camera#3028]
### Question

when i try make a Apk.
  
  cd android && ./gradlew app:assembleRelease && cd ..

 getting error 

"Execution failed for task ':react-native-vision-camera:buildCMakeRelWithDebInfo[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `/node_modules/react-native-vision-camera/android/.cxx/RelWithDebInfo/6vrrw3b6/arm64-v8a'"

react native version 0.74.2
react native vision camera 4.3.2
react-native-worklets-core 1.3.3

how to fix this CMakeFile issue already try with troubleshoot no change happens

### What I tried

when try to generate APK

### VisionCamera Version

4.3.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by dankocher** [comment]
I have the same problem. Any solution?

**Comment by dankocher** [comment]
Deleting folder `android/.gradle` worked for me

**Comment by mrousavy** [comment]
wrong issue template.

**Comment by LuizFBrisighello** [comment]
Related to #1913 probably

**Comment by vaibhavdhake123** [comment]
Same iusse Here
