### ISSUE TITLE
🐛 'UIWindowScene' is only available in iOS 13.0 or newer

### ISSUE THREAD

**Issue by Romick2005** [cuvent/react-native-vision-camera#3040]
### What's happening?

![image](https://github.com/mrousavy/react-native-vision-camera/assets/17779660/52dd534b-308b-4aa6-9797-2a1e462e83f0)

Please add version checks.

### Reproduceable Code

```tsx
No code needed.
```

### Relevant log output

```shell
It does not build on iOS for relevant output, but works on Android.
```

### Camera Device

```json
{
  device: "Any iPhone device with iOS > 13"
}
```

### Device

iPhone XS

### VisionCamera Version

4.4.0

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by rodrigobertolottizinsp** [comment]
Project is set to run for iOS 13.4 and higher, maybe you are modifying your pods target iOS deployment version in the Podfile?

**Comment by Romick2005** [comment]
> Project is set to run for iOS 13.4 and higher, maybe you are modifying your pods target iOS deployment version in the Podfile? 

I already have that. Latest react native do that for me in:
/node_modules/react-native/scripts/cocoapods/helpers.rb
min_ios_version_supported 13.4

**Comment by geekabhinavp** [comment]
+1 facing same issue!

**Comment by geekabhinavp** [comment]
I fixed it!
Step 1: Check the deployment versions using this command:
```
grep -r 'IPHONEOS_DEPLOYMENT_TARGET' ios/
```
Step 2: If any version lower than 13 is found, run the following:
```
find ios/Pods/Pods.xcodeproj -name project.pbxproj -print0 | xargs -0 sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]*\.[0-9]*/IPHONEOS_DEPLOYMENT_TARGET = 13.0/g'
```

**Comment by moigamijunior** [comment]
I've fixed using the Xcode FIX; adding `@available(iOS 13, *)` in every problematic `function` or `class`, like this

```objectve-c
@available(iOS 11, macOS 10.13, *)
func newMethod() {
    // Use iOS 11 APIs.
}
```

[See swift docs](https://developer.apple.com/documentation/swift/marking-api-availability-in-objective-c#Mark-Availability)

**Comment by TeraBlitz** [comment]
Is there any reason this is closed? this is still an issue.

**Comment by SarjuHansaliya** [comment]
Fixed it with this code in Podfile and then run `pod install`

```ruby
platform :ios, '14.2'

target 'YourAppName' do
  #...some code...

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.2' # replace here with your minimum deployment 
      end
    end
  end
end
```

You might be facing this issue because one of the pod in your project is using <13.0 target. You can check that by searching `IPHONEOS_DEPLOYMENT_TARGET` in `ios` directory.

**Comment by w4t3r-45** [comment]
same issue even with testing to set the minimum deployment version , is there any other solutions guys ?

**Comment by iliapnmrv** [comment]
hey! I've just reinstalled pods using `npx pod-install` and app build worked for me

**Comment by parnekov** [comment]
it happened after install react-native-permissions. 

Fix it!

**Close Xcode -> Open -> Command +K (Clean) -> Run -> Works!**

**Comment by jay10895** [comment]
<img width="441" alt="image" src="https://github.com/user-attachments/assets/04c80d47-eeb6-4705-9702-ba3ee1e74004">


I fixed it by changing Deployment iOS Deployment Target in Pods > react-native-vision-camera > Build Settings iOS Deployment Target

**Comment by praveenflymeout** [comment]
<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/0b4e58f8-ca4a-4c93-ac04-1c1af330bf0e" /> I followed above all suggestion like update iOS deployment target inside pod file need to update(14.2), but still i am facing same issue in my project. Could you please anybody help me in this.

"react-native": "0.72.3",
"react": "18.2.0",
"react-native-vision-camera": "4.6.3",
