### ISSUE TITLE
🔧 Interface: NativeBuffer

### ISSUE THREAD

**Issue by kHanHnq4901** [cuvent/react-native-vision-camera#3056]
### How were you trying to build the app?

how to delete Interface: NativeBuffer vision camera react native https://react-native-vision-camera.com/docs/api/interfaces/DrawableFrame

### Full build logs

```tsx
how to delete Interface: NativeBuffer vision camera react native https://react-native-vision-camera.com/docs/api/interfaces/DrawableFrame
```

### Project dependencies

```json
how to delete Interface: NativeBuffer vision camera react native https://react-native-vision-camera.com/docs/api/interfaces/DrawableFrame
```

### VisionCamera Version

3.1.6

### Target platforms

Android

### Operating system

MacOS

### Can you build the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
no idea what you're asking, but if you want to delete a NativeBuffer you just call `NativeBuffer.delete()`.
