### ISSUE TITLE
🐛 videoBitRate parameter has no effect on Samsung Galaxy S24

### ISSUE THREAD

**Issue by james-cohen** [cuvent/react-native-vision-camera#3059]
### What's happening?

Firstly, thank you for creating and maintaining this package. We wouldn't be able to have an app without it!

Our app involves users recording videos and uploading them. To reduce the file size, we use the videoBitRate parameter. This works across most devices, but one user who has a Samsung S24 Plus is uploading videos with a bit rate of 48MB/s! For whatever reason, the limit isn't being recognised.

It could be that we are implementing the approach incorrectly, or if this is a bug with Samsung or Android in particular. In any case, any input you have to help figure out how to remedy the issue would be greatly appreciated.

### Reproduceable Code

```tsx
const device = useCameraDevice(position, {
    physicalDevices: [
      'ultra-wide-angle-camera',
      'wide-angle-camera',
      'telephoto-camera',
    ],
  });    

const format = useCameraFormat(device, [
    { fps: use60Fps ? 60 : 30 },
    { videoAspectRatio: frameHeight / frameWidth },
    { videoResolution: 'max' },
    { photoAspectRatio: frameHeight / frameWidth },
    { photoResolution: 'max' },
  ]);

const startRecording = useCallback(() => {
    if (!camera.current || isRecording) {
      return;
    }

    try {
      Logger.log('calling startRecording()...');
      camera.current.startRecording({
        fileType: 'mp4',
        videoBitRate: 4,
        onRecordingError: (error) => {
          onError(error);
          setIsRecording(false);
        },
        onRecordingFinished: (video) => {
          const { path, duration } = video;
          Logger.log('Recording successfully finished!');
          onMediaCaptured(path, duration);
          setIsRecording(false);
        },
      });
      setIsRecording(true);
    } catch (err) {
      onError(err);
    }
  }, [camera, isRecording, onError, onMediaCaptured]);

  return (
    <GestureDetector gesture={gesture}>
      <View className="flex-1 w-full h-full">
        <ReanimatedCamera
          style={cameraStyle}
          exposure={0}
          ref={camera}
          device={device}
          format={format}
          photo={false} // only video for now
          video
          fps={fps}
          torch={flashMode}
          videoHdr={!!useHdr && supportsHdr}
          lowLightBoost={device.supportsLowLightBoost && !!useNightMode}
          isActive={isActive && cameraPermission === 'granted'}
          onInitialized={handleInitialisation}
          onError={onError}
          outputOrientation="preview"
          audio={micPermission === 'granted'}
          frameProcessor={frameProcessorPlugin ? frameProcessor : undefined}
          animatedProps={animatedProps}
        />
        <FullScreenOverlay classOverride="flex justify-center items-center">
          <CameraZoomIndicator
            zoomValue={zoomValue}
            isVisible={showZoom}
            maxZoom={maxZoom}
            minZoom={device.minZoom}
          />
        </FullScreenOverlay>
      </View>
    </GestureDetector>
  );
}
```

### Relevant log output

```shell
Unable to retrieve from user
```

### Camera Device

```json
Unable to retrieve from user
```

### Device

Samsung S24 Plus

### VisionCamera Version

3.4.4

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by vishalyad16** [comment]
I am using 
"react-native-vision-camera": "^4.4.2",
"react-native": "^0.73.8",

 const format = useCameraFormat(backCamera, [
        { videoResolution: { width: 1280, height: 720 } },
        { fps: 30 },{pixelFormat: 'native'}
        ])

await cameraRef.current?.startRecording({
                    videoCodec: 'h264',
                    videoBitRate: 'extra-low',
                    onRecordingFinished: video => {
                        const path = video?.path
                        setVideoPath(path)
                        clearInterval(timerId);
                        setCustomUrl(path)
                    },
                    onRecordingError: error => {
                        setIsRecording(false);
                        console.error('Recording error: ', error);
                        clearInterval(timerId);
                    }
                });
     While recording a video for 1 minute, the file size becomes as large as 151 MB. How can I reduce the file size? Please help.
