### ISSUE TITLE
💭 How to take a photo in portrait preview with portrait orientation output?

### ISSUE THREAD

**Issue by mercyaj** [cuvent/react-native-vision-camera#3062]
### Question

I'm relatively new to working with mobile device cameras, so I apologise in advance if these aren't great questions.

In my use case I only allow users to view a portrait preview when taking a photo. Once the photo is taken I need it to be actually portrait. As I understand it as device sensors are rotated compared to the screen, the required rotation to make the photo portrait is stored in the EXIF orientation property, represented by the EXIF orientation number. 

<img width="515" alt="Screenshot 2024-07-10 at 08 31 35" src="https://github.com/mrousavy/react-native-vision-camera/assets/27196636/60f71e82-4414-40c2-b729-dd4d78c4cc17">

For example, a portrait photo taken on an iPhone 14 Pro using iOS 17 produces the following:

`{ Orientation: 6 }`

Meaning the photo needs to be rotated 90deg to show the intended orientation.

Assuming that my understanding is correct, is it possible for this library to instead automatically rotate the photo 90deg or do we have to do this manually? If rotated manually does the EXIF orientation then need to be reset to `1`?

I should make clear that using the various `Image` components in react-native/expo correctly show the photo in portrait as I assume they respect the EXIF orientation. Unfortunately the photos taken in my use case are used in places that don't respect the EXIF orientation, hence why I need the photo to "just" be naturally portrait.

In addition I've also found that portrait snapshots taken with `takeSnapshot` don't render portrait using the `Image` components in react-native/expo, instead rendering landscape-left. I assume this is due to snapshots not carrying EXIF orientation data?

### VisionCamera Version

4.4.1

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey - yes you cannot _physically_ rotate images using VisionCamera. This is intentional, as it is a performance bottleneck to rotate 4k buffers pixel by pixel. That's why EXIF flags or video metadata tags or view transforms are used to rotate the buffer streams.

For Snapshot I think this is a bug tbh. But for photos it will be physically rotated, then counter rotated with an EXIF flag.

**Comment by mercyaj** [comment]
Thank you!
