### ISSUE TITLE
🐛 `frame.isMirrored` is `false` with selfie camera on iOS

### ISSUE THREAD

**Issue by bglgwyng** [cuvent/react-native-vision-camera#3075]
### What's happening?

`frame.isMirrored` is `false` with selfie camera on iOS, while the image in the frame object is mirrored.

### Reproduceable Code

```tsx
const frameProcessor = useFrameProcessor((frame) => {
  'worklet'

  console.info(frame.isMirrored)
```

### Relevant log output

```shell
.
```

### Camera Device

```json
{
  "minZoom": 1,
  "formats": [],
  "maxZoom": 121.875,
  "position": "back",
  "sensorOrientation": "portrait",
  "hasFlash": true,
  "name": "Back Camera",
  "minExposure": -8,
  "id": "com.apple.avfoundation.avcapturedevice.built-in_video:0",
  "hasTorch": true,
  "supportsRawCapture": false,
  "supportsFocus": true,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "neutralZoom": 1,
  "minFocusDistance": 15,
  "hardwareLevel": "full",
  "isMultiCam": false,
  "supportsLowLightBoost": false,
  "maxExposure": 8
}
```

### Device

iPhone 13 (iOS 17.5)

### VisionCamera Version

4.4.2

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [X] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Oh, I forgot to add `isMirrored` on iOS. Fixed in https://github.com/mrousavy/react-native-vision-camera/pull/3078
