### ISSUE TITLE
💭 Capturing photo of Drawable Frames of SkiaFrameProcessor

### ISSUE THREAD

**Issue by clouddaa** [cuvent/react-native-vision-camera#3097]
### Question

I have gone through the documentation that states 
_**Skia Frame Processors are currently preview-only. Any content drawn to the Frame will not be visible in captured photos, snapshots or videos.**_

I don't want drawn content to be captured in my photos, I just want to capture photos without the drawn components.
However, when I try to create a Camera component that can take photos on drawable frames an error appears as follows.

Camera.onError(session/invalid-output-configuration): Failed to configure the Camera Session because the output/stream configurations are invalid! [session/invalid-output-configuration: Failed to configure the Camera Session because the output/stream configurations are invalid!]

Am I missing something? Is it not possible at all to capture photos when Drawable frames are being rendered?

### VisionCamera Version

"react-native-vision-camera": "^4.0.3"

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
This is possible, but it seems like something went wrong when trying to create the session. Please create a bug report **with native logs**.
