### ISSUE TITLE
💭 Prevent permissions being requested when the app starts

### ISSUE THREAD

**Issue by ed-sparkes** [cuvent/react-native-vision-camera#3106]
### Question

Hi, i have removed all other libraries managing permissions in an attempt  to understand why my app requests camera permissions at startup. 

The only place i am importing anything from react-native-vision-camera is in a stack navigation screen that is not loaded at app startup and in there i have a call to requestPermissions in a useEffect hook. 

I cant work out why the permission is being requested at startup and wondered if you had any insight, and if there was anything in the library that might be forcing this?

### VisionCamera Version

4.4.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Upgrade to latest VisionCamera. I think this is fixed.
