### ISSUE TITLE
💭 Example in Documentation Incorrect?

### ISSUE THREAD

**Issue by quiringk** [cuvent/react-native-vision-camera#3107]
### Question

Hey, I just found a potential error in the documentation that I just wanted to point out. Correct me if I'm wrong, but shouldn't this example line here (SS 1) look more like this (SS 2)? 

<img width="920" alt="Screenshot 2024-07-30 at 8 34 01 PM" src="https://github.com/user-attachments/assets/da48a4cf-0e26-4f5f-a250-1623bb3a5192">

<img width="827" alt="image" src="https://github.com/user-attachments/assets/40187d3d-754a-4db0-b370-20f89038a5f3">

Thanks for the library!

### VisionCamera Version

3.9.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey - ah yes, exactly. Can you submit a PR to fix that in the docs? thanks
