### ISSUE TITLE
💭 Code scans only in the top right corner

### ISSUE THREAD

**Issue by alextusinean** [cuvent/react-native-vision-camera#3116]
### Question

Hello, I was testing this library on an Android emulator and it worked great. When I tried using it on a real device (Android), I encountered an issue. The barcodes were only scanned if they were in the top right corner of the preview.

Setting `<Camera ... video={true} photo={true} />` solves the issue.

I thought of sharing this in case anyone runs into this and maybe raise awareness if it's an actual issue.

### VisionCamera Version

4.5.1
### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by vishalyad16** [comment]
@alextusinean 
How can I reduce the size of a video that is 151 MB for a 1-minute recording? The bitRate setting does not seem to be working.
https://github.com/mrousavy/react-native-vision-camera/issues/3113
