### ISSUE TITLE
💭 Is there a way to record a video together with an overlay?

### ISSUE THREAD

**Issue by VasilP202** [cuvent/react-native-vision-camera#3142]
### Question

I'm using Skia Frame Processor to run pose detection on each frame and draw pose landmarks in real time. 
Is there a way to save the video along with the landmarks drawn over the video?

I'm using Camera's [startRecording(...)](https://react-native-vision-camera.com/docs/api/classes/Camera#startrecording) to record the video, but this only serves to save video frames, without any overlay.

### What I tried

I tried using **react-native-skia** / **react-native-video** to play video and draw landmarks separately (based on a timestamp of each frame). However, this causes significant desynchronization between the skeleton and the video. I still haven't found a way to access the video canvas at the exact timestamps. Therefore I want to record the video together with pose landmarks and play the video directly.

### VisionCamera Version

4.0.5

### Additional information

- [ ] I am using Expo
- [x] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by VasilP202** [comment]
How do I fill the issue template for queries?

**Comment by VasilP202** [comment]
Here's the code snippet used for frame processing:

```
const frameProcessor = useSkiaFrameProcessor(frame => {
    'worklet';

    frame.render();

    if (!isRecording.value) {
      return;
    }

    // Detect pose for the current frame
    const detectedPose = poseDetection(
      frame,
      frameNumber.value,
    );

    if (Object.values(detectedPose).length === 0) {
      frameNumber.value++;
      return;
    }

    // Normalize pose data - convert to 0-1 range
    const poseArray = getFramePoseNormalized(detectedPose, frame.width, frame.height);

    // Create 3D skeleton from 2D
    const poseArray3D = create3DSkeletonFrom2DMediapipe(poseArray, frame.width, frame.height);

    // Set start timestamp, frame.timestamp returns system time
    if (startTimestamp.value === 0) {
      startTimestamp.value = frame.timestamp;
    }
    const timeSinceFirstFrame = frame.timestamp - startTimestamp.value;

    // Process the pose data
    const processedFrameData = processLearningExerciseFrame(
      poseArray,
      poseArray3D,
      frameNumber.value,
      timeSinceFirstFrame,
    )

    // Draw the current skeleton pose
    const currentPose = processedFrameData.skeletonPose;
    drawFramePose(frame, currentPose);

    frameNumber.value++;
    frame.restore();
  }, [frameNumber]);
```

**Comment by mrousavy** [comment]
No, this is mentioned in the docs.

**Comment by mjhoracek** [comment]
Since it's almost a year later I think it might be fair to bump this again. Are there any examples for how this could be built? If not, what's a possible route to a solution? 

Thanks @mrousavy, your library is awesome.

**Comment by mrousavy** [comment]
We build tailored solutions like this for our clients at [Margelo](https://margelo.com).

**Comment by mjhoracek** [comment]
@VasilP202 did you ever figure out how to do this?

**Comment by VasilP202** [comment]
@mjhoracek Unfortunately not.

**Comment by mjhoracek** [comment]
@VasilP202 found a solution using only swift, adding [Core Animation Layers](https://developer.apple.com/documentation/quartzcore/calayer) to the video at the timestamps where data was passed from react native and redux to my swift video module.
