### ISSUE TITLE
🐛 getCameraCharacteristics:1041: Unable to retrieve camera characteristics for unknown device

### ISSUE THREAD

**Issue by stevenmathers** [cuvent/react-native-vision-camera#3148]
### What's happening?

crash on specific android device S22+

I dont have this device, I am seeing this in our firebase crashlytics

<img width="1261" alt="Screenshot 2024-08-23 at 10 05 46 am" src="https://github.com/user-attachments/assets/fab99c68-a3c2-45f1-8b32-699ed300cf57">

### Reproduceable Code

```tsx
<Camera
                    ref={camera}
                    style={{flex:1}}
                    device={device}
                    isActive={isFocused && isForeground}
                    photo={true}
                    enableZoomGesture
                    orientation='portrait'
                    resizeMode={'contain'}
                />
```

### Relevant log output

```shell
see image above
I dont have this device, I am seeing this in our firebase crashlytics
but I have captured the stack trace
for you
```

### Camera Device

```json
unknown
```

### Device

Galaxy S22+

### VisionCamera Version

4.1.5

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Sorry, without logs I cannot help you. You need to reproduce this bug on an actual device and send me the adb logcat logs.

**Comment by stevenmathers** [comment]
Hi @mrousavy perhaps just keep this ticket open in case it is not just how Im using the library, but an issue for everybody who uses the library with this device.    Its been around for 2 years though.

**Comment by mrousavy** [comment]
Yes but as I just said, there's nothing I can do without logs.

**Comment by stevenmathers** [comment]
Ill try to track down an online real device of this type and see what
happens.
