### ISSUE TITLE
🐛 ins iOS iphone 11, Camera get blank screen

### ISSUE THREAD

**Issue by ViralGroovy** [cuvent/react-native-vision-camera#3149]
### What's happening?

In iOS device iPhone 11, When i try to open camera at that time got White blank screen.

### Reproduceable Code

```tsx
const cameraRef = useRef(null);
  const [cameraDevice, setCameraDevice] = useState("back");
  const device = useCameraDevice(cameraDevice, {
    physicalDevices: ['ultra-wide-angle-camera', 'wide-angle-camera', 'telephoto-camera'],
  });
  const format = useCameraFormat(device, [
      { 
        photoResolution: 'max'
      },
      {
        fps: 'max',
      },
      {
        iso: 'max'
      },
  ])

<Camera
              ref={cameraRef}
              style={{ 
                flex: 1,
              }}
              isActive={isCameraOpen}
              photo={true}
              video={true}
              device={device}
              enableZoomGesture={true}
              audio={true}
              enableHighQualityPhotos
              format={format}
            />
```

### Relevant log output

```shell
Exception thrown while executing UI block: UIGraphicsBeginImageContext() failed to allocated CGBitampContext:
```

### Camera Device

```json
{
  "hasTorch": true,
  "isMultiCam": false,
  "id": "com.apple.avfoundation.avcapturedevice.built-in_video:0",
  "supportsRawCapture": false,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "neutralZoom": 1,
  "supportsFocus": true,
  "hasFlash": true,
  "name": "Back Camera",
  "minExposure": -8,
  "minZoom": 1,
  "formats": [],
  "position": "back",
  "hardwareLevel": "full",
  "minFocusDistance": 12,
  "maxZoom": 189,
  "maxExposure": 8,
  "supportsLowLightBoost": false,
  "sensorOrientation": "landscape-right"
}
```

### Device

iPhone 11 (17.6.)

### VisionCamera Version

^3.9.2

### Can you reproduce this issue in the VisionCamera Example app?

No, I cannot reproduce the issue in the Example app

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Upgrade to VisionCamera V4.
