### ISSUE TITLE
✨ Able to use this library detect QR code from the image

### ISSUE THREAD

**Issue by LeXuanKhanh** [cuvent/react-native-vision-camera#3185]
### What feature or enhancement are you suggesting?

Hi, in most apps, especially in bank/finance apps, the QR code scan feature always comes with "scan QR code from the image". It would be great if the library supported this feature although it does not relate much. Besides all the current library support this tends to be deprecated or not maintained anymore
If you ok with this then I'm happy to make a PR to this feature, it's quite easy since in Android the mlkit.barcode can scan code from the image already, and in iOS we will use built-in CIDetector

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
Hi - no, this is a Camera library. That's not the scope of this library, and would just make everything bloated.

**Comment by xulihang** [comment]
The following frame processor plugins can read barcodes from an image:

* https://github.com/tony-xlh/vision-camera-dynamsoft-barcode-reader/
* https://github.com/xulihang/vision-camera-zxing
* https://github.com/gev2002/react-native-vision-camera-barcodes-scanner (using ML Kit)
