### ISSUE TITLE
🔧 could not build Objective-C module 'vision_camera_code_scanner'

### ISSUE THREAD

**Issue by Rajshah555999** [cuvent/react-native-vision-camera#3190]
### How were you trying to build the app?

yarn install
cd ios
pod install

### Full build logs

```tsx
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "vision-camera-code-scanner-umbrella.h"
        ^
ios/Pods/Headers/Public/vision_camera_code_scanner/vision-camera-code-scanner-umbrella.h:13:9: note: in file included from ios/Pods/Headers/Public/vision_camera_code_scanner/vision-camera-code-scanner-umbrella.h:13:
#import "VisionCameraCodeScanner-Bridging-Header.h"
        ^
node_modules/vision-camera-code-scanner/ios/VisionCameraCodeScanner-Bridging-Header.h:4:9: error: 'VisionCamera/FrameProcessorPlugin.h' file not found
#import <VisionCamera/FrameProcessorPlugin.h>
        ^
<unknown>:0: error: could not build Objective-C module 'vision_camera_code_scanner'


Showing All Messages
/ios/Pods/<module-includes>:1:9: In file included from <module-includes>:1:

/ios/Pods/Headers/Public/vision_camera_code_scanner/vision-camera-code-scanner-umbrella.h:13:9: In file included from /ios/Pods/Headers/Public/vision_camera_code_scanner/vision-camera-code-scanner-umbrella.h:13:

/node_modules/vision-camera-code-scanner/ios/VisionCameraCodeScanner-Bridging-Header.h:4:9: 'VisionCamera/FrameProcessorPlugin.h' file not found

Could not build Objective-C module 'vision_camera_code_scanner'
```

### Project dependencies

```json
"dependencies": {
    "react-native": "0.75.2",
    "react-native-vision-camera": "^4.5.3",
    "vision-camera-code-scanner": "^0.2.0"
  },
```

### VisionCamera Version

4.5.3

### Target platforms

iOS

### Operating system

MacOS

### Can you build the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [X] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
This is not a VisionCamera issue. Please stop creating all issues from community plugins here. Create that issue in the community plugin you are using. It even says so in the name.
