### ISSUE TITLE
✨ Enable multitasking camera access on iOS

### ISSUE THREAD

**Issue by ethul** [cuvent/react-native-vision-camera#3210]
### What feature or enhancement are you suggesting?

Would it be possible to add support for enabling multitasking camera access?

This would be useful for apps running on iPads with Stage Manager or Split View/Slide Over turned on.

From the [Apple developer documentation](https://developer.apple.com/documentation/avkit/accessing-the-camera-while-multitasking-on-ipad) I tried adding the following to the camera session, which seemed to do the trick.

```swift
if #available(iOS 16.0, *) {
  if self.captureSession.isMultitaskingCameraAccessSupported {
    // Enable use of the camera in multitasking modes.
    self.captureSession.isMultitaskingCameraAccessEnabled = true
  }
}
```

### What Platforms whould this feature/enhancement affect?

iOS

### Alternatives/Workarounds

I manually made the change in `Core/CameraSession.swift`.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by ethul** [comment]
Without the change to enable multitasking, when Stage Manager or Split View/Slide Over was turned on, the camera preview was blank, and recording a video issued an error:

```
capture/unknown: Error Domain=AVFoundationErrorDomain Code=-11803 "Cannot Record" UserInfo={AVErrorRecordingFailureDomainKey=3, NSLocalizedDescription=Cannot Record, NSLocalizedRecoverySuggestion=Try recording again.}
```

**Comment by mrousavy** [comment]
Hey! Oh, pretty cool. Yea I can add that feature if I have some free time soon, thanks for posting the code here this is really helpful.

**Comment by ethul** [comment]
Great, thanks!

**Comment by ChristopherGabba** [comment]
+1 on this, I have `CameraRuntimeError`'s every now and then when another task interrupts the camera. Not 100% sure if this would fix the problem, but it couldn't hurt! Sometimes, this also creates a video recording with no audio when another video in the background hijacks the audio session.

**Comment by mrousavy** [comment]
Reading the docs wouldn't hurt - this is already `true` if you have the entitlement for it (which is required, and would crash otherwise)

![Screenshot 2024-10-29 at 09 23 56](https://github.com/user-attachments/assets/a95d766c-9141-445a-bba6-57ae5effab35)

**Comment by ethul** [comment]
I think it is important to note that the multitaasking-camera-access entitlement [is deprecated](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_avfoundation_multitasking-camera-access).

<img width="766" alt="Screen Shot 2024-10-30 at 10 27 50 AM" src="https://github.com/user-attachments/assets/78b8214d-d1d4-4a75-8501-47097233ee14">

It seems like the recommended approach is to use `isMultitaskingCameraAccessEnabled`.
