### ISSUE TITLE
🔧 Android build failure on v4

### ISSUE THREAD

**Issue by decSunshineHe** [cuvent/react-native-vision-camera#3218]
### How were you trying to build the app?

I tried to build app using 'npm run android' or 'cd android' & './gradlew clean' command，but failed

### Full build logs

```tsx
> Configure project :react-native-reanimated
Android gradle plugin: 8.1.1
Gradle: 8.3

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-vision-camera'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':react-native-vision-camera:classpath'.
      > Could not resolve com.android.tools.build:gradle:8.5.2.
        Required by:
            project :react-native-vision-camera
         > Could not resolve com.android.tools.build:gradle:8.5.2.
            > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/8.5.2/gradle-8.5.2.pom'.
               > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/8.5.2/gradle-8.5.2.pom'.
                  > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. For more on this, please refer to https://docs.gradle.org/8.3/userguide/build_environment.html#sec:gradle_system_properties in the Gradle documentation.
                     > Remote host terminated the handshake
         > Could not resolve com.android.tools.build:gradle:8.5.2.
            > Could not get resource 'https://plugins.gradle.org/m2/com/android/tools/build/gradle/8.5.2/gradle-8.5.2.pom'.
               > Could not GET 'https://plugins.gradle.org/m2/com/android/tools/build/gradle/8.5.2/gradle-8.5.2.pom'.
                  > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. For more on this, please refer to https://docs.gradle.org/8.3/userguide/build_environment.html#sec:gradle_system_properties in the Gradle documentation.
                     > Remote host terminated the handshake

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```

### Project dependencies

```json
"dependencies":{
    "react": "18.2.0",
    "react-native": "0.73.2",
    "react-native-reanimated": "^3.6.1",
    "react-native-vision-camera": "^4.5.3",
}
```

### VisionCamera Version

4.5.3

### Target platforms

Android

### Operating system

MacOS

### Can you build the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [X] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
> ```
>         > Could not resolve com.android.tools.build:gradle:8.5.2.
>            > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/8.5.2/gradle-8.5.2.pom'.
>               > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/8.5.2/gradle-8.5.2.pom'.
>                  > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. For more on this, please refer to https://docs.gradle.org/8.3/userguide/build_environment.html#sec:gradle_system_properties in the Gradle documentation.
>                     > Remote host terminated the handshake
> ```

This definitely isn't an issue with VisionCamera. For some reason, you cannot use gradle 8.5.2.
