### ISSUE TITLE
💭 How to convert Uint8Array to Frame

### ISSUE THREAD

**Issue by i7soft** [cuvent/react-native-vision-camera#3219]
### Question

On "frameProcessor" event, I use "react-native-fast-opencv" process the frame data, and opencv return Uint8Array Data, I want to know how to convert Uint8Array to Frame

`
const frameProcessor2 = useSkiaFrameProcessor((frame) => {
        'worklet';

        const height = frame.height
        const width = frame.width

        const src = OpenCV.frameBufferToMat(height, width, frame.planesCount, new Uint8Array(frame.toArrayBuffer()));
        const dst = OpenCV.createObject(ObjectType.Mat, 0, 0, DataTypes.CV_8U);

        var matrix = OpenCV.createObject(ObjectType.Mat, 4, 2, DataTypes.CV_16F, [0, 0, width - 100, 0, width - 1, height - 1, 0, height - 1]);

        OpenCV.invoke('perspectiveTransform', src, dst, matrix);
        var newFrame = OpenCV.matToBuffer(dst,"uint8")
       
        //TODO:How to convert newFrame to frame?
        
        frame.render();

        OpenCV.clearBuffers(); // REMEMBER TO CLEAN
    }, []);

`

### VisionCamera Version

4.5.3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
This is currently not possible. It is also not really how GPU Frames work - a Uint8Array is a CPU based data set / array buffer. A Frame is a GPU-based buffer or even texture.
