### ISSUE TITLE
🐛 Camera preview not full screen device

### ISSUE THREAD

**Issue by catchellers** [cuvent/react-native-vision-camera#3224]
### What's happening?

- It work nice on IOS, 
- But on android (S23 ultra or more new models) the preview of the camera not full screen device

- Use with format, not stretch but not full preview camera
![IMG_0654](https://github.com/user-attachments/assets/e7f1d8a4-dcf7-4515-9e25-f44a95e47ff2)

- Without format: It full with but not height and it strectch
![IMG_0655](https://github.com/user-attachments/assets/bd383f2f-7b50-4e00-8eff-46f32a341dba)

### Reproduceable Code

```tsx
const device = useCameraDevice(front ? 'front' : 'back');

<Camera
   style={[StyleSheet.absoluteFill, { top: 10 }]}
   device={device}
   isActive={true}
   photo={true}
   pixelFormat='yuv'/>
```

### Relevant log output

```shell
null
```

### Camera Device

```json
{
  "formats": [],
  "sensorOrientation": "landscape-left",
  "hardwareLevel": "full",
  "maxZoom": 10,
  "minZoom": 0.6000000238418579,
  "maxExposure": 20,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera",
    "ultra-wide-angle-camera",
    "wide-angle-camera",
    "telephoto-camera",
    "telephoto-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": false,
  "isMultiCam": true,
  "minFocusDistance": 10,
  "minExposure": -20,
  "name": "0 (BACK) androidx.camera.camera2",
  "hasFlash": true,
  "hasTorch": true,
  "position": "back",
  "id": "0"
}
```

### Device

Samsung s23 utral

### VisionCamera Version

4.5.3

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by catchellers** [comment]
I already fixed!

Just change android:hardwareAccelerated="true" to false or REMOVE (recommend) in AndroidManifest.xml

**Comment by mussacharles60** [comment]
@dzungmv by removing it fixed the issue for me. Thanks
