### ISSUE TITLE
💭 (Android) Is it possible to access/expose the active Camera initiated by vision?

### ISSUE THREAD

**Issue by good-idea** [cuvent/react-native-vision-camera#3227]
### Question

I'm hoping to implement some custom camera functionality - specifically, disabling auto-focus and metering using [cancelFocusAndMetering()](https://developer.android.com/reference/androidx/camera/core/CameraControl#cancelFocusAndMetering()) and resuming them with `startFocusAndMetering()`. But, from what I can tell, I can't create my own connection to the device without closing the one created by Vision.

Is it possible to access the `camera` created within `CameraSession` within my own android code? And if not - what might it take to expose it?

I'm not sure if this is a complicated ask - but, it could be a nice way for people to extend the capabilities of Vision.

### What I tried

Wrote a bunch of java using `camera2` only to find that the connection I make to the device is closed once my app renders a `<Camera />`...

### VisionCamera Version

4.5.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey - nope, there is no public API for this.

You can find the CameraView via findNodeHandle on JS, then pass that ID to native and find it yourself, downcast it to a CameraView, unwrap the `cameraSession` from there and access it - but I really do not recommend doing that. It's not a public API, and I don't plan on supporting this.
