### ISSUE TITLE
💭 perspective Transform (@shopify/react-native-skia) not work on "frameProcessor" event

### ISSUE THREAD

**Issue by i7soft** [cuvent/react-native-vision-camera#3228]
### Question

Use processTransform3d in the code, **rotate** is work, but **perspective** not work.

`

          import { Matrix4, PaintStyle, perspective, processTransform3d, processTransformProps, rotateX, scale, Skia,SkImage, TileMode } from '@shopify/react-native-skia';
          import { useEffect } from 'react';
          import { StyleSheet, Text } from 'react-native';
          
          import {
              Camera,
              useCameraDevice,
              useCameraPermission,
              useSkiaFrameProcessor,
              useFrameProcessor
          } from 'react-native-vision-camera';
          
          
          export function CameraRealtimeDetection() {
              const device = useCameraDevice('back');
              const { hasPermission, requestPermission } = useCameraPermission();
          
          
          
              useEffect(() => {
                  requestPermission();
              }, [requestPermission]);
          
          
          
              const frameProcessor2 = useSkiaFrameProcessor((frame) => {
                  'worklet';
          
                  var matrix = processTransform3d([
                      { rotateZ: 0.5 },       // work √
                      { perspective: 500 },   // no work ×
                  ])
              
                  frame.concat(matrix)
          
                  frame.render()
                  
                  
              }, []);
          
              if (!hasPermission) {
                  return <Text>No permission</Text>;
              }
          
              if (device == null) {
                  return <Text>No device</Text>;
              }
          
              return (
                  <Camera
                      style={[{height:300,width:200}]}
                      device={device}
                      isActive={true}
                      frameProcessor={frameProcessor2}
                  />
              );
          }

`

### VisionCamera Version

4.5.3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Not enough details, no demo, and wrong issue template.
