### ISSUE TITLE
💭 send custom frame, which modified with RN-Skia to WebRTC

### ISSUE THREAD

**Issue by fukemy** [cuvent/react-native-vision-camera#3233]
### Question

Hello, I can integrate the library with webrtc in native code, but I am stucking at send custom frame(which using RN-skia to make effect) to webrtc, because I am using Rn-skia in JS side. Can you give me some avice

### What I tried

get native frame, send to webrtc

### VisionCamera Version

4.5.3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22💭+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
This is currently not supported and pretty difficult to implement.
