### ISSUE TITLE
🐛 Android Motorola device not reporting all existing cameras

### ISSUE THREAD

**Issue by okalil** [cuvent/react-native-vision-camera#3262]
### What's happening?

I want to use the ultra wide device camera that exist on Motorola Moto G84 5G, but it is not listed as one of the available camera devices.

Related issue: #595 

### Reproduceable Code

```tsx
const devices = useCameraDevices();
  useEffect(() => {
    console.log(JSON.stringify(devices));
  }, [devices]);
```

### Relevant log output

```shell
None
```

### Camera Device

```json
{
        "sensorOrientation": "landscape-left",
        "hardwareLevel": "full",
        "maxZoom": 8,
        "minZoom": 1,
        "maxExposure": 24,
        "supportsLowLightBoost": false,
        "neutralZoom": 1,
        "physicalDevices": [
            "wide-angle-camera"
        ],
        "supportsFocus": true,
        "supportsRawCapture": false,
        "isMultiCam": false,
        "minFocusDistance": 10,
        "minExposure": -24,
        "name": "0 (BACK) androidx.camera.camera2",
        "hasFlash": true,
        "hasTorch": true,
        "position": "back",
        "id": "0"
    }
```

### Device

Motorola Moto G84 5G

### VisionCamera Version

4.5.2

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
> Relevant log output
> 
> None

Closing, because no logs are provided.
