### ISSUE TITLE
✨ Record video from frame processor

### ISSUE THREAD

**Issue by ivgawev** [cuvent/react-native-vision-camera#3265]
### What feature or enhancement are you suggesting?

Forgive me if this already exists but I have not found any information about it.
When I try to record a video with a frame processor the video that is recorded is directly the output of the camera not the processed video.

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

I could not find

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
> When I try to record a video with a frame processor the video that is recorded is directly the output of the camera not the processed video.

Hey- what is a "processed video"?

**Comment by ivgawev** [comment]
> > When I try to record a video with a frame processor the video that is recorded is directly the output of the camera not the processed video.
> 
> Hey- what is a "processed video"?

Excuse my English. 

I mean that from our project we are trying to capture a video but with the image already processed by the frame processor. What we find is that when using the utility of this camera the native image of the camera is recorded, but without the changes applied by useSkiaFrameProcessor.

**Comment by mrousavy** [comment]
Ah you mean a Skia Frame Processor? No, this is currently not possible. This limitation is documented in the docs.

It's very very very very hard to build this, and I currently don't have the time to do so.
