### ISSUE TITLE
🐛 ReactNative | V0.76.0 react-native-vision-camera not getting autlinked

### ISSUE THREAD

**Issue by sandeep36butte** [cuvent/react-native-vision-camera#3279]
### What's happening?

I have upgraded the RN version to latest(0.76.0) to enable the RN NewArchitecture.
The React-native-vision-camera not package not seems to be autolinked.Getting getting error in the getcameradevices hooks.
<img width="525" alt="Screenshot 2024-11-05 at 10 21 39 AM" src="https://github.com/user-attachments/assets/7f190e29-1ccd-4f40-b4ed-7159313293ed">
<img width="1067" alt="Screenshot 2024-11-05 at 10 21 49 AM" src="https://github.com/user-attachments/assets/1acf22fe-6e62-4da8-9f26-bb1cf28bae42">

### Reproduceable Code

```tsx
GitHub Repo:https://github.com/sandeep36butte/RNBrownFeldApp

This is the brownfield Application.Just clone and run the app with yarn start and run on android.
```

### Relevant log output

```shell
ERROR  Warning: TypeError: Cannot read property 'CameraDevices' of undefined

This error is located at:
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in ReactNativeBrownFieldApp(RootComponent), js engine: hermes
 ERROR  Warning: TypeError: Cannot read property 'CameraDevices' of undefined

This error is located at:
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in ReactNativeBrownFieldApp(RootComponent), js engine: hermes
```

### Camera Device

```json
Null
```

### Device

pixel 8

### VisionCamera Version

4.6.0

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
~~Heyo - thanks for reporting! I investigated this and just created a fix for this here: https://github.com/mrousavy/react-native-vision-camera/pull/3281 :)~~

EDIT Sorry wrong issue - I haven't seen yours yet. Other people are running visioncamera on RN 0.76 fine 🤔

**Comment by mrousavy** [comment]
I'd appreciate a GitHub sponsor donation if you feel like this package and fix has helped you. :)

**Comment by sandeep36butte** [comment]
@mrousavy 
This is working fine now.The issue is with passing the proper location of the reactnative config file.
**autolinkLibrariesFromCommand** needs to know where to run the config command from. In this case. By default would be .. but in my case, my package.json is in ../ReactNative.

Can refer here for solution
https://github.com/facebook/react-native/issues/47406
