### ISSUE TITLE
🐛 [device/invalid-device] The given Camera Device (61) does not have any formats!

### ISSUE THREAD

**Issue by iliapnmrv** [cuvent/react-native-vision-camera#3284]
### What's happening?

There is an error caught in Sentry, looks like you can only reproduce it on this particular device. What can I do about low-end devices that do not have any formats?

https://sentry.vibeapp.ru/share/issue/828ac4a592d448d9a318440e80fbd49b/

### Reproduceable Code

```tsx
const device = useCameraDevice('back', {
    physicalDevices: [
      'ultra-wide-angle-camera',
      'telephoto-camera',
      'wide-angle-camera',
    ],
  });

  const format =
    device &&
    getCameraFormat(device, [
      {fps: 20},
      {videoAspectRatio: screenAspectRatio},
      {videoResolution: 'max'},
      {photoAspectRatio: screenAspectRatio},
      {photoResolution: 'max'},
      {autoFocusSystem: 'contrast-detection'},
    ]);


<Camera
    format={format}
    zoom={device.neutralZoom}
    device={device}
    onError={onError}
    codeScanner={codeScanner}
    lowLightBoost={false}
/>
```

### Relevant log output
[2025-02-28T11:31:35.658000Z] INFO    [CameraDevices]: Initializing ProcessCameraProvider...
[2025-02-28T11:31:35.750000Z] INFO    [CameraDevices]: Camera #0 is now available.
[2025-02-28T11:31:35.751000Z] INFO    [CameraDevices]: Camera #1 is now available.
[2025-02-28T11:31:35.751000Z] INFO    [CameraDevices]: Camera #20 is now available.
[2025-02-28T11:31:35.751000Z] INFO    [CameraDevices]: Camera #61 is now available.
[2025-02-28T11:31:39.679000Z] INFO    [Camera2CameraInfo]: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_3
[2025-02-28T11:31:39.718000Z] INFO    [Camera2CameraInfo]: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_3
[2025-02-28T11:31:39.723000Z] INFO    [Camera2CameraInfo]: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
[2025-02-28T11:31:39.727000Z] INFO    [Camera2CameraInfo]: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_FULL
[2025-02-28T11:31:39.979000Z] INFO    [CameraDevices]: Initializing ExtensionsManager...
[2025-02-28T11:31:40.085000Z] INFO    [CameraDevices]: Successfully initialized!
[2025-02-28T11:31:40.317000Z] ERROR   [CapabilitiesByQuality]: No supported EncoderProfiles
[2025-02-28T11:31:40.320000Z] ERROR   [CapabilitiesByQuality]: No supported EncoderProfiles

### Camera Device

```json
formats is null
```

### Device

Xiaomi Redmi 9C (Android 10)

### VisionCamera Version

4.6.2

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
<img width="342" alt="Screenshot 2024-11-11 at 11 10 13" src="https://github.com/user-attachments/assets/5522e4c6-a3a8-4758-ac4e-3ddf319e928d">

I need those. I don't really know where the error is coming from. Sentry gives you those logs.

**Comment by mrousavy** [comment]
Either way -if a device doesn't have any formats there's nothing I can do, it simply cannot be used.

I don't really know if you are experiencing a crash here or not because you didn't share that information with me - but if it is a crash I guess the only thing I can do is to just not return any devices in thsi case.

**Comment by iliapnmrv** [comment]
Hi! I've added native android logging in Sentry

Looks like this device's camera works. At least users get this error during a few hours of using the app. If camera didn't work at all, users would have leave and delete app immediately (but sentry has it as `fatal` level)

Devices are
- Redmi 9C NFC (74%)
- Smart slim plus (21%)
- Redmi Note 9 (4%)

Error: No supported EncoderProfiles. 
```js
{
  tag: CapabilitiesByQuality
}
```

**Comment by Semiteplov** [comment]
@mrousavy I am experiencing the same issue on a Redmi 9C NFC. The useCameraFormat call crashes the app when used as follows:
```typescript
const format = useCameraFormat(device, [
    {
      photoAspectRatio: window.height / window.width,
    },
  ])

<Camera
    photo
    device={device}
    format={format}
    ...
/>
```

**Comment by iliapnmrv** [comment]
@Semiteplov do you have this device with you? I've only got this error in Sentry and I'm not able to debug it properly
You can try [these steps](https://react-native-vision-camera.com/docs/guides/troubleshooting#runtime-issues-1)

**Comment by Semiteplov** [comment]
> do you have this device with you? I've only got this error in Sentry and I'm not able to debug it properly
> You can try [these steps](https://react-native-vision-camera.com/docs/guides/troubleshooting#runtime-issues-1)

Unfortunately, I don’t have this device either. I only saw the crash log in Sentry as well.
