### ISSUE TITLE
🐛 useSkiaFrameProcessor's coordinate system is incorrect and the camera frame is not available

### ISSUE THREAD

**Issue by fax1ty** [cuvent/react-native-vision-camera#3314]
### What's happening?

There are many issues related to this specific problem.
https://github.com/mrousavy/react-native-vision-camera/issues/3301, https://github.com/mrousavy/react-native-vision-camera/issues/3297, https://github.com/mrousavy/react-native-vision-camera/issues/3296, https://github.com/mrousavy/react-native-vision-camera/issues/3169, https://github.com/mrousavy/react-native-vision-camera/issues/3160

![image](https://github.com/user-attachments/assets/cc9cc4ab-bd34-4a9f-961c-990dbe5b0434)

### Reproduceable Code

```tsx
import {
  Camera,
  useCameraDevice,
  useCameraPermission,
  useSkiaFrameProcessor,
} from "react-native-vision-camera";
import { StyleSheet } from "react-native";
import { useEffect } from "react";
import { Skia } from "@shopify/react-native-skia";

export default function Index() {
  const device = useCameraDevice("back");
  const { hasPermission, requestPermission } = useCameraPermission();

  const frameProcessor = useSkiaFrameProcessor((frame) => {
    "worklet";

    frame.render();

    const centerX = frame.width / 2;
    const centerY = frame.height / 2;

    const paint = Skia.Paint();
    paint.setColor(Skia.Color("red"));
    const rect = Skia.XYWHRect(centerX, centerY, 150, 150);
    frame.drawRect(rect, paint);
  }, []);

  useEffect(() => {
    requestPermission();
  }, []);

  if (!hasPermission || !device) return null;

  return (
    <>
      <Camera
        style={StyleSheet.absoluteFill}
        device={device}
        isActive
        frameProcessor={frameProcessor}
      />
    </>
  );
}
```

### Relevant log output

```shell
11-30 17:33:21.758  5546  5558 W System  : A resource failed to call HardwareBuffer.close.
11-30 17:33:24.289  5546  5546 I RNSkia  : updateAndRelease() failed. The exception above can safely be ignored
11-30 17:33:24.356  5546  5546 E app.warpzone: [SurfaceTexture-0-5546-6] updateAndRelease: EGLConsumer is not attached to an OpenGL ES context
```

### Camera Device

```json
{
  "formats": [],
  "sensorOrientation": "landscape-left",
  "hardwareLevel": "limited",
  "maxZoom": 1,
  "minZoom": 1,
  "maxExposure": 6,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "ultra-wide-angle-camera"
  ],
  "supportsFocus": false,
  "supportsRawCapture": false,
  "isMultiCam": false,
  "minFocusDistance": 0,
  "minExposure": -6,
  "name": "10 (BACK) androidx.camera.camera2",
  "hasFlash": false,
  "hasTorch": false,
  "position": "back",
  "id": "10"
}
```

### Device

Android Emulator

### VisionCamera Version

4.6.3

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [X] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by fax1ty** [comment]
@mrousavy

**Comment by ghost** [comment]
same issue 
react-native: 0.76.3
react-native-vision-camera: 4.6.3

**Comment by agoransson** [comment]
I'm seeing the same issue.

Dependencies:
```
    "react-native": "0.76.3",
    "react-native-vision-camera": "^4.6.3",
    "@shopify/react-native-skia": "^1.7.0",
    "react-native-reanimated": "^3.16.3",
```

I think the output looks mirrored, along both axis'.

Camera:
```
<Camera
    outputOrientation="device"
    frameProcessor={frameProcessor}
    style={StyleSheet.absoluteFill}
    device={device}
    isActive={true}
/>
```

Frame 1: (square, in middle)
```
        const centerX = frame.width / 2
        const centerY = frame.height / 2
        const rect = Skia.XYWHRect(centerX, centerY, 10, 10)
        const paint1 = Skia.Paint()
        paint1.setColor(Skia.Color('red'))
        frame.drawRect(rect, paint1)
```
![Screenshot_20241208_094950](https://github.com/user-attachments/assets/c71cf06d-79c0-4403-909a-bb256e54577c)


Frame 2: (increased width, in middle)
```
        const centerX = frame.width / 2
        const centerY = frame.height / 2
        const rect = Skia.XYWHRect(centerX, centerY, 100, 10)
        const paint1 = Skia.Paint()
        paint1.setColor(Skia.Color('red'))
        frame.drawRect(rect, paint1)
```
![Screenshot_20241208_095115](https://github.com/user-attachments/assets/2518804a-dff5-40e7-9407-071d40d299cb)
