### ISSUE TITLE
🐛 JNI Crash when trying to use multiple Frame Processor Plugins in a single Frame Processor

### ISSUE THREAD

**Issue by ldstein** [cuvent/react-native-vision-camera#431]
### Question

Hi,

Hi created two test plugins, ([Plugin1](https://github.com/ldstein/MeshCameraTest/blob/master/android/app/src/main/java/com/meshcameratest/frameprocessors/ExamplePlugin1.java), [Plugin2](https://github.com/ldstein/MeshCameraTest/blob/master/android/app/src/main/java/com/meshcameratest/frameprocessors/ExamplePlugin2.java)) based on the [ExamplePlugin](https://github.com/mrousavy/react-native-vision-camera/blob/main/example/src/frame-processors/ExamplePlugin.ts).

They have been added a to [Package](https://github.com/ldstein/MeshCameraTest/blob/master/android/app/src/main/java/com/meshcameratest/frameprocessors/FrameProcessorPackage.java) and added to the [MainApplication](https://github.com/ldstein/MeshCameraTest/blob/master/android/app/src/main/java/com/meshcameratest/MainApplication.java) as per the examples provided.

In my App I call both of them [here](https://github.com/ldstein/MeshCameraTest/blob/8104b30e2bf3cac3a8677b7ad94c3361d4d31cfe/App.js#L45-L58), which causes the app to consistently crash with the following error:

```
2021-09-14 21:17:03.138 12726-12883/com.meshcameratest A/.meshcamerates: java_vm_ext.cc:577] JNI DETECTED ERROR IN APPLICATION: can't call java.lang.Object com.meshcameratest.frameprocessors.ExamplePlugin1.callback(androidx.camera.core.ImageProxy, java.lang.Object[]) on instance of com.meshcameratest.frameprocessors.ExamplePlugin2
    java_vm_ext.cc:577]     in call to CallObjectMethodV
    java_vm_ext.cc:577]     from void com.mrousavy.camera.CameraView.frameProcessorCallback(androidx.camera.core.ImageProxy)
```

The crash will always occur on the second call regardless of order. No crash occurs if I run call just a single plugin.

It's very possible I'm missing some fundamental understanding of what you can and cannot do within a worklet, hence this is phrased as a question rather than a bug.

Any guidance appreciated. 

Example repo available at https://github.com/ldstein/MeshCameraTest

### What I tried

- Register plugins directly in onCreate
- Moved packages around
- Clear cache in metro, gradle 
- Ensure react-reanimated plugin + setup is complete

### VisionCamera Version

2.7.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hi! Thanks for the _very detailed_ bug report and clear reproduceable example! 🖤 

You should be able to call both plugins, yes, so this is a bug. Does this work on iOS?

**Comment by mrousavy** [comment]
Can you share the full adb (or Android Studio) logs? At the start of the app there should be two logs saying "Installing Frame Processor Plugin ..."

**Comment by ldstein** [comment]
No problem. Really excited by what your lib solves.

Unfortunately the IOS side is outside by knowledge.

I added the adb logcat [here](https://github.com/ldstein/MeshCameraTest/blob/master/logs/crash.log). The "Installing Frame Processor Plugin" lines start  [here](https://github.com/ldstein/MeshCameraTest/blob/5013c323c6ef45a477f1802f919713c9b281b4fc/logs/crash.log#L45-L50).

Let me know if I can be of futher assistance.

**Comment by rodgomesc** [comment]
ohh no, this is crucial for a project that i'm involved :/

**Comment by mrousavy** [comment]
@rodgomesc can you test iOS?

**Comment by mrousavy** [comment]
You guys wanna see something really weird? I tried to reproduce this here in the `example/` app and called 2 separate frame processor plugins like this:

```ts
  const frameProcessor = useFrameProcessor((frame) => {
    'worklet';
    const values = examplePlugin(frame);
    console.log(`Return Values: ${JSON.stringify(values)}`);
    const another = anotherPlugin(frame);
    console.log(`Another plugin: ${another}`);
  }, []);
```

and it works. No crash. [Here's the branch](https://github.com/mrousavy/react-native-vision-camera/tree/fix/two-plugins)

**Comment by ldstein** [comment]
Interesting. Crashing on my end if I enable two plugins but okay when running a single plugin.

I noticed it's crashing if I close the App then relaunch. Seems to be ok if the Camera/Mic permissions screen is displayed first.

Could it possibly be related to me building in Windows? 

[react-native-vision-camera-two-plugins-crash.log](https://github.com/mrousavy/react-native-vision-camera/files/7169665/react-native-vision-camera-two-plugins-crash.log)

**Comment by mrousavy** [comment]
Hmm, did you clean your metro cache before launching the app? `yarn start --reset-cache`

**Comment by ldstein** [comment]
Tried a few things this morning:

- Clean install of your two plugins branch
- Build from Android Studio and `npm run android`
- `yarn start --reset-cache` on every attempt. Also `npx react-native start --reset-cache`

I'm observing two crashes: 

1. Occurs when second plugin executes (consistent)

```
 -------------------------------------------------------
 react-native-vision-camera-two-plugins-crash2.log:
 react-native-vision-camera-two-plugins-crash3.log:
 ------------------------------------------------------- 
 LOG  Running "CameraPage" with {"initialProps":{"componentId":"Component1"},"rootTag":1}
 LOG  re-rendering camera page without active camera
 LOG  Re-rendering camera page with active camera. Device: "back (0)" (4000x2000 @ 60fps)
 LOG  Camera initialized!
 LOG  Re-rendering camera page with active camera. Device: "back (0)" (4000x2000 @ 60fps)
 LOG  Return Values: {"example_str":"Test","example_array":["Hello!",true,17.38],"example_double":5.3,"example_bool":true}
 BUNDLE  ./index.js
```

2. App loads to camera view, Permission was granted in previous use. (Intermittent, doesn't look like Frame Processor has a chance):
```
 -------------------------------------------------------
 react-native-vision-camera-two-plugins-crash4.log:
 -------------------------------------------------------
 LOG  Running "CameraPage" with {"initialProps":{"componentId":"Component1"},"rootTag":1}
 LOG  re-rendering camera page without active camera
 LOG  Re-rendering camera page with active camera. Device: "back (0)" (4000x2000 @ 60fps)
```

I'm going to pull my old Macbook Pro out of storage, see if OS makes a difference.

What version of Node are you running on your end? 

[react-native-vision-camera-two-plugins-crash2.log](https://github.com/mrousavy/react-native-vision-camera/files/7173819/react-native-vision-camera-two-plugins-crash2.log)
[react-native-vision-camera-two-plugins-crash3.log](https://github.com/mrousavy/react-native-vision-camera/files/7173817/react-native-vision-camera-two-plugins-crash3.log)
[react-native-vision-camera-two-plugins-crash4.log](https://github.com/mrousavy/react-native-vision-camera/files/7173818/react-native-vision-camera-two-plugins-crash4.log)

**Comment by mrousavy** [comment]
I'm using Node v14.17.4. This might also be an NDK/JNI/[fbjni](https://github.com/facebookincubator/fbjni) bug....

**Comment by ldstein** [comment]
Small update. I noticed disabling hermes greatly improves the stability of FrameProcessors.

I have a simple QR Scanner App based on Google Vision processing 2K images at 30FPS for over an hour. 

If I enable Hermes, it crashes out with JNI error.

Unfortunately it doesn't solve the multi-FrameProcessor bug. That still occurs regardless of hemes being used or not.

Still working on procuring a Macbook for further testing. It's been hijacked for remote learning by my daughter.

I suspect the issue lies somewhere within my development environment.

**Comment by mrousavy** [comment]
> Small update. I noticed disabling hermes greatly improves the stability of FrameProcessors.

Huh, then it's a Hermes bug? Maybe the Hermes garbage collector (Hades) does not run on the same Thread? I'd have to coordinate that with the guys from the Hermes team, are you [still on hermes-engine 8.1.0](https://github.com/ldstein/MeshCameraTest/blob/5013c323c6ef45a477f1802f919713c9b281b4fc/package-lock.json#L7377)?

> I have a simple QR Scanner App based on Google Vision processing 2K images at 30FPS for over an hour.

Wow! Awesome, I really did something cool with the Frame Processor API 😄 

> Unfortunately it doesn't solve the multi-FrameProcessor bug. That still occurs regardless of hemes being used or not.

That's so weird. I wish I could reproduce it somehow... Did you try to run it on other Android phones maybe? What Android Studio, what Android SDK, what JDK and what NDK versions are you using? All latest?

> It's been hijacked for remote learning by my daughter

😄 

> I suspect the issue lies somewhere within my development environment.

 I would normally say I doubt that, but we'll see.

**Comment by ldstein** [comment]
Small update:

- Brand new install of Android Studio and Node on the trusty 2011 Macbook Pro. Everything left at defaults. No other development tools on this machine
- Cloned https://github.com/mrousavy/react-native-vision-camera/tree/fix/two-plugins
- `npm install` then `cd example` then `npm install`
- `npm run android`

No other changes.

Compiles and installs on the phone ok, grant permission, camera fades in and crashes on second frameprocessor call  with identical error as on Windows machine.

Tested on both a Pixel 3 and Pixel 2 with similar result. Going to find myself some non-Pixel phones to test.

Also going to mess around with the Android SDKs / ndk / Java versions as per your suggestion.

**Comment by astanb** [comment]
If it's any help, I did the above steps using a Samsung Galaxy Tab A7 and a Xiaomi Mi9 and had a similar crash on both.

[Samsung Logcat here](https://gist.github.com/alexstanbury/7f5d06e1084e15af24bd6f774cb0cc2f)
[Xiaomi Logcat here](https://gist.github.com/alexstanbury/9254c9ab2b2d809cbc9453d72007bef7)

**Comment by icc-guerrero** [comment]
I tried with 2.8.0 and Im also suffering the same JNI crash, @mrousavy. If I enable a second plugin, it crashes. I checked @alexstanbury logs and seems the same problem. This log entry could might help you identifying the issue:

JNI DETECTED ERROR IN APPLICATION: can't call java.lang.Object com.visioncameraocr.**VisionCameraOcrPlugin**.callback(androidx.camera.core.ImageProxy, java.lang.Object[]) on instance of com.visioncamerafacedetector.**VisionCameraFaceDetectorPlugin**

Why the callback from one plugin is been called from the other one?

**Comment by mrousavy** [comment]
> Why the callback from one plugin is been called from the other one?


Yeah I also don't get that. The past few days have been really busy for me so I couldn't investigate this further, I hope I can find some free time to do that soon.

**Comment by astanb** [comment]
Running two frame processors appears to work fine on iOS, tested on an iPhone 7 device running iOS 13.6.1. I had to downgrade the reanimated version to 2.2.2 (from the alpha used in the examples) as it seems the reanimated pods reference react-native-screens for some reason which gave a build error. 

So it looks like this is purely an Android issue. I tried separating the two test plugins into their own Android packages to see if that made a difference but it didn't.

**Comment by mrousavy** [comment]
@alexstanbury in the logs you shared I can see the following:

```
2021-09-21 17:03:24.669 16150-19603/com.mrousavy.camera.example I/VisionCamera: Calling Plugin "class com.mrousavy.camera.example.ExampleFrameProcessorPlugin"...
2021-09-21 17:03:24.669 16150-19603/com.mrousavy.camera.example D/ExamplePlugin: 640 x 480 Image with format #35. Logging 6 parameters:
2021-09-21 17:03:24.669 16150-19603/com.mrousavy.camera.example D/ExamplePlugin:   -> hello! (java.lang.String)
2021-09-21 17:03:24.669 16150-19603/com.mrousavy.camera.example D/ExamplePlugin:   -> parameter2 (java.lang.String)
2021-09-21 17:03:24.669 16150-19603/com.mrousavy.camera.example D/ExamplePlugin:   -> true (java.lang.Boolean)
2021-09-21 17:03:24.670 16150-19603/com.mrousavy.camera.example D/ExamplePlugin:   -> 42.0 (java.lang.Double)
2021-09-21 17:03:24.671 16150-19603/com.mrousavy.camera.example D/ExamplePlugin:   -> { NativeMap: {"test":0,"second":"test"} } (com.facebook.react.bridge.ReadableNativeMap)
2021-09-21 17:03:24.671 16150-19603/com.mrousavy.camera.example D/ExamplePlugin:   -> ["another test",5] (com.facebook.react.bridge.ReadableNativeArray)
2021-09-21 17:03:24.674 16150-19603/com.mrousavy.camera.example I/VisionCamera: Calling Plugin "class com.mrousavy.camera.example.AnotherPlugin"...
2021-09-21 17:03:24.674 16150-19603/com.mrousavy.camera.example A/.camera.exampl: java_vm_ext.cc:578] JNI DETECTED ERROR IN APPLICATION: can't call java.lang.Object com.mrousavy.camera.example.ExampleFrameProcessorPlugin.callback(androidx.camera.core.ImageProxy, java.lang.Object[]) on instance of com.mrousavy.camera.example.AnotherPlugin
    java_vm_ext.cc:578]     in call to CallObjectMethodV
    java_vm_ext.cc:578]     from void com.mrousavy.camera.CameraView.frameProcessorCallback(androidx.camera.core.ImageProxy)
2021-09-21 17:03:24.674 16150-19461/com.mrousavy.camera.example I/ReactNativeJS: Return Values: {"example_str":"Test","example_array":["Hello!",true,17.38],"example_double":5.3,"example_bool":true}
2021-09-21 17:03:24.992 16150-19603/com.mrousavy.camera.example A/.camera.exampl: runtime.cc:677] Runtime aborting...
```


So at first it's calling

```
2021-09-21 17:03:24.669 16150-19603/com.mrousavy.camera.example I/VisionCamera: Calling Plugin "class com.mrousavy.camera.example.ExampleFrameProcessorPlugin"...
```

which works fine, then it's calling

```
2021-09-21 17:03:24.674 16150-19603/com.mrousavy.camera.example I/VisionCamera: Calling Plugin "class com.mrousavy.camera.example.AnotherPlugin"...
```

which crashes with the error 

```
can't call java.lang.Object com.mrousavy.camera.example.ExampleFrameProcessorPlugin.callback(androidx.camera.core.ImageProxy, java.lang.Object[]) on instance of com.mrousavy.camera.example.AnotherPlugin
```

wtf?

**Comment by mrousavy** [comment]
Can you try again with the latest change in https://github.com/mrousavy/react-native-vision-camera/pull/435?

**Comment by icc-guerrero** [comment]
#435 just tested. Same issue :(
2021-09-23 12:20:28.264 12948-13338/org.unfccc.cop26idcheck A/cc.cop26idchec: runtime.cc:638] JNI DETECTED ERROR IN APPLICATION: can't call java.lang.Object com.visioncameraocr.VisionCameraOcrPlugin.callback(androidx.camera.core.ImageProxy, java.lang.Object[]) on instance of com.visioncamerafacedetector.VisionCameraFaceDetectorPlugin

**Comment by astanb** [comment]
> Can you try again with the latest change in #435?

I couldn't get the example to build, I get the following build error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-vision-camera:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /Users/alexstanbury/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /Users/alexstanbury/Desktop/pluginfix/react-native-vision-camera/android/.cxx/cmake/debug/armeabi-v7a VisionCamera}
  ninja: Entering directory `/Users/alexstanbury/Desktop/pluginfix/react-native-vision-camera/android/.cxx/cmake/debug/armeabi-v7a'
  [1/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/java-bindings/JHashMap.cpp.o
  [2/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/FrameProcessorPlugin.cpp.o
  FAILED: CMakeFiles/VisionCamera.dir/src/main/cpp/FrameProcessorPlugin.cpp.o 
  /Users/alexstanbury/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-androideabi21 --gcc-toolchain=/Users/alexstanbury/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/alexstanbury/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot  -DVisionCamera_EXPORTS -I../../../../build/fbjni-0.2.2-headers.jar -I../../../../build/third-party-ndk/boost -I../../../../build/third-party-ndk/double-conversion -I../../../../build/third-party-ndk/folly -I../../../../build/third-party-ndk/glog -I/Users/alexstanbury/Desktop/pluginfix/react-native-vision-camera/example/android/../node_modules/react-native/React -I/Users/alexstanbury/Desktop/pluginfix/react-native-vision-camera/example/android/../node_modules/react-native/React/Base -I/Users/alexstanbury/Desktop/pluginfix/react-native-vision-camera/example/android/../node_modules/react-native/ReactAndroid/src/main/jni -I/Users/alexstanbury/Desktop/pluginfix/react-native-vision-camera/example/android/../node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/turbomodule/core/jni -I/Users/alexstanbury/Desktop/pluginfix/react-native-vision-camera/example/android/../node_modules/react-native/ReactCommon -I/Users/alexstanbury/Desktop/pluginfix/react-native-vision-camera/example/android/../node_modules/react-native/ReactCommon/callinvoker -I/Users/alexstanbury/Desktop/pluginfix/react-native-vision-camera/example/android/../node_modules/react-native/ReactCommon/jsi -I/Users/alexstanbury/Desktop/pluginfix/react-native-vision-camera/example/android/../node_modules/hermes-engine/android/include -I/Users/alexstanbury/Desktop/pluginfix/react-native-vision-camera/example/android/../node_modules/react-native-reanimated/Common/cpp/headers/Tools -I/Users/alexstanbury/Desktop/pluginfix/react-native-vision-camera/example/android/../node_modules/react-native-reanimated/Common/cpp/headers/SpecTools -I/Users/alexstanbury/Desktop/pluginfix/react-native-vision-camera/example/android/../node_modules/react-native-reanimated/Common/cpp/headers/SharedItems -I/Users/alexstanbury/Desktop/pluginfix/react-native-vision-camera/example/android/../node_modules/react-native-reanimated/Common/cpp/headers/Registries -I/Users/alexstanbury/Desktop/pluginfix/react-native-vision-camera/example/android/../node_modules/react-native-reanimated/Common/cpp/headers/LayoutAnimations -I/Users/alexstanbury/Desktop/pluginfix/react-native-vision-camera/example/android/../node_modules/react-native-reanimated/Common/cpp/hidden_headers -I../../../../src/main/cpp -DFOLLY_NO_CONFIG=1 -DFOLLY_HAVE_CLOCK_GETTIME=1 -DFOLLY_HAVE_MEMRCHR=1 -DFOLLY_USE_LIBCPP=1 -DFOLLY_MOBILE=1 -DON_ANDROID -DONANDROID -DFOR_HERMES=true -O0 -fno-limit-debug-info  -fPIC   -std=gnu++14 -MD -MT CMakeFiles/VisionCamera.dir/src/main/cpp/FrameProcessorPlugin.cpp.o -MF CMakeFiles/VisionCamera.dir/src/main/cpp/FrameProcessorPlugin.cpp.o.d -o CMakeFiles/VisionCamera.dir/src/main/cpp/FrameProcessorPlugin.cpp.o -c ../../../../src/main/cpp/FrameProcessorPlugin.cpp
  ../../../../src/main/cpp/FrameProcessorPlugin.cpp:33:125: error: no member named 'c_str' in 'facebook::jni::basic_strong_ref<facebook::jni::JClass, facebook::jni::LocalReferenceAllocator>'
    __android_log_print(ANDROID_LOG_INFO, TAG, "Plugin \"%s\" (actual: \"%s\"): Calling callback...", typeName.c_str(), clzzz.c_str());
                                                                                                                        ~~~~~ ^
  ../../../../src/main/cpp/FrameProcessorPlugin.cpp:33:41: error: use of undeclared identifier 'TAG'
    __android_log_print(ANDROID_LOG_INFO, TAG, "Plugin \"%s\" (actual: \"%s\"): Calling callback...", typeName.c_str(), clzzz.c_str());
                                          ^
  2 errors generated.
  [3/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/java-bindings/JImageProxy.cpp.o
  [4/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/CameraView.cpp.o
  [5/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/java-bindings/JImageProxyHostObject.cpp.o
  [6/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/VisionCameraScheduler.cpp.o
  [7/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/JSIJNIConversion.cpp.o
  [8/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/VisionCamera.cpp.o
  [9/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/FrameProcessorRuntimeManager.cpp.o
  ninja: build stopped: subcommand failed.
  ```

So I commented the offending line and it built ok, but unfortunately I'm still getting the same issue.  [Logs here](
https://gist.github.com/alexstanbury/c8dffbff2b84373ad82e2ce298c4f95c)

**Comment by ldstein** [comment]
> Can you try again with the latest change in #435?

Also a compiler error for me:

[compile-error.log](https://github.com/mrousavy/react-native-vision-camera/files/7217427/compile-error.log)

**Comment by mrousavy** [comment]
Whoops, can you replace `TAG` with something like `"testtest"` and try again? I need that log.

**Comment by ldstein** [comment]
Different error this time (C++ is completely foreign to me)

[compile-error.log](https://github.com/mrousavy/react-native-vision-camera/files/7217415/compile-error.log)

**Comment by mrousavy** [comment]
ah shit sorry again! doing this on mobile 😅 try again now

**Comment by astanb** [comment]
> ah shit sorry again! doing this on mobile 😅 try again now

[Here you go](https://gist.github.com/alexstanbury/6a65d22c396edf8804f477194f43946d)

Think these are the lines you're interested in:

`2021-09-23 14:01:18.687 22965-23043/com.mrousavy.camera.example I/TEST_TAG: Plugin "class com.mrousavy.camera.example.ExampleFrameProcessorPlugin" (actual: "class com.mrousavy.camera.example.ExampleFrameProcessorPlugin"): Calling callback...
`

`2021-09-23 14:01:18.690 22965-23043/com.mrousavy.camera.example I/TEST_TAG: Plugin "class com.mrousavy.camera.example.AnotherPlugin" (actual: "class com.mrousavy.camera.example.ExampleFrameProcessorPlugin"): Calling callback...
`

**Comment by mrousavy** [comment]
what the f

**Comment by mrousavy** [comment]
gonna report abuse on that gist because that's the weirdest thing I've ever seen 
![Screenshot 2021-09-23 at 15 06 41](https://user-images.githubusercontent.com/15199031/134512222-d266c2cb-8d4f-4c32-a130-2e622c0c0396.png)

**Comment by mrousavy** [comment]
Trying a really weird thing - does the latest commit in the PR fix the issue for you guys? cc @alexstanbury

**Comment by astanb** [comment]
> Trying a really weird thing - does the latest commit in the PR fix the issue for you guys? cc @alexstanbury

Yep, that works:

[ log here  :tada:](https://gist.github.com/alexstanbury/ba44096c3b4acbcb516e375e162cc523)

**Comment by mrousavy** [comment]
lol, fresh

will clean up the PR and merge when I get home

**Comment by astanb** [comment]
Brilliant, thanks for sorting it.

**Comment by mrousavy** [comment]
thanks for testing + reporting 🙏

**Comment by icc-guerrero** [comment]
@mrousavy: I can confirm that is also works for me.  I mentioned a few hours ago that was not working, but was clearly my fault: C++ libraries were not properly cleaned up. After deleting cached ones it worked as expected. Thanks!

**Comment by ldstein** [comment]
Nice one, all good on this end too.

**Comment by mrousavy** [comment]
I've fixed this in [**2.8.1**](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v2.8.1) 🎉🚀

**Comment by mhorowitz** [comment]
> Maybe the Hermes garbage collector (Hades) does not run on the same Thread?

That's correct.  From jsi.h: "The [HostObject] C++ object's dtor will be called when the GC finalizes this object.  (This may be as late as when the Runtime is shut down.) You have no control over which thread it is called on."  Before Hades, this would always happen synchronously, but one of the ways Hades reduces JS stalls is by sometimes calling dtors on a separate thread.  If you need to delete an fbjni global_ref, then you need to arrange to queue that work on a Java-registered thread (preferred), or use ThreadScope::WithClassLoader to temporarily register the current thread.

**Comment by mrousavy** [comment]
Thanks for elaborating @mhorowitz! I actually use WithClassLoader in the dtor now, but how does "you need to arrange to queue that work on a Java-registered thread (preferred)" work? Register the Hades GC Thread with JNI?

**Comment by mhorowitz** [comment]
You can't usefully register the Hades GC thread, because there's no way to safely unregister it.

I mean you would have some queue which you could add to in native from any thread, and read from on a java thread, which would destroy the references added to the queue.  This is mostly independent from JNI.

**Comment by mrousavy** [comment]
I see, thanks for clarifying! I'm going to stick with the fbjni Class Loader solution for now.
