### ISSUE TITLE
🐛 iOS Build Error: `"RNReanimated/Scheduler.h"` not found

### ISSUE THREAD

**Issue by john-mokaied** [cuvent/react-native-vision-camera#454]
### What were you trying to do?

error while building the app (iOS)

### What happened instead?

RNReanimated/Scheduler.h not found in VisionCameraScheduler.h

### Device

Xcode

### VisionCamera Version

2.8.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
* Which react-native version are you using?
* Which react-native-reanimated version are you using?

**Comment by john-mokaied** [comment]
"react-native-reanimated": "^2.2.2",
  "react": "17.0.2",
    "react-native": "0.65.1",
    "react-native-screens": "^3.7.2",

**Comment by john-mokaied** [comment]
I had tried to use same your     "react-native-reanimated": "^2.3.0-alpha.3",
but got the same issue.

**Comment by mrousavy** [comment]
Can you open Xcode and hit <kbd>⌘</kbd> + <kbd>⇧</kbd> + <kbd>O</kbd> (Command + Shift + O), then enter `Scheduler` and let me know what Xcode finds? 

I assume you did run `pod install` correctly and Reanimated works inside your App, right?

**Comment by adhip94** [comment]
I get this.
<img width="1080" alt="Screenshot 2021-09-27 at 3 55 08 PM" src="https://user-images.githubusercontent.com/20703483/134891468-24335ab1-e881-44cf-b27e-46a2bc342b1b.png">

My react-native-reanimated version is quite low (1.13.3). Rest all dependencies are up to date.

**Comment by mrousavy** [comment]
Oh yeah, VisionCamera requires react-native-reanimated 2.2.0 or higher. I'm working on making Reanimated an optional dependency here: https://github.com/mrousavy/react-native-vision-camera/pull/412 but haven't found the time to finish that yet.

**Comment by adhip94** [comment]
@mrousavy I finally upgraded react-native-reanimated to v2.2.2, and now while building in Xcode I get this error
<img width="1019" alt="Screenshot 2021-09-28 at 11 24 49 AM" src="https://user-images.githubusercontent.com/20703483/135031073-816e5b8d-dbd9-4849-87bb-9bfa7cafbe41.png">

**Comment by mrousavy** [comment]
Hmm, is that with Hermes enabled?

**Comment by adhip94** [comment]
Yes, Hermes is enabled. I did manage to resolve the issue by adding [this patch](https://github.com/mrousavy/react-native-vision-camera/issues/390#issuecomment-912819523).

**Comment by mrousavy** [comment]
Cool! Can you shoot me a PR to fix this issue once and for all, instead of patching the library yourself?

**Comment by hadus07** [comment]
Any updates on this?

**Comment by rodgomesc** [comment]
weird, i'm not facing this problem anymore after last ra-alpha-3

**Comment by john-mokaied** [comment]
<img width="1010" alt="Screenshot 2021-10-15 at 11 57 38" src="https://user-images.githubusercontent.com/50097658/137469804-eea2e271-a879-4a60-b06f-1a45840073c7.png">

**Comment by john-mokaied** [comment]
<img width="1130" alt="Screenshot 2021-10-15 at 11 54 48" src="https://user-images.githubusercontent.com/50097658/137469856-69146493-791f-4f28-99b8-43dbce3062e3.png">

**Comment by john-mokaied** [comment]
Still facing same issue :(

**Comment by coolvasanth** [comment]
@yahyamokaied were you able to resolve this issue ?

**Comment by adhip94** [comment]
Try upgrading react-native-reanimated to v2.2.3 and react-native-vision-camera to v2.9.3, clear pod and Xcode caches and build again.

**Comment by coolvasanth** [comment]
@adhip94 I updated the react-native-reanimated and react-native-vision-camera  to the plugin you suggested. Later deleted the Pods folder and pod.lock file from iOS folder and did pod install. Afterwards went to Xcode and cleaned the build and rebuild it. Still no luck, can you help me, where I might have made a mistake ?

**Comment by john-mokaied** [comment]
I did all setps many times but didn’t worked but **Finally I'm close to find the issue**,
 there is something missing during reanimated installing steps
 :( they have repo called playground, I cloned that repo and added this package and it worked well
  so you can investigate the difference between playground and yours to find the issue.

**Comment by coolvasanth** [comment]
@yahyamokaied  I will also try, but if you find a solution please comment here.

**Comment by john-mokaied** [comment]
import 'react-native-reanimated';
in top of index.js solved my porblem

**Comment by coolvasanth** [comment]
I did it @yahyamokaied  still I'm getting the error. Can you please confirm your react and react-native and react-native-reanimated package version ?

**Comment by coolvasanth** [comment]
@yahyamokaied can you please confirm you react, react-native react-native-reanimated package version ?

**Comment by coolvasanth** [comment]
Hi @mrousavy  can you suggest me the fix for this ?

**Comment by AbdurakhmonZiyodov** [comment]
hello everyone, has anyone been able to fix this error? I also get the same error and I can't fix it

**Comment by AbdurakhmonZiyodov** [comment]
I'm installing pod and it gives me this error at the end
<img width="938" alt="Screenshot 2022-11-11 at 10 02 37" src="https://user-images.githubusercontent.com/83976512/201267158-700fc1c1-e2d2-4a90-8523-451dcd7073ee.png">

**Comment by AbdurakhmonZiyodov** [comment]
my package.json file
<img width="497" alt="image" src="https://user-images.githubusercontent.com/83976512/201267358-d6bd7a01-b262-4a78-875a-be1d2f9cfabd.png">

Please help me
