### ISSUE TITLE
Crash in android while using frameProcessor❓ 

### ISSUE THREAD

**Issue by Invictus-Munish** [cuvent/react-native-vision-camera#474]
### Question

I am unable to use frame processor api. The app crashes if i use frame processor and works properly if i comment it down.

**Versions :**
"react-native": "0.64.2",
"react-native-reanimated": "2.2.2",
"react-native-vision-camera": "^2.8.3"

### What I tried

I tried using various versions of react native and reanimated but it still crashes.

### VisionCamera Version

2.8.3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
i have no information to diagnose this issue.
