### ISSUE TITLE
🐛 iPhone 11 doesn't record video with H.264 codec

### ISSUE THREAD

**Issue by HorbachAndrii** [cuvent/react-native-vision-camera#485]
### What were you trying to do?

I tried to record video with H.264 codec

### Reproduceable Code

```tsx
<Camera
    ref={cameraRef}
    device={devices.front}
    video={true}
    audio={true}
    isActive={true}
    preset="iframe-960x540"
    fps={25}
    onInitialized={() => setCameraReady(true)}
/>
```

### What happened instead?

When I tried to record a video with H.264 codec, I got HEVC video codec.

### Device

iPhone 11 (IOS 15.0.1)

### VisionCamera Version

2.8.0.

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
You can use `format={...}` to pick a format that records in H.264 codec. (I think I added those fields, if not, this is a feature request.)

**Comment by HorbachAndrii** [comment]
I didn't find line about codec(
https://github.com/mrousavy/react-native-vision-camera/blob/c627febde5c51336be058172d0ed4d19ea47d697/src/CameraDevice.ts#L109

**Comment by HorbachAndrii** [comment]
If you add the ability to control video I will be very happy.

**Comment by HorbachAndrii** [comment]
Could you add the ability to record video with h264 codec in the next release?
I very much needed this feature.

Or just say where can I make changes in code?

**Comment by mrousavy** [comment]
Right, I didn't include this in the format. I'm currently very busy with moving + work, so I don't know when I can build this feature. You can place a bug bounty to resolve it faster 😄

**Comment by HorbachAndrii** [comment]
If somebody needs to quick fix you can change in file

`node_modules/react-native-vision-camera/ios/RecordingSession.swift`

from:
 ` let videoWriter = AVAssetWriterInput(mediaType: .video, outputSettings: settings)`

to:
  ```
let videoWriter = AVAssetWriterInput(
          mediaType: .video,
          outputSettings: [
            AVVideoCodecKey: AVVideoCodecType.h264,
            AVVideoWidthKey: 540,
            AVVideoHeightKey: 960,
          ]
        )
```
