### ISSUE TITLE
✨ Use volume buttons to make photo / start video recoding

### ISSUE THREAD

**Issue by pke** [cuvent/react-native-vision-camera#486]
### What feature or enhancement are you suggesting?

Device default Camera apps allow users to use the volume buttons to make photos or start video recording.
It would be nice if this plugin would support this too.

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

There is currently no workaround for this feature.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
Hi!

> There is currently no workaround for this feature.

That's technically not correct. You can just use a react native library that detects when the volume down (or up) button is pressed, and call `takePhoto()` in that handler.

**Comment by pke** [comment]
You are right, that's actually how I do it with `react-native-camera` at the moment. Of course the event is triggered in fast succession and the listener needs to accommodate for that and only call `takePhoto` once. 
And I thought, triggering photos with volume buttons is such a common use case, that the camera module could bring such functionality already backed in (incl throttling the takePhoto calls).

Do you think an `optionalPeerDependency` combined with feature detection inside the `<Camera>` component could work? This way all users would instantly have this feature and don't need to add (and debounce) it themselves.

```ts
function Camera({ onPhoto, onPhotoError, device, ...props}) {

  React.useEffect(() => {
    let listener, SystemSetting
    try {
      SystemSetting = require("react-native-system-setting")
      SystemSetting.addVolumeListener(() => {
         debounce(device.takePhoto().then(onPhoto, onPhotoError)
      })
    } catch {
    }
    return () => listener && SystemSetting.removeVolumeListner(listener)
  }, [])

  // Rest of Camera component
}
```

**Comment by jqn** [comment]
@pke but how do you handle the volume button changing the volume level? Last time I tried I had to keep track of the volume levels and set it back to the original level when the camera screen unmounts.

**Comment by mrousavy** [comment]
You'd have to handle those using events, this is not something the Camera should do imo

**Comment by WilliamWelsh** [comment]
For anyone that searches for this, here is my solution using `react-native-volume-manager`

```tsx
  useEffect(() => {
    VolumeManager.setVolume(0.5);

    VolumeManager.showNativeVolumeUI({ enabled: false });
    const volumeListener = VolumeManager.addVolumeListener(() => {
      // If they get to volume 0 and keep pressing
      // the down button, we won't get any alerts,
      // but if we keep the volume at 0.5 then they
      // can never get to 0
      // same for volume at 100
      VolumeManager.setVolume(0.5);

      onInternalCameraImageCaptured();
    });

    return () => volumeListener.remove();
  }, [onInternalCameraImageCaptured]);
```

**Comment by stevengoldberg** [comment]
Hi @mrousavy, I was going to make a new issue for this but I found this old one. Using something like `react-native-volume-manager` is an imperfect hack. This should be handled by the camera library, per Apple docs:

https://developer.apple.com/documentation/avkit/avcaptureeventinteraction
