### ISSUE TITLE
🐛  Camera: Native Module 'CameraView' was null!

### ISSUE THREAD

**Issue by manuelbieh** [cuvent/react-native-vision-camera#488]
### What were you trying to do?

Hey, first of all, although I've worked with React for over 5 years on a daily basis I am still pretty new to React Native, so please bear with me if I've missed out on a step or if I'm just use it incorrectly. 

I've just tried to use this wonderful package in a completely new and bare Expo project. Once I call `Camera.getAvailableCameraDevices()` I get the error above. 

One of the reasons might be that I'm using the most recent versions of basically everything. I'm using an iPhone 13 with iOS 15 to test on, Expo Go, Expo 42, XCode 13 on an arm64 Mac. Not sure about that. Anyway, I had to follow the steps from the troubleshooting guide and had to set `SWIFT_VERSION` to `5.2` manually. Which I did, but didn't help.

### Reproduceable Code

The code I'm using is as minimal as it can be:

```sh
expo init react-native-app
cd react-native-app
expo install react-native-vision-camera
npx pod-install
expo prebuild
expo start
```

My App.tsx looks as simple as that:
```
import React, { useEffect } from 'react';
import { Button, View } from 'react-native';
import { Camera } from 'react-native-vision-camera';

export default function App() {
  useEffect(() => {
      const getDevices = async () => {
          const devices = await Camera.getAvailableCameraDevices();
          console.log(devices);
      };

      getDevices();
  }, []);

  return (
      <View>
          <Button title='Record video' onPress={() => {}} />
      </View>
  );
}
```

### What happened instead?

Once I open the app in Expo Go I get the following error:
```
Camera: Native Module 'CameraView' was null! Did you run pod install?
```
Yes, I did.

### Relevant log output

```shell
Camera: Native Module 'CameraView' was null! Did you run pod install?
at node_modules/react-native-vision-camera/src/Camera.tsx:40:26 in <global>
at node_modules/react-native-vision-camera/src/index.ts:1:0 in <global>
at App.tsx:3:0 in <global>
at index.js:4:0 in <global>
at http://192.168.178.193:19000/index.bundle?platform=ios&dev=true&hot=false&minify=false:121154:3 in global code

[Unhandled promise rejection: TypeError: null is not an object (evaluating 'CameraModule.getAvailableCameraDevices')]
at node_modules/react-native-vision-camera/src/Camera.tsx:257:31 in getAvailableCameraDevices
at node_modules/react-native-vision-camera/src/Camera.tsx:255:2 in getAvailableCameraDevices
at App.tsx:12:34 in getDevices
at App.tsx:11:27 in getDevices
at App.tsx:16:18 in useEffect$argument_0
at node_modules/react-native/Libraries/ReactNative/renderApplication.js:54:4 in renderApplication
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:117:25 in runnables.appKey.run
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:202:4 in runApplication
```

### Device

iPhone 13

### VisionCamera Version

2.8.3

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey! So in Expo Go you cannot use _native_ libraries, and VisionCamera is a native library.

You can either use Expo EAS (with the prebuild command) or a bare react-native project to use VisionCamera.

**Comment by kjoonas1** [comment]
I'm having the same problem with a bare react-native project. I keep getting error 
`Camera: Native Module 'CameraView' was null! Did you run pod install?`
 Tested with iOS (device & simulator).

**Comment by mrousavy** [comment]
@kjoonas1 well did you run pod install?

**Comment by kjoonas1** [comment]
> @kjoonas1 well did you run pod install?

Yes I did, and I also did everything mentioned under iOS in troubleshooting guide.
I also upgraded Xcode to latest version and checked swift version which is 5.2 and IPHONEOS_DEPLOYMENT_TARGET is set to 11.0.

^ Problem solved, had to clear everything again after updating Xcode and remove & build app again in iPhone to make it work.

**Comment by 9a-aaaaaaaa** [comment]
I'm having the same problem  ios

**Comment by gregdelaun** [comment]
same also on IOS

**Comment by dreese33** [comment]
Also seeing this on iOS for react-native@0.71.3

**Comment by monkeedev** [comment]
it looks odd but I've faced this issue too after I tried to install my project with `npx expo start` 
now I tried `yarn ios` (stands for `expo run:ios`) and the issue have gone
