### ISSUE TITLE
✨ Add support for generating videos in mp4?

### ISSUE THREAD

**Issue by adhip94** [cuvent/react-native-vision-camera#497]
### What feature or enhancement are you suggesting?

Currently when running this library for iOS it generates videos in mov format. I have a chat application which runs on both iOS and Android. Is it possible to generate videos in mp4 format for iOS so that it is cross compatible because I cannot play mov files on android using react-native-video.

### What Platforms whould this feature/enhancement affect?

iOS

### Alternatives/Workarounds

At the moment none, I am considering using [this](https://github.com/taltultc/react-native-mov-to-mp4), but since it is not mantained, not sure if it will work or not.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by jasonKRR** [comment]
it supports mp4 
https://mrousavy.com/react-native-vision-camera/docs/api/#videofiletype

**Comment by jasonKRR** [comment]
@adhip94

**Comment by mrousavy** [comment]
fixed in V3!
