### ISSUE TITLE
[2.9.0] Error: The given view was not found in view manager🐛 

### ISSUE THREAD

**Issue by ldstein** [cuvent/react-native-vision-camera#500]
### What were you trying to do?

Build and run example App at https://github.com/mrousavy/react-native-vision-camera/commit/bd46da614ee2f43b23eb90a71ab4c59be54fd01f on Android device.

Maybe related to #457

**Build Environment:**
Windows 10 x64
Openjdk 11.0.10 2021-01-19
Python 2.7.18

### Reproduceable Code

```tsx
git clone https://github.com/mrousavy/react-native-vision-camera.git
cd react-native-vision-camera
git checkout bd46da614ee2f43b23eb90a71ab4c59be54fd01f
npx yarn
cd example
npx yarn
npx yarn android
```

### What happened instead?

After app launches and user grants permission to Camera and Mic, red error box appears with Stack Trace:

![image](https://user-images.githubusercontent.com/3657344/136718767-0164ddcc-5980-4b98-abdc-55350308100c.png)

### Relevant log output

```shell
LOG  Running "VisionCameraExample" with {"rootTag":1}
 LOG  Re-rendering Navigator. Camera: undefined | Microphone: undefined
 LOG  Re-rendering Navigator. Camera: denied | Microphone: undefined
 LOG  Re-rendering Navigator. Camera: denied | Microphone: denied
 LOG  Requesting camera permission...
 LOG  Camera permission status: authorized
 LOG  Requesting microphone permission...
 LOG  Microphone permission status: authorized
 LOG  re-rendering camera page without active camera
 LOG  re-rendering camera page without active camera
 LOG  Re-rendering camera page with active camera. Device: "back (0)" (4000x2000 @ 60fps)
 ERROR  Error: Exception in HostFunction: com.mrousavy.camera.ViewNotFoundError: [system/view-not-found] The given view (ID 95) was not found in the view manager., js engine: hermes
```

### Device

Pixel 3, Android 11

### VisionCamera Version

2.9.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by Danilo-Js** [comment]
It seems like this is an Expo project, and you're trying to run it as a CLI project.
If that's the problem here, there are 3 ways to proceed.

1 - Use Expo (fast solution)
2 - Expo Eject
3 - Create a new CLI project and manually include the Expo Code there

**Comment by Danilo-Js** [comment]
You're right! I was mistaken.. =/

**Comment by mrousavy** [comment]
That's such an annoying bug. Can't seem to find a fix for that :(

**Comment by mrousavy** [comment]
maybe #511 fixes this issue... it's giving me headaches.

**Comment by ldstein** [comment]
> maybe #511 fixes this issue... it's giving me headaches.

I'm a little late to the party, but happy to report #511 fixed the issue, thanks!

**Comment by r0b0t3d** [comment]
I'm using 2.9.3 and still see this error


**Update**: I am only got this error when using `<Camera />` inside `<Modal />`

<img src="https://user-images.githubusercontent.com/8109285/138548370-7cb2a648-6def-46b7-ba20-d278c4eeee4e.png" alt="drawing" width="200"/>

**Comment by iAmGhost** [comment]
> **Update**: I am only got this error when using `<Camera />` inside `<Modal />`

I have similar problem while using `@react-navigation/native-stack`. using `react-native-vision-camera@2.9.3`

It happens when:
* Using Android
* Pressing back arrow button at header left(not happening with system back button)

Workaround was adding custom back button at headerLeft that disables camera before popping screen.

Example code:

```jsx
function CameraScreen() {
  const [quit, setQuit] = useState(false);
  const navigation = useNavigation();
  
  useEffect(() => {
    if (Platform.OS !== 'android') {
      return;
    }

    navigation.setOptions({
      headerLeft: () => (
        <Button
          title="Dismiss"
          onPress={() => {
            setQuit(true);
          }}
        />
      ),
    });
  }, [navigation]);

  useEffect(() => {
    if (quit) {
      navigation.goBack();
    }
  }, [navigation, quit]);

  return (
    <Camera active={!quit} />
  );
}
```

**Comment by rusakovic** [comment]
> I'm using 2.9.3 and still see this error
> 
> **Update**: I am only got this error when using `<Camera />` inside `<Modal />`
> 
> <img alt="drawing" width="200" src="https://user-images.githubusercontent.com/8109285/138548370-7cb2a648-6def-46b7-ba20-d278c4eeee4e.png">

Confirm this issue, if use `react-native-modal` or import from `react-native`

Only on Android. 
iOS is working perfect.

```json
"react-native-reanimated": "^2.2.4",
"react-native-modal": "^13.0.0",
"react": "17.0.2",
"react-native": "0.66.1",
"react-native-vision-camera": "^2.9.3",
"vision-camera-face-detector": "^0.1.8",
```

@mrousavy may you could give some suggestions, how to wrap the `<Camera />` component correctly to show camera in fullscreen mode.

This info could be useful to add in documentation. To avoid potential issues.

Thank you for your great library!

**Comment by ldstein** [comment]
I ended up having to use similar workarounds as [described above](https://github.com/mrousavy/react-native-vision-camera/issues/500#issuecomment-952684835). 

The workaround involves deactivating or unmounting the `<camera />` component before a screen transition. The logic is more or less:

- Intercept a screen transition (via navigation, back button press or hardware back button event)
- Cancel the transition
- Re-render the current screen with  `<camera active={false} ...otherProps />` or unmount it completely.
- Trigger the previously cancelled transition

The ViewID bug seems to only crop up when using RNVC in conjunction with screen management libraries (`react-native-navigation`, `react-navigation`, `react-native-modal`).

**Comment by rusakovic** [comment]
> I ended up having to use similar workarounds as [described above](https://github.com/mrousavy/react-native-vision-camera/issues/500#issuecomment-952684835).
> 
> The workaround involves deactivating or unmounting the `<camera />` component before a screen transition. The logic is more or less:
> 
> * Intercept a screen transition (via navigation, back button press or hardware back button event)
> * Cancel the transition
> * Re-render the current screen with  `<camera active={false} ...otherProps />` or unmount it completely.
> * Trigger the previously cancelled transition
> 
> The ViewID bug seems to only crop up when using RNVC in conjunction with screen management libraries (`react-native-navigation`, `react-navigation`, `react-native-modal`).

1. Thank you for your quick reply. So, your issue during Unmount of the camera, right?
But you could mount the camera in modal?

Is it correct?

Because my issue, I couldn't mount the `Camera` in `Modal`.

2. So, you move Camera to react-navigation as Modal screen, right?

**Comment by ldstein** [comment]
It's been awhile. I think I only hit `assertFrameProcessors` error when the screen with the active camera was being transitioned away from.

**Edit** - Just checked my code I'm only setting `active={true}` and `frameProcessor={processFrame}` after the screen transition has completed and screen containing the camera component is in focus.

I should also mention I ended up moving away from `react-navigation`. Hit some compatibility issues with the alpha and beta builds of `react-native-reanimated`. #542 .

**Comment by iAmGhost** [comment]
> It's been awhile. I think I only hit `assertFrameProcessors` error when the screen with the active camera was being transitioned away from.

I can confirm this issue only happens when `frameProcessor` is set.

@rusakovic 
> Because my issue, I couldn't mount the Camera in Modal.

Sorry for confusing, I had problem when unmounting screen but similar error so I thought it can be helpful.
It looks this happens when setting `frameProcessor` during animation so try to avoid it. It will be ugly but maybe `setTimeout` can be helped.

I'm not sure this issue should be re-opened or separated, please help us @mrousavy

**Comment by rusakovic** [comment]
Agree.
Maybe @mrousavy could give some advices or usecases for Modal. Or how to wrap Camera correctly.
For `react-native-modal` I tried to use 

onModalShow | func | () => null | Called when the modal is completely visible
-- | -- | -- | --

to activate the Camera, but it didn't help.



Update:
The issue with `Modal` is not with mounting of Modal. I added Button inside the Modal to open the Camera. And the issue is the same: `com.mrousavy.camera.ViewNotFoundError: [system/view-not-found]`

**Comment by ldstein** [comment]
FWIW, here is a mimimal App demonstrating the crash with `react-native-modal`

This is different to my original issue which I was able to work around by avoiding mounting/unmounting during transitions.

https://github.com/ldstein/MeshCameraTest/tree/modal-test

**Comment by mrousavy** [comment]
@ldstein thank you! This is helpful. I currently don't have the time to investigate this, but if I do, I'll get back to this.

**Comment by astanb** [comment]
I'm also seeing this issue. The Camera shows fine in the React Native Modal, but when I call `takePhoto` I am receiving the view-not-found error.

**Comment by rusakovic** [comment]
> @ldstein thank you! This is helpful. I currently don't have the time to investigate this, but if I do, I'll get back to this.

will be very helpful, if you could help with this issue.

**Comment by astanb** [comment]
Perhaps we need to open a new issue as this one has been closed.

**Comment by fundon** [comment]
Same issue, Follow the workaround of @iAmGhost.
