### ISSUE TITLE
❓ 2.8.0 > 2.9.1 - Android build error: JSI_LIB not found 

### ISSUE THREAD

**Issue by ldstein** [cuvent/react-native-vision-camera#513]
### Question

Hi,

I'm attempting to upgrade from RNVC 2.8 > 2.9 and hitting a build error:

```
Execution failed for task ':react-native-vision-camera:generateJsonModelDebug'.
> C:\dev\MeshMobile\node_modules\react-native-vision-camera\android\CMakeLists.txt : C/C++ debug|arm64-v8a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  JSI_LIB
      linked by target "VisionCamera" in directory C:/dev/MeshMobile/node_modules/react-native-vision-camera/android
```

**Observations:**
- No problems with 2.8.xx.
- Seems to only affect 2.9.0 and 2.9.1
- I'm not seeing this error when building the [example app](https://github.com/mrousavy/react-native-vision-camera/tree/main/example)
- Affecting multiple projects (all based on boilerplate provided by `npx react-native init ProjectName`)

Repo+branch demonstrating the issue [here](https://github.com/ldstein/MeshCameraTest/tree/test2.9.1)

Full Build Log: [rnvc2.9.1-build-error.log](https://github.com/mrousavy/react-native-vision-camera/files/7327056/rnvc2.9.1-build-error.log)

The offending CMakeLists.txt: [~\node_modules\react-native-vision-camera\android\CMakeLists.txt](https://github.com/mrousavy/react-native-vision-camera/files/7327091/CMakeLists.txt)

I'm stumped. Any thoughts on what I'm doing wrong?

### What I tried

- Read the install instructions
- Tested all releases of RNVC from 2.8.0 onwards
- Enable/disable hermes in build.gradle
- Set compileSdkVersion to 31
- Set targetSdkVersion to 31
- Add android:exported to main activity
- cd android && gradlew clean
- Build via `npm run android` and Android Studio

### VisionCamera Version

2.9.0 and 2.9.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by ldstein** [comment]
Nevermind, looks like the cause of the issue is something else. Will investigate further.

*Edit* - On further testing, this issue only occurs if I switch to 2.9.0 or 2.9.1.

**Comment by Hajan39** [comment]
In previous issues, there was a bug that 2.9.0/2.9.1 was working only with RN 66, but RN 66 currently doesn't work with the current version react-native-reanimated.

**Comment by ldstein** [comment]
Thanks for the tip @Hajan39 , didn't see that.

Downgrading `react-native-reanimated` to 2.3.0-beta.2 got me past the build error.

**Comment by mrousavy** [comment]
To patch this, you need to remove these:

https://github.com/mrousavy/react-native-vision-camera/blob/3315f51faf380dff7c9d57c174c489f65f376081/android/CMakeLists.txt#L90-L95

and this:

https://github.com/mrousavy/react-native-vision-camera/blob/3315f51faf380dff7c9d57c174c489f65f376081/android/CMakeLists.txt#L128

line in your local node_modules. I'll try to figure out a way to make that CMake dependency optional...

**Comment by ldstein** [comment]
Thanks for that, all good now.

**Comment by thanhnh-alobridge** [comment]
can you help me @mrousavy
Error: Requiring module "node_modules/vision-camera-qrcode-scanner/src/index.ts", which threw an exception: TypeError: undefined is not a function, js engine: hermes

**Comment by D4nt4lion** [comment]
> Thanks for that, all good now.

In my case fixing it locally is not a good solution because many people have to develop on this app.

**Comment by xOIBrandon** [comment]
> In my case fixing it locally is not a good solution because many people have to develop on this app.

@D4nt4lion Patch Package can help with that - https://www.npmjs.com/package/patch-package

**Comment by joeyfigaro** [comment]
@D4nt4lion alternatively if you're using yarn 2, you can use `yarn patch react-native-vision-camera` ([docs](https://yarnpkg.com/cli/patch))

**Comment by dahyeyudev** [comment]
[android, didn't check iOS]
I'm getting same issue even I tried that patch solutions..
Where should I fix?
```
//package.json
 "react-native": "^0.64.2",
 "react-native-gesture-handler": "^1.10.3",
 "react-native-reanimated": "^2.2.3",
 "react-native-scan-barcode": "^3.1.5",
 "react-native-vision-camera": "^2.9.3",
```
``` 
//build.gradle
buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 26
        compileSdkVersion = 31
        targetSdkVersion = 31
    }
}
 ```
 
 errors in terminal with patch package solution
 ```
 FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-vision-camera:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /Users/yudahye/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /Users/projectName/node_modules/react-native-vision-camera/android/.cxx/cmake/debug/armeabi-v7a VisionCamera}
  ninja: Entering directory `/Users/projectName/node_modules/react-native-vision-camera/android/.cxx/cmake/debug/armeabi-v7a'
  [1/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/java-bindings/JHashMap.cpp.o
  [2/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/java-bindings/JImageProxy.cpp.o
  [3/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/java-bindings/JFrameProcessorPlugin.cpp.o
  [4/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/CameraView.cpp.o
  [5/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/JSIJNIConversion.cpp.o
  FAILED: CMakeFiles/VisionCamera.dir/src/main/cpp/JSIJNIConversion.cpp.o 
  
  ~~
    In file included from ../../../../src/main/cpp/JSIJNIConversion.cpp:15:
  In file included from /Users/projectName/android/../node_modules/react-native/ReactAndroid/src/main/jni/react/jni/NativeMap.h:11:
  ../../../../build/third-party-ndk/folly/folly/dynamic.h:63:10: fatal error: 'boost/operators.hpp' file not found
  #include <boost/operators.hpp>
           ^~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  [6/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/VisionCameraScheduler.cpp.o
  [7/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/FrameProcessorRuntimeManager.cpp.o
  FAILED: CMakeFiles/VisionCamera.dir/src/main/cpp/FrameProcessorRuntimeManager.cpp.o 
  
  ~~
  BUILD FAILED in 19s

    at makeError (/Users/projectName/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
    at /Users/projectName/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runOnAllDevices (/Users/projectName/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/Users/projectName/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:186:9)
 ```
errors without patch package solution
```
* What went wrong:
Execution failed for task ':react-native-vision-camera:generateJsonModelDebug'.
> /Users/yudahye/today/todaypickup_partners/node_modules/react-native-vision-camera/android/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  JSI_LIB
      linked by target "VisionCamera" in directory /Users/yudahye/today/todaypickup_partners/node_modules/react-native-vision-camera/android
 ```

**Comment by florcalomino** [comment]
Any update on this issue? Still doesn't work on Android.

**Comment by dahyeyudev** [comment]
Any update? 🥲

**Comment by byteab** [comment]
here is the juicy part about this error

```
error: redefinition of 'JHashMap'
```

here is the full error

``` javascript
In file included from ../../../../src/main/cpp/JSIJNIConversion.cpp:25:
../../../../src/main/cpp/java-bindings/JHashMap.h:16:8: error: redefinition of 'JHashMap'
../../../../build/fbjni-0.3.0-headers.jar/fbjni/detail/Iterator.h:170:8: note: previous definition is here
In file included from ../../../../src/main/cpp/java-bindings/JHashMap.cpp:5:
../../../../src/main/cpp/java-bindings/JHashMap.h:16:8: error: redefinition of 'JHashMap'
../../../../build/fbjni-0.3.0-headers.jar/fbjni/detail/Iterator.h:170:8: note: previous definition is here
../../../../src/main/cpp/java-bindings/JHashMap.cpp:15:43: error: redefinition of 'create'
../../../../build/fbjni-0.3.0-headers.jar/fbjni/detail/Iterator-inl.h:230:42: note: previous definition is here
```

**Comment by Hajan39** [comment]
@TheEhsanSarshar update to version 2.9.4 this is solved.

**Comment by byteab** [comment]
Thank you so much @Hajan39

**Comment by jettandres** [comment]
The only way I was able to fix this issue was updating my `react` and `react-native` packages

```
"react-native": "0.66.3",
"react": "17.0.2",
```

I used this [tool](https://react-native-community.github.io/upgrade-helper/) also

Make sure to follow to download the latest NDK specified via SDK manager and update your `local.properties` from your `/android` directory

**Comment by hirbod** [comment]
Expo SDK 44, Custom Dev Client, I get:
Version: 2.10.0

```
* What went wrong:
Execution failed for task ':react-native-vision-camera:generateJsonModelDebug'.
> /myapp//node_modules/react-native-vision-camera/android/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  JSI_LIB
      linked by target "VisionCamera" in directory /myapp//node_modules/react-native-vision-camera/android
```

**Comment by geoffreyLB** [comment]
still have error when building for Android, any update ?

**Comment by mark-hayward** [comment]
I am still getting this error too.

**Comment by laogui** [comment]
I am still getting this error too. 

react-native-vision-camera 2.12.1
react-native 0.66.5. 
enabled hermes.

**Comment by sunnhyn** [comment]
I met this kind of Error and solved it by uninstall and reinstall react-native-vision-camera.

"react-native-vision-camera": "^2.12.2",
"react-native": "0.67.2",
hermes enabled

```
* What went wrong:
Execution failed for task ':react-native-vision-camera:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /Users/sunghyun/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /Users/sunghyun/Desktop/Roubit/pipit_app/node_modules/react-native-vision-camera/android/.cxx/cmake/debug/armeabi-v7a VisionCamera}
  ninja: Entering directory `/Users/sunghyun/Desktop/Roubit/pipit_app/node_modules/react-native-vision-camera/android/.cxx/cmake/debug/armeabi-v7a'
  [1/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/java-bindings/JHashMap.cpp.o
  [2/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/java-bindings/JImageProxy.cpp.o
  [3/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/java-bindings/JFrameProcessorPlugin.cpp.o
  [4/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/VisionCameraScheduler.cpp.o
  [5/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/JSIJNIConversion.cpp.o
  FAILED: CMakeFiles/VisionCamera.dir/src/main/cpp/JSIJNIConversion.cpp.o 
```

**Comment by mrousavy** [comment]
Can you paste more log output? There's no error here.

Maybe try cleaning everything and making sure your NDK and CMake is installed correctly via Android Studio

**Comment by sunnhyn** [comment]
> Can you paste more log output? There's no error here.
> 
> 
> 
> Maybe try cleaning everything and making sure your NDK and CMake is installed correctly via Android Studio

Cleaning everything (re-install library) works!

thanks for great library! 😁

**Comment by mrousavy** [comment]
Awesome, nice to hear!

**Comment by GSFZamai** [comment]
> [android, didn't check iOS] I'm getting same issue even I tried that patch solutions.. Where should I fix?
> 
> ```
> //package.json
>  "react-native": "^0.64.2",
>  "react-native-gesture-handler": "^1.10.3",
>  "react-native-reanimated": "^2.2.3",
>  "react-native-scan-barcode": "^3.1.5",
>  "react-native-vision-camera": "^2.9.3",
> ```
> 
> ```
> //build.gradle
> buildscript {
>     ext {
>         buildToolsVersion = "29.0.3"
>         minSdkVersion = 26
>         compileSdkVersion = 31
>         targetSdkVersion = 31
>     }
> }
> ```
> 
> errors in terminal with patch package solution
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-vision-camera:externalNativeBuildDebug'.
> > Build command failed.
>  Error while executing process /Users/yudahye/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /Users/projectName/node_modules/react-native-vision-camera/android/.cxx/cmake/debug/armeabi-v7a VisionCamera}
>  ninja: Entering directory `/Users/projectName/node_modules/react-native-vision-camera/android/.cxx/cmake/debug/armeabi-v7a'
>  [1/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/java-bindings/JHashMap.cpp.o
>  [2/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/java-bindings/JImageProxy.cpp.o
>  [3/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/java-bindings/JFrameProcessorPlugin.cpp.o
>  [4/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/CameraView.cpp.o
>  [5/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/JSIJNIConversion.cpp.o
>  FAILED: CMakeFiles/VisionCamera.dir/src/main/cpp/JSIJNIConversion.cpp.o 
>  
>  ~~
>    In file included from ../../../../src/main/cpp/JSIJNIConversion.cpp:15:
>  In file included from /Users/projectName/android/../node_modules/react-native/ReactAndroid/src/main/jni/react/jni/NativeMap.h:11:
>  ../../../../build/third-party-ndk/folly/folly/dynamic.h:63:10: fatal error: 'boost/operators.hpp' file not found
>  #include <boost/operators.hpp>
>           ^~~~~~~~~~~~~~~~~~~~~
>  1 error generated.
>  [6/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/VisionCameraScheduler.cpp.o
>  [7/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/FrameProcessorRuntimeManager.cpp.o
>  FAILED: CMakeFiles/VisionCamera.dir/src/main/cpp/FrameProcessorRuntimeManager.cpp.o 
>  
>  ~~
>  BUILD FAILED in 19s
> 
>    at makeError (/Users/projectName/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
>    at /Users/projectName/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
>    at processTicksAndRejections (internal/process/task_queues.js:93:5)
>    at async runOnAllDevices (/Users/projectName/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
>    at async Command.handleAction (/Users/projectName/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:186:9)
> ```
> 
> errors without patch package solution
> 
> ```
> * What went wrong:
> Execution failed for task ':react-native-vision-camera:generateJsonModelDebug'.
> > /Users/yudahye/today/todaypickup_partners/node_modules/react-native-vision-camera/android/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
>   Please set them or make sure they are set and tested correctly in the CMake files:
>   JSI_LIB
>       linked by target "VisionCamera" in directory /Users/yudahye/today/todaypickup_partners/node_modules/react-native-vision-camera/android
> ```

In iOS compiled with success. But in android I'm getting both error, like you. With or without the patch fix

**Comment by mrousavy** [comment]
Which RN versions are you on? Compare your versions with the Example/ app here

**Comment by GSFZamai** [comment]
I'm on RN 0.64.2. 
After i saw this issue #957 , I've updated the library to v2.13.0 and worked on Android.
But for now, I need to use v2.10.0 for iOS builds (with XCode 12) #716  and v 2.13.0 for android.

I'll try to build with v2.13.0 in iOS with XCode 13.

**Comment by lfabl** [comment]
You must only install C++ sdk to your pc.

For x64: [here](https://aka.ms/vs/17/release/vc_redist.x64.exe)
For x86: [here](https://aka.ms/vs/17/release/vc_redist.x86.exe)

and do the following processes respectively:

- delete node_modules directory.
- delete android/build directory.
- delete android/.gradle directory.
- delete android/app/build directory
then
- run "yarn ios" or "yarn android" command. ( run the project. )
