### ISSUE TITLE
🐛 Android build failure: "Multiple task action failures occurred" 

### ISSUE THREAD

**Issue by haibert** [cuvent/react-native-vision-camera#515]
### What were you trying to do?

trying to install Vision Camera in a project thats been updated to Expo v43

### Reproduceable Code

```tsx
https://github.com/haibert/sh43
```

### What happened instead?

the build fails on android

### Relevant log output

```shell
> Task :expo-camera:generateDebugRFile
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:checkDebugAarMetadata'.
[stderr] > Multiple task action failures occurred:
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
[stderr]       > The minCompileSdk (31) specified in a
[stderr]         dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
[stderr]         is greater than this module's compileSdkVersion (android-30).
[stderr] Dependency: androidx.camera:camera-view:1.0.0-alpha29.
[stderr]         AAR metadata file: /root/.gradle/caches/transforms-3/4479f38bc3eaae98943cd374b46bc381/transformed/jetified-camera-view-1.0.0-alpha29/META-INF/com/android/build/gradle/aar-metadata.properties.
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
[stderr]       > The minCompileSdk (31) specified in a
[stderr]         dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
[stderr]         is greater than this module's compileSdkVersion (android-30).
[stderr]         Dependency: androidx.camera:camera-extensions:1.0.0-alpha29.
[stderr]         AAR metadata file: /root/.gradle/caches/transforms-3/d0a11acf76330fde11c34be5b2a72e9c/transformed/jetified-camera-extensions-1.0.0-alpha29/META-INF/com/android/build/gradle/aar-metadata.properties.
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
[stderr]       > The minCompileSdk (31) specified in a
[stderr]         dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
[stderr]         is greater than this module's compileSdkVersion (android-30).
[stderr]         Dependency: androidx.camera:camera-camera2:1.1.0-alpha09.
[stderr]         AAR metadata file: /root/.gradle/caches/transforms-3/db3514a32fe0b62e158c388a78d7f05b/transformed/jetified-camera-camera2-1.1.0-alpha09/META-INF/com/android/build/gradle/aar-metadata.properties.
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
[stderr]       > The minCompileSdk (31) specified in a
[stderr]         dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
[stderr]         is greater than this module's compileSdkVersion (android-30).
[stderr]         Dependency: androidx.camera:camera-lifecycle:1.1.0-alpha09.
[stderr]         AAR metadata file: /root/.gradle/caches/transforms-3/a80afd1f80836503755bde7c14d1b27b/transformed/jetified-camera-lifecycle-1.1.0-alpha09/META-INF/com/android/build/gradle/aar-metadata.properties.
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
[stderr]       > The minCompileSdk (31) specified in a
[stderr]         dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
[stderr]         is greater than this module's compileSdkVersion (android-30).
[stderr]         Dependency: androidx.camera:camera-core:1.1.0-alpha09.
[stderr]         AAR metadata file: /root/.gradle/caches/transforms-3/b24399c83c5c2319ec1d9045fd4846ec/transformed/jetified-camera-core-1.1.0-alpha09/META-INF/com/android/build/gradle/aar-metadata.properties.
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 3m 1s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
349 actionable tasks: 349 executed
Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.
```

### Device

iPhone 12 iOS 14

### VisionCamera Version

2.9.1

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Oh yeah this is an issue with the native CameraX library by Google.

I fixed this in the example app with those two diffs: 

1. https://github.com/mrousavy/react-native-vision-camera/pull/472/commits/7bc3815e168e6b6b8def5e954750f091b9ad9722
2. https://github.com/mrousavy/react-native-vision-camera/pull/472/commits/a4bfa7a21a261a40a2eb3228d0ee97f967a1b35c

**Comment by haibert** [comment]
This is pretty much a modification I would have to do using config plugins if i'm in a managed work flow correct?

**Comment by mrousavy** [comment]
Yes. I'll contact the google devs to find out why this is a requirement in hopes of it being reverted. In the meantime, you can use VisionCamera v2.9.0. :)

**Comment by haibert** [comment]
Sounds good! Ty for the quick response Marc. btw 2.9.0 failed with the following error. if there isnt a quick fix to it dont sweat it, we'll wait until the issue is sorted out after you speak with google devs. 

```
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':react-native-vision-camera:generateJsonModelDebug'.
[stderr] > /build/workingdir/build/node_modules/react-native-vision-camera/android/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
[stderr]   Please set them or make sure they are set and tested correctly in the CMake files:
[stderr]   JSI_LIB
[stderr]       linked by target "VisionCamera" in directory /build/workingdir/build/node_modules/react-native-vision-camera/android
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 7m 30s
Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.
```

**Comment by mrousavy** [comment]
Oh yeah damn! I should really add a GitHub Action Workflow that tests the build for expo projects. Otherwise I'll never know when that breaks because VisionCamera focuses on bare React Native rn 😅

**Comment by haibert** [comment]
That would be awesome❤️🥺 Expo has gotten so much better and it's only going up from here. I think making expo support more solid will definitely make many people pick this amazing library over Expo-Camera... its a no brainer, this is so much more performant and gives you so much more functionality.

**Comment by rodgomesc** [comment]
same problem here :(  updating sdk to 31 breaks a lot of other dependencies in the project

**Comment by haibert** [comment]
I think Marc is going to release a version that addresses this issue for expo users

**Comment by HyopeR** [comment]
What is the status of this issue?

**Comment by iAmGhost** [comment]
Workaround for this issue, add below code to app/build.gradle. tested on 2.9.3

```gradle
configurations.all {
    resolutionStrategy {
        force "androidx.camera:camera-core:1.1.0-alpha08"
        force "androidx.camera:camera-camera2:1.1.0-alpha08"
        force "androidx.camera:camera-lifecycle:1.1.0-alpha08"
        force "androidx.camera:camera-extensions:1.0.0-alpha28"
        force "androidx.camera:camera-view:1.0.0-alpha28"
        force "androidx.exifinterface:exifinterface:1.3.3"
    }
}
```

**Comment by JonasHiltl** [comment]
Any updates on a realase addressing this issue? I will try the workaround of @iAmGhost

**Comment by paulrostorp** [comment]
~~On version `2.9.3`, using sdk v31, I'm getting an error at~~


~~> Task :react-native-vision-camera:compileDebugKotlin FAILED~~

~~Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.~~
~~Use '--warning-mode all' to show the individual deprecation warnings.~~
~~See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings~~
~~332 actionable tasks: 2 executed, 330 up-to-date~~
~~e: /Users/paulrostorp/work/crimson-frog/mobile/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/frameprocessor/FrameProcessorRuntimeManager.kt: (11, 33): Unresolved reference: Scheduler~~
~~FAILURE: Build failed with an exception.~~

_edit:_ It seems the above error was caused by an outdated local install of react-native-reanimated

**Comment by tennispro7797** [comment]
Any updates on this? I don't think the workaround mentioned above by @iAmGhost is possible for anyone using expo.

**Comment by sandlands** [comment]
> Workaround for this issue, add below code to app/build.gradle. tested on 2.9.3
> 
> ```groovy-gradle
> configurations.all {
>     resolutionStrategy {
>         force "androidx.camera:camera-core:1.1.0-alpha08"
>         force "androidx.camera:camera-camera2:1.1.0-alpha08"
>         force "androidx.camera:camera-lifecycle:1.1.0-alpha08"
>         force "androidx.camera:camera-extensions:1.0.0-alpha28"
>         force "androidx.camera:camera-view:1.0.0-alpha28"
>         force "androidx.exifinterface:exifinterface:1.3.3"
>     }
> }
> ```

@iAmGhost Where should this be added? After adding it to the bottom of `node_modules/react-native-vision-camera/android/build.gradle`, I still see `androidx.camera:camera-view:1.0.0-alpha29` in the error message while `androidx.camera:camera-view:1.0.0-alpha28` should be forced, right?

```
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
[stderr]       > The minCompileSdk (31) specified in a
[stderr]         dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
[stderr]         is greater than this module's compileSdkVersion (android-30).
[stderr]         Dependency: androidx.camera:camera-view:1.0.0-alpha29.
[stderr]         AAR metadata file: /root/.gradle/caches/transforms-3/ec1d9540f517ae013626dc5276ef20f9/transformed/jetified-camera-view-1.0.0-alpha29/META-INF/com/android/build/gradle/aar-metadata.properties.
```

**Comment by sandlands** [comment]
Please see if [this comment](https://github.com/mrousavy/react-native-vision-camera/issues/546#issuecomment-1000849122) helps you.
