### ISSUE TITLE
🐛 RN 0.66.1 build fails on Android

### ISSUE THREAD

**Issue by adhip94** [cuvent/react-native-vision-camera#525]
### What were you trying to do?

My app was building fine previously when I was using RN 0.66.0 and Vision Camera 2.9.3 on both iOS and Android. 

I just upgraded to RN 0.66.1 and it builds on iOS fine without any errors, but on Android it throws an error during build time.

### Reproduceable Code

```tsx
No code changes.

I tried doing the following:
cd android
./gradlew clean
cd ..
npx react-native run-android --variant=release
```

### What happened instead?

The build fails.

### Relevant log output

```shell
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-vision-camera:externalNativeBuildRelease'.
> Build command failed.
  Error while executing process /Users/user/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /Users/user/app/node_modules/react-native-vision-camera/android/.cxx/cmake/release/armeabi-v7a VisionCamera}
  ninja: Entering directory `/Users/user/app/node_modules/react-native-vision-camera/android/.cxx/cmake/release/armeabi-v7a'
  
  ninja: error: '../../../../build/react-native-0.66.0.aar/jni/armeabi-v7a/libjsi.so', needed by '../../../../build/intermediates/cmake/release/obj/armeabi-v7a/libVisionCamera.so', missing and no known rule to make it
```

### Device

iPhone 8 Plus

### VisionCamera Version

2.9.3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
It still looks for the RN 0.66.0 aar, try deleting `android/app/build`

**Comment by adhip94** [comment]
Wow, you are right, deleting the build folder worked... Thanks @mrousavy
