### ISSUE TITLE
✨ AR - Record and Capture with AR objects

### ISSUE THREAD

**Issue by MadCoderme** [cuvent/react-native-vision-camera#526]
### What feature or enhancement are you suggesting?

I think it would be great if AR functionalities were available here. As we have in Viro, If something similar can be added in this library, it will help a lot.

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

Currently, there are no alternatives for this, we can display images on the screen based on frame processor recognition, but we can't record or capture it

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
Could you describe what you mean by "AR functionalities"? What's Viro?

> we can display images on the screen based on frame processor recognition, but we can't record or capture it

Yes you can, you can write a Frame Processor Plugin that also records the given `Frame`. Of course this is not part of VisionCamera itself, because VisionCamera doesn't know what you use to display "images on the screen".

**Comment by MadCoderme** [comment]
By AR functionalities, I mean, integration of AR in this library. So we can show AR texts, objects and so on.

The method I mentioned is actually that useful to present AR. It is locked to screen, not to the scene.

Viro React is the best option right now for AR and VR in react native.

**Comment by mrousavy** [comment]
I see. Sounds very interesting, and I believe a fast, nice to use, cross-platform AR API would be a game-changer.

However, the scope of this feature request is so huge that I won't be able to have enough free-time to work on it. If you, or anyone else reading this comment, is interested in this becoming reality, consider a collaboration with me and my app development/consulting agency. Contact me at me@mrousavy.com

**Comment by MadCoderme** [comment]
Cool! Android uses ARCore library and IOS uses ARKit library. That can be a starting point.

**Comment by Angelk90** [comment]
@MadCoderme : Are there any news?

**Comment by MadCoderme** [comment]
Not really.

I tried adding image overlay using frame processor data, then capture it. If you just need photo capture, it works well(viewshot is really good thing dude). In case of video, you really can't rely on it. You have to touch native code.

I had to write a native library for my purpose :(

**Comment by Angelk90** [comment]
@MadCoderme : Are you testing on IOS or Android at the moment?

**Comment by thomas-coldwell** [comment]
Marking this as a duplicate of https://github.com/mrousavy/react-native-vision-camera/issues/724. We are actively working on adding support for write-back frame processors in Vision Camera V3 (the in-progress PR for this functionality can be found at https://github.com/mrousavy/react-native-vision-camera/pull/1198).

Color filters or custom shaders can then be applied to the camera texture or the camera texture could be used as an unlit background in a 3D engine such as [Filament](https://github.com/google/filament)
