### ISSUE TITLE
🐛 takeSnapshot throws Not in application's main thread

### ISSUE THREAD

**Issue by du5rte** [cuvent/react-native-vision-camera#547]
### What were you trying to do?

When using `takeSnapshot()` it throws this error, anyone else come across it on Android? I can take photos fine just not snapshots

```
 ERROR  [unknown/unknown: [unknown/unknown] Not in application's main thread]
```

### Reproduceable Code

```tsx
const snapshot = await camera.current.takeSnapshot();
```

### What happened instead?

App throw `Not in application's main thread` error in the console

### Relevant log output

```shell
ERROR  [unknown/unknown: [unknown/unknown] Not in application's main thread]
```

### Device

Samsung SM-T575

### VisionCamera Version

2.9.3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by rodgomesc** [comment]
same problem here with version 2.9.0

**Comment by savv** [comment]
I get the same error when calling takePhoto, when running on an emulator on Android, with API 26 and version 2.11.1

**Comment by whysetiawan** [comment]
any update on this?

**Comment by mrousavy** [comment]
Sorry, did not have any free time to investigate this yet.

**Comment by mateusschenato** [comment]
Hi,

How i can help u to resolve this problem, i having this problem and i need to solve.

**Comment by bekatd** [comment]
I am facing same issue. v2.13.0 and 0.64.1

I tried to patch-package with PR you made, but unfortunately build is failing with this error message
`Cannot access 'coroutineScope': it is private in 'CameraView'`
```
e: C:\Users\...\app\node_modules\react-native-vision-camera\android\src\main\java\com\mrousavy\camera\CameraView+TakeSnapshot.kt: (25, 30): Cannot access 'coroutineScope': it is private in 'CameraView'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-vision-camera:compileDebugKotlin'.
```

**Comment by bekatd** [comment]
above mentioned build issue somehow get resolved, but takeSnapshot throws Not in application's main thread again

changes made in #961 does not work :| this should not be closed

**Comment by mrousavy** [comment]
Did you try with the latest version?

**Comment by bekatd** [comment]
Sorry false alarm [#1030](https://github.com/mrousavy/react-native-vision-camera/issues/1030#issuecomment-1117473084)
