### ISSUE TITLE
🐛 Changing position when record result in frames stretch in wrong orientation 

### ISSUE THREAD

**Issue by msimon** [cuvent/react-native-vision-camera#548]
### What were you trying to do?

While recording switching the front to back camera and back to front.
Tested iPhone 8 & iPhone 11 Pro, both on ios 15.

### Reproduceable Code

```tsx
To record the video:

import React, { useState } from "react"
import { View, Pressable, StyleSheet } from "react-native"

import { CameraSwitchIcon, RecordingBtnRedIcon, RecordBtnWhiteInactiveIcon } from 'src/icons/icons'

import { Camera, CameraPosition, useCameraDevices, VideoFile } from "react-native-vision-camera"
import { useIsFocused } from "@react-navigation/core"

const style = StyleSheet.create({
  CameraContainer: {
    flex: 1,
    zIndex: 1,
    backgroundColor: "black"
  },

  videoOverlay: {
    flex: 1,
  },

  footerContainer: {
    width: "100%",
    position: "absolute",
    bottom: 0,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    zIndex: 10
  },

  recordingImgContainer: {
    width: 100,
    height: 100,
  },

  recordingImg: {
    width: "100%",
    height: "100%",
  },

  recordingImgPending: {
    opacity: 0.5,
  },

  cameraSwitchContainer: {
    marginLeft: 30
  },

})

interface VideoRecorderProps {
  onRecordEnded: (res: VideoFile) => void,
}

export const VideoRecorder: React.FC<VideoRecorderProps> = (props) => {
  const devices = useCameraDevices()
  const [isRecordRequested, setIsRecordRequested] = useState(false)
  const [isRecording, setIsRecording] = useState(false)
  const [cameraPosition, setCameraPosition] = useState<CameraPosition>('front')
  const isFocused = useIsFocused()
  const camera = React.useRef<Camera>(null)

  const device = cameraPosition == 'front' ? devices.front : devices.back

  const recordBtnStyle = !isRecording && isRecordRequested
    ? { ...style.recordingImg, ...style.recordingImgPending }
    : style.recordingImg

  const recordBtnImgSource = isRecording ? <RecordingBtnRedIcon  style={recordBtnStyle} /> : <RecordBtnWhiteInactiveIcon style={recordBtnStyle}  />

  const onClickRecordBtn = () => {
    if (!camera.current) {
      return
    }

    if (isRecordRequested || isRecording) {
      camera.current.stopRecording()
    } else {
      camera.current
      .startRecording({
        onRecordingError:((error) => {
          setIsRecordRequested(false)
          setIsRecording(false)
          console.error("ERROR VIDEO RECORDING", error),
        }),
        onRecordingFinished:((res) => {
          props.onRecordEnded(res)
          setIsRecordRequested(false)
          setIsRecording(false)
        }),
      })
      setIsRecording(true)
    }
  }

  const toggleCameraType = () => {
    if (cameraPosition == 'front') {
      setCameraPosition('back')
    } else {
      setCameraPosition('front')
    }
  }

  return (
    <View style={style.videoOverlay}>
      <View style={style.footerContainer}>
        {/* Keep symmetry by button same exact button on the left but hidden  */}
        <View style={{ ...style.cameraSwitchContainer, opacity: 0 }}>
          <CameraSwitchIcon height={30} width={30} />
        </View>
        <Pressable
          style={style.recordingImgContainer}
          onPress={() => {
            onClickRecordBtn()
          }}
        >
          {recordBtnImgSource}
        </Pressable>
        <Pressable
          style={{ ...style.cameraSwitchContainer }}
          onPress={() => toggleCameraType()}
        >
          <CameraSwitchIcon height={30} width={30} />
        </Pressable>
      </View>
      {
        device
        ? (
         <Camera
            ref={camera}
            style={style.CameraContainer}
            device={device}
            isActive={isFocused}
            preset={"hd-1280x720"}
            video={true}
            audio={true}
            onError={(e) => {
              console.error("Camera runtime error", e)
            }}
          />
        ): <></>
      }

    </View>
  )
}

```

To display the video I use a simple `<video>` from react-native-video

## Video of the issue:
https://www.youtube.com/watch?v=asM-IF2cGhk

### Front to back: 

<img src="https://user-images.githubusercontent.com/321204/138298135-0f6ea08f-5857-4eb2-94ac-410494f4faec.PNG" width="300" />

### Back to front: (notice the light going from one side to the other side)
<img src="https://user-images.githubusercontent.com/321204/138298162-13830328-e627-40db-ad02-379ba34e8149.PNG" width="300" /> <img src="https://user-images.githubusercontent.com/321204/138298158-afcc3eca-a831-4ea9-9b91-d698c55e4852.PNG" width="300" />

### Relevant log output

```shell
N/A
```

### Device

Iphone 11 Pro & Iphone 8 Pro (15.0) 

### VisionCamera Version

2.9.3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by msimon** [comment]
@mrousavy If I wanted to look into the problem and possibly open a PR to fix it, how would I start?
Do you have a quick internal guide or maybe just some pointer for me?

Thank you so much for this library! I could feel getting insane while using react-native-camera. You made my life a lot easier.

**Comment by mrousavy** [comment]
> You made my life a lot easier.

Thanks for the kind words! I feel like VisionCamera solves a lot of common problems for Cameras in React Native.

As for contributing, take a look at the [Contributing Guidelines](https://github.com/mrousavy/react-native-vision-camera/blob/main/CONTRIBUTING.md). For implementing this feature, I guess it would make sense to start with Android first. not sure how well CameraX supports that, on iOS it'll be a bit more complicated as I use a custom video queue. (to support frame processing and stuff)

Btw I like your name, my brother's name is Simon so it was funny reading "Marc Simon" in an email 😄

**Comment by zzzkasper-1995** [comment]
Is there any news about this issue?

**Comment by ratz6** [comment]
any fix while going from front to back cam ?

**Comment by mrousavy** [comment]
Hey - I'm tracking Orientation in this feature request/issue now: https://github.com/mrousavy/react-native-vision-camera/issues/1891 ✨ 

Make sure to upvote or sponsor to support this feature, and leave a comment if you have any additional thoughts/ideas.
