### ISSUE TITLE
✨ Pausing and resuming record

### ISSUE THREAD

**Issue by hirbod** [cuvent/react-native-vision-camera#562]
### What feature or enhancement are you suggesting?

I think it would be awesome to have a pause and resume record feature. I did dig around at all available Camera libs and pausing the record will always save the file and you can’t resume recording, creating a single file at the end.

From my understanding, implementation for iOS with AV should be possible. I am not sure about Android. 

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

Current workaround would be to implement ffmpegkit and merge all recorded clips to get a single video.

ffmpegkit isn’t easy to implement, has many pitfalls, issues with license and patents etc. If there is an easier way doing this natively would be awesome! 

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
Hi @Hirbod, thanks for the feature request!

### Android

This is possible with the newest CameraX version, I'm working on upgrading here: https://github.com/mrousavy/react-native-vision-camera/pull/543 - that's a completely new API for recording, so that PR has to be thoroughly tested before merging, and I didn't have the time to do that yet

### iOS

This is possible because I implemented a completely custom video recording queue so it's simply flicking a boolean true/false 😄 

I even added the methods, but didn't expose them to JS yet (wanted to wait for Android)

**Comment by hirbod** [comment]
Beast! Can’t wait to test it! I am on vacation from tomorrow on for 7 days, but hit me up if you need beta testers afterwards.

**Comment by hirbod** [comment]
@mrousavy Just as a side question/enhancement: will it be possible to define a maximum recording duration? I need to limit my videos to 2 minutes max. So the final video shall not exceed max duration and shall stop recording. Would be nice to also have the recorded length duration exposed while recording to show a progress bar.

**Comment by mrousavy** [comment]
I always prefer to do those things on the JS side, avoids complex logic. So after `startRecording` has returned, start a timer for 2 mins that then stops, and also start an interval which shows the progress.

**Comment by hirbod** [comment]
Ok you’re right, that should be feasible. So starting a timer on startRecording.

Will your new queue system be able to drop the „last recorded segment?“. 

Imagine a camera view. You hit record, then you stop / release the record button. First clip is recorded. You continue recording and you make a mistake. First part is perfect but the new recorded chunk isn’t. Is this a temporary segment which could be discarded or will it already be written to the final file?

**Comment by mrousavy** [comment]
That's already written, if you want to separate that it would be cleaner to actually stop recording in between and stich the videos together in post processing. This also has the bonus of not corrupting the entire recording when something goes wrong.

**Comment by hirbod** [comment]
So we would end up with ffmpeg again :(

**Comment by ddtch** [comment]
So what about this feature? Implemented? And can we strict duration of recording video?

**Comment by remento-matheus** [comment]
> So what about this feature? Implemented? And can we strict duration of recording video?

@hirbod @ddtch
Pausing/resuming on Android seems to be working nicely! iOS is broken though (looks like there are timestamp conflicts between the "chapters" - between pauses/resumes)

**Comment by mrousavy** [comment]
Yea I think I need to add some custom code on iOS to pause the muxer, will do that in V3

**Comment by remento-matheus** [comment]
That's really exciting @mrousavy! Looking forward to it 😎

**Comment by satyanarayananunc** [comment]
@mrousavy Can you please suggest us on IOS version of this issue a part from using ffmpeg!. we r struck on this as it is working fine in Android.  So, when could we expect V3?

**Comment by mrousavy** [comment]
woohoo implemented in V3!

**Comment by Danielboanca06** [comment]
> @hirbod @ddtch Pausing/resuming on Android seems to be working nicely! iOS is broken though (looks like there are timestamp conflicts between the "chapters" - between pauses/resumes)

This is still an issue even when using 3.6.10??
