### ISSUE TITLE
✨  Sound when taking picture

### ISSUE THREAD

**Issue by Hajan39** [cuvent/react-native-vision-camera#565]
### What feature or enhancement are you suggesting?

It would be great if there would be a possibility to enable sound when taking pictures. Some other components have it.

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

I am currently using react-native-sound-player library, but when you are taking pictures with flash, the sound is too soon.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
Hey! I just implemented this in V3! :) https://github.com/mrousavy/react-native-vision-camera/pull/1702
