### ISSUE TITLE
maxDuration props✨ 

### ISSUE THREAD

**Issue by Ppang0405** [cuvent/react-native-vision-camera#571]
### What feature or enhancement are you suggesting?

 I think it would be great if we have maxDuration props.

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

I mean using JS Timer is not good enough.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
> I mean using JS Timer is not good enough.

Why?

**Comment by Ppang0405** [comment]
Because the JS timer does not guarantee the exact delay [somewhere around 300ms -1000ms missing/redundancy in different devices]. I need high precision [around 2-5ms is ok].

**Comment by mrousavy** [comment]
Where did you get the info from that a Timer has a 1000ms inaccuracy?

**Comment by Ppang0405** [comment]
I got it from my company project. 
Close this issues because I have already fork and do my own custom.
