### ISSUE TITLE
🐛 CocoaPods could not find compatible versions for pod "VisionCamera"

### ISSUE THREAD

**Issue by hungdev** [cuvent/react-native-vision-camera#615]
### What were you trying to do?

Thank you for your lib
I got this error. Please tell me how to fix it.
im trying to install the lib, but i get the error

### What happened instead?

![image](https://user-images.githubusercontent.com/12009276/143775729-bdbe82a6-6b83-4486-8700-aa780b56dede.png)

### Device

Ios

### VisionCamera Version

Latest version

### React Native Version
"react-native": "0.64.2",

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by hungdev** [comment]
I found solution. replace `platform :ios, '10.0'` to `platform :ios, '11.0'` in podfile

**Comment by jagdeepChicmic** [comment]
replace platform :ios, '10.0' to platform :ios, '12.4' in podfile in latest relese (react native vision camera 3.1.0)
