### ISSUE TITLE
🐛 Photo element data has no lens, equipment or location information.

### ISSUE THREAD

**Issue by mushan0x0** [cuvent/react-native-vision-camera#625]
### What were you trying to do?

I hope the photos I took contain more information.

### What happened instead?

Check it in the album after taking the photo directly, but I don’t see more picture information.

### Device

iPhone 11 Pro Max iOS 15

### VisionCamera Version

2.9.3

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by hungdev** [comment]
+1
i hope it will have lat long information

**Comment by hungdev** [comment]
@mrousavy I hope you add location ( lat, long) to image <3

**Comment by tomgreco** [comment]
@mrousavy  +1 to lat/long

**Comment by mrousavy** [comment]
Hey, lat/lng will not be part of VisionCamera, it's not a location library. But lens information is already in there!
