### ISSUE TITLE
🐛 Links on docs/api main page are 404

### ISSUE THREAD

**Issue by pke** [cuvent/react-native-vision-camera#638]
### What were you trying to do?

Links on main page https://mrousavy.com/react-native-vision-camera/docs/api are all 404

![5Vn13kFDe0](https://user-images.githubusercontent.com/164625/145391620-a406205c-db80-4dde-a271-90d0418fd877.gif)

### What happened instead?

All links on main page are 404.

### Device

Desktop

### VisionCamera Version

n/a

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Ah that sucks. Do you by any chance have experience with docusaurus + typedoc?

**Comment by pke** [comment]
Unfortunately I am not familiar with it. Probably just a config issue. Maybe it could help to file a bug over at docusaurus and point to this repo?

**Comment by mrousavy** [comment]
Fixed I think!
