### ISSUE TITLE
What is the a minmum required RN version to use this lib❓ 

### ISSUE THREAD

**Issue by angelos3lex** [cuvent/react-native-vision-camera#663]
### Question

Is there some way where we can find out which versions of RN are needed for the versions of this lib?
i.e like `RN>=0.65` for `v2.5.x+`and `RN>=0.64` till `v2.5.0`
Personally I had build issues, but I'm in `RN 0.63.4` and would like to know if this is a problem.

### VisionCamera Version

2.10.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by Siti-Shaufi** [comment]
Why does this is solved? What is the answer??
