### ISSUE TITLE
✨ make VISION_CAMERA_DISABLE_FRAME_PROCESSORS=1 configurable via expo-config-plugin

### ISSUE THREAD

**Issue by hirbod** [cuvent/react-native-vision-camera#674]
### What feature or enhancement are you suggesting?

In order to be able to disable VISION_CAMERA_DISABLE_FRAME_PROCESSORS=1 for expo, we would need to have config-plugin param for it. Would be nice if you could provide this via the config-plugin.

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

None

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
I don't know how I can write to `GCC_PREPROCESSOR_DEFINITIONS` in the user's `project.pbxproj` file using Expo Config Plugins...

**Comment by mrousavy** [comment]
Or to `gradle.properties` for Android

**Comment by mrousavy** [comment]
summoning the legend @EvanBacon 🤲

**Comment by hirbod** [comment]
I think this will need some sort of brutforce regexp methods, but I am not sure if the file is "readable"? Evan is most likely the best fit for this question!

**Comment by hirbod** [comment]
Done. #708
