### ISSUE TITLE
🐛 VisionCamera_disableFrameProcessors not working?

### ISSUE THREAD

**Issue by hirbod** [cuvent/react-native-vision-camera#707]
### What were you trying to do?

I am not sure if this is my mistake or if there is another small bug, but I tried to patch-package your libs gradle.properties and I also changed gradle.properties inside /android, adding

`VisionCamera_disableFrameProcessors=true` but the console is still compiling frame processors and I have this log in my console:

VisionCamera: Frame Processors are enabled! Building C++ part...

### What happened instead?

VisionCamera: Frame Processors are enabled! Building C++ part...

### Relevant log output

```shell
VisionCamera: Frame Processors are enabled! Building C++ part...
```

### Device

Redmi Note

### VisionCamera Version

2.11.0

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
You need to add

```
disableFrameProcessors=true
```

, without the `VisionCamera_` prefix

**Comment by hirbod** [comment]
VisionCamera: Frame Processors are disabled because the user explicitly disabled it ('disableFrameProcessors=true'). C++ part will not be built.

🤦 

Thanks!

**Comment by hirbod** [comment]
Huge compile difference. Now I need to find a way for iOS, but not bothering you anymore for now :D

**Comment by mrousavy** [comment]
Would appreciate it if you could contribute and add a `disableFrameProcessors` parameter to the `withVisionCamera` config plugin so it's also easy for Expo users 🙏 

I gotta get back to work now 😅

**Comment by hirbod** [comment]
@mrousavy that is what I am on it right now :)
