### ISSUE TITLE
🐛  Build Failed in new app created with react-native init

### ISSUE THREAD

**Issue by firofame** [cuvent/react-native-vision-camera#716]
### What were you trying to do?

run the app on ios simulator/device after installing react-native-vision-camera

### What happened instead?

Build failed with "Cannot convert value of type '[AnyHashable : Any]' to expected argument type '[String : Any]'"

### Relevant log output

```shell
npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 11.6.2
    CPU: (8) arm64 Apple M1
    Memory: 142.83 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - /opt/homebrew/bin/npm
    Watchman: 2021.11.15.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 31
      Build Tools: 29.0.2, 31.0.0
      System Images: android-29 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Device

iPhone 12 (iOS 14.4)

### VisionCamera Version

2.11.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Which Xcode version and which Swift version are you using?

**Comment by firofame** [comment]
XCode 12.4, Swift version 5.3.2

**Comment by firofame** [comment]
/Users/firozahmed/Desktop/MyApp/node_modules/react-native-vision-camera/ios/CameraView+RecordVideo.swift:135:70: Cannot convert value of type '[AnyHashable : Any]' to expected argument type '[String : Any]'

@mrousavy  this is the exact error I get. I wonder if it's just me

**Comment by champikamendis** [comment]
I got the same error. Do anyone know the reason?

**Comment by firofame** [comment]
@champikamendis what version of Xcode are you using?

**Comment by champikamendis** [comment]
@firofame XCode 12

**Comment by mrousavy** [comment]
Okay looks like they changed the type of that value. If I cast it, it breaks for other users 😅

**Comment by firofame** [comment]
there is one more build error. just an fyi

/Users/firozahmed/Desktop/MyApp/node_modules/react-native-vision-camera/ios/CameraView+RecordVideo.swift:267:26: Type of expression is ambiguous without more context

**Comment by champikamendis** [comment]
Can @mrousavy tell me what to change in my code? I have two errors when building like @firofame faced.

1. "Cannot convert value of type '[AnyHashable : Any]' to expected argument type '[String : Any]'"
2. "Type of expression is ambiguous without more context"
Can you tell what are the changes to be made build it successfully?

**Comment by HERMESMATEUS** [comment]
I got the same issue, my xcode version is 12.4 with "react": "16.13.1", "react-native": "0.63.3"

node_modules/react-native-vision-camera/ios/CameraView+RecordVideo.swift:135:70: Cannot convert value of type '[AnyHashable : Any]' to expected argument type '[String : Any]'

node_modules/react-native-vision-camera/ios/CameraView+RecordVideo.swift:267:26: Type of expression is ambiguous without more context

**Comment by firofame** [comment]
vision-camera works fine with XCode 13. unfortunately, I am stuck with XCode 12.4 since I have some dependency on Swift 5.3.

@mrousavy is there an older version that works with XCode 12.4?

**Comment by brianangulo** [comment]
Having the same issue on xcode 12.5

**Comment by ReyGuez** [comment]
Having the same issue on Xcode 13, any solution?

**Comment by Borhanof** [comment]
Having the same issue please help me out how to fix it

**Comment by Navipro70** [comment]
Same issue, for XCode 12.5 (also test with XCode 13.2, also unsuccessful because of new errors), and RN 66.4

**Comment by mrousavy** [comment]
On my end it builds, running Xcode 13.2.1 (13C100)

**Comment by Navipro70** [comment]
@mrousavy 
Sorry, errors described at my previous message are not related to Xcode version (see screenshot with errors). I'm typecast places with errors in _VisionCamera_ swift module on Xcode 12.5 and it starts building, but I got another error's, same as on Xcode 13.2:
<img width="294" alt="Vision camera" src="https://user-images.githubusercontent.com/60893275/150147454-3c1367b3-da87-4a22-99f3-0a4f991c140d.png">

UPD:
Finally i found problem. 
This errors appeared because I used use_frameworks (for custom native swift module), I just add :modular_headers => true for every dependency in Podfile and remove use_frameworks and now all works!

**Comment by hungdev** [comment]
i get same issue

**Comment by Aris-ngoy** [comment]
> Okay looks like they changed the type of that value. If I cast it, it breaks for other users 😅

what do you propose?

**Comment by mrousavy** [comment]
I propose that I fix the issue once I also get this issue. For me, on Xcode 13, everything builds fine so far. I also mentioned all of the versions (e.g. Swift) in the Troubleshooting section.

**Comment by GKyomen** [comment]
same error here. Any prevision on fixing?

**Comment by davidshariff** [comment]
Same issue: Xcode 12.5, Swift 5.3

**Comment by hungdev** [comment]
I dont understand what's probblem. But i do some steps and it can run successfully.
Delete node module and remove yarn.lock ( use yarn instead of npm, i used npm before ). And change "react-native-vision-camera": "2.9.4", ( delete ^ in front 2.9.4). Then run: `yarn` to install library, after that delete Podfile.lock then `npx pod-install`
Rerun and it worked for me.
Xcode Version 12.5
"react-native": "0.64.2"

here is folder `react-native-vision-camera` in node_module. You can try to extract it and put in your node_module. Hope this help.
https://drive.google.com/file/d/1VUlXvxxownyQnvgbnEOxppCWc_Htrm-D/view?usp=sharing

**Comment by john-christian-melendres** [comment]
I also encounter the same issue, I'm using Xcode 12.4 and Swift 5.3.2

**Comment by john-christian-melendres** [comment]
I'm did not encounter the error anymore after updating to Xcode 13.3

**Comment by mrousavy** [comment]
Great!

**Comment by firofame** [comment]
@mrousavy 
"Troubleshooting" page says "VisionCamera requires a minimum Swift version of 5.2", This needs to be changed to XCode 13. 

many repositories have a minimum requirement section in the readme so that people with older version do not waste their time.

**Comment by mrousavy** [comment]
> This needs to be changed to XCode 13

Wrong, it does not need to be changed to XCode 13. I was using XCode 12 back when I originally created VisionCamera.

> so that people with older version do not waste their time

That's what the TROUBLESHOOTING guide is for. If you run into any issues, I have specifically created a document that helps you troubleshoot any common issues I can think of. It's your responsibility to look there, and not waste your time.

**Comment by firofame** [comment]
Sir, I respect & appreciate your work very much.

swift 5.2 was shipped with XCode 11.4. https://swiftversion.net/

Everyone was using XCode 12+. so, they probably had swift 5.2+ and still had the same error.

I trust you 100% when you say you were using XCode 12 when you originally created this project, but is there a chance the minimum version could have changed for the latest version of VisionCamera?

**Comment by mrousavy** [comment]
Thanks! Yeah, I guess we could add an additional point to the TROUBLESHOOTING guide that states "Make sure you're using Xcode 13 or higher". just to be sure

**Comment by marinne** [comment]
If you encounter this issue and cannot upgrade to Xcode 13, you can try version 2.10.0, which, during my tests, is the latest version currently that doesn't have this issue in Xcode 12. It's not quite a solution but 2.10.0 may already suit your needs.

**Comment by hushaudio** [comment]
> If you encounter this issue and cannot upgrade to Xcode 13, you can try version 2.10.0, which, during my tests, is the latest version currently that doesn't have this issue in Xcode 12. It's not quite a solution but 2.10.0 may already suit your needs.

thank you this worked instantly
