### ISSUE TITLE
❓ Dependency update

### ISSUE THREAD

**Issue by Angelk90** [cuvent/react-native-vision-camera#726]
### Question

I was having a look at the dependencies, maybe some would be better to update them to the latest version.

Such as:

- react-native-reanimated
- react-native-video
- and others

devDependencies:

<img width="1411" alt="Schermata 2022-01-10 alle 11 30 48" src="https://user-images.githubusercontent.com/20476002/148751510-e60485db-0d07-4f6e-8e81-7b2425c69eda.png">

example/dependencies:

<img width="1410" alt="Schermata 2022-01-10 alle 11 32 03" src="https://user-images.githubusercontent.com/20476002/148751659-f251e794-6dcc-4485-b4fe-7dee395f763f.png">

example/devDependencies:

<img width="1406" alt="Schermata 2022-01-10 alle 11 32 39" src="https://user-images.githubusercontent.com/20476002/148751732-d1a0c44b-ecb1-4150-9aa7-6eb633d37f87.png">

docs/devDependencies:

<img width="1405" alt="Schermata 2022-01-10 alle 11 35 05" src="https://user-images.githubusercontent.com/20476002/148752058-7d689c97-360f-4220-b286-a3277557e7cd.png">

### VisionCamera Version

2.11.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Sure, you can try upgrading them on your end and if everything works then you can send me a PR :)
