### ISSUE TITLE
Can it do recording and face detection at the same time❓ 

### ISSUE THREAD

**Issue by domoretrix** [cuvent/react-native-vision-camera#739]
### Question

Can it do recording and face detection at the same time? 
I am thinking as as use case, if face detected then record if not stop recording.

### VisionCamera Version

*

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Yes, you can. Check the documentation. (["The `supportsParallelVideoProcessing` prop"](https://mrousavy.com/react-native-vision-camera/docs/guides/devices#the-supportsparallelvideoprocessing-prop))
