### ISSUE TITLE
✨ startRecording callback/promise 

### ISSUE THREAD

**Issue by hirbod** [cuvent/react-native-vision-camera#742]
### What feature or enhancement are you suggesting?

Would be lovely to have a callback or / be able to use `await startRecording()` in order to make sure that recording indeed did start.

https://github.com/mrousavy/react-native-vision-camera/blob/main/example/src/views/CaptureButton.tsx#L119

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

No workaround currently

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
https://github.com/mrousavy/react-native-vision-camera/blob/00fc39891a5cd6c68121fd5cd5f6ede90c9eb333/ios/CameraView%2BRecordVideo.swift#L60-L63

**Comment by hirbod** [comment]
Ok, I see! Gonna live with that for now :)

**Comment by mrousavy** [comment]
Started working on something here: https://github.com/mrousavy/react-native-vision-camera/pull/2194

as of now this doesn't really work, but we'll see what we can do

**Comment by mrousavy** [comment]
Closing because this is being tracked in https://github.com/mrousavy/react-native-vision-camera/issues/1319
