### ISSUE TITLE
How can I get an image from Frame Processors❓ 

### ISSUE THREAD

**Issue by JarvanWang66** [cuvent/react-native-vision-camera#757]
### Question

How can I get an image from Frame Processors.
I am a react native camera user. My project requires me to save the current frame when the code scanning is successful

### What I tried

I printed the frame, but I didn't find any information except the size of the picture

### VisionCamera Version

2.10.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
You can either

a. Write a frame processor plugin that saves the Frame to a file
b. call takePhoto() when a code was detected

But I prefer a.
