### ISSUE TITLE
🐛 Camera: Native Module 'CameraView' was null! Did you run pod install?

### ISSUE THREAD

**Issue by saurabhkanswal** [cuvent/react-native-vision-camera#779]
### What were you trying to do?

trying to set up a vision camera with the project.
Have tried all things in troubleshoot guide.

### What happened instead?

I am getting an error message:
`Camera: Native Module 'CameraView' was null! Did you run pod install?`

I have also done pod install.
I don't have any idea, why it is not working...

android:
```
        buildToolsVersion = "30.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        supportLibVersion = "27.0.0"
        kotlinVersion = '1.5.0'
        ndkVersion = "21.4.7075529"
```

### Device

Android  realme Narzo 20a

### VisionCamera Version

^2.12.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Did you rebuild the android app?

**Comment by saurabhkanswal** [comment]
yeah i did that, still issue is same.

**Comment by mrousavy** [comment]
Which RN version

**Comment by saurabhkanswal** [comment]
0.63.2

**Comment by ArthurDias01** [comment]
facing same issue here,

also using expo (SDK 44.0)
RN 0.64.3

**Comment by paul-castro** [comment]
any update on this?

**Comment by ArthurDias01** [comment]
> any update on this?

I surrendered to Update macOS to Monterey and then updated Xcode to 13.0, after that everything went fine....

**Comment by matpandino** [comment]
same issue here

**Comment by ongnicolas** [comment]
same issue, is there a solution?

    expo: ~44.0.0
    react-native: 0.64.3

oh wait, reading from other threads, if I understand it correctly. Vision Camera wont work with Expo Go right? As mentioned here https://github.com/mrousavy/react-native-vision-camera/issues/488#issuecomment-934360712

**Comment by zhenguet** [comment]
have any update for this?

**Comment by b-alidra** [comment]
I have the same issue and I'm not using expo...
```
RN 0.65.1
VC 2.13.0
```

**Comment by b-alidra** [comment]
> I have the same issue and I'm not using expo...
> 
> ```
> RN 0.65.1
> VC 2.13.0
> ```

I've fixed the problem on my side: I was just missing `packages.add(new CameraPackage());` in my `MainApplication.java`...

**Comment by muyi0327** [comment]
I have the same issue，because i forget to add 'react-native-reanimated/plugin' to babel plugins. like this:

[https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/](react-native-reanimated)


I've fixed the problem!

**Comment by fizefeko** [comment]
> > I have the same issue and I'm not using expo...
> > ```
> > RN 0.65.1
> > VC 2.13.0
> > ```
> 
> I've fixed the problem on my side: I was just missing `packages.add(new CameraPackage());` in my `MainApplication.java`...

Can you please tell me from which package did you import the CameraPackage class :)

**Comment by gkartalis** [comment]
I was getting the same error but only when running tests, adding this to our `setupJest` file fixed the issue:

```js
jest.mock("react-native-vision-camera", () => {})
```

**Comment by 9a-aaaaaaaa** [comment]
ios  I have the same issue and I'm not using expo...
