### ISSUE TITLE
Build failed  Error':react-native-fast-image:compileDebugJavaWithJavac'.❓ 

### ISSUE THREAD

**Issue by NithinSK04** [cuvent/react-native-vision-camera#790]
### Question

Initially  after installing   react-native-vision-camera i  ran into an error
 >     "The minCompileSdk (31) specified in a dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)is greater than this  module's compileSdkVersion (android-30).  Dependency: androidx.camera:camera-view:1.0.0-alpha32."
 
and after changing  minCompileSdk to 31 and re running the build :

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-fast-image:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s

    at makeError (/Users/nithinsk/Documents/nighthack/ViveRN/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
    at /Users/nithinsk/Documents/nighthack/ViveRN/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/nithinsk/Documents/nighthack/ViveRN/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/usr/local/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:192:9)
```

>buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "21.4.7075529"

### What I tried
```
./android/gradlew clean
rm -rf package-lock.json && rm -rf yarn.lock && rm -rf node_modules
npm i  # or "yarn"

```
and Steps mentioned in the Troubleshooting Guide

### VisionCamera Version

"react-native-vision-camera": "^2.12.0",

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Your second error is not complete. You didn't include an actual error message.

**Comment by jonotrybe** [comment]
one issue i find is, if you are using adoptjdk then this can happen. In Android Studio you can set to use the embedded JDK with the studio. once I did that and also fixed my appcenter build to use it then my issues were resolved

**Comment by NithinSK04** [comment]
@mrousavy my bad.! I've updated it now. please check

**Comment by NithinSK04** [comment]
@jonotrybe Oh.. I'll look into it ,Thank you

**Comment by jonotrybe** [comment]
> @jonotrybe Oh.. I'll look into it ,Thank you

you will know if the stack trace on the failure (above what you pasted) shows that there was an error in the Java Compiler.

**Comment by NithinSK04** [comment]
> one issue i find is, if you are using adoptjdk then this can happen. In Android Studio you can set to use the embedded JDK with the studio. once I did that and also fixed my appcenter build to use it then my issues were resolved

How do i set it to embedded JDK?

**Comment by jonotrybe** [comment]
I'd look here: 
https://stackoverflow.com/a/30631386

**Comment by mrousavy** [comment]
There is still no actual error message here, looks like you have outdated tooling (Java, Android, ...)
