### ISSUE TITLE
Video Recording file size❓ 

### ISSUE THREAD

**Issue by saurabhkanswal** [cuvent/react-native-vision-camera#792]
### Question

<img width="872" alt="Screenshot 2022-02-02 at 11 46 22 AM" src="https://user-images.githubusercontent.com/26677033/152102625-46a3b189-4e6f-4640-8a3b-68294a335fa9.png">

### VisionCamera Version

^2.12.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Kilobytes.
