### ISSUE TITLE
Not getting all exif data when taking photo❓ 

### ISSUE THREAD

**Issue by ARaulinaitis-ManiMe** [cuvent/react-native-vision-camera#797]
### Question

Is there something I can do to get all of the exif data for an image?  When I take an image, this is what I see:

> metadata: {
    '{TIFF}': {
      YResolution: 0,
      Model: 'Pixel 6 Pro',
      XResolution: 0,
      DateTime: '2022:02:03 10:49:50',
      Make: 'Google',
      Software: null,
      ResolutionUnit: 0
    },
    '{Exif}': {
      MeteringMode: 0,
      ExposureProgram: 0,
      Flash: 0,
      OffsetTime: '-08:00',
      ExifVersion: '0220',
      OffsetTimeOriginal: '-08:00',
      DateTimeDigitized: '2022:02:03 10:49:50',
      WhiteBalance: 0,
      ISOSpeedRatings: [Array],
      PixelYDimension: 2268,
      LensMake: null,
      FocalLength: 6.81,
      SubsecTimeOriginal: '202529',
      OffsetTimeDigitized: '-08:00',
      SubsecTimeDigitized: '202529',
      SubjectArea: [],
      ApertureValue: 0,
      SensingMethod: 1,
      ShutterSpeedValue: 0,
      ExposureMode: 0,
      LensModel: null,
      SceneType: 1,
      BrightnessValue: 0,
      FocalLenIn35mmFilm: 0,
      ExposureBiasValue: 0,
      ColorSpace: 1,
      ExposureTime: 0.033330682,
      DateTimeOriginal: '2022:02:03 10:49:50',
      LensSpecification: [],
      FNumber: 1.85,
      PixelXDimension: 4032
    },
    Orientation: 6
  }

### What I tried

Here is my call to `takePhoto()`

```
camera.current
      .takePhoto({
        enableAutoDistortionCorrection: false,
        enableAutoRedEyeReduction: false,
        enableAutoStabilization: false,
        flash: "off",
        qualityPrioritization: "balanced",
        skipMetadata: false,
      })
```

I've tried setting the `Camera` component to `StyleSheet.absoluteFill` originally, then saw [this issue](https://issuetracker.google.com/issues/193342619) and they recommended not resizing the image, so I removed the absoulteFill and took another image at full size that my camera wanted to take and got this: 

> metadata: {
    '{TIFF}': {
      YResolution: 0,
      Model: 'Pixel 6 Pro',
      XResolution: 0,
      DateTime: '2022:02:03 11:09:10',
      Make: 'Google',
      Software: null,
      ResolutionUnit: 0
    },
    '{Exif}': {
      MeteringMode: 0,
      ExposureProgram: 0,
      Flash: 0,
      OffsetTime: '-08:00',
      ExifVersion: '0220',
      OffsetTimeOriginal: '-08:00',
      DateTimeDigitized: '2022:02:03 11:09:10',
      WhiteBalance: 0,
      ISOSpeedRatings: [Array],
      PixelYDimension: 3072,
      LensMake: null,
      FocalLength: 6.81,
      SubsecTimeOriginal: '498672',
      OffsetTimeDigitized: '-08:00',
      SubsecTimeDigitized: '498672',
      SubjectArea: [],
      ApertureValue: 0,
      SensingMethod: 1,
      ShutterSpeedValue: 0,
      ExposureMode: 0,
      LensModel: null,
      SceneType: 1,
      BrightnessValue: 0,
      FocalLenIn35mmFilm: 0,
      ExposureBiasValue: 0,
      ColorSpace: 1,
      ExposureTime: 0.033330682,
      DateTimeOriginal: '2022:02:03 11:09:10',
      LensSpecification: [],
      FNumber: 1.85,
      PixelXDimension: 4080
    }

So far I've only been able to try this on Android (waiting on an iPhone).  The intent is for this app to be used on both Android and iOs.

When I take a picture with my phone through its native camera app, I get more fields with values (specifically I'm looking for `FocalLenIn35mmFilm` 

This is what I see from my phone's native camera app:
![image](https://user-images.githubusercontent.com/67437406/152413126-4f785ca6-dacf-4c1a-9b86-04e44708be9c.png)

This is what I see if I download the saved photo from react-native-vision-camera:
![image](https://user-images.githubusercontent.com/67437406/152413391-5eb23504-3684-4c9d-b86c-836027c4805e.png)

### VisionCamera Version

7.7.6

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hmm, I think I get all of the metadata (+ Exif data) there is on a normal capture, see code here:

https://github.com/mrousavy/react-native-vision-camera/blob/7335883969c9102b8a6d14ca7ed871f3de7e1389/ios/PhotoCaptureDelegate.swift#L57

If there is additional flags to specify, you can shoot me a PR to enable them, assuming they do not sacrifice performance or have other drawbacks. 

I have also heard this feature request quite often now, so maybe a way to edit EXIF data is the way to go here. I am working on bringing [JSI Image](https://github.com/mrousavy/react-native-jsi-image) support to VisionCamera, so once that's done, we can do all of this in a modular (extensible by other modules or by your own native code to just read the image in-memory) and performant (in-memory) manner, so that would solve your problem.
