### ISSUE TITLE
🐛  Inconsistent docs: stopRecording 

### ISSUE THREAD

**Issue by deevus** [cuvent/react-native-vision-camera#812]
### What were you trying to do?

Read the docs

### Reproduceable Code

```tsx
await camera.current.startRecording()
setTimeout(async () => {
 const video = await camera.current.stopRecording()
}, 5000)
```

### What happened instead?

![Screen Shot 2022-02-09 at 3 57 50 pm](https://user-images.githubusercontent.com/856194/153125963-1c5b06e1-cc51-4625-8d3f-62f2e693936a.png)

Example shows awaiting a `video` object from `stopRecording()`. Docs say that `stopRecording()` returns a `Promise<void>`. 

Which is it?

### Device

Not relevant

### VisionCamera Version

2.12.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Ah sorry, I had the API changed and forgot to update the Docs.

It is void, the video is returned in the `startRecording` callback prop. I will take another look at this once Fabric releases, maybe there's room for improvement here.

If you could update the API & shoot me a PR that would be great 🙏
