### ISSUE TITLE
❓ Frame Processor threw an error: Value is undefined, expected an Object

### ISSUE THREAD

**Issue by meridPL** [cuvent/react-native-vision-camera#815]
### Question

Hi,

When I add to the Component frameProcessor as props when I get that error from title.

In index.tsx I have add `import 'react-native-reanimated';`

This it Camera component:
`
      <Camera
        style={StyleSheet.absoluteFill}
        device={device}
        isActive={true}
        frameProcessor={frameProcessor}
      />
`

and function frameProcessor:

`
const frameProcessor = useFrameProcessor((frame: Frame) => {
    'worklet'
    console.log("Not Hotdog.")
  }, [])
`

`
"react-native": "0.67.2",
"react-native-reanimated": "^2.4.1",
`

Maybe I somewhere get mistake but I not any idea where :)

### VisionCamera Version

2.12.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey! Maybe you need to add the import to the file where you use `useFrameProcessor` instead of just index.tsx?

**Comment by mrousavy** [comment]
Did you also follow [the installation guide from reanimated](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation)?

**Comment by meridPL** [comment]
From intruction reanimate I done:

`module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
};`

`project.ext.react = [
  enableHermes: true  // <- here | clean and rebuild if changing
]`

`import com.facebook.react.bridge.JSIModulePackage; // <- add 
import com.swmansion.reanimated.ReanimatedJSIModulePackage; // <- add
`
and

`  @Override
      protected JSIModulePackage getJSIModulePackage() {
        return new ReanimatedJSIModulePackage(); // <- add
      }
`

I don't use progroud.

I added also import to App.jsx but it not resolved my problem.

**Comment by meridPL** [comment]
I am cleaning my android project for each time

**Comment by mrousavy** [comment]
Hmm, did you start with clean metro cache as well? `yarn start --reset-cache`

**Comment by meridPL** [comment]
Ok thanks, It started work, maybe reset metro was needed.

**Comment by mrousavy** [comment]
Great! Let me know how you like the library :)

**Comment by meridPL** [comment]
I have yet one question.
In the older version RNCamera was prop onTextRecognized. Then I could used like it `onTextRecognized={({textBlocks})=>{console.log(textBlocks)}}`.

How I can do something similar in your library?
I saw useFrameProcessor, but it is very complicated for me.

**Comment by dungnguyentri3110** [comment]
have any solution?. when i build release apk faced with this. Work well on mode debug.
