### ISSUE TITLE
takePhoto and Frame Processor❓ 

### ISSUE THREAD

**Issue by xulihang** [cuvent/react-native-vision-camera#819]
### Question

I want to run OCR on an image taken as well in a live stream. Now that there are frame processor plugins like https://github.com/rodgomesc/vision-camera-ocr, I wonder if it is possible to use it for a photo taken as well.

### VisionCamera Version

2.12.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey! 

For running algorithms from a captured Image, you probably want to write a React Native Native Module and pass the photo file string to it. There's not much more I can provide to make this easier except the JSI Image HostObject (working on this)
