### ISSUE TITLE
How do I send the photo using fetch❓ 

### ISSUE THREAD

**Issue by ToasterIntervention** [cuvent/react-native-vision-camera#824]
### Question

How would I use fetch to POST a photo to my backend? I am not sure how to convert the file name file:///...name.jpg to a format that can be sent. I am fairly new at this, so it would be greatly helpful if anyone can post a working code for the file processing and POST request or provide more details suitable for a noob. Any help would be greatly appreciated!  I know that the author of this library is working on a faster way to save files, but unfortunately my school project is due within the week. ~ cry

(I am not using Expo)

### What I tried

I tried saving the file as a blob, but never was successful. I also tried to send it directly to the backend but the file was always empty.

### VisionCamera Version

Latest version

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by ToasterIntervention** [comment]
I managed to access the file in cache with react-native-fs

**Comment by mrousavy** [comment]
Hey! Good luck with the school project 😄

**Comment by josmmv** [comment]
Hi @ToasterIntervention, could you share the way you managed it with react-native-fs?
