### ISSUE TITLE
✨ Lack of function (Barcode or TextRecognized)

### ISSUE THREAD

**Issue by meridPL** [cuvent/react-native-vision-camera#829]
### What feature or enhancement are you suggesting?

I know sometimes you have to change everything, but the previous version RNCamera was the best. When I have scanned the barcode aztec (very big and difficult) that new the solution even doesn't detect it. When I want to detect text I event don't have this solution.

If you deprecated that super library as it was RNCamera, I will think the newest solution is even better, but it isn't.

Now I must found the solution in another library, which doesn't work the way I want it to

Please rewrite these functional :)

### What Platforms whould this feature/enhancement affect?

Android

### Alternatives/Workarounds

RNCamera!!!

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
Closing because you don't understand how Frame Processors work, and because you don't respect open source.
