### ISSUE TITLE
🐛 【iOS】Main Thread Checker: UI API called on a background thread: -[UIWindowScene interfaceOrientation]

### ISSUE THREAD

**Issue by voids** [cuvent/react-native-vision-camera#831]
### Question

Is this what caused take first photo slowly?

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/7220523/154050259-b8c93a06-5ac7-477f-9dda-e0f02430200d.png">

### VisionCamera Version

2.12.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hi, thanks for reporting! This has to be restructured, you're right.
