### ISSUE TITLE
❓How to scan GS1-DataBar Expanded code?

### ISSUE THREAD

**Issue by SarotaM** [cuvent/react-native-vision-camera#843]
### Question

How can i scan and decrypt GS1-DataBar Expanded code with react-native-vision-camera? It is even possible to do it?

### What I tried

I have tried to use 'vision-camera-code-scanner' package in react-native app, but this package doesn't recognize this type of code.

### VisionCamera Version

2.9.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hey, you should use Frame Processors for this. If the existing packages do not support this specific code yet, you can easily build your own Frame Processor Plugin :)

**Comment by xulihang** [comment]
You can try [vision-camera-dynamsoft-barcode-reader](https://github.com/xulihang/vision-camera-dynamsoft-barcode-reader) which supports GS1-DataBar Expanded.
