### ISSUE TITLE
🐛 Video encoded with wrong codec

### ISSUE THREAD

**Issue by TheNerdGuyLulu** [cuvent/react-native-vision-camera#844]
### What were you trying to do?

Record a video with h264 coded and upload it, making it playable in a web application through Chrome.

### Reproduceable Code

```tsx
startRecording({
   fileType: 'mp4',
   videoCodec: 'h264',
   onRecordingError: error => console.error('onRecordingError', error),
});

const devices = useCameraDevices();
const device = devices.front;
const format = useMemo(() => {
  return device?.formats.find(format => format.videoHeight === 360);
}, [device?.formats]);

<Camera
  ref={cameraRef}
  device={device}
  isActive={true}
  video={true}
  audio={true}
  format={format}
  frameProcessor={frameProcessor}
  onInitialized={() => {
    if (!isCameraReady) {
      setIsCameraReady(true);
    }
  }}
  onError={error => {
    log('Camera Error:', error);
  }}
  frameProcessorFps={30}
/>
```

### What happened instead?

Video is using HEVC for some users, which is not playable in any browser except Safari.

I cannot reproduce it with my iPhone 12 nor 11 mini -  iOS 15. We are only seeing this issue on production devices, where all users were provided with an iPhone 8, however, we don't have access to which iOS version our users have now installed and expecting 0 support from their end.

I checked the lib code, it seems fine. Maybe this is an issue with a particular iOS version?

### Device

iPhone 8 - We don't have access to user's iOS version :(

### VisionCamera Version

2.12.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey!

Hmm, this sounds weird. My Video Recorder should be encoding in h264.. Could you somehow put log statements there to see if that works? Also, is the video uploaded raw, without any additional processing from neither device nor server?

**Comment by TheNerdGuyLulu** [comment]
Hello Marc!

I logged the videoSettings outputted from recommendedVideoSettings method [in my iPhone 12], it clearly shows h264 is used.

Upload is raw, no processing is being done.
We just move the video to RNFetchBlob.fs.dirs.DocumentDir from temp folder, and upload it to S3 bucket from there using rn-background-upload with raw option instead of multipart.

EDIT:
I forgot to add that it doesn't happen to all the users, that's why I'm asking if it could possibly be an iOS bug. I tried to search for bugs related, but no luck.

**Comment by mrousavy** [comment]
hm, that's weird. It _might_ be an iOS bug, but those are rare..

**Comment by TheNerdGuyLulu** [comment]
This issue from rn-camera seems similar to mine
react-native-camera/react-native-camera/issues/1858

**Comment by paulrostorp** [comment]
@TheNerdGuyLulu Could you try logging the output of `getAvailableVideoCodecs` ? https://github.com/mrousavy/react-native-vision-camera/blob/06bcb53691c5029b08285b434e67c68ad723c0b7/src/Camera.tsx#L241-L250

**Comment by TheNerdGuyLulu** [comment]
Hi @paulrostorp.
Unfortunately, that is not an option atm. I work full remotely with a different device than the ones deployed. Plus, my assignment for this project ended last Monday.

@mrousavy I have no objection if you prefer to close this issue.

**Comment by TheNerdGuyLulu** [comment]
Btw, we tested on iPhone 6S and it didn't show any problems. I'm still not totally sure if this isn't a bug with an iOS release for iPhone 8. Only specific devices were affected, not all iPhone 8 deployed.

**Comment by mrousavy** [comment]
Video Codec is now controllable in V3! 🥳

**Comment by yspreen** [comment]
@mrousavy I'm still getting HEVC files after setting the codec to 264 on 3.6.3. I'm on iOS 17.0.3 with an iPhone 15 pro

**Comment by mrousavy** [comment]
@yspreen I can investigate this for $50: https://github.com/sponsors/mrousavy

**Comment by yspreen** [comment]
@mrousavy no thank you

**Comment by mrousavy** [comment]
@yspreen okay 👍

**Comment by yspreen** [comment]
Fixed as outlined here https://github.com/mrousavy/react-native-vision-camera/issues/2109#issuecomment-1787435134
