### ISSUE TITLE
❓ Any limitations on the camera presets to use?

### ISSUE THREAD

**Issue by pot2mayo** [cuvent/react-native-vision-camera#861]
### Question

Hi

I am trying to select a specific [camera preset](https://github.com/mrousavy/react-native-vision-camera/blob/main/src/CameraPreset.ts) in order to receive a smaller image in my frame processor.

Here is how I create my camera:

```
            <Camera
              device={device}
              preset={"cif-352x288"}
              isActive={true}
              frameProcessor={frameProcessor}
              frameProcessorFps={3}
            />
```

However whatever value I set in the `preset` attribute, I always receive an image of resolution 1280x720 as input in my frame processor.

Is there any other setting or any limitation to the use of presets.
I'm on Android OnePlus8 Pro.

Thanks!

### VisionCamera Version

2.12.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hi! `preset` is only an iOS flag. You should pass a custom `format` instead (get by finding/filtering/sorting `device.formats`)

**Comment by pot2mayo** [comment]
@mrousavy 
This flag is iOS only, I must have missed that in the doc 
Thanks!
I managed to get the available formats and select the one I want to use.
Is there any reason why even passing the format `320x240` when initializing the camera I still get an image at resolution `640x640` from the Java side?
Some kind of minimal resolution requirement somewhere in the pipeline?
(I was getting `1280x720` when initializing the camera without specifying a format)

**Comment by mrousavy** [comment]
Android is unfortunately not working with this format-based system like iOS does. So to make both platforms work, I had to estimate/round resolution on Android side.

I'll find a better API soon!

**Comment by siddharthkr** [comment]
Hi @mrousavy ,

I am trying to record video on user device and then the video needs to be uploaded to server but i am facing the same problem as @pot2mayo described (ON ANDROID) :

> @mrousavy This flag is iOS only, I must have missed that in the doc Thanks! I managed to get the available formats and select the one I want to use. Is there any reason why even passing the format `320x240` when initializing the camera I still get an image at resolution `640x640` from the Java side? Some kind of minimal resolution requirement somewhere in the pipeline? (I was getting `1280x720` when initializing the camera without specifying a format)

Its important for me to upload medium size videos(1280*720) not large videos like 4k.
Problem is if i set format prop on camera then it gives me output of resolution 480*640 (and recorded file also seems zoomed)
even if the format passed is.
   {
      "pixelFormat":"420v",
      "videoStabilizationModes":[
         "off",
         "auto",
         "standard"
      ],
      "maxZoom":10,
      "minISO":50,
      "maxISO":800,
      "autoFocusSystem":"none",
      "supportsPhotoHDR":false,
      "colorSpaces":[
         "jpeg"
      ],
      "videoWidth":4000,
      "videoHeight":3000,
      "photoWidth":4000,
      "frameRateRanges":[
         {
            "maxFrameRate":15,
            "minFrameRate":1
         },
         {
            "maxFrameRate":10,
            "minFrameRate":10
         },
         {
            "maxFrameRate":15,
            "minFrameRate":15
         },
         {
            "maxFrameRate":28,
            "minFrameRate":8
         },
         {
            "maxFrameRate":28,
            "minFrameRate":28
         },
         {
            "maxFrameRate":30,
            "minFrameRate":8
         },
         {
            "maxFrameRate":30,
            "minFrameRate":30
         }
      ],
      "photoHeight":3000,
      "supportsVideoHDR":false,
      "isHighestPhotoQualitySupported":true,
      "fieldOfView":68.38481019665146
   },

and if i do not pass any format then camera takes the highest resolution available on device.
What should i do ?

**Comment by benedusi** [comment]
~~I'm having a similar problem on android (takePhoto), it ignores the format and always use the largest image size (3000x3000)~~
Update: I uninstalled the app, deleted node_modules and run everything again and it is now working perfectly.

**Comment by mrousavy** [comment]
Okay that sucks. Might be an issue with CameraX, I'll try to look into this.
