### ISSUE TITLE
🐛 capture/no-valid-data

### ISSUE THREAD

**Issue by Srinivas2445** [cuvent/react-native-vision-camera#869]
### What were you trying to do?

Got this error while start the recording, faced this issue from 3 days, before that, its works fine

### Reproduceable Code

```tsx
<Camera
          ref={cameraRef}
          style={styles.camera}
          isActive
          video
          
          audio
          preset="vga-640x480"
          device={
            route.params.deviceData && isBack
              ? route.params.deviceData.back
              : route.params.deviceData.front
          }
        />
```

### What happened instead?

![image (3)](https://user-images.githubusercontent.com/68465638/156982519-6b291bf3-7769-4d02-b4ed-c3d40873fa61.png)

### Device

pixel 3

### VisionCamera Version

2.12.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Maybe you called `stopRecording` immediately after `startRecording`?

**Comment by Srinivas2445** [comment]
> Maybe you called `stopRecording` immediately after `startRecording`?

Thanks lot..
