### ISSUE TITLE
Zoom does not work in debug mode 🐛 

### ISSUE THREAD

**Issue by tomgreco** [cuvent/react-native-vision-camera#890]
### What were you trying to do?

When running the example project with chrome debug tools enabled zoom throws an error "Cannot read property 'setAttribute' of undefined” which comes from react-native-reanimated. 

Works fine without debug. 

### What happened instead?

Cannot read property 'setAttribute' of undefined

### Device

iPhone 13 Pro

### VisionCamera Version

Latest

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
That's a Reanimated v2 issue. Report over there.

You can also use Animated or Reanimated v1 to animate the zoom property of the Camera (or set it via state)
