### ISSUE TITLE
The 'kotlin-android-extensions' Gradle plugin is deprecated

### ISSUE THREAD

**Issue by msnainps** [cuvent/react-native-vision-camera#891]
### What were you trying to do?

I wanted to build project.

### Reproduceable Code

```tsx
Just try to rebuild project with latest gradle
```

### What happened instead?

The 'kotlin-android-extensions' Gradle plugin is deprecated

### Relevant log output

```shell
The 'kotlin-android-extensions' Gradle plugin is deprecated
```

### Device

At the time of build

### VisionCamera Version

2.12.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Yea I know, that's not an error though.
