### ISSUE TITLE
✨ Build apk for each release

### ISSUE THREAD

**Issue by Angelk90** [cuvent/react-native-vision-camera#909]
### What feature or enhancement are you suggesting?

Whenever a release is released, it would be nice for a sample apk to be generated so that you can get a general idea of the sample project.

### What Platforms whould this feature/enhancement affect?

Android

### Alternatives/Workarounds

Use the github actions, which every time a release is released, a sample apk is generated.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
Yeah actually not a bad idea - release builds take a little bit longer than debug but we can hook it to Release Trigger

**Comment by mrousavy** [comment]
I don't think this makes sense atm
