### ISSUE TITLE
❓ Enable torch without shot

### ISSUE THREAD

**Issue by whalemare** [cuvent/react-native-vision-camera#913]
### Question

Can this library enable torch without doing a photo?

My use case, it is scanning qr-code in realtime, when user don't want to create any photo, but want to use torch (moonlight is not enough bright, for example)

### VisionCamera Version

2.12.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Yes, it's on the docs.
