### ISSUE TITLE
🐛 Errors when building for simulator, works fine on devices

### ISSUE THREAD

**Issue by ademirmochi** [cuvent/react-native-vision-camera#914]
### What were you trying to do?

I'm trying to build my react-native application, it works on devices, but when I try to build on the simulator, it gives me plenty of errors, I've already tried the solutions in the troubleshooting guide, didn't change much.

### What happened instead?

When selecting "any iOS Device arm64" it builds without issues, and I can create the IPA file and test on TestFlight, but when trying to test on simulator, regardless of version, it gives me a collection of erros, usually around the MLKIT components and:

Showing Recent Messages
Undefined symbol: _GULLogBasic
Undefined symbol: _OBJC_CLASS_$_GPBEnumArray
Undefined symbol: _GPBClearOneof
Undefined symbol: _OBJC_CLASS_$_GTMLogMininumLevelFilter
Undefined symbol: _OBJC_METACLASS_$_GTMLogger
Undefined symbol: _OBJC_CLASS_$_GPBCodedOutputStream
Undefined symbol: _OBJC_CLASS_$_GPBFileDescriptor
Undefined symbol: _OBJC_CLASS_$_GPBEnumDescriptor
Undefined symbol: _OBJC_CLASS_$_GPBDescriptor
Undefined symbol: _kGTMSessionFetcherStatusDomain
Undefined symbol: _OBJC_CLASS_$_GDTCORTransport
Undefined symbol: _OBJC_CLASS_$_GTMSessionFetcherService
Undefined symbol: _OBJC_CLASS_$_GTMSessionFetcher
Undefined symbol: _OBJC_METACLASS_$_GPBMessage
Undefined symbol: _OBJC_CLASS_$_GTMLogger
Undefined symbol: _OBJC_CLASS_$_FlipperClient
Undefined symbol: _OBJC_METACLASS_$_GPBRootObject
Undefined symbol: _OBJC_CLASS_$_GULCCComponentContainer
Undefined symbol: _OBJC_CLASS_$_GULCCComponentType
Undefined symbol: _OBJC_CLASS_$_GPBMessage
Undefined symbol: _OBJC_CLASS_$_GULUserDefaults
Undefined symbol: _OBJC_CLASS_$_FlipperKitNetworkPlugin
Undefined symbol: _OBJC_CLASS_$_GPBRootObject
Undefined symbol: _OBJC_CLASS_$_RCTBundleURLProvider
Undefined symbol: _OBJC_CLASS_$_SKIOSNetworkAdapter
Undefined symbol: _OBJC_CLASS_$_FlipperKitReactPlugin
Undefined symbol: _OBJC_CLASS_$_SKDescriptorMapper
Undefined symbol: _OBJC_CLASS_$_GPBInt32Array
Undefined symbol: _OBJC_CLASS_$_GTMSessionCookieStorage
Undefined symbol: _OBJC_CLASS_$_FlipperKitLayoutPlugin
Undefined symbol: _OBJC_CLASS_$_FKUserDefaultsPlugin
Undefined symbol: _OBJC_CLASS_$_GULCCComponent
Undefined symbol: _OBJC_CLASS_$_RCTRootView
Undefined symbol: _OBJC_CLASS_$_RCTBridge

### Relevant log output

```shell
Undefined symbols for architecture x86_64:
  "_GULLogBasic", referenced from:
      _MLKLog in MLKitCommon(MLKLogger.o)
  "_OBJC_CLASS_$_GPBEnumArray", referenced from:
      objc-class-ref in MLKitVision(GMVLogger.o)
  "_GPBClearOneof", referenced from:
      _MLKITx_EPTFlagValue_ClearValueOneOfCase in MLKitCommon(FlagValues.pbobjc.o)
      _MLKITx_PHENORegistrationInfo_ClearPackageVersionOneOfCase in MLKitCommon(RegistrationInfo.pbobjc.o)
      _MLKITx_PHENORegistrationInfo_ClearApplicationInfoOneOfCase in MLKitCommon(RegistrationInfo.pbobjc.o)
      _MLKITx_CLCCCounter_ClearCounterIdOneOfCase in MLKitCommon(Counters.pbobjc.o)
  "_OBJC_CLASS_$_GTMLogMininumLevelFilter", referenced from:
      objc-class-ref in MLKitCommon(GIPLoggingReroutingGTMLogger.o)
  "_OBJC_METACLASS_$_GTMLogger", referenced from:
      _OBJC_METACLASS_$_MLKITx_GIPLoggingReroutingGTMLogger in MLKitCommon(GIPLoggingReroutingGTMLogger.o)
  "_OBJC_CLASS_$_GPBCodedOutputStream", referenced from:
      objc-class-ref in MLKitCommon(CCTLogOutputStream.o)
  "_OBJC_CLASS_$_GPBFileDescriptor", referenced from:
      objc-class-ref in MLKitCommon(Enums.pbobjc.o)
      objc-class-ref in MLKitCommon(UploaderState.pbobjc.o)
      objc-class-ref in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      objc-class-ref in MLKitCommon(Barhopper.pbobjc.o)
      objc-class-ref in MLKitCommon(FlatFile.pbobjc.o)
      objc-class-ref in MLKitCommon(TypedFeatures.pbobjc.o)
      objc-class-ref in MLKitCommon(PhenotypeLog.pbobjc.o)
      ...
  "_OBJC_CLASS_$_GPBEnumDescriptor", referenced from:
      objc-class-ref in MLKitCommon(Enums.pbobjc.o)
      objc-class-ref in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      objc-class-ref in MLKitCommon(Barhopper.pbobjc.o)
      objc-class-ref in MLKitCommon(FlatFile.pbobjc.o)
      objc-class-ref in MLKitCommon(PhenotypeLog.pbobjc.o)
      objc-class-ref in MLKitCommon(Clientanalytics.pbobjc.o)
      objc-class-ref in MLKitCommon(VisionExtension.pbobjc.o)
      ...
  "_OBJC_CLASS_$_GPBDescriptor", referenced from:
      objc-class-ref in MLKitCommon(Enums.pbobjc.o)
      objc-class-ref in MLKitCommon(UploaderState.pbobjc.o)
      objc-class-ref in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      objc-class-ref in MLKitCommon(Barhopper.pbobjc.o)
      objc-class-ref in MLKitCommon(FlatFile.pbobjc.o)
      objc-class-ref in MLKitCommon(TypedFeatures.pbobjc.o)
      objc-class-ref in MLKitCommon(PhenotypeLog.pbobjc.o)
      ...
  "_kGTMSessionFetcherStatusDomain", referenced from:
      ___69-[MLKModelDownloader beginModelDownloadWithURL:modelInfo:conditions:]_block_invoke.285 in MLKitCommon(MLKModelDownloader.o)
      ___91-[MLKITx_PHTInternalHeterodyneSyncer syncHoldingLockWithSyncedScopes:fetchReason:callback:]_block_invoke_2 in MLKitCommon(PHTInternalHeterodyneSyncer.o)
      ___150-[MLKITx_PHTHeterodyneSyncer batchSyncWithAccounts:syncedScopes:fetchReason:throttlingCache:heterodyneSyncInfo:accountToAuthToken:lastError:callback:]_block_invoke_2 in MLKitCommon(PHTHeterodyneSyncer.o)
      ___63-[MLKITx_GMVCloudVisionClient initWithCloudUri:apiKey:options:]_block_invoke in MLKitVision(GMVCloudVisionClient.o)
  "_OBJC_CLASS_$_GDTCORTransport", referenced from:
      objc-class-ref in MLKitCommon(MLKFirelogTransport.o)
  "_OBJC_CLASS_$_GTMSessionFetcherService", referenced from:
      objc-class-ref in MLKitCommon(MLKModelDownloader.o)
      objc-class-ref in MLKitVision(GMVCloudVisionClient.o)
  "_OBJC_CLASS_$_GTMSessionFetcher", referenced from:
      objc-class-ref in MLKitCommon(CCTClearcutUploader.o)
      objc-class-ref in MLKitCommon(PHTInternalHeterodyneSyncer.o)
      objc-class-ref in MLKitCommon(PHTHeterodyneSyncer.o)
  "_OBJC_METACLASS_$_GPBMessage", referenced from:
      _OBJC_METACLASS_$_MLKITx_EXHFetchReason in MLKitCommon(Enums.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_CCTUploaderState in MLKitCommon(UploaderState.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_FBMLSystemInfo in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_FBMLModelInfo in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_FBMLOtherError in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_FBMLImageInfo in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_FBMLInferenceCommonLogEvent in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      ...
  "_OBJC_CLASS_$_GTMLogger", referenced from:
      objc-class-ref in MLKitCommon(CCTClearcutUploader.o)
      objc-class-ref in MLKitCommon(CCTClearcutMetaLogger.o)
      objc-class-ref in MLKitCommon(PHTFlatFilePhenotype.o)
      objc-class-ref in MLKitCommon(PHTURL.o)
      objc-class-ref in MLKitCommon(CCTLogWriter.o)
      objc-class-ref in MLKitCommon(CCTLogOutputStream.o)
      objc-class-ref in MLKitCommon(CCTClearcutFileUtility.o)
      ...
  "_OBJC_CLASS_$_FlipperClient", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_METACLASS_$_GPBRootObject", referenced from:
      _OBJC_METACLASS_$_MLKITx_EXHEnumsRoot in MLKitCommon(Enums.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_CCTUploaderStateRoot in MLKitCommon(UploaderState.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_FBMLFirebaseMlSdkRoot in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_BARBarhopperRoot in MLKitCommon(Barhopper.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_EPIFlatFileRoot in MLKitCommon(FlatFile.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_TypedFeaturesRoot in MLKitCommon(TypedFeatures.pbobjc.o)
      _OBJC_METACLASS_$_MLKITx_PHTPhenotypeLogRoot in MLKitCommon(PhenotypeLog.pbobjc.o)
      ...
  "_OBJC_CLASS_$_GULCCComponentContainer", referenced from:
      objc-class-ref in MLKitCommon(MLKContext.o)
      objc-class-ref in MLKitCommon(MLKCustomModelManager.o)
      objc-class-ref in MLKitImageLabeling
  "_OBJC_CLASS_$_GULCCComponentType", referenced from:
      objc-class-ref in MLKitCommon(MLKContext.o)
      objc-class-ref in MLKitCommon(MLKCustomModelManager.o)
      objc-class-ref in MLKitCommon(MLKModelManager.o)
      objc-class-ref in MLKitImageLabelingCommon(MLKImageLabeler.o)
      objc-class-ref in MLKitObjectDetectionCommon(MLKObjectDetector.o)
  "_OBJC_CLASS_$_GPBMessage", referenced from:
      _OBJC_CLASS_$_MLKITx_EXHFetchReason in MLKitCommon(Enums.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_CCTUploaderState in MLKitCommon(UploaderState.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_FBMLSystemInfo in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_FBMLModelInfo in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_FBMLOtherError in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_FBMLImageInfo in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_FBMLInferenceCommonLogEvent in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      ...
  "_OBJC_CLASS_$_GULUserDefaults", referenced from:
      objc-class-ref in MLKitCommon(MLKAnalyticsLogger.o)
      objc-class-ref in MLKitCommon(MLKModelDownloader.o)
      objc-class-ref in MLKitCommon(MLKModelPreferencesManager.o)
  "_OBJC_CLASS_$_FlipperKitNetworkPlugin", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_GPBRootObject", referenced from:
      _OBJC_CLASS_$_MLKITx_EXHEnumsRoot in MLKitCommon(Enums.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_CCTUploaderStateRoot in MLKitCommon(UploaderState.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_FBMLFirebaseMlSdkRoot in MLKitCommon(FirebaseMlSdk.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_BARBarhopperRoot in MLKitCommon(Barhopper.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_EPIFlatFileRoot in MLKitCommon(FlatFile.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_TypedFeaturesRoot in MLKitCommon(TypedFeatures.pbobjc.o)
      _OBJC_CLASS_$_MLKITx_PHTPhenotypeLogRoot in MLKitCommon(PhenotypeLog.pbobjc.o)
      ...
  "_OBJC_CLASS_$_RCTBundleURLProvider", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_SKIOSNetworkAdapter", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_FlipperKitReactPlugin", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_SKDescriptorMapper", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_GPBInt32Array", referenced from:
      objc-class-ref in MLKitCommon(CCTClearcutLogEvent.o)
  "_OBJC_CLASS_$_GTMSessionCookieStorage", referenced from:
      objc-class-ref in MLKitCommon(CCTClearcutUploader.o)
  "_OBJC_CLASS_$_FlipperKitLayoutPlugin", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_FKUserDefaultsPlugin", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_GULCCComponent", referenced from:
      objc-class-ref in MLKitCommon(MLKCustomModelManager.o)
      objc-class-ref in MLKitImageLabeling
  "_OBJC_CLASS_$_RCTRootView", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_RCTBridge", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Device

iPhone 11 (15) Xcode Simulator

### VisionCamera Version

2.12.2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by vlorian-de** [comment]
same here

**Comment by mrousavy** [comment]
Hey, you did not share any reproduceable code, I cannot reproduce your error.

**Comment by vlorian-de** [comment]
This issue is already closed. But I had exactly the same problem and found a solution for it.
So maybe it will help somebody in the future, if I share it here:

The build failed only in projects when using the frame processor "react-native-vision-camera".

When I experienced this issue I developed on an MBP with M1Max Apple Silicon running macOS Monterey and XCode 13.3.
I wanted to give it another try with a different macOS / XCode version and did a checkout on my old 2017 Intel based MBP: And everything worked fine. Then I updated my old Intel based MBP to the same versions of node / macOS / XCode and the builds still ran sucessfully.

It seems that the only issue is the hardware platform. Even when working with Rosetta.

**So here is a fix that worked on my Apple silicon MPB:
Make sure that you add "arm64" as "Excluded Architecture" to your project AND the pod configuration:**

![Bildschirmfoto 2022-04-07 um 11 23 07](https://user-images.githubusercontent.com/64640147/162168635-9c693e4d-6816-483f-afd2-72370aed35ac.png)

**Comment by mrousavy** [comment]
Nice catch @vlorian-de, this shouldn't be happening but glad it's working for you now

**Comment by ademirmochi** [comment]
So I'm aware already that the problem was the new chip and all the headache that comes with it, this solution, where you put the "arm64" at excluded architectures, solves a lot of different issues i've been having, in a lot of different libs, but, in this particular case, it didn't, still, glad to know it worked for you.

**Comment by vlorian-de** [comment]
@ademirmochi Can you confirm that you are also on some kind of M1 chip?
Would you like to checkout if you can build my quick and dirty test app? I uploaded it here: https://github.com/vlorian-de/vision-camera-code-scanner-test-app

**Comment by SpaghettiC0des** [comment]
@mrousavy This is still happening on `2.13.3` using the frame processor.

**Comment by moygospadin** [comment]
> @ademirmochi Can you confirm that you are also on some kind of M1 chip? Would you like to checkout if you can build my quick and dirty test app? I uploaded it here: https://github.com/vlorian-de/vision-camera-code-scanner-test-app

dont work on MacBook Pro (13-inch, M1, 2020) Xcode Version 13.3 (13E113)

**Comment by moygospadin** [comment]
> 
Also happening here

**Comment by moygospadin** [comment]
> @ademirmochi Can you confirm that you are also on some kind of M1 chip? Would you like to checkout if you can build my quick and dirty test app? I uploaded it here: https://github.com/vlorian-de/vision-camera-code-scanner-test-app

Also happening here

**Comment by hdvinhhoang** [comment]
> This issue is already closed. But I had exactly the same problem and found a solution for it. So maybe it will help somebody in the future, if I share it here:
> 
> The build failed only in projects when using the frame processor "react-native-vision-camera".
> 
> When I experienced this issue I developed on an MBP with M1Max Apple Silicon running macOS Monterey and XCode 13.3. I wanted to give it another try with a different macOS / XCode version and did a checkout on my old 2017 Intel based MBP: And everything worked fine. Then I updated my old Intel based MBP to the same versions of node / macOS / XCode and the builds still ran sucessfully.
> 
> It seems that the only issue is the hardware platform. Even when working with Rosetta.
> 
> **So here is a fix that worked on my Apple silicon MPB: Make sure that you add "arm64" as "Excluded Architecture" to your project AND the pod configuration:**
> 
> ![Bildschirmfoto 2022-04-07 um 11 23 07](https://user-images.githubusercontent.com/64640147/162168635-9c693e4d-6816-483f-afd2-72370aed35ac.png)
Thank @vlorian-de. it works for me on M1 chip

**Comment by moygospadin** [comment]
@hdvinhhoang could you show your podfile ?

**Comment by hdvinhhoang** [comment]
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

target 'vinhproject' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  pod 'GoogleSignIn', '~> 6.1.0'
  target 'vinhprojectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```


this is my podfile @moygospadin

**Comment by vlorian-de** [comment]
Hello all,
since people with the same old problem are still coming in here regularly, I wanted to point out the following:

With the current version of ReactNative (0.68.2), the problem no longer occurs (at least for me).

Just try a `npx react-native init YouNameIt`
If that works for you, just update your project to the current dependencies or use a diff to get to the actual error location.

Tested on a MBP2021 M1-Max:
MacOS 12.3.1 (21E258)
XCode 13.3.1 (13E500a)
CommandLine Tools: 13.4.0.0.1.1651278267
ReactNative: 0.68.2

**Comment by svbasi** [comment]
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
    end
  end
end
```

**Comment by Ace090** [comment]
> This issue is already closed. But I had exactly the same problem and found a solution for it. So maybe it will help somebody in the future, if I share it here:
> 
> The build failed only in projects when using the frame processor "react-native-vision-camera".
> 
> When I experienced this issue I developed on an MBP with M1Max Apple Silicon running macOS Monterey and XCode 13.3. I wanted to give it another try with a different macOS / XCode version and did a checkout on my old 2017 Intel based MBP: And everything worked fine. Then I updated my old Intel based MBP to the same versions of node / macOS / XCode and the builds still ran sucessfully.
> 
> It seems that the only issue is the hardware platform. Even when working with Rosetta.
> 
> **So here is a fix that worked on my Apple silicon MPB: Make sure that you add "arm64" as "Excluded Architecture" to your project AND the pod configuration:**
> 
> ![Bildschirmfoto 2022-04-07 um 11 23 07](https://user-images.githubusercontent.com/64640147/162168635-9c693e4d-6816-483f-afd2-72370aed35ac.png)

It works for me. Thanks!

**Comment by liptonzuma** [comment]
> This issue is already closed. But I had exactly the same problem and found a solution for it. So maybe it will help somebody in the future, if I share it here:
> 
> The build failed only in projects when using the frame processor "react-native-vision-camera".
> 
> When I experienced this issue I developed on an MBP with M1Max Apple Silicon running macOS Monterey and XCode 13.3. I wanted to give it another try with a different macOS / XCode version and did a checkout on my old 2017 Intel based MBP: And everything worked fine. Then I updated my old Intel based MBP to the same versions of node / macOS / XCode and the builds still ran sucessfully.
> 
> It seems that the only issue is the hardware platform. Even when working with Rosetta.
> 
> **So here is a fix that worked on my Apple silicon MPB: Make sure that you add "arm64" as "Excluded Architecture" to your project AND the pod configuration:**
> 
> ![Bildschirmfoto 2022-04-07 um 11 23 07](https://user-images.githubusercontent.com/64640147/162168635-9c693e4d-6816-483f-afd2-72370aed35ac.png)

So I did this and the problem went away but I deleted the project and cloned the repo for some reason the problem is back with all this configurations in place. Please what do I do?

**Comment by ospfranco** [comment]
This is happening to me to:

macbook air m2
xcode 14.1
RN 0.69.7

The workaround on my podfile is to exclude arm64 compilation:

```ruby
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
    installer.pods_project.targets.each do |target|
      # Prevents dependencies to be compiled under m1
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
        end
      end

      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
```

**Comment by comur** [comment]
Hi all,

This still happens:

macbook air m1
xcode 14.1
RN 0.68.0

Your workaround works @ospfranco ! thanks

**Comment by Jeppeer** [comment]
I had the same problem. Upgrading to v3 and removing `vision-camera-code-scanner` solved it.

**Comment by bumios** [comment]
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
>     end
>   end
> end
> ```

I'm working on MLKit vision only for iOS, but this solution worked for me too, thank you!

**Comment by yvza** [comment]
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
>     end
>   end
> end
> ```

Tested on same issue, using Macbook Pro M2 and Macbook Pro M1. Thanks mate! its working @svbasi

**Comment by hoscahmet** [comment]
> arm64



> > This issue is already closed. But I had exactly the same problem and found a solution for it. So maybe it will help somebody in the future, if I share it here:
> > The build failed only in projects when using the frame processor "react-native-vision-camera".
> > When I experienced this issue I developed on an MBP with M1Max Apple Silicon running macOS Monterey and XCode 13.3. I wanted to give it another try with a different macOS / XCode version and did a checkout on my old 2017 Intel based MBP: And everything worked fine. Then I updated my old Intel based MBP to the same versions of node / macOS / XCode and the builds still ran sucessfully.
> > It seems that the only issue is the hardware platform. Even when working with Rosetta.
> > **So here is a fix that worked on my Apple silicon MPB: Make sure that you add "arm64" as "Excluded Architecture" to your project AND the pod configuration:**
> > ![Bildschirmfoto 2022-04-07 um 11 23 07](https://user-images.githubusercontent.com/64640147/162168635-9c693e4d-6816-483f-afd2-72370aed35ac.png)
> 
> It works for me. Thanks!

**Comment by nathangabriel27** [comment]
> This issue is already closed. But I had exactly the same problem and found a solution for it. So maybe it will help somebody in the future, if I share it here:
> 
> The build failed only in projects when using the frame processor "react-native-vision-camera".
> 
> When I experienced this issue I developed on an MBP with M1Max Apple Silicon running macOS Monterey and XCode 13.3. I wanted to give it another try with a different macOS / XCode version and did a checkout on my old 2017 Intel based MBP: And everything worked fine. Then I updated my old Intel based MBP to the same versions of node / macOS / XCode and the builds still ran sucessfully.
> 
> It seems that the only issue is the hardware platform. Even when working with Rosetta.
> 
> **So here is a fix that worked on my Apple silicon MPB: Make sure that you add "arm64" as "Excluded Architecture" to your project AND the pod configuration:**
> 
> ![Bildschirmfoto 2022-04-07 um 11 23 07](https://user-images.githubusercontent.com/64640147/162168635-9c693e4d-6816-483f-afd2-72370aed35ac.png)

It works for me. Thanks!
