### ISSUE TITLE
❓ fatal error: 'AnimatedSensorModule.h' file not found

### ISSUE THREAD

**Issue by rajaryan1990** [cuvent/react-native-vision-camera#919]
### Question

In file included from ../../../../src/main/cpp/VisionCamera.cpp:3:
In file included from ../../../../src/main/cpp/FrameProcessorRuntimeManager.h:13:
In file included from /some_path/node_modules/react-native-reanimated/Common/cpp/headers/SharedItems/RuntimeManager.h:9:
/some_path/node_modules/react-native-reanimated/Common/cpp/headers/SharedItems/ShareableValue.h:9:10: fatal error: 'AnimatedSensorModule.h' file not found
#include "AnimatedSensorModule.h"
^~~~~~~~~~~~~~~~~~~~~~~~

1 error generated.
  [8/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/CameraView.cpp.o
  [9/10] Building CXX object CMakeFiles/VisionCamera.dir/src/main/cpp/JSIJNIConversion.cpp.o
  ninja: build stopped: subcommand failed.

### What I tried

React Native Version: 0.64.2
Reanimated Version: 2.5.0
Vision Camera version: 2.9.4

Build is running on IOS but failing on Android

### VisionCamera Version

2.9.4

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
This looks like a Reanimated build error. Not VisionCamera.

**Comment by rajaryan1990** [comment]
But If I remove this vision camera library the error is not showing. I am using this reanimated library from long time back but never seen this type of error.

**Comment by mrousavy** [comment]
I want to apologize, you're right. I added the missing header and will ship an update soon

**Comment by DeVoresyah** [comment]
> I want to apologize, you're right. I added the missing header and will ship an update soon

is this already solved? I had the same issue when using react-native-vision-camera `2.10.0`. And if I use the latest version `2.13.1`, I got an issue from #716

**Comment by GSFZamai** [comment]
> > I want to apologize, you're right. I added the missing header and will ship an update soon
> 
> is this already solved? I had the same issue when using react-native-vision-camera `2.10.0`. And if I use the latest version `2.13.1`, I got an issue from #716

Same problem here. Having different errors on each versions. 
Version 2.10.0 don't build on android and version 2.13.1 don't build on iOS.

**Comment by tatiana-lonestone** [comment]
Same here, it doesn't build on ios with 2.14.1
