### ISSUE TITLE
✨ MacOS catalyst support

### ISSUE THREAD

**Issue by samuelscheit** [cuvent/react-native-vision-camera#920]
### What feature or enhancement are you suggesting?

With Catalyst, you can easily compile your existing React-native iOS apps for macOS.
However, it fails in many stages, all with the error "...is only available in Mac Catalyst 14.0 or newer".

### What Platforms whould this feature/enhancement affect?

iOS, macOS

### Alternatives/Workarounds

I am currently adding ``Add 'if #available' version `` checks to nearly every line, but this isn't feasible for development.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
This is now implemented with V3! 🥳

**Comment by tommycarpi** [comment]
I'm still experiencing this in v3.8.2.
Is there any workaround? @mrousavy 

<img width="268" alt="Screenshot 2024-02-03 at 19 05 22" src="https://github.com/mrousavy/react-native-vision-camera/assets/10156527/149d0028-82cb-4ce7-85ce-984805f14991">

<img width="336" alt="Screenshot 2024-02-03 at 19 05 49" src="https://github.com/mrousavy/react-native-vision-camera/assets/10156527/d06edf9f-3c0f-49db-b28b-65246a6369e7">

**Comment by Hunnainwali** [comment]
Facing same issue, my app was crashing on Mac when camera was being rendered multiple times. Tried enabling Mac Catalyst into my project and example project as well but no luck : (
