### ISSUE TITLE
🐛 .globals is not a valid Plugin property

### ISSUE THREAD

**Issue by binitgurzu** [cuvent/react-native-vision-camera#929]
### What were you trying to do?

According to documentation, I have added `globals __scanQRCodes` inside `babel.config.js`.

<img width="498" alt="ojAYy" src="https://user-images.githubusercontent.com/68578227/159837138-9dfc6480-32d3-49d2-8dba-353f8fd2beb0.png">

But after adding `globals __scanQRCodes` inside `babel.config.js`. I got BABEL TRANSFORM ERROR **.globals is not a valid Plugin property**

![dIyLE](https://user-images.githubusercontent.com/68578227/159837358-af262a47-2a7a-40ef-9b36-0f8d11948e95.png)

### Reproduceable Code

```tsx
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    '@babel/plugin-transform-runtime',
    'react-native-reanimated/plugin',
    {
      globals: ['__scanQRCodes'],
    },
  ],
};
```

### What happened instead?

The app is throwing errors after launching the app from the closed state.

![WhatsApp Image 2022-03-24 at 09 27 17](https://user-images.githubusercontent.com/68578227/159837882-7e9ec07a-38e9-4106-bd06-2223920085f6.jpeg)
t

### Relevant log output

```shell
error: index.js: [BABEL] /Users/binitchandrajha/Desktop/app/index.js: .globals is not a valid Plugin property
- Maybe you meant to use
"plugins": [
  ["react-native-reanimated/plugin", {
  "globals": [
    "__scanQRCodes"
  ]
}]
]
To be a valid plugin, its name and options should be wrapped in a pair of brackets
```

### Device

iPhone 13  simulator and Samsung M11 real device.

### VisionCamera Version

2.13.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey, you are missing `[` and `]` around the entire block, see here:

```js
  plugins: [
    [ // <-- this
      'react-native-reanimated/plugin',
      {
        globals: ['__example_plugin', '__example_plugin_swift'],
      },
    ], // <-- this
```
