### ISSUE TITLE
🐛 [ios] Crash report - Cannot call method when status is 1

### ISSUE THREAD

**Issue by hirbod** [cuvent/react-native-vision-camera#930]
### What were you trying to do?

My user was recording multiple videos. So a bunch of startRecording / stopRecording calls.
From what I can tell, this issue is related to older iPhone devices. My user is using an iPhone SE 2nd Generation with iOS 15.4

The App crashes, heats up a lot and also screen dimming is happening.
It is kinda hard to tell what is happening, I just have those crash reports. I never had a crash on my iPhone 13 Pro Max, guess it has more CPU, GPU, RAM etc and can handle frequent start/stop triggers.

### What happened instead?

The app crashes with `Cannot call method when status is 1`

<img width="985" alt="Bildschirmfoto 2022-03-24 um 13 00 27" src="https://user-images.githubusercontent.com/504909/159911950-4559cc59-572b-41cd-b9d2-171b6a9c36d7.png">

### Relevant log output

```shell
NSInternalInconsistencyException
*** -[AVAssetWriter finishWritingWithCompletionHandler:] Cannot call method when status is 1
```

### Device

iPhone SE 2nd Generation (15.4)

### VisionCamera Version

2.13.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Not sure what status 1 is, I'd have to read AVFoundation headers again. Maybe not enough disk space?

**Comment by hirbod** [comment]
I've double checked, disk space is not the issue, 16GB free space left.

**Comment by hirbod** [comment]
@mrousavy  I found a fix for it thanks to this article
https://code-examples.net/en/q/e14f33

PR incoming

**Comment by hirbod** [comment]
So sorry @mrousavy but I really thought my PR fixed it. It happened again, but less frequent though.

Maybe you'll need to revert my PR
