### ISSUE TITLE
✨ Create panorama/360 degrees photo

### ISSUE THREAD

**Issue by DenisDov** [cuvent/react-native-vision-camera#932]
### What feature or enhancement are you suggesting?

I have an design, where i need to implement ability to create panorama/360 degrees photo. I see in the docs that is not possible now. Can u have any ideas how to create this? Or it is not possible?

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

No workaround now

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by mrousavy** [comment]
Hey!

No, this is not possible right now. I'm actually not sure if this must be a native implementation or if you can actually do this yourself in React today?

Just shoot a photo, get orientation value and tell the user to not tilt the phone too much. Then automatically shoot the next photo after you detected that gyroscope has moved to the right, and combine the photos using some sort of combine algorithm
