### ISSUE TITLE
❓ Feed PhotoFile instead of Frame to Frame Processor

### ISSUE THREAD

**Issue by sandlands** [cuvent/react-native-vision-camera#935]
### Question

Hi there,

I managed to successfully implement a Frame Processor and feed it with the `Camera`'s `Frame` objects.
I was wondering if it's also possible to feed it with a `PhotoFile` (as a result from the `Camera.takePicture()` method).

Thanks in advance.

Kind regards,
Sander Landsmeer

### VisionCamera Version

2.11.2

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hi! No, this is not supported. It's a Frame Processor, not a Photo Processor.

If you want to pass static photos to a function like MLKit OCR, just create a native module and pass the file path.

Why would you need this?
