### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by cdalen16** [cuvent/react-native-vision-camera#947]
### What were you trying to do?

Running my application on a physical device with the react native vison camera installed.

### Reproduceable Code

```tsx
build.gradle:

buildscript {
    ext {
        minSdkVersion = 24
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "20.1.5948944"
        buildToolsVersion = "30.0.2"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.2.2')
        classpath('com.google.gms:google-services:4.3.5')
        // implementation 'com.android.support:multidex:2.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

}


AndroidManifest.xml:

  <activity
    android:name=".MainActivity" android:exported="false" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize" android:theme="@style/Theme.App.SplashScreen" android:screenOrientation="portrait">
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>

      <!-- Auth0 URI Scheme -->
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data
            android:host="localyte.us.auth0.com"
            android:pathPrefix="/android/${applicationId}/callback"
            android:scheme="${applicationId}" />
      </intent-filter>

      <!-- Branch URI Scheme -->
      <intent-filter>
        <data android:scheme="us.localyte.consumer" />
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
      </intent-filter>

      <!-- Branch App Links (optional) -->
      <intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="https" android:host="localyte.app.link" />
      </intent-filter>

    </activity>
    <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" android:exported="false"/>
```

### What happened instead?

When I tried to run the app on my device originally I received an error saying the compileSDK must be 31 instead of 30. However, when I change the SDK to 31, I then get this error instead. I am not sure why because I do have a specified value for android:exported in my AndroidManifest.xml. I have seen this issue all over the internet and not a single one of the suggestions I have seen fixed my issue. I have included the important parts of my build.gradle and my AndroidManifest.xml here. I am really just not sure what to do at this point. I have seen there was a post on this forum with the same problem as me however the responses did not help solve my problem so I am hoping for a different solution. Thanks!

### Relevant log output

```shell
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : Apps targeting Android 12 and higher are re
specify an explicit value for `android:exported` when the correspondin
t has an intent filter defined. See https://developer.android.com/guid
anifest/activity-element#exported for details.
```

### Device

Motorola Moto Z

### VisionCamera Version

2.13.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hi!

1. Incorrect issue title.
2. This is not a VisionCamera issue. A 5 second google search showed me [this SO post](https://stackoverflow.com/questions/68554294/androidexported-needs-to-be-explicitly-specified-for-activity-apps-targeting) as as first result, this contains a solution. You have to use `android:exported="true"` in your MainActivity and intents, false otherwise.
