### ISSUE TITLE
🐛 Frame processor crashed application

### ISSUE THREAD

**Issue by vgorte** [cuvent/react-native-vision-camera#952]
### What were you trying to do?

I wanted to use the vision-camera with the [code-scanner](https://github.com/rodgomesc/vision-camera-code-scanner) plugin. 
All installation steps, as far as I could tell (vision-camera, code-scanner, reanimated) have been executed by me, like instructed on the corresponding installation guides. Reanimated is imported first in the `index.js`

### Used Code

```tsx
Component: 
export const QRScannerScreen = () => {
  const [ hasPermission, setHasPermission ] = React.useState(false);
  const devices = useCameraDevices();
  const device = devices.back;

  const [ frameProcessor, barcodes ] = useScanBarcodes([ BarcodeFormat.QR_CODE ]);

  React.useEffect(() => {
    (async () => {
      const status = await Camera.requestCameraPermission();
      setHasPermission(status === 'authorized');
    })();
  }, []);

  if (!device || !hasPermission) return <Text>Fallback</Text>;

  return (hasPermission && device &&  (
    <>
      <Camera
        style={ StyleSheet.absoluteFill }
        device={ device }
        isActive={ true }
        frameProcessor={ frameProcessor }
        frameProcessorFps={ 1 }
      />
      { barcodes.map((barcode, idx) => (
        <Text key={ idx } style={ styles.barcodeTextURL }>
          { barcode.displayValue }
        </Text>
      )) }
    </>
  ));
};

babel.config.js:
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'react-native-reanimated/plugin',
      {
        globals: ['__scanCodes'],
      },
    ]
  ],
};
```

### What happened instead?

The `camera` component is working like intended. However, as soon as I pass the `frameProcessor` property, the application crashes with an `java.lang.UnsatisfiedLinkError`

I searched for other issues with this kind of error but could not find any / was not able to fix the error with the provided solutions.

### Relevant log output

`Node: v15.14.0`

`Java: openjdk 11.0.12 2021-07-20`

```
 buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"
```
`        classpath("com.android.tools.build:gradle:7.0.4")
`

```shell
FATAL EXCEPTION: pool-10-thread-1

java.lang.UnsatisfiedLinkError: No implementation found for void com.mrousavy.camera.CameraView.frameProcessorCallback(androidx.camera.core.ImageProxy) (tried Java_com_mrousavy_camera_CameraView_frameProcessorCallback and Java_com_mrousavy_camera_CameraView_frameProcessorCallback__Landroidx_camera_core_ImageProxy_2)

FATAL EXCEPTION: pool-10-thread-1
Process: XX.XX.XX.XXXXXXXX, PID: XXXXX
java.lang.UnsatisfiedLinkError: No implementation found for void com.mrousavy.camera.CameraView.frameProcessorCallback(androidx.camera.core.ImageProxy) (tried Java_com_mrousavy_camera_CameraView_frameProcessorCallback and Java_com_mrousavy_camera_CameraView_frameProcessorCallback__Landroidx_camera_core_ImageProxy_2)
	at com.mrousavy.camera.CameraView.frameProcessorCallback(Native Method)
	at com.mrousavy.camera.CameraView.configureSession$lambda-7$lambda-6(CameraView.kt:484)
	at com.mrousavy.camera.CameraView.$r8$lambda$cqtIchEZdTZaV3R0UUrDpVbB1Es(Unknown Source:0)
	at com.mrousavy.camera.CameraView$$ExternalSyntheticLambda1.analyze(Unknown Source:2)
	at androidx.camera.core.ImageAnalysis.lambda$setAnalyzer$2(ImageAnalysis.java:463)
	at androidx.camera.core.ImageAnalysis$$ExternalSyntheticLambda0.analyze(Unknown Source:2)
	at androidx.camera.core.ImageAnalysisAbstractAnalyzer.lambda$analyzeImage$0$androidx-camera-core-ImageAnalysisAbstractAnalyzer(ImageAnalysisAbstractAnalyzer.java:283)
	at androidx.camera.core.ImageAnalysisAbstractAnalyzer$$ExternalSyntheticLambda1.run(Unknown Source:14)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

### Device

OnePlus 6t (Android 11)

### VisionCamera Version

2.13.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
it looks like VisionCamera wasn't built with Frame Processors enabled, can you share your build logs?

Are you sure you installed Reanimated v2? Did you clean cache (Gradle as well as Metro) before building?

**Comment by vgorte** [comment]
@mrousavy 
My reanimated version: 
`"react-native-reanimated": "^2.5.0",`

 The build log indicates that frame processor should be enabled: 

```
> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
C:\P\nuue-app\node_modules\react-native-reanimated\android\react-native-reanimated-67-hermes.aar

> Configure project :react-native-vision-camera
VisionCamera: node_modules/ found at: C:\P\XXXX-app\node_modules
VisionCamera: Building with Hermes...
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/li
braries/view-binding) and the 'kotlin-parcelize' plugin.
VisionCamera: Frame Processors are enabled! Building C++ part...
WARNING:DSL element 'dexOptions' is obsolete and should be removed.
It will be removed in version 8.0 of the Android Gradle plugin.
Using it has no effect, and the AndroidGradle plugin optimizes dexing automatically.

The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build.
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':react-native-pager-view', ':react-native-vision-camera'
```

I cleaned the caches of gradle (./gradlew clean) and metro (npm start -- --cache-reset) multiple times. Is there more that I can try?

**Comment by mrousavy** [comment]
Maybe this is a Proguard issue? Can you try disabling Proguard?

**Comment by vgorte** [comment]
I have proguard disabled. The issue still persists.
I would happily provide more logs, if you could tell me what kind of logs would be helpful.

**Comment by vgorte** [comment]
I shared the code with someone else and he was able to build and run the aplpication + frame processor.
That would indicate a problem with my setup, I guess. 
We checked the node and java versions, which matched between his computer and mine. 

I think the installations of reanimated and vision-camera are correct, since he was able to simply install and run it.

Is there anything else in my environment that could cause this issue? 

Edit: I also have the above mentioned issue when running the example provided in this repo.

**Comment by vgorte** [comment]
I managed to resolve the issue. It looked like none of the c code was compiling. It looked like CMake was not correctly installed or something of that sort. Works fine now

**Comment by cgorski28** [comment]
@vgorte can you share some more details on how you resolved this issue? I'm experiencing a nearly identical scenario (error is a bit different, but app works fine without frame processor and crashes as soon as it is passed)

**Comment by kaiyes** [comment]
> I managed to resolve the issue. It looked like none of the c code was compiling. It looked like CMake was not correctly installed or something of that sort. Works fine now

This seems to solve it for this dev
