### ISSUE TITLE
🐛 "Camera" API documentation not found  

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [cuvent/react-native-vision-camera#975]
### What were you trying to do?

Hi

I was trying to open the "Camera" link in this page https://mrousavy.com/react-native-vision-camera/docs/api but this link cannot be found https://mrousavy.com/react-native-vision-camera/docs/classes/Camera.

The same goes for links like https://mrousavy.com/react-native-vision-camera/docs/api/interfaces/cameraprops.cameraprops-1/#torch.

Best regards
Jens

### What happened instead?

Page not found

### Device

Not relevant

### VisionCamera Version

Not relevant

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Huh, this works for me?

**Comment by vgorte** [comment]
Where did you get this link?
[https://mrousavy.com/react-native-vision-camera/docs/classes/Camera]( https://mrousavy.com/react-native-vision-camera/docs/classes/Camera)

Navigating from `/docs/api` to the camera docs results in a different link:
[ https://mrousavy.com/react-native-vision-camera/docs/api/classes/Camera]( https://mrousavy.com/react-native-vision-camera/docs/api/classes/Camera)
 
 The same goes for the `torch` camera props:
[ https://mrousavy.com/react-native-vision-camera/docs/api/interfaces/CameraProps#torch]( https://mrousavy.com/react-native-vision-camera/docs/api/interfaces/CameraProps#torch)

**Comment by jenskuhrjorgensen** [comment]
Hmm, good question. I think I might have used the search functionality. Can you reproduce similar "not found" issues if you search for "torch" and click on the first result? That takes me to this non-existing URL: https://mrousavy.com/react-native-vision-camera/docs/api/interfaces/cameraprops.cameraprops-1/#torch

![Screenshot 2022-04-08 at 16 02 41](https://user-images.githubusercontent.com/28528363/162451737-947f1c46-85f4-4e1e-b273-5e4c270ab8cc.png)

**Comment by mrousavy** [comment]
hmm, maybe this will get fixed if I upgrade docusaurus?

**Comment by losh11** [comment]
The entire search part of the api website is broken for me. Not able to search for anything without the not found error.

**Comment by mrousavy** [comment]
@losh11 Yeah I don't know why. If you have any idea how to fix it, please let me know.

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.
