### ISSUE TITLE
🐛 How to fix blank screen when open camera on ios ? 

### ISSUE THREAD

**Issue by Heanphearak** [cuvent/react-native-vision-camera#984]
### What were you trying to do?

follow this document ==> https://mrousavy.com/react-native-vision-camera/docs/guides/troubleshooting

### Reproduceable Code

```tsx
import React, {useCallback} from 'react';

import {StyleSheet, Text} from 'react-native';
import {Camera, useCameraDevices} from 'react-native-vision-camera';
import {useScanBarcodes, BarcodeFormat} from 'vision-camera-code-scanner';

export default function App() {
  const [hasPermission, setHasPermission] = React.useState(false);
  const devices = useCameraDevices();
  const device = devices.back;

  const [frameProcessor, barcodes] = useScanBarcodes([BarcodeFormat.QR_CODE], {
    checkInverted: true,
  });

  React.useEffect(() => {
    (async () => {
      const status = await Camera.requestCameraPermission();
      setHasPermission(status === 'authorized');
    })();
  }, []);

  return (
    device != null &&
    hasPermission && (
      <>
        <Camera
          onError={onError}
          style={StyleSheet.absoluteFill}
          device={device}
          isActive={true}
          frameProcessor={frameProcessor}
          frameProcessorFps={2}
        />
        {barcodes.map((barcode, idx) => (
          <Text key={idx} style={styles.barcodeTextURL}>
            {barcode.displayValue}
          </Text>
        ))}
      </>
    )
  );
}

const styles = StyleSheet.create({
  barcodeTextURL: {
    fontSize: 20,
    color: 'white',
    fontWeight: 'bold',
  },
});
```

### What happened instead?

![telegram-cloud-photo-size-5-6242089560456671308-y](https://user-images.githubusercontent.com/40253277/162711158-27a87cae-7476-4b5f-8903-67c59971aced.jpg)

### Relevant log output

```shell
Assertion failed: (object->ctx_ == ctx_ && "Don't try to clone an object backed by a different Runtime"), function cloneObject, file JSCRuntime.cpp, line 611.
```

### Device

iphone xs max version 14.8.1

### VisionCamera Version

"react-native-vision-camera": "^2.13.1",

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Does this happen on Hermes too?

**Comment by Heanphearak** [comment]
what you mean ? 
I need to set hermes_enabled => false to hermes_enabled => true right ?

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.
