### ISSUE TITLE
🐛 App crash in captureOutput

### ISSUE THREAD

**Issue by tinaszheng** [cuvent/react-native-vision-camera#992]
### What were you trying to do?

App crashes when camera scanner is mounted on the screen. This happens maybe 1/10 times, so not on every render.

### What happened instead?

App freezes with this error in xcode:

`Swift/arm64-apple-ios.swiftinterface:30564: Fatal error: Double value cannot be converted to UInt64 because it is either infinite or NaN`

on line 219 of `CameraView+RecordVideo.swit` 
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/59578595/163265697-17f480e6-70cc-415e-9eb2-17f5d602e1bf.png">

### Device

iPhone 12

### VisionCamera Version

2.12.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey, thanks for the bug report! That's quite interesting, I wonder how it got there. Maybe division by 0?

**Comment by gary-cohen** [comment]
I'm seeing the same issue consistently when I `runOnJS(setCameraAvailable)(true)` in the worklet where `setCameraAvailable` is the setter in useState.

**Comment by schwrzd** [comment]
Had the same issue, this is my workaround:

(CameraView+RecordVideo.swit):

```
  let nanosecondsPerFrame = secondsPerFrame * 1_000_000_000.0
        // Check if nanosecondsPerFrame is a valid number
        if !nanosecondsPerFrame.isNaN && !nanosecondsPerFrame.isInfinite {
            let nanosecondsPerFrameUInt64 = UInt64(nanosecondsPerFrame)
            if lastFrameProcessorCallElapsedTime >= nanosecondsPerFrameUInt64 {
        if !isRunningFrameProcessor {
          // we're not in the middle of executing the Frame Processor, so prepare for next call.
          CameraQueues.frameProcessorQueue.async {
            self.isRunningFrameProcessor = true

            let perfSample = self.frameProcessorPerformanceDataCollector.beginPerformanceSampleCollection()
            let frame = Frame(buffer: sampleBuffer, orientation: self.bufferOrientation)
            frameProcessor(frame)
            perfSample.endPerformanceSampleCollection()

            self.isRunningFrameProcessor = false
          }
          lastFrameProcessorCall = frameTime
        } else {
          // we're still in the middle of executing a Frame Processor for a previous frame, so a frame was dropped.
          ReactLogger.log(level: .warning, message: "The Frame Processor took so long to execute that a frame was dropped.")
        }
      }
    }
```

**Comment by mrousavy** [comment]
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.
