### ISSUE TITLE
🐛 Doc: Missing expo managed section in Getting Started

### ISSUE THREAD

**Issue by obasille** [cuvent/react-native-vision-camera#993]
### What were you trying to do?

In the "Getting Started" guide, the index mentions a "Expo Managed" section but it's content is missing.

![image](https://user-images.githubusercontent.com/6388620/163378518-2a7a831b-a5e3-4654-ba52-674dc518d32e.png)

https://mrousavy.com/react-native-vision-camera/docs/guides/#managed-expo

Thanks!

### What happened instead?

Not sure how to install with config plugin for expo

### Device

Android

### VisionCamera Version

Release 2.13.2

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey!

Yea this section is only visible if you press the "Expo" tab. I don't think docusaurus allows you to dynamically hide the invisible sections.

![Screenshot 2022-04-14 at 13 08 06](https://user-images.githubusercontent.com/15199031/163379281-fe7f5a51-43e5-4757-ba95-3c133584ac39.png)
